docker-compose.yml
package.json

Changed the Back Office API port from 3000 to 3004 so it doesn't clash with the Appeals Service API port when both the Back Office and Appeals Service dev environments are running together.
Also changed the commitlint from param which is used as a starting commit to validate the commit message format because it appears that some commits have been pushed with incorrectly formatted messages since this was last set.

feat(as-3316): change the back office api port

---

README.md
packages/api/api/openapi.yaml
packages/api/database/migrations/00037-amend-has-appeal-table.js
packages/api/database/migrations/00038-amend-has-lpa-submission-table.js
packages/api/database/migrations/00039-amend-appeal-link-table copy.js
packages/api/database/migrations/00040-amend-appeal-data-view.js
packages/api/database/migrations/00041-amend-questionnaire-data-view.js

1. Updated the schema with the following new db fields:
- Appeal Validation date, which is set in the validation flow for the `Invalid` or `Something is missing or wrong` paths
- Appeal Start date,  which is set in the validation flow for the `Valid` path
- Questionnaire Due date,  which is set in the validation flow for the `Valid` path
- Case officer email, which is displayed on the View Appeal page
- Validation officer email, which is displayed on the View Appeal page
- Inspector email, which is displayed on the View Appeal page
2. Moved the Questionnaire Status field from the `HASLPASubmission` table to the `AppealLink` table so it can be updated before the LPA Questionnaire has been completed.
3. Updated the `AppealData` and `QuestionnaireData` views to return additional fields.
4. …

feat(as-3485): update db schema with new fields

---

packages/api/database/migrations/00042-amend-message-queue-table-trigger.js

Changed the data type of `ID` and `AppealID` from `UNIQUEIDENTIFIER` to `CHAR(36)` because `UNIQUEIDENTIFIER` appears to be uppercasing the letters and we need them as lowercase for Blob Storage searches.

fix(api): update the datatype of ID and AppealID in the message queue trigger

---

packages/api/database/migrations/00044-amend-has-appeal-table.js

Update the `MessageQueue` trigger to remove the `MinisterialTargetDate` field.
Normally migrations shouldn't be updated but in this case it makes the down migration cleaner because in a new migration we'd not have the `MinisterialTargetDate` field so couldn't revert the trigger correctly unless we add the field again in another migration but that could cause other issues. The new migrations including this one haven't been run in dev yet so there shouldn't be any clashes.

fix(as-3485): update message queue trigger to remove ministerialtargetdate

---

packages/web-app/src/controllers/review-questionnaire-submission.js
packages/web-app/src/controllers/review-questionnaire-submission.test.js

This fix populates the values that the CO selected / Entered in the Review Questionnaire page whenever they navigated back to this page

fix(as-3039): populate user selected/entered data during page navigation

---

apps/web/src/server/app/validation/validation.controller.js
apps/web/src/server/lib/helpers.js
apps/web/src/server/views/validation/check-and-confirm.njk

Fixed issue where missing or wrong docs reasons rendering was broken on check and confirm page if only one reason was selected
Added arrayifyIfString helper function and used it to normalise the incompleteReasons and missingOrWrongDocumentsReasons passed to the check and confirm template. This fixes an issue where if only one reason is selected, the template erroneously treats the string value as an array.
N/A

BOCM-32: fix

---

apps/web/src/server/app/validation/validation.controller.js

Fix for incorrect back url on validation check and confirm page (for invalid outcome)
Updated back URL for validation journey check and confirm page, when user has selected invalid outcome for the review
[BOCM-219](https://pins-ds.atlassian.net/browse/BOCM-219)

BOCM-219 fix

---

apps/api/pipelines/azure-pipelines-build.yml
apps/api/pipelines/azure-pipelines-release.yml
apps/web/pipelines/azure-pipelines-build.yml
apps/web/pipelines/azure-pipelines-release.yml

Swap token used by the pipelines to get templates. The "Planning-Inspectorate" token is automatically created and uses the GitHub Azure Pipelines app instead of an OAuth token. This will stop the token expiring and the need for it to be refreshed.

Change token used for pipeline templates

---

apps/web/src/server/__tests__/validation.test.js
apps/web/src/server/app/app.express.js
apps/web/src/server/app/validation/validation.guards.js
apps/web/src/server/app/validation/validation.router.js

This is a smaller PR containing two bug fixes originally committed in the (as of now, unmerged) https://github.com/Planning-Inspectorate/back-office/pull/321. These fixes should really be merged ahead of the show and tell.
- Fix an issue with csrf token not being read on forms posting multipart data
- Fix an issue with validation guard only allowing edits to appeal details on incomplete appeals

fixes for show and tell

---

apps/api/pipelines/azure-pipelines-release.yml
apps/web/pipelines/azure-pipelines-release.yml

Splits the App Service deploy and slot swap steps into individual stages. This allows deployments in Test and Production environments to seek manual approval prior to swapping a deployment into a production slot thereby allowing a developer to check the staged deployment prior to go-live in the respective environment.
N/A

Enable approvals prior to App Service slot swap

---

apps/web/src/server/app/app.express.js

Passing Multer().none() to the express middleware fixes the JsDocs error but creates a new one when trying to upload files.
Now the whole instance of multer() is passed and the error is just ignored.
Also,
No reason to have this working differently on the test env.
https://pins-ds.atlassian.net/browse/BOAS-185

fix(web/appeals): fix upload file on statements form (boas-185)

---

azure-pipelines-db-seed.yml

- removes redundant `npm run build` command when seeding

fix(api): removes redundant build command (BOAS-217)

---

apps/api/src/server/applications/case-admin-officer/case-admin-officer.controller.js
apps/api/src/server/applications/case-officer/case-officer.controller.js
apps/api/src/server/applications/inspector/inspector.controller.js
apps/api/src/server/applications/sector/sector.controller.js

- change the getApplications apis used by Case Officer, CAO, and Inspector Dashboards, to display the sectors in the correct order (which is alphabetical order of abbreviation - eg BC, EN, . . . WA, WS, WW)
- also updated the getSectors api to return the list in the correct order too

fix(api/applications): dashboard-sector-names-ordering (BOAS-180)

---

apps/web/src/server/applications/create/key-dates/applications-create-key-dates.validators.js

Fix the validation of future date in the Key dates page.  Issue was that the Date() function month parameter is 0-11, was passing in the real month number 1-12 - hence past dates in this month were considered future - next month.
https://pins-ds.atlassian.net/browse/BOAS-315

fix(web/applications): key dates future date validation (BOAS-315)

---

apps/web/src/server/applications/create/applicant/applications-create-applicant.validators.js

Create Applicant - Applicant Telephone Number - validation bug fix - odd behaviour: not validating good input, and alternately validating and not-validating.  Issue was with /g in the regex, needed to be either removed, or set a separate 'g' parameter in the matches() fn call.
https://pins-ds.atlassian.net/browse/BOAS-285

fix(web/applications): applicant tel number validation fix (BOAS-285)

---

apps/api/src/server/applications/search/__tests__/case-search.test.js
apps/api/src/server/repositories/case.repository.js

amend the api - Search Applications By Criteria - used by search applications - to only include status data for valid statuses.  It was returning all historic statuses, which caused an error on front end searching.
Unit tests updated.
(raised against BOAS-197)
https://pins-ds.atlassian.net/browse/BOAS-360

fix(api/applications): search applications only return valid status

---

apps/api/src/server/applications/application/application.validators.js

- fixed bug that stopped Save and Continue in the draft case create journey, for non mandatory fields:
phone number, email.  And website
- there was a typo in the API validation that meant website not being validated at the API side, fixing this meant that this issue would also occur for website. Fixed.
- ensured that the validation checks for phone number, email and website are the same as the checks performed on the web app - eg the special case where the express-validator IsUrl fn allows a @ in the url - which is not correct.
https://pins-ds.atlassian.net/browse/BOAS-363

fix(api/applications): case create allow non-mandatory (BOAS-363)

---

apps/web/src/server/applications/pages/create/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap
apps/web/src/server/views/applications/create/check-your-answers.njk

Map zoom level label should have a lower case l

fix(web/applications): map zoom level spelling (BOAS-357)

---

apps/web/src/server/applications/pages/create/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap
apps/web/src/server/views/applications/create/check-your-answers.njk

On case creation journey, no breadcrumbs wanted.  Back link should be on top left, not bottom left.  
Continue / save button should now be bottom left.
Only the check-your-answers page needed updating, all others are already correct.

feat(web/applications): move backlink, button and breadcrumbs (BOAS-391)

---

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap
apps/web/src/server/applications/pages/case/__tests__/__snapshots__/applications-case.test.js.snap
apps/web/src/server/applications/pages/search-results/__tests/__snapshots__/applications-search.test.js.snap
apps/web/src/server/applications/pages/search-results/__tests/applications-search.test.js
apps/web/src/server/lib/nunjucks-filters/url.js

a trailing slash in some url links stops further pages working - particularly when returning to dashboard after visiting search or display case pages, the backlink adds a slash eg case-officer/ and further searches etc do not work
https://pins-ds.atlassian.net/browse/BOAS-525

fix(web/applications): slash in url stops some pages working (BOAS-525)

---

apps/api/src/server/applications/application/documents/__tests__/document.test.js
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.routes.js
apps/api/src/server/swagger-output.json

New api to return the blob storage info for a single document on a case, eg
GET /applications/{caseId}/documents/{guid}
to return
{
"blobStorageContainer": "document-service-uploads",
"blobStoragePath": "application/TR010002/d38ef007-98d8-4d89-b7bb-34160d97e84e/screenshot 2.png"
}
https://pins-ds.atlassian.net/browse/BOAS-695
(part of ticket BOAS-694)

feat(api/applications): api to return blob file uri info (BOAS-695)

---

apps/api/src/server/applications/application/__tests__/update-document-status.test.js
apps/api/src/server/applications/application/application.controller.js
apps/api/src/server/applications/applications.routes.js
apps/api/src/server/repositories/document.repository.js
apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/documentation-folder.njk
apps/web/src/styles/7-components/files-list.scss

If document status is "awaiting upload", "waiting for av check" or "av check failed" the file row is disabled: checkbox is fake, links don't have an href attribute and everything in the row is unclickable
https://pins-ds.atlassian.net/browse/BOAS-699

feat(web/applications): disable file row if AV check hasnt passed yet (boas-699)

---

apps/api/prisma/seed.js

These are fixes to the seeding script, and therefore only affect local, dev, and test environments, not Production.
1. This fixes seeding case not displaying correctly - both in draft, and for started cases, when trying to amend Application Info details.  
2. all seeded cases are assigned a caseReference eg EN010001.  This should not be the case for Draft cases, as cases are assigned a caseReference when they progress from Draft to Pre-application.  Code amended to set caseReference to NULL for Draft seeded cases.
3. case references have changed from a 4 digit number to include a leading ‘1' to separate these cases from existing Horizon case references. eg EN010001 should be EN0110001.  Seed code still generates 8 char ref codes, needs to change to 9 to include the '1’ after the SubSector …

fix(api/applications): fix seeded cases display error (BOAS-704)

---

apps/api/prisma/schema.d.ts
apps/api/src/server/applications/application/documents/__tests__/document.test.js
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.routes.js
apps/api/src/server/applications/application/file-folders/__tests__/get-folder-details.test.js
apps/api/src/server/applications/application/file-folders/folders.routes.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js
apps/api/src/server/utils/mapping/map-document-details.js

- modify the get document by guid endpoint to return all document properties required (extending this from just returning the 2 blob uri values)
**GET /applications/{caseId}/documents/{guid}**
- modify the get documents in folder endpoint to return the same document properties in the items[] array
**GET /applications/{caseId}/folders/{folderId}/documents**
https://pins-ds.atlassian.net/browse/BOAS-726

feat(api/applications): extend document properties returned (BOAS-726)

---

apps/api/src/server/repositories/folder.repository.js

Small fix to correct spelling mistake: Other docuents folder.  Note that this will only apply to applications made from now on, not existing applications.
https://pins-ds.atlassian.net/browse/BOAS-771

fix(api/applications): correct spelling other docuents folder (BOAS-771)

---

apps/api/src/message-schemas/events/interested-party.schema.json
apps/api/src/message-schemas/events/representation.schema.json

This change adds the Representation message schema to support:
- registering interest in a case from front office;
- the relevant representations workflow in back office;
- and the publishing of relevant representations to front office
Some points to note for the schema:
- The schema supports the entire workflow FO (register)-> BO (operations)-> (publish) FO.   This could be split in the future. 
- The schema supports the concept of the representation submitted by an agent (representative) for a person/organisation (represented).
- Both representative and represented use the interested-party.schema.json to capture the personal details
- Some changes have been made to the interested-party.schema.json to include some additional fields used in this domain, eg under18 and contactMethod.
- …

feat(api): add message schema for representations

---

apps/api/prisma/migrations/20230420095018_documentversion_documenttype_nullable/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.validators.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js

Fix error when trying to set No Document Type on a document.
This fix changes the DB structure of DocumentVersion to allow documentType to be nullable.  This should NOT be a breaking change.  DB migrate will have to be performed to update local dev etc.
The change also now changes Web as well as API.
https://pins-ds.atlassian.net/browse/BOAS-830

fix(api/applications): error setting no document type (BOAS-830)

---

apps/api/prisma/schema.d.ts
apps/api/src/server/appeals/appeals.routes.js
apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals-formatter.js
apps/api/src/server/appeals/appeals/appeals.controller.js
apps/api/src/server/appeals/appeals/appeals.routes.js
apps/api/src/server/repositories/appeal.repository.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js
apps/api/src/server/utils/address-block-formtter.js

Added `/appeals` route for returning data for the Appeals List page.
Also added swagger docs and tests
https://pins-ds.atlassian.net/browse/BOAT-40

feat(api): add /appeals route for returning appeals list data (BOAT-40)

---

packages/event-client/package.json

`packages/event-client` was missing a main entry in the package definition, resulting in a Node deprecated warning ([DEP0151](https://nodejs.org/api/deprecations.html#DEP0151)). A main entry has been added.
N/A

chore(tooling): add main entry point to fix node dep0151 warning

---

apps/api/prisma/prisma.truncate.js
apps/api/prisma/seed-production.js
apps/api/prisma/seed.js

Prisma DeleteMany fails on more than 2100 records.  This causes seeding to fail when clearing the 
RegionsOnApplicationDetails table.  Added a simple truncateTable fn to call raw SQL to TRUNCATE TABLE.
This issue meant that seeding failed in Test, giving rise to the error of no exam timetable items in the dropdown
https://pins-ds.atlassian.net/browse/BOAS-852

fix(api/applications): add truncatetable as deletemany fails on 2100 records (BOAS-852)

---

apps/api/src/server/applications/application/__tests__/start-case.test.js
apps/api/src/server/repositories/raw_sql_queries/update-application-reference.sql

Fixed some expressions containing NULL where they shouldn't. If this is the first case of its kind, the expression evaluating against the minimum reference number will return falsy (because NULL < Number is false), and then @reference_number becomes NULL (because NULL + 1 = NULL).
Then eventually, the entire string concatenation (with pluses) will return NULL even if the left operand is a string, because NULLs are the wild west in MSSQL.
In future I think we should move this logic out of SQL and into the codebase, that way we can test it and get better observability on it too. I understand why it's in SQL, but I think we'd get equal value from just putting a UNIQUE constraint on the reference column and allowing it to fail in race conditions (there's almost no chance we'll be creating two …

fix(api): set base reference number if one doesn't exist

---

apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals.controller.js
apps/api/src/server/appeals/appeals/appeals.routes.js
apps/api/src/server/appeals/appeals/appeals.validators.js
apps/api/src/server/appeals/constants.js
apps/api/src/server/repositories/appeal.repository.js
apps/api/src/server/swagger-output.json

Adds pagination for the `/appeals` route as query params.
For example `http://localhost:3000/appeals?pageNumber=1&pageSize=30`.
If no pagination params are given then the response is limited to the first 30 appeals.
If pagination params are given then:
- Both `pageNumber` and `pageSize` must be given
- Both `pageNumber` and `pageSize` must be numeric
- Both `pageNumber` and `pageSize` must be greater than 0
Also added tests for success and error states and updated swagger docs.
https://pins-ds.atlassian.net/browse/BOAT-41

feat(api): add pagination for /appeals route

---

apps/api/prisma/schema.d.ts
apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals.formatter.js
apps/api/src/server/appeals/appeals/appeals.validators.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js

Updated the `/appeals/:appealId` endpoint to return the `startedAt` date field
Also:
- Removed some fields (`developmentType`, `eventType` and `visitType`) from the same endpoint that are no longer displayed in the Case View page
- Updated `hasPageNumberAndSize` validation function to return a boolean rather than a string
Also updated the tests and swagger docs
https://pins-ds.atlassian.net/jira/software/projects/BOAT/boards/207?selectedIssue=BOAT-98

feat(api): return startedAt field in the /appeals/:appealId endpoint

---

apps/api/setup-tests.js
apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals.controller.js
apps/api/src/server/repositories/appeal.repository.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js

Updated the pagination response to include `itemCount`, `page`, `pageCount` and `pageSize`, following the naming convention used in Applications.
For example:
```
{
"itemCount": 57,
"items": [
{
"appealId": 1,
"appealReference": "APP/Q9999/D/21/235348",
"appealSite": {
"addressLine1": "19 Beauchamp Road",
"town": "Bristol",
"postCode": "BS7 8LQ"
},
"appealStatus": "awaiting_lpa_questionnaire",
"appealType": "household",
"createdAt": "2023-02-16T11:43:27.096Z",
"localPlanningDepartment": "Wiltshire Council"
}
],
"page": 1
"pageCount": 29,
"pagaeSize": 30
}
```
Also updated test and swagger docs.

feat(api): update appeal pagination results to include item and page count

---

apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals.controller.js
apps/api/src/server/appeals/appeals/appeals.routes.js
apps/api/src/server/appeals/appeals/appeals.validators.js
apps/api/src/server/appeals/constants.js
apps/api/src/server/repositories/appeal.repository.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js

Added a `PATCH` route for `/appeals/:appealId` for saving appeal data. Currently this will be used for saving the start date with the following request body:
```
{
"startedAt": "2023-05-09"
}
```
Also added validation to ensure that if a date is given: 
- It’s in the correct format
- It's a valid date
- It contains leading zeros
Also added tests and updated swagger docs
https://pins-ds.atlassian.net/browse/BOAT-101

feat(api): add patch route for /appeals/:appealId for saving appeal data

---

apps/api/src/server/repositories/case.repository.js
apps/api/src/server/repositories/raw_sql_queries/update-application-reference.sql

SQL script to create case used to have a space on the end of each line, this was inadvertently cleaned up on the last update, however when the sql script file is read, it removes all CR and LF chars, replacing them with ''.
With the removal of spaces, therefor the wordsallruntogether.  eg SELECT  * FROM ApplicationDetailsWHERE ...
Fix was to replace the new lines with a space, to avoid having to remember to add a space to each line.
https://pins-ds.atlassian.net/browse/BOAS-866

fix(api/applications): fix sql error on case creation (BOAS-866)

---

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
apps/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
apps/web/src/server/views/appeals/appeal/appeal-details.njk

The accordion state is stored in local storage by tag id. It now appends ID to make sure they are only stored by appeal and not for all appeals.
https://pins-ds.atlassian.net/browse/BOAT-132

fix(web/appeals): accordion should not save state between appeals

---

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
apps/web/src/server/views/appeals/components/status-tag.njk

Fix for incorrect status tag colours for case documentation on appeal-details page
BOAT-156

fix(web): BOAT-156 - fix status tag colours

---

apps/api/package.json

Previously it appeared after running swagger-autogen that I had lots of changes, but they get removed when prettier runs via lint-staged. Now the `swagger-autogen` script also runs prettier so the output is as expected.
N/A

chore(api): run prettier after swagger-autogen

---

apps/api/src/database/seed/data-static.js
apps/api/src/database/seed/data-test.js

Changed the display name for appeal types, and moved the generation to `seedStaticData`.  
https://pins-ds.atlassian.net/browse/BOAT-160

fix(web/appeals): appeal type names

---

apps/api/src/database/migrations/20230530111714_add_linked_appeals/migration.sql
apps/api/src/database/schema.d.ts
apps/api/src/database/schema.prisma
apps/api/src/server/appeals/appeals.d.ts
apps/api/src/server/appeals/appeals/__tests__/appeals.test.js
apps/api/src/server/appeals/appeals/appeals.formatter.js
apps/api/src/server/repositories/appeal.repository.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js
apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
apps/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
apps/web/src/server/appeals/appeal-details/appeal-details.controller.js
apps/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
apps/web/src/server/views/appeals/appeal/appeal-details.njk
apps/web/testing/app/fixtures/referencedata.js

Add `linkedAppeals` and `otherAppeals` fields to the database to enable appeal linking.
Update the API with the following field changes:
- Rename `caseProcedure` to `procedureType`
- Rename `linkedAppeal` to `linkedAppeals`
- Change `linkedAppeals` to return multiple appeals
- Return additional `otherAppeals` field
- Return additional `isParentAppeal` field (only API as it’s not used in the UI right now)
Updated the Case Details page in the UI for the naming changes and to display the list of linked appeals and created a new macro to display the data for the linked/other appeals. 
https://pins-ds.atlassian.net/browse/BOAT-176

fix(api): update linked/other appeal fields to return data from the database

---

apps/web/src/styles/_shame.scss

-negate smooth scrolling on chrome based browsers that made the previous fix less impactful. Scoped only to the relevant representations table/page

fix(web/applications): negate smooth scroll on table sort

---

commitlint.config.cjs

Follow on from https://github.com/Planning-Inspectorate/back-office/pull/1008 to allow more dependabot commits through. The body line length is fairly arbitrary anyway.
N/A

chore(tooling): allow longer commit body line lengths

---

apps/document-storage/package.json

`cross-env` was not correctly used so `test` for `document-storage` wouldn't work on Windows.
N/A

fix(document-storage): fix use of cross-env

---

apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
apps/web/src/server/views/applications/case-timetable/timetable-preview.njk

Fix for: BOAS-953 - Within the Publish examination timetable page, there should be a 'Back to examination timetable' link.  This is not present
https://pins-ds.atlassian.net.mcas.ms/browse/BOAS-953

fix(web): boas-953 - no back to examination timetable link

---

appeals/api/src/server/appeals/appeals/appeals.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
package.json

Restored ability to run ALL tests from `npm run test`.
Added specific scripts for appeals development:
- web:appeals
- api:appeals

chore(appeals): full tests and new appeals script

---

package.json
turbo.json

Prisma-generate keeps failing in the pipelines now there are two API apps. Changing to run in series, without turbo, to see if that helps.
N/A

chore(tooling): don't run prisma-generate with turbo

---

appeals/web/environment/config.js
appeals/web/environment/schema.js
apps/web/environment/config.js
apps/web/environment/schema.js

If the web app was missing the require SESSION_SECRET env var, the resulting error was obscure and unhelpful. The schema validation for the environment setup doesn't require any fields by default. SessionSecret has been marked as required now, so the error is caught earlier and the message more helpful ("Error: Env validation error: "sessionSecret" is required")
N/A

fix(web): clearer error when missing session secret

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk

Fix for: 
"There is no hint text for Item name field.  (See image)
Requirements say 'There is a limit of 200 characters'"
https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?isInsightsOpen=true&selectedIssue=BOAS-860

fix(web): boas-860 - ensure item name has hint

---

appeals/web/environment/schema.js
apps/web/environment/schema.js
azure-pipelines-ci.yml

Temporary fix to let web build correctly, session secret env var isn't required.
N/A

fix(web): sessionSecret isn't required for web build

---

appeals/api/src/server/appeals/appeals/__tests__/appeals.test.js
appeals/api/src/server/appeals/appeals/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/appeals/appeals/appeals.controller.js
appeals/api/src/server/appeals/appeals/appeals.routes.js
appeals/api/src/server/appeals/appeals/appeals.validators.js
appeals/api/src/server/appeals/constants.js
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appeal.repository.js

Updated the GET Appeals API to accept a `searchTerm` parameter, which searches the Appeal Reference and Postcode fields and does a case-insensitive, partial match. 
Added validation to check that the `searchTerm` param is between 2 and 8 characters.
Added unit tests
Updated swagger
https://pins-ds.atlassian.net/browse/BOAT-243

feat(api): add appeals search using appeal reference or postcode

---

appeals/api/package.json
apps/api/package.json

We are clearing the jest cache for API tests, but no one knows why! The docs state this can slow down tests significantly, and should only be done if there are issues. All the other packages run with the cache and are OK.
The other issue is that since tests are run concurrently across packages (with turbo), some test runs fail because the cache is cleared while another test suite is running, e,g,  [failed test logs](https://dev.azure.com/planninginspectorate/back-office/_build/results?buildId=55021&view=logs&j=4915e90a-f1c2-55b0-f3a8-aede04c03102&t=b9fc72a1-1467-5c9b-5728-71623aec9bc0&l=56).
N/A

chore(tooling): test script doesn't need to clear jest cache

---

apps/api/src/server/utils/query/__tests__/sort-by.test.js
apps/api/src/server/utils/query/sort-by.js

`sortByFromQuery` should handle an empty string, and not return an invalid sort by object.
N/A

fix(api): sort-by should handle empty string

---

azure-pipelines-build.yml

`handle-subscriptions` build was incorrect, `node_modules` ended up nested, so module resolution was broken.
N/A

build: don't nest node_modules in zip for handle-sub function build

---

apps/api/src/server/applications/subscriptions/__tests__/subscriptions.test.js
apps/api/src/server/applications/subscriptions/subscriptions.js

Subscription update API didn't work as expected as previous "subscribed to" values were left in the DB, but should've been cleared.
[ASB-1511](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1511)
[ASB-1511]: https://pins-ds.atlassian.net/browse/ASB-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): ensure subscription updates reset previously set fields

---

appeals/api/jsconfig.json
apps/api/jsconfig.json
apps/api/package.json
apps/api/src/server/applications/subscriptions/__tests__/subscriptions.test.js
apps/api/src/server/applications/subscriptions/subscriptions.controller.js
apps/api/src/server/applications/subscriptions/subscriptions.routes.js
apps/api/src/server/applications/subscriptions/subscriptions.service.js
apps/api/src/server/applications/subscriptions/subscriptions.validators.js
apps/api/src/server/repositories/subscription.respository.js

Using [subpath-imports](https://nodejs.org/docs/latest-v18.x/api/packages.html#subpath-imports) for common paths makes the imports clearer, regardless of folder depth. 
An example refactoring has been applied to the subscriptions endpoint.
N/A

refactor(api): add subpath imports for common paths

---

appeals/api/src/database/migrations/20230707131036_update_lpa_questionnaire/migration.sql
appeals/api/src/database/schema.d.ts
appeals/api/src/database/schema.prisma
appeals/api/src/database/seed/data-samples.js
appeals/api/src/database/seed/data-test.js
appeals/api/src/database/seed/seed-clear.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Add additional LPA Questionnaire fields related to neighbouring sites.
- `isAffectingNeighbouringSites`
- `neighbouringSiteContacts`
https://pins-ds.atlassian.net/browse/BOAT-263

fix(appeals/api): add additional lpa questionnaire fields

---

appeals/api/src/database/migrations/20230707180928_enforce_folder_appeal_constraint/migration.sql

Additional migration to add constraints to folder and making Appeal.reference unique.

fix(appeals/api): missing migration for folder constraints

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/views/appeals/appeal/appeal-details.njk

Fix display of LPAQ review link, if review is null
BOAT-271

fix(appeals/web): display of lpaq review if null BOAT-271

---

.gitignore
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/applications/documents/documents.service.js
apps/api/src/server/repositories/folder.repository.js
apps/api/src/server/swagger-output.json
apps/api/src/server/swagger.js

- When uploading new documents, generate a document reference in the format `{application_ref}-{index}` e.g. `T8-000001`
- The index part increments for each document uploaded
I'm unable to test locally as the change relies on blob storage which doesn't work locally. Will need to test in dev.
This will need to be followed up by some UI changes.
[BOAS-770](https://pins-ds.atlassian.net/browse/BOAS-770)
[BOAS-770]: https://pins-ds.atlassian.net/browse/BOAS-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api/applications): generate a reference for each uploaded document

---

packages/event-client/index.d.ts

The `packages/event-client` type definition didn't include `event-type`, which results in errors in vscode. The definition has been updated to include this.
N/A

fix(packages/event-client): ensure module definition includes EventType

---

appeals/api/package.json
apps/api/package.json
package-lock.json

The versions of `prisma` and `@prisma/client` were out of sync. Both have been updated to 4.16.1, for applications and appeals.
Note this isn't the latest, 4.16.2, because of a typescript issue and I didn't want to update both (https://github.com/prisma/prisma/issues/20024). We should investigate going to v5 soon, which is meant to be significantly faster.
N/A

chore(deps): update prisma and @prisma/client to 4.16.1

---

apps/document-storage/Dockerfile

We want to move away from using `.env` files in builds, but a recent change to the Dockerfiles broke the document-storage-api as an environment variable was missing. This will be added to Azure, but for now this will fix it.
N/A

fix(applications): document-storage-api was expecting a .env file

---

apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/repositories/document.repository.js

When uploading new documents, we currently fetch all existing documents in a case to derive the next document reference. This change improves scalability by using SQL to only fetch the latest row.
Tested locally and working.
Related to [BOAS-770](https://pins-ds.atlassian.net/browse/BOAS-770)
[BOAS-770]: https://pins-ds.atlassian.net/browse/BOAS-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve scalability of document querying on upload

---

appeals/api/src/server/endpoints/appeals/appeals.validators.js

The LPA Questionnaire and Appellant Case validators in appeals.validators are no longer used since they have been moved to lpa-questionnaires.validators and appellant-cases.validators

refactor(appeals/api): remove old lpa questionnaire and appellant case validators

---

apps/web/src/client/components/html-content-editor/html-content-editor.js

It was not possible to get passed the rich-text editor with the keyboard (tabbing). This has been fixed. 
The solution is not ideal at all, unfortunately the library has very little options exposed, and by default overrides the tab behaviour. After much searching and trial-and-error with the library and it's inner workings, this seemed like the best solution unfortunately (short of using the underling library - `prosemirror` and building the editor ourselves).
[ASB-1689](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1689)
[ASB-1689]: https://pins-ds.atlassian.net/browse/ASB-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): keyboard-only nav

---

appeals/api/setup-tests.js
appeals/api/src/server/common/controllers/lookup-data.controller.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/designated-sites/__tests__/designated-sites.test.js
appeals/api/src/server/endpoints/designated-sites/designated-sites.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the designated sites, which provides values that can be used to dynamically create a field list in the UI. 
https://pins-ds.atlassian.net/browse/BOAT-397

feat(appeals/api): add an api endpoint for returning the designated sites

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/knowledge-of-other-landowners/__tests__/knowledge-of-other-landowners.test.js
appeals/api/src/server/endpoints/knowledge-of-other-landowners/knowledge-of-other-landowners.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the knowledge of other landowners, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-398

feat(appeals/api): add api endpoint to get the knowledge of other landowners

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/lpa-notification-methods/__tests__/lpa-notification-methods.test.js
appeals/api/src/server/endpoints/lpa-notification-methods/lpa-notification-methods.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the LPA Notification Methods, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-399

feat(appeals/api): add api endpoint to get the lpa notification methods

---

appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/lpa-questionnaire-validation-outcomes/__tests__/lpa-questionnaire-validation-outcomes.test.js
appeals/api/src/server/endpoints/lpa-questionnaire-validation-outcomes/lpa-questionnaire-validation-outcomes.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js

Added an API endpoint to return the LPA Questionnaire Validation Outcomes, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-400

feat(appeals/api): add api endpoint to get the lpa questionnaire validation outcomes

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/planning-obligation-statuses/__tests__/planning-obligation-statuses.test.js
appeals/api/src/server/endpoints/planning-obligation-statuses/planning-obligation-statuses.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the Planning Obligation Statuses, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-401

feat(appeals/api): add an api endpoint to get the planning obligation statuses

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/tests/data.js

Updated the GET appeals endpoint to return the Appeal Due Date rather than the hardcoded `null` value.
The value is returned as `documentationSummary.appellantCase.dueDate`

fix(appeals/api): update get appeals endpoint to return the appeal due date

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/procedure-types/__tests__/procedure-types.test.js
appeals/api/src/server/endpoints/procedure-types/procedure-types.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the Procedure Types, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-402

feat(appeals/api): add an api endpoint to get the procedure types

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/procedure-types/__tests__/procedure-types.test.js
appeals/api/src/server/endpoints/schedule-types/__tests__/schedule-types.test.js
appeals/api/src/server/endpoints/schedule-types/schedule-types.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js
apps/api/src/server/swagger-output.json

Added an API endpoint to return the Schedule Types, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-403

feat(appeals/api): add an api endpoint to get the schedule types

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/site-visit-types/__tests__/site-visit-types.test.js
appeals/api/src/server/endpoints/site-visit-types/site-visit-types.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added an API endpoint to return the Site Visit Types, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-404

feat(appeals/api): add an api endpoint to get the site visit types

---

appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/appellant-case-validation-outcomes/__tests__/appellant-case-validation-outcomes.test.js
appeals/api/src/server/endpoints/appellant-case-validation-outcomes/appellant-case-validation-outcomes.routes.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js

Describe your changes
Added an API endpoint to return the Appellant Case Validation Outcomes, which provides values that can be used to dynamically create a field list in the UI.
https://pins-ds.atlassian.net/browse/BOAT-396

feat(appeals/api): add api endpoint to get the appellant case validation outcomes

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/appellants/__tests__/appellants.test.js
appeals/api/src/server/endpoints/appellants/appellants.controller.js
appeals/api/src/server/endpoints/appellants/appellants.formatter.js
appeals/api/src/server/endpoints/appellants/appellants.routes.js
appeals/api/src/server/endpoints/appellants/appellants.service.js
appeals/api/src/server/endpoints/appellants/appellants.validators.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appellant.repository.js
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Added GET/PATCH API endpoints for Appellants. Initially this is used for saving the Appellant Name on the Appellant Case page.
Also added validation, swagger docs and unit tests.
https://pins-ds.atlassian.net/browse/BOAT-425

feat(appeals/api): add get/patch api endpoints for appellants

---

appeals/api/setup-tests.js
appeals/api/src/server/common/validators/string-parameter.js
appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
appeals/api/src/server/endpoints/addresses/addresses.controller.js
appeals/api/src/server/endpoints/addresses/addresses.formatter.js
appeals/api/src/server/endpoints/addresses/addresses.routes.js
appeals/api/src/server/endpoints/addresses/addresses.service.js
appeals/api/src/server/endpoints/addresses/addresses.validators.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
appeals/api/src/server/endpoints/appellants/__tests__/appellants.test.js
appeals/api/src/server/endpoints/appellants/appellants.validators.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.validators.js
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/address.repository.js
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js
appeals/api/src/server/utils/error-message-replacement.js

Added GET/PATCH API endpoints for Addresses. Initially this is used for saving the Site Address on the Appellant Case page.
Also added validation, swagger docs and unit tests.
Also a little refactoring for replacing hard coded max character length values with a constant and error messages that can handle dynamic replacement of values (max character length, for example).
https://pins-ds.atlassian.net/browse/BOAT-427

feat(appeals/api): add get/patch api endpoints for addresses

---

appeals/api/src/database/schema.d.ts
appeals/api/src/server/common/validators/boolean-parameter.js
appeals/api/src/server/common/validators/boolean-with-conditional-string-parameters.js
appeals/api/src/server/common/validators/string-parameter.js
appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
appeals/api/src/server/endpoints/appellants/__tests__/appellants.test.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.validators.js
appeals/api/src/server/repositories/appellant-case.repository.js
appeals/api/src/server/utils/error-message-replacement.js

Updated the PATCH Appellant Case API endpoint to enable the saving of the fields on the Appellant Case page..
Also added validation, swagger docs and unit tests.
Also a little refactoring for error message replacement so that multiple replacements can be done in a single error message.
https://pins-ds.atlassian.net/browse/BOAT-428

feat(appeals/api): update patch appellant case api endpoint to save additional fields

---

apps/api/src/server/applications/application/project-updates/notification-logs/__tests__/notification-logs.test.js

Notification log tests used several instances of new Date() that wouldn't always match, resulting in some test failures.
N/A

fix(applications/api): use single date in tests

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js

Removed name, telephone and email neighbouring site contact details from the GET Appeals API endpoint as these properties are no longer required on the Case Details page.
https://pins-ds.atlassian.net/browse/BOAT-395

feat(appeals/api): remove neighbouring site contact details from get appeals api endpoint

---

apps/api/setup-tests.js
apps/api/src/message-schemas/commands/register-representation.schema.json
apps/api/src/message-schemas/events/nsip-representation.schema.json
apps/api/src/server/applications/application/representations/__tests__/publish-representation.test.js
apps/api/src/server/applications/application/representations/publish/publish.controller.js
apps/api/src/server/applications/application/representations/publish/publish.route.js
apps/api/src/server/applications/application/representations/publish/publish.service.js
apps/api/src/server/applications/application/representations/publish/publish.validators.js
apps/api/src/server/applications/application/representations/publish/representation.js
apps/api/src/server/applications/application/representations/representations.routes.js
apps/api/src/server/applications/application/representations/status/status.service.js
apps/api/src/server/infrastructure/topics.js
apps/api/src/server/repositories/representation.repository.js
apps/api/src/server/swagger-output.json

ASB-1688
- adds new endpoint: `PATCH /applications/{id}/representations/publish`
this endpoint takes a list of representation IDs and publishes a message for each to the nsip-representation topic.
It then sets the status of each rep to PUBLISHED if they have not already been previously published, and for those that have, it sets the unpublishedUpdates flag to false.

feat(api): publish representations endpoint

---

apps/functions/deadline-submissions/deadline-submission-command/__tests__/deadline-submission-command.test.js
apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js
apps/functions/deadline-submissions/deadline-submission-command/index.js

Populate document metadata after creating the document from an FO submission. This is needed for display on the front end.
[BOAS-960](https://pins-ds.atlassian.net/browse/BOAS-960)
[BOAS-960]: https://pins-ds.atlassian.net/browse/BOAS-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(functions): populate document metadata after successful creation

---

appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.validators.js
appeals/api/src/server/utils/__tests__/date-comparison.test.js
appeals/api/src/server/utils/date-comparison.js

API updates to disallow updated due dates which are in the past for lpaq and appellant case incomplete flows
BOAT-445

fix(api): appellant case and lpaq incomplete flows - should not be able to enter past dates

---

appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.validators.js
appeals/web/src/server/lib/validators/time-input.validator.js

arrange site visit unaccompanied visit type should not require times
Update validation for set site visit route to make start and end times optional for unaccompanied visit type
BOAT-424

fix(web): arrange site visit unaccompanied visit type should not require times

---

apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js
apps/api/src/server/repositories/representation.repository.js

ASB-1736
Set `unpublishedUpdates` to `true` when redacting a Representation that has already been published (`status = 'PUBLISHED'`)

feat(api): set unpublishedUpdates when redacting published representation

---

apps/api/src/server/applications/application/representations/contacts/__tests___/delete-contact.test.js
apps/api/src/server/repositories/representation.repository.js

ASB-1737
Set `unpublishedUpdates` to `true` when deleting Contact from Representation that has been published (`status = 'PUBLISHED'`)

feat(api): set unpublishedUpdates when deleting contact from published representation

---

apps/api/src/server/applications/application/representations/__tests__/patch-representation.test.js
apps/api/src/server/applications/application/representations/attachment/__tests__/delete-attachment.test.js
apps/api/src/server/applications/application/representations/attachment/__tests__/post-attachment.test.js
apps/api/src/server/applications/application/representations/attachment/attachment.controller.js
apps/api/src/server/applications/application/representations/attachment/attachment.service.js
apps/api/src/server/repositories/representation.repository.js

ASB-1741, ASB-1743, ASB-1732
Set `unpublishedUpdates` to `true` when updating a Representation that has already been published (`status = 'PUBLISHED'`)
1. 48892fa8 - when calling `PATCH /representation/:repid`
2. 1e8ebf98 - `POST /representation/:repid/attachment`
3. 7a83971b - `DELETE /representation/:repid/attachment/:id`

feat(api): setting representation unpublishedupdates flag when updating rep

---

azure-pipelines-build.yml

We currently just copy the @pins folder. Something that must have slipped through previously.

build: copy whole node_modules for document publish function

---

appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
appeals/api/src/server/endpoints/site-visits/site-visits.validators.js
appeals/api/src/server/utils/check-strings-match.js
appeals/api/src/server/utils/check-validation-outcome.js

Updated the Appeals Site Visit POST/PATCH API endpoints to allow unaccompanied site visits to be saved without a visit time.
https://pins-ds.atlassian.net/browse/BOAT-488

fix(appeals/api): allow unaccompanied site visits to be saved without a visit time

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

Update the Appeals GET Appellant Case API endpoint to return `appellantId` and `addressId` to enable these values to be passed to the relevant Change page so they can be used to save the updated data.
Also updated some dates in the Timetable tests to put them more in the future to prevent false-positive failures for a while longer.
https://pins-ds.atlassian.net/browse/BOAT-427

fix(appeals/api): add address and appellant ids to the get appellant case api endpoint

---

appeals/api/src/server/config/config.js

Add a default value for `TEST_MAILBOX` env var.
This should fix the issue of the seeding failing in the pipeline because it can't find the TEST_MAILBOX env var.

fix(appeals/api): add a default value for test_mailbox env var

---

apps/api/src/message-schemas/events/nsip-document.schema.json
apps/api/src/message-schemas/events/nsip-representation.schema.json
apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
apps/api/src/server/applications/application/representations/publish/publish.service.js
apps/api/src/server/applications/application/representations/publish/representation.js
apps/api/src/server/applications/application/representations/publishable/__tests__/publishable-representations.test.js
apps/api/src/server/applications/application/representations/representaions.service.js
apps/api/src/server/applications/application/representations/status/__tests__/patch-status.test.js
apps/api/src/server/applications/application/representations/status/status.service.js
apps/api/src/server/repositories/__tests__/representation.repository.test.js
apps/api/src/server/repositories/representation.repository.js

ASB-1742
A change to the `PATCH /applications/{id}/representations/{repId}/status` endpoint:
When changing the status of a `Representation` from `PUBLISHED` to another value:
1. publish a `Update` event to the `nsip-representations` topic containing the `Representation` details. 
2. also set the `unpublishedUpdates` flag to `false`.

feat(api): publish event when unpublishing representation

---

appeals/api/package.json
apps/api/package.json
package-lock.json

We need prisma to be 4.16.1 - see comment in https://github.com/Planning-Inspectorate/back-office/pull/1204
We had ^4.16.1 which would allow 4.16.2
N/A

fix(tooling): fix prisma version to 4.16.1

---

apps/web/src/client/components/file-uploader/_server-actions.js

Currently when duplicates are found, the new file is not created, but it isn't clear to the user that this has happened. This change should display the error when this happens.
It's difficult to test locally because uploading files crashes the app. Will need to check it's working in dev once merged.

feat(web): provide feedback to the user when duplicates return

---

apps/api/src/server/applications/application/representations/publish/representation.js
apps/api/src/server/applications/application/representations/status/__tests__/patch-status.test.js
apps/api/src/server/repositories/representation.repository.js

bug found when testing ASB-1742
pass 'representation status update' message payload to `sendEvents` as an array. Function does not accept a non-array value as was being passed

fix(api): representation status update payload

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/views/applications/case-documentation/documentation-table.njk
apps/web/src/server/views/applications/case-s51/properties/tab-attachments.component.njk

Only allow downloading documents after they've passed the virus scan step.
[BOAS-1117](https://pins-ds.atlassian.net/browse/BOAS-1117)
[BOAS-1117]: https://pins-ds.atlassian.net/browse/BOAS-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): disallow file downloads before virus check

---

apps/functions/deadline-submissions/test-deadline-submission/function.json

Add a service bus output binding. Currently there is an error being thrown when `sendEvents` is called.
[BOAS-1110](https://pins-ds.atlassian.net/browse/BOAS-1110)
[BOAS-1110]: https://pins-ds.atlassian.net/browse/BOAS-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(functions): add a service bus output binding to test function

---

appeals/web/environment/config.js
appeals/web/environment/schema.js

Added new legal and customer service AD groups to the app configuration. Users in these groups will have a read-only view of the appeal data.

feat(appeals/web): adding additional read-only groups to AD config

---

apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
apps/api/src/server/applications/application/representations/publish/publish.controller.js
apps/api/src/server/applications/application/representations/publish/publish.route.js
apps/api/src/server/applications/application/representations/publish/publish.service.js
apps/api/src/server/applications/application/representations/publishable/__tests__/publishable-representations.test.js
apps/api/src/server/repositories/representation.repository.js

- Fixes ASB-1838: return publishable reps in desired sort order (by status, then reference)
- Fixes ASB-1843: return 400 error if no rep ids are publishable, and do not publish message to message queue

fix(api): representations publishing endpoint fixes

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/data.js

The Site Visit details are displayed on the Case Details page not the Appellant Case page so we need to ensure that this data is available in the UI.
- Remove the Site Visit data from the GET Appellant Case API endpoint
- Add Site Visit data to the GET Appeal API endpoint
https://pins-ds.atlassian.net/browse/BOAT-539

fix(appeals/api): add site visit fields to the get appeal endpoint

---

apps/api/src/server/repositories/s51-advice.repository.js

Addition to 1st PR for BOAS-1163 to also ignore deleted advice on the api that gets advice in the ready-to-publish queue
https://pins-ds.atlassian.net/browse/BOAS-1163

feat(api/applications): s51 advice delete api part 2 (boas-1163)

---

README.md
appeals/web/.env.development
appeals/web/.env.example
appeals/web/.env.test
appeals/web/environment/base-config.js
appeals/web/environment/config.d.ts
appeals/web/environment/config.js
appeals/web/environment/schema.js
appeals/web/scripts/rollup/bundle-js.js
appeals/web/scripts/rollup/compile-css.js
apps/web/.env.example
apps/web/.env.test
apps/web/environment/base-config.js
apps/web/environment/config.d.ts
apps/web/environment/config.js
apps/web/environment/schema.js
apps/web/scripts/rollup/bundle-js.js
apps/web/scripts/rollup/compile-css.js

By default `joi` treats all fields as optional, so if some environment configuration is missing there no immediate error.
Instead fields that are required are treated as such, with an error on startup. For example if missing the `web` session secret, the error would be:
```
throw new Error(`loadConfig validation error: ${error.message}`);
^
Error: loadConfig validation error: "sessionSecret" is required
```
Changes:
- create baseConfig for web, used for build steps only
- set all fields to required in the config schema
- update `.env.example` to be a working example for local development
[BOAS-1098](https://pins-ds.atlassian.net/browse/BOAS-1098)
[BOAS-1098]: https://pins-ds.atlassian.net/browse/BOAS-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

feat: ensure required config is set at startup

---

apps/api/src/server/repositories/__tests__/subscription.repository.test.js
apps/api/src/server/repositories/subscription.respository.js

`subscriptions/list` filter by `type` was broken because of a bad reference to the `Subscription.Type.` values.
[ASB-1878](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1878)
[ASB-1878]: https://pins-ds.atlassian.net/browse/ASB-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(applications/api): ensure subscriptions list filter by type works!

---

apps/web/src/server/views/applications/case/overview.njk

Currently the overview page continues to show `NOT PUBLISHED` after publishing the case. This change introduces a green `PUBLISHED` tag and the datetime at which the case was published.
[BOAS-1195](https://pins-ds.atlassian.net/browse/BOAS-1195)
[BOAS-1195]: https://pins-ds.atlassian.net/browse/BOAS-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web/applications): change to a PUBLISHED tag in after publishing

---

apps/api/src/server/repositories/representation.repository.js

Some PATCH `/applications/{id}/representations/{repId}` requests were failing with error:
```javascript
{ 
"errors": "Cannot set properties of undefined (setting 'unpublishedUpdates')" 
}
```
This was because when patching items objects that did not include `representationDetails` then this would be undefined and we would throw an error on this line:
```javascript
representationDetails.unpublishedUpdates = true
```
This PR simply adds a default value for the `representationDetails` in the `updateApplicationRepresentation` which means we don't unexpectedly throw an error when setting `representationDetails.unpublishedUpdates`.
---
Example of previously failing request
```javascript
// PATCH /applications/1/representations/363
{
"represented": {
"firstName": "Dante",
"lastName": "Alighieri" …
```

fix(applications/api): patch representation bug

---

apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js

Examination timetable page crashes if there are no exam timetable items on that case.  Fixed.
https://pins-ds.atlassian.net/browse/BOAS-1200

fix(web/applications): fix exam timetable display no items (boas-1200)

---

apps/web/src/server/applications/case/s51/applications-s51.controller.js

There is currently a logic error that blocks you from updated the title of an S51 item. This is the correct logic.
Tested locally
[BOAS-1207](https://pins-ds.atlassian.net/browse/BOAS-1207)
[BOAS-1207]: https://pins-ds.atlassian.net/browse/BOAS-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): only refresh s51 title page if title isn't unique

---

appeals/api/package.json
appeals/api/src/database/seed/seed-clear.js

Changed npm script to run the db:seed
Update appeals to remove user refs when seeding
Delete audit data before users when seeding

chore(appeals/api): trying to fix DB seed

---

appeals/api/package.json
appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/documents/documents.mapper.js
appeals/api/src/server/utils/business-days.js

Moves the following config settings to static constants:
- AppealTimetable
- AppealFolderPaths
- AppealStages
Reverted the npm script for db:seed
Unit tests ok, db:seed ok locally.

chore(appeals): moved static config to constants

---

apps/api/src/database/seed/seed-clear.js

Fix to make seeding script work again.  Specifically, deleting of certain new tables: 
- DocumentActivityLog
- S51Advice
- S51AdviceDocument
- ExaminationTimetable
https://pins-ds.atlassian.net/browse/BOAS-1216

fix(api/applications): add missing tables to seed script (boas-1216)

---

apps/web/src/client/components/html-content-editor/html-content-editor.js
apps/web/src/server/applications/case/project-updates/project-updates.mapper.js

Copy+pasted update content could fail the sanitisation check, so strip out `&nbsp;` from copied content.
[ASB-1929](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1929)
[ASB-1929]: https://pins-ds.atlassian.net/browse/ASB-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(applications/web): remove &nbsp; from copied update content

---

apps/web/src/server/applications/case/s51/applications-s51.service.js

Render the proper error from the API when trying to change the status of an S51 item that is already published.
[BOAS-1204](https://pins-ds.atlassian.net/browse/BOAS-1204)
[BOAS-1204]: https://pins-ds.atlassian.net/browse/BOAS-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): render proper error on S51 status change

---

apps/api/src/server/applications/application/documents/document.controller.js

Reducer function is missing the `...acc` line which builds up the accumulated value rather than overwriting it.
* fix(api/applications): do not overwrite previous version history
Reducer function is missing the `...acc` line which builds up the
accumulated value rather than overwriting it.
[BOAS-1226](https://pins-ds.atlassian.net/browse/BOAS-1226)
[BOAS-1226]: https://pins-ds.atlassian.net/browse/BOAS-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): do not overwrite previous version history

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/documentation-delete.njk

Use the `author` property on the document to fill the `From` column on the delete page.
[BOAS-1159](https://pins-ds.atlassian.net/browse/BOAS-1159)
[BOAS-1159]: https://pins-ds.atlassian.net/browse/BOAS-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): display document author on delete page

---

apps/api/src/server/repositories/document.repository.js

* fix(api/applications): fix logic error when counting documents
The `getAllDocuments` argument should only affect the `where` clause
when it is `false`.
$$
getAllDocuments = true \implies isDeleted = true\ ||\ isDeleted = false
$$
$$
getAllDocuments = false \implies isDeleted = false
$$
[BOAS-1267](https://pins-ds.atlassian.net/browse/BOAS-1267)
[BOAS-1267]: https://pins-ds.atlassian.net/browse/BOAS-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): fix logic error when counting documents

---

apps/api/src/server/applications/s51advice/s51-advice.js

* fix(api/applications): use document GUIDs instead of relation IDs
Front Office don't have knowledge of our mapping table, so using these IDs will make no sense on their end. We should use the document GUID instead.
[BOAS-1267](https://pins-ds.atlassian.net/browse/BOAS-1267)
[BOAS-1267]: https://pins-ds.atlassian.net/browse/BOAS-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): use document GUIDs instead of relation IDs

---

apps/api/src/server/applications/application/documents/document.service.js

Include the `owner` when creating document versions. We don't currently do this, so after unpublishing, it says it was the `System` that acted rather than the user.
I can't test this locally as it is a step that happens post-crash when you upload a file. Will need to test in dev.

fix(api/applications): include the owner when creating document versions

---

apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
apps/web/src/server/views/applications/case-documentation/documentation-unpublish.njk

The back link is currently not working on the unpublish queue page.

fix(web/applications): fix back link on document unpublish queue page

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/components/folder/folder-actions.component.njk

Use a relative path for the unpublish `formaction`.
There is currently a bug in dev where the wrong error message shows up after clicking the 'Unpublish selected' button. I suspect it's an issue with the path but I'll need to test in dev.

fix(web/applications): use a relative path for unpublish formaction

---

apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js
apps/api/src/server/applications/application/project-updates/project-updates.validators.js
apps/api/src/server/migration/migrators/nsip-project-update-migrator.js

As per title, allowing `mailto:` links in project updates, which are used quite often.
[BOAS-1307](https://pins-ds.atlassian.net/browse/BOAS-1307)
[BOAS-1307]: https://pins-ds.atlassian.net/browse/BOAS-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(applications/api): allow mailto links in project updates

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/mappers/appeal.mapper.js
appeals/web/src/server/lib/mappers/global-mapper-formatter.js
appeals/web/src/server/lib/times.js

Add the start and end times of site visits as described in the prototype.
[BOAT-540](https://pins-ds.atlassian.net/browse/BOAT-540)
[BOAT-540]: https://pins-ds.atlassian.net/browse/BOAT-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals/web): add time display to site visit in appeals details

---

apps/api/src/database/schema.d.ts
apps/api/src/message-schemas/events/nsip-exam-timetable.d.ts
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.routes.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
apps/api/src/server/repositories/examination-timetable.repository.js
apps/api/src/server/swagger-output.json

- Fix for Error publishing exam timetable on a case.  The original code used to include the Exam Type record with the Exam Items, as the type.name is needed in the map fn for publishing, but this is missing in the latest fn.  Amended to include this.
- also fixed some type errors / mismatches, and swagger api definitions
https://pins-ds.atlassian.net/browse/BOAS-1322

fix(api/applications): fix error publishing timetable (boas-1322)

---

apps/functions/document-publish/unpublish-document/config.js

fix to Document Unpublish function app code, to ensure the blob source container name (which the passing doc URI contains) is correctly pulled from config, used to split the string.
Tested in Azure Dev
https://pins-ds.atlassian.net/browse/BOAS-1321

fix(functions): fix azure doc unpublishing 2 (boas-1321)

---

apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.validators.js

Allow Document Transcription Reference to be cleared by a user.  
API modified to allow blank value, and to set the DB field transcriptGuid to null.
- The other 2 scenarios on the bug ticket (MP3 and MP4 issues) appear to be solved already
https://pins-ds.atlassian.net/browse/BOAS-1316

fix(api/applications): allow clearing document transcript ref (boas-1316)

---

apps/api/src/server/app.js
apps/api/src/server/config/schema.js

fix(api/applications): skip initialising app insights locally
[BOAS-481](https://pins-ds.atlassian.net/browse/BOAS-481)
[BOAS-481]: https://pins-ds.atlassian.net/browse/BOAS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): skip initialising app insights locally

---

appeals/api/src/database/migrations/20231130170615_document_version_refactor/migration.sql
appeals/api/src/database/schema.prisma
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
appeals/api/src/server/endpoints/documents/documents.controller.js
appeals/api/src/server/endpoints/documents/documents.formatter.js
appeals/api/src/server/endpoints/documents/documents.routes.js
appeals/api/src/server/endpoints/documents/documents.validators.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/document.repository.js
appeals/api/src/server/swagger.js
appeals/functions/document-processing/document-copy/function.json
appeals/functions/document-processing/malware-detection/back-office-api-client.js
appeals/functions/document-processing/malware-detection/index.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

Implementation of AV scanning and document metadata updates:
- Azure function reporting AV scan status through EventGrid
- API endpoint to update the `virusCheckStatus` field in document versions
- Introduced a `draft` flag on the document version, to replace the current use of the `published` flag
- Refactored the DocumentVersion SQL table to remove unused fields
[BOAT-710](https://pins-ds.atlassian.net/browse/BOAT-710)
- [ x I have performed a self-review of my own code
[BOAT-710]: https://pins-ds.atlassian.net/browse/BOAT-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals): av scan result and api

---

appeals/api/src/server/endpoints/documents/documents.controller.js
appeals/api/src/server/repositories/document.repository.js
appeals/functions/document-processing/malware-detection/index.js
appeals/web/src/server/app/components/file-downloader.component.js

Fix the regex to get document guid and version from documentURI
Throws an error when trying to download a file not scanned successfully

fix(appeals): av scan regex and block downloads

---

apps/api/Dockerfile

Use npm script instead of npx directly in Dockerfile.
The dev build is failing when running `npx prisma generate`. I suspect it might be because of a version mismatch--using the script in package.json should prevent this.

fix(api/applications): use npm script instead of npx directly in Docker

---

appeals/api/src/server/repositories/integrations.repository.js

When creating a new appeal as a result of an integration with the FO, the status should be 'assign_case_officer'

fix(appeals/api): new appeals default to assign_case_officer

---

apps/web/src/server/views/applications/case-documentation/documentation-unpublish.njk

Form for unpublishing multiple documents was pointing to the wrong endpoint, and therefore being blocked by a validator which shouldn't have been running at that stage.
[BOAS-1380](https://pins-ds.atlassian.net/browse/BOAS-1380)
[BOAS-1380]: https://pins-ds.atlassian.net/browse/BOAS-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): correct unpublish documents form endpoint

---

apps/api/src/server/applications/application/representations/representaions.service.js
apps/api/src/server/applications/application/representations/representations.controller.js
apps/api/src/server/repositories/__tests__/representation.repository.test.js
apps/api/src/server/repositories/representation.repository.js

Fixes issue with `GET /applications/{id}/representations/{repId}` endpoint where passing `caseId` parameter caused an error to be thrown due to Prisma's `findUnique` function only allowing a single parameter to be passed in the `where` section. Passing `{ id: 1, caseId: 2 }` is invalid so I have simplified it to be `{ id: 1 }` - removing `caseId`, as it is not needed anyway.
To replicate:
- Call the  `GET /applications/{id}/representations/{repId}` endpoint
- for example, on dev: `GET /applications/2133/representations/7707`
- An error is returned: `Argument where of type RepresentationWhereUniqueInput needs exactly one argument, but you provided id and case.\nUnknown arg `case` in where.case for type RepresentationWhereUniqueInput`
Root cause appears to be passing `caseId` and `id` to …

fix(api/applications): remove caseId param from representation.getById

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
appeals/web/src/server/appeals/appeal.constants.js
appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
appeals/web/src/server/lib/mappers/notification-banners.mapper.js
appeals/web/src/server/views/appeals/documents/manage-document.njk
appeals/web/src/server/views/appeals/documents/manage-folder.njk
appeals/web/src/server/views/patterns/display-page.pattern.njk
appeals/web/testing/app/fixtures/referencedata.js

Adds notification banner when file that affects current screen is being scanned:
Appellant Case
LPAQ
Manage folder
Manage Document
Adds error message when file that affects current screen has failed a virus scan:
Appellant Case
LPAQ
Manage folder
Manage Document
[BOAT-711](https://pins-ds.atlassian.net/browse/BOAT-711)
[BOAT-711]: https://pins-ds.atlassian.net/browse/BOAT-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals/web): add notification banner and error banner for virus status

---

apps/api/src/database/seed/data-samples.js
apps/api/src/database/seed/data-test.js

Updated the seeding script so that the representations seed data matches the latest schema changes (ServiceUser)
- Also populates the type field which is currently blank
https://pins-ds.atlassian.net/browse/BOAS-1390

fix(api/applications): seeding reps bug (BOAS-1390)

---

appeals/api/src/server/repositories/document-metadata.repository.js

The DB transaction adding new document versions was missing a where clause, causing the errors reported.
[BOAT-763](https://pins-ds.atlassian.net/browse/BOAT-763)
[BOAT-763]: https://pins-ds.atlassian.net/browse/BOAT-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals/api): BOAT-763 bug adding random versions to other documents

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/views/patterns/display-page.pattern.njk

constrain notification banner to 2/3 width on display pages
BOAT-787

fix(web): constrain notification banner to 2/3 width on display pages

---

apps/api/src/server/applications/s51advice/s51-advice.service.js

S51 Advice publishing fails on the service bus event broadcast for documents, when there are no attached documents. Fix to only attempt doc publishing for S51 advice if there are attached documents
- also ensured the publishedDocs call uses await, as it is async
https://pins-ds.atlassian.net/browse/BOAS-1394

fix(api/applications): unable to publish s51 advice no docs (boas-1394)

---

apps/api/src/server/applications/application/documents/document.service.js

the previous PR fixed S51 advice publishing for advice without documents attached, but Advice with docs fails to publish.  This fixes this by only publishing docs that have been verified as ready for publishing (eg required properties are complete)
https://pins-ds.atlassian.net/browse/BOAS-1394

fix(api/applications): unable to publish s51 advice 2 (boas-1394)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/properties/tab-details.component.njk

- Rename 'Case stage' to 'Document case stage' within the 'Document properties' tab
- Amend unit test to work with the change
This has been tested manually to make sure that 'Document case stage' is displayed within the 'Document properties' tab.
https://pins-ds.atlassian.net/browse/BOAS-1371

feat(web/applications): rename case stage to document case stage (BOAS-1371)

---

apps/web/src/server/views/applications/case-s51/s51-publishing-queue.njk

When the S51 publishing queue is empty, it displays `Showing 1 - 0 items` because we explicitly add 1 to the lower bound of items being shown; when there are no items being shown this resolves to 1.
[BOAS-1425](https://pins-ds.atlassian.net/browse/BOAS-1425)
[BOAS-1425]: https://pins-ds.atlassian.net/browse/BOAS-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): fix incorrect item range for S51 publishing queue

---

apps/functions/document-publish/package.json
package-lock.json

…
The publish function was erroring:
```
'Cannot find package '@pins/platform' imported from /home/site/wwwroot/publish-document/config.js' 
```
This was broken inadvertently when the function build was changed. Before it copied all packages, now it just copies the actual dependencies. Since platform wasn't in package.json, it broke.
[BOAS-1419](https://pins-ds.atlassian.net/browse/BOAS-1419)
[BOAS-1419]: https://pins-ds.atlassian.net/browse/BOAS-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(functions/document-publish): add @pins/platform dependency to package.json

---

apps/functions/applications-migration/common/back-office-api-client.js
apps/functions/applications-migration/common/config.js
apps/functions/applications-migration/common/synapse-db.js
apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js

Split up function `config` / `loadConfig` into separate parts: api, synpase and wordpress. Allows for each function to only import the config it needs. 
Fixes an issue where the `project-updates` migration function fails in production due to the Synapse host environment variable not being defined. That function now only imports the config it needs (wordpress)
https://pins-ds.atlassian.net/browse/BOAS-1423

fix(functions): split config into separate functions

---

appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.middleware.js

Missed AWAITING_TRANSFER in the states that cannot be changed

fix(appeals/api): adds awaiting_transfer to states

---

apps/api/src/server/migration/migrators/nsip-subscription-migrator.js
apps/api/src/server/migration/migrators/utils.js

Fixes issue with `/migration/nsip-subscription` endpoint where is was attempting to write to the `emailAddress` field in the `Subscription` table, which no longer exists. Updated the implementation to fetch or create the ServiceUser associated with the email, and link the `Subscription` and `ServiceUser` via `serviceUserId`
https://pins-ds.atlassian.net/browse/BOAS-1423

fix(api/applications): subscription service user migration

---

apps/api/src/database/migrations/20240112144180_remove_city_town_junction_from_zoomlevels_table/migration.sql
apps/api/src/database/seed/data-static.js

- Remove the zoom levels of city, town and junction from the data static definition
- Add a migration to make sure all application detail records with a zoom level of city, town or junction are updated to have a zoom level of district and to remove those zoom levels from the zoom level table
This has been tested manually to make sure the zoom levels of city, town and junction are no longer available.
https://pins-ds.atlassian.net/browse/BOAS-1331

fix(applications/api): remove some of the options from map zoom level list (BOAS-1331)

---

apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/views/applications/case-s51/properties/s51-properties.njk
apps/web/src/server/views/applications/components/folder/folder-status.component.njk

- Changed the S51 advice copy as described in the linked ticket
- Updated the affected web unit tests
This has been tested manually to make sure the S51 Advice copy is now as expected.
https://pins-ds.atlassian.net/browse/BOAS-1258

fix(applications/web): fix S51 advice copy (BOAS-1258)

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk

- Increased the height of the description field from 5 rows to 20 rows
- Updated the affected web unit tests
This has been tested manually to make sure the description field height has increased.
https://pins-ds.atlassian.net/browse/BOAS-1349

feat(applications/web): Increase height of description field for Examination Timetable (BOAS-1349)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/lib/validators/date-input.validator.js

Fixes async validator for calculating business days.

fix(appeals): async validator needs to return a rejected promise

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/applications/create-new-case/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap
apps/web/src/server/lib/nunjucks-filters/bold.js
apps/web/src/server/lib/nunjucks-filters/index.js
apps/web/src/server/lib/nunjucks-filters/key-dates-property.js
apps/web/src/server/views/applications/case-key-dates/key-dates-section.njk
apps/web/src/server/views/applications/components/case-form/key-dates/date-published.njk
apps/web/src/server/views/applications/components/inputs/date-input.component.njk

- Amend key date names where required
- Amend explainer copy on certain key dates
- Add additional explainer copy in bold when required
- Update the dateInput component to use the govukHint component to allow formatting of the hint with html
- Fix affected unit tests for web (Note that the hint id has been corrected to give an id of "{{fileName}}-hint" 
This has been tested manually to make sure the above changes have been made correctly.
https://pins-ds.atlassian.net/browse/BOAS-1042

feat(applications/web): Amend key date name and update explainer copy on certain key dates (BOAS-1349)

---

apps/api/src/server/repositories/folder.repository.js

- Set `Developer's Application` as the document case stage for documents uploaded to the folder `Application documents`
This has been tested manually to make sure that for any new case,  `Developer's Application` is the value displayed in the Document properties for any uploaded documents in the `Application documents` folder.
https://pins-ds.atlassian.net/browse/BOAS-1443

fix(applications/web): application documents folder needs developers application (BOAS-1443)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/properties/tab-details.component.njk

- Rename incorrectly named 'Documentation case stage' to 'Document case stage' within the 'Document properties' tab
- Amend unit test to work with the change
This has been tested manually to make sure that 'Document case stage' is displayed within the 'Document properties' tab.
https://pins-ds.atlassian.net/browse/BOAS-1439

fix(applications/web): fix document case stage copy (BOAS-1439)

---

apps/api/src/server/applications/application/documents/document.js

- Amend the validation of required properties to ignore publishedBlobPath and publishedBlobContainer if they are not present
- Report on which required properties are missing in the error message if thrown
- Don't attempt to populate the publishedDocumentURI if publishedBlobPath is missing
This has been tested manually to make sure that documents can be published for an S51 Advice,  This should also solve the issue [BOAS-1437](https://pins-ds.atlassian.net/browse/BOAS-1437) as this was a bug that affected publishing all documents.
https://pins-ds.atlassian.net/browse/BOAS-1449
[BOAS-1437]: https://pins-ds.atlassian.net/browse/BOAS-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(applications/api): unable to publish a document for s51 advice (BOAS-1449)

---

apps/web/src/server/applications/case/representations/representation-details/representation-status/representation-status-notes/__tests__/representation-status-notes.test.js
apps/web/src/server/applications/case/representations/representation-details/representation-status/representation-status-notes/representation-status-notes.view-model.js

- Remove test option from representation invalid
- Fix unit tests
This has been tested manually to make sure the 'TEST' option is no longer displayed
https://pins-ds.atlassian.net/browse/BOAS-1391

fix(applications/web): remove test option from representation invalid (BOAS-1391)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js
apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
apps/web/src/server/views/applications/case-documentation/documentation-delete.njk

The steps 1, 2, 4, and 5 of the ticket have been implemented in this PR as follows:
- Amended the title in the documentation delete page to ‘Delete document’.
- Added the warning ‘This will delete all versions of this document.’
- Added the case name to the successful delete page.
- Added the case reference to the successful delete page.
Note that step 3 has not been implemented as a long filename already wraps to the next line but only if there are spaces in the filename.  I don't think it's possible to wrap the filename when there are no spaces in the name as I've tried several possible solutions that have all failed.
The changes have been tested manually to make sure the user journey works as expected for the deletion of a document for steps 1, 2, 4 and 5 in the ticket. …

feat(applications/web): updates to delete document and success pages (BOAS-1237)

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/views/applications/case-timetable/timetable-success-banner.njk

- Remove return to folder text from timetable success banner
- Fix unit tests
https://pins-ds.atlassian.net/browse/BOAS-1327

feat(applications/web): remove return to folder text (BOAS-1327)

---

apps/web/src/server/app/config/session.js

In production an error is thrown if Redis can't initialise, but in dev and test we want to allow this while making it clear that Redis was bypassed. Locally we expect developers not to be running Redis, so we'll use express-session.
* chore(web/applications): display a warning if bypassing Redis
In production an error is thrown if Redis can't initialise, but in dev
and test we want to allow this while making it clear that Redis was
bypassed. Locally we expect developers not to be running Redis, so we'll
use express-session.
[BOAS-1034](https://pins-ds.atlassian.net/browse/BOAS-1034)
[BOAS-1034]: https://pins-ds.atlassian.net/browse/BOAS-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(web/applications): display a warning if bypassing Redis

---

apps/web/src/client/components/html-content-editor/__tests__/html-content-editor.test.js
apps/web/src/server/applications/case/project-updates/project-updates.view-model.js
apps/web/src/server/views/applications/components/html-content-editor.njk

The content passed into the toastUI editor must match the format it expects to handle line breaks correctly.
- Make sure the html editor is initialised with the content converted to the format expected by the toastUI editor
- Added a unit test to make sure extra lines are not added when nothing is changed
https://pins-ds.atlassian.net/browse/BOAS-1308

fix(applications/web): prevent extra newline added when going back to edit (BOAS-1308)

---

appeals/web/src/client/components/file-uploader/_client-actions.js

add beforeunload listener to display native browser confirmation dialog when user attempts to navigate away from file upload page while upload is still in progress
BOAT-831

feat(web): file upload back modal

---

apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
apps/api/src/server/utils/mapping/__tests__/map-examination-timetable-item-description.test.js
apps/api/src/server/utils/mapping/map-examination-timetable-item-description.js

After splitting the Exam Timetable Item Description, remove new lines from items before saving to the database.
- Make sure the new lines are removed from items before saving to the database
- Make sure new lines are added to items after retrieving from the database
https://pins-ds.atlassian.net/browse/BOAS-1461

fix(applications/api): format exam timetable item description items (BOAS-1461)

---

apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js
apps/web/src/server/views/applications/case-timetable/timetable-success-banner.njk

Corrected text in timetable item success banner
- Updated the timetable success banner to replace 'Timetable successfully' with 'Timetable item successfully'
- Updated the web unit tests to match
- Updated the e2e test to match
This has also been tested manually
https://pins-ds.atlassian.net/browse/BOAS-1327

fix(applications/web): fix timetable item success page (BOAS-1327)

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/web/testing/app/fixtures/referencedata.js

Additional API changes to remove old appellant fields.
BOAT-676

feat(appeals/api): clearing up old fields for BOAT-676

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case/project-documentation.njk
apps/web/src/styles/7-components/link-menu.scss
apps/web/src/styles/main.scss

- Create a new scss component for the class pins-link-menu
- Add a div for the links with the pins-link-menu class
- Fix the web unit tests
https://pins-ds.atlassian.net/browse/BOAS-1465

fix(applications/web): fix highlighting in project documentation link menu (BOAS-1465)

---

apps/web/src/server/app/auth/__tests__/auth.test.js
apps/web/src/server/app/auth/auth.controller.js

* fix(web/applications): log user out before destroying session
There is currently an error when trying to logout. It seems to be caused by the session being destroyed before the cache can be cleared for the relevant account.

fix(web/applications): log user out before destroying session

---

apps/web/src/server/views/applications/case-s51/properties/edit/s51-edit-advice-detail.njk
apps/web/src/server/views/applications/case-s51/properties/edit/s51-edit-enquiry-details.njk
apps/web/src/server/views/applications/layouts/s51-edit.layout.njk
apps/web/src/styles/7-components/s51-edit-form.scss
apps/web/src/styles/main.scss

- Fix s51-layout css classes so all controls including the buttons line up correctly
- Fix the classes in both the "Edit advice details" and "Edit enquiry details" so the button is under the text area as expected
- Checked the web unit tests for any regression
All s51 advice property edit pages have been tested manually
https://pins-ds.atlassian.net/browse/BOAS-1208

fix(applications/web): fix s51 advice property edit pages styling (BOAS-1208)

---

apps/api/src/server/applications/application/representations/representation.mapper.js
apps/api/src/server/repositories/__tests__/representation.repository.test.js
apps/api/src/server/repositories/representation.repository.js
apps/functions/applications-command-handlers/register-representation-command/__tests__/register-representation-command.test.js
apps/functions/applications-command-handlers/register-representation-command/index.js
packages/applications/types/representation.d.ts

Bug fix for relevant reps command messages:
1) Fix reference Id issue where if API is invoked then POST creates a BO reference ignoring the Front Office reference.
2) Fix status issue so that reps arriving from Front Office a put into AWAITING_REVEW status rather than defaulting to DRAFT.
Unit tested and tested locally via API.
https://pins-ds.atlassian.net/browse/ASB-2229

fix(api): fix integration of reps representation reference and status

---

apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/repositories/document-metadata.repository.js

On publish/unpublish, set training cases to published/unpublished (respectively) immediately rather than waiting for the Azure function to run.
[BOAS-1466](https://pins-ds.atlassian.net/browse/BOAS-1466)
[BOAS-1466]: https://pins-ds.atlassian.net/browse/BOAS-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api/applications): set training documents to published immediately

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/appeals/appeals.controller.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.routes.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.service.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.validators.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/linked-appeals/mocks.js

Adds 3 new endpoints to the API:
- Links an appeal to the current appeal: `/#/Linked%20Appeals/post_appeals__appealId__link_appeal`
- Links a legacy (Horizon) appeal to the current appeal: `/#/Linked%20Appeals/post_appeals__appealId__link_legacy_appeal`
- Remove a linked appeal from the current appeal: `/#/Linked%20Appeals/delete_appeals__appealId__unlink_appeal`
[BOAT-655](https://pins-ds.atlassian.net/browse/BOAT-655)
[BOAT-655]: https://pins-ds.atlassian.net/browse/BOAT-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals/api): endpoints to manage current and legacy linked appeals

---

apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
apps/api/src/server/applications/application/representations/publish/publish.service.js
apps/api/src/server/applications/application/representations/representations.service.js

Change to the send of publish relevant reps so that the status is sent as 'PUBLISHED' rather than 'VALID'.  
We only want to do this specifically on the publish of reps rather than patch of status/redaction or other messages sent on create and update for ODW.
A wrapper has been created specifically for the publish service so that the status is updated on the message payload.
This does mean that the message is sent with Published status set optimistically before the DB has updated, however the message is idempotent and in the rare case of DB update failure a republish will sync BO with FO.
https://pins-ds.atlassian.net/browse/ASB-2246

fix(api): fix for publishing of reps where status being sent as valid

---

apps/functions/applications-background-jobs/notify-subscribers/src/back-office-api-client.js
apps/web/src/server/applications/case/representations/__tests__/applications-representaions.test.js
apps/web/src/server/applications/common/components/__tests__/build-query-string.unit.test.js
apps/web/src/server/applications/common/components/build-query-string.js

- Replaced usages of querystring with URLSearchParams accounting for the differences
- Created a unit test to ensure undefined values are treated as they were before
- Created a unit test to ensure array values are treated as they were before
The Relevant representations page has been tested manually to make the filters work correctly as they did previously
https://pins-ds.atlassian.net/browse/BOAS-1113

chore(applications): remove usage of querystring (BOAS-1113)

---

apps/api-testing/tests/inspector/inspector.test.js
apps/api-testing/tests/region/region.test.js
apps/api-testing/tests/sector/sector.test.js
apps/api-testing/tests/zoom-level/zoom-level.test.js
apps/api/src/server/build-app.js

- Replaced the catch-all 405 error with a catch-all 404 error
- Updated application-service tests to expect a 404 instead of a 405 when the route does not exist
The missing routes were tested using postman.
I have been unable to run the application-service tests locally, but I expect them to work as expected when they do run.
https://pins-ds.atlassian.net/browse/BOAS-1009

chore(applications): stop returning 405 for unregistered routes (BOAS-1009)

---

appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.service.js

Fixes the logic for assigning additional linked appeals:
- Can only add child appeals to an existing parent appeal (as long as the child is not already linked)
- Cannot add any lead or child relationship to an existing child appeal

fix(appeals/api): logic to add linked appeals

---

apps/api/src/server/applications/application/__tests__/update-application.test.js
apps/api/src/server/applications/subscriptions/subscriptions.service.js
apps/api/src/server/infrastructure/event-broadcasters.js

* feat(api/applications): add entityType header to SERVICE_USER events
This will allow consumers of this event type to create correlation
filters based on the type of user.
[BOAS-1409](https://pins-ds.atlassian.net/browse/BOAS-1409)
[BOAS-1409]: https://pins-ds.atlassian.net/browse/BOAS-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api/applications): add entityType header to SERVICE_USER events

---

apps/api/src/server/applications/application/representations/__tests__/create-representation.test.js
apps/api/src/server/applications/application/representations/__tests__/patch-representation.test.js
apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js
apps/api/src/server/applications/application/representations/representations.service.js
apps/api/src/server/applications/application/representations/status/__tests__/patch-status.test.js

Fix for publishing messages for representations.  Currently failing because the message is being sent as an object rather than a list.
https://pins-ds.atlassian.net/browse/ASB-2258

fix(api): send representation messages as list to fix update bug

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.controller.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/tests/appeals/mocks.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/lib/mappers/appeal.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

Adds an inset to the case details page, if the case is complete. The inset is under the status tag and contains the decision information.
[BOAT-610](https://pins-ds.atlassian.net/browse/BOAT-610)
[BOAT-610]: https://pins-ds.atlassian.net/browse/BOAT-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals): inset for completed appeal

---

apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk

As the optional/mandatory fields were changing causing the generic template types not to be so generic, It was easier to implement the required changes by making the template types specific to each particular examination timetable type.
- Updated the view to create a new deadline timetable item to make sure the static text is displayed
The create a new deadline timetable item page has been tested manually to make sure the static text is displayed as expected
https://pins-ds.atlassian.net/browse/BOAS-1497

fix(applications/web): deadline static text missing (BOAS-1497)

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk

As the optional/mandatory fields were changing causing the generic template types not to be so generic, It was easier to implement the required changes by making the template types specific to each particular examination timetable type.
- Updated the view to create a new deadline timetable item to make sure the static text is displayed
- Removed the redundant code from the timetable controller
- Fixed the web tests to make sure the snapshot displays the static text
The create a new deadline timetable item page has been tested manually to make sure the static text is displayed as expected
https://pins-ds.atlassian.net/browse/BOAS-1497

fix(applications/web): fix deadline static text missing (BOAS-1497)

---

apps/api/src/server/applications/application/documents/document.service.js
packages/event-client/src/local-event-client.js
packages/event-client/src/service-bus-event-client.js

- Suppress the events for publishing and unpublishing when the sector is training
- Add more information the "No events provided" error thrown in the service-bus-event-client
- Make the local-event-client throw like the service-bus-event-client does to make it easier to debug
I tested the above manually to make sure the publishing and unpublishing of documents do not fail when the sector is training
https://pins-ds.atlassian.net/browse/BOAS-1503

fix(applications/api): do not send publish document events when training (BOAS-1503)

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/appeals.controller.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js

Display the Virus scanning status tag on the appeal decision.

feat(appeals/web): display virus scan status on decision letter

---

apps/api/src/database/seed/data-static.js
apps/api/src/server/repositories/raw_sql_queries/update-application-reference.sql

The seeded data for a training sub sector abbreviation "TRAIN01" was more than 4 characters long causing issues with the query generating the next reference number.  The sql has been changed to allow for differing sub sector abbreviation lengths.
I tested the above manually to make sure new cases with a sub sector of training create new reference numbers as expected.
https://pins-ds.atlassian.net/browse/BOAS-1507

fix(applications/api): case reference number does not increment for training (BOAS-1507)

---

appeals/api/src/server/repositories/integrations.repository.js

When developing linked appeals, we introduced a bug in the LPAQ import, related to nearby case reference and `other appeals` functionality. As this was work in progress, that functionality has been removed until we have the full requirements for `other appeals`.

fix(appeals/api): disable lpaq import of other appeals

---

appeals/api/src/database/seed/data-static.js
appeals/api/src/server/endpoints/constants.js

Adjust the mapping of appeal types as described in BOAT-883.
2 appeal types have been commented out but not removed: these will be for migration of discontinued types, and will require some DB remodelling which is best left after the ODW schemas agreements.
[BOAT-883](https://pins-ds.atlassian.net/browse/BOAT-883)
[BOAT-883]: https://pins-ds.atlassian.net/browse/BOAT-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals/api): remapped appeal types (BOAT-883)

---

apps/api/src/server/applications/application/__tests__/start-case.test.js
apps/api/src/server/applications/application/application.service.js
apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
apps/api/src/server/infrastructure/event-broadcasters.js
apps/api/src/server/infrastructure/payload-builders/nsip-folder.js
apps/api/src/server/infrastructure/topics.js

- Added "nsip-folder" events for the folders and subfolders when a case is started.
- Added "nsip-folder" events for the folder and subfolders create, update and delete actions within the examination timetable pages.
- Amended unit tests to test for the existence of the events as above.
- Manually tested the creation of the "nsip-folder" events while starting a case..
- Manually tested the creation of the "nsip-folder" events while creating, updating and deleting examination timetable items.
https://pins-ds.atlassian.net/browse/BOAS-1432

feat(applications/api): add event broadcasts nsip-folder (BOAS-1432)

---

apps/api/src/server/applications/application/application.validators.js
apps/api/src/server/applications/application/documents/__tests__/create-document.test.js
apps/api/src/server/applications/application/documents/__tests__/delete-document.test.js
apps/api/src/server/applications/application/documents/__tests__/document-payload.test.js
apps/api/src/server/applications/application/documents/__tests__/document.service.test.js
apps/api/src/server/applications/application/documents/__tests__/mark-as-published.test.js
apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js
apps/api/src/server/applications/application/documents/__tests__/store-document-metadata.test.js
apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.js
apps/api/src/server/applications/application/documents/document.routes.js
apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/applications/documents/documents.controller.js
apps/api/src/server/applications/documents/documents.service.js
apps/api/src/server/applications/s51advice/__tests__/s51-advice-update.test.js
apps/api/src/server/applications/s51advice/__tests__/s51-advice.test.js
apps/api/src/server/applications/s51advice/s51-advice.controller.js
apps/api/src/server/repositories/document-metadata.repository.js
apps/api/src/server/repositories/document.repository.js

(bad commit here: https://github.com/Planning-Inspectorate/back-office/pull/2105)
Ensure events are broadcast for NSIP Documents, for all CRUD action and other changes
- create event broadcast and and tests added - works for Normal docs and S51 Advice docs
- update event broadcast and tests for:
-- new doc version
-- normal metatdata property updates
-- status and redaction status changes
-- reverting document publish status
-- publishing
- delete - event broadcast and tests added
- Also refactored some document records function names
https://pins-ds.atlassian.net/browse/BOAS-1431

feat(api/applications): event broadcasts nsip document (boas-1431)

---

apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js
apps/api/src/server/applications/application/documents/document.service.js

- Amended the document service to make sure there are nsip-document events (not created when training) before attempting to send them.
- Amended unit tests to include a training case as well as a non-training case too prove the changes work.
- Manually tested updating a document status to "ready to publish" for both a training case and a non-training case.
https://pins-ds.atlassian.net/browse/BOAS-1527

fix(applications/api): unable to publish the document due to errors (BOAS-1527)

---

apps/api/src/database/schema.prisma
apps/api/src/server/applications/application/application.service.js
apps/api/src/server/applications/project-team/__tests__/project-team.test.js
apps/api/src/server/applications/project-team/project-team.controller.js
apps/api/src/server/infrastructure/event-broadcasters.js
apps/api/src/server/infrastructure/payload-builders/nsip-project.js
apps/api/src/server/repositories/case.repository.js
apps/web/.env.example
apps/web/environment/config.d.ts
apps/web/environment/config.js
apps/web/environment/schema.js
apps/web/src/server/applications/case/project-team/application-project-team.azure-service.js

- Added a relation between Case and ProjectTeam in the prisma schema.
- Added an option to retrieve the related project team when getting the case data from the db.
- Amended building the nsip-project event data to include the project team data when available.
- Updated the api unit tests to support the changes.
- Added the ability to simulate the AD user data with dummy user data to make it easier to develop locally where AD is unavailable.
I have also tested the functionality above manually.
Reseeding has been tested to make sure it is unaffected.
https://pins-ds.atlassian.net/browse/BOAS-1434

feat(applications): add event broadcasts nsip-project case team (BOAS-1434)

---

appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js

[BOAT-843](https://pins-ds.atlassian.net/browse/BOAT-843)
[BOAT-843]: https://pins-ds.atlassian.net/browse/BOAT-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals/web): BOAT-843 clicking on "back to your list" navigates to national list as opposed to personal list on Appeal Closed page

---

appeals/api/src/server/utils/format-linked-appeals.js

A small fix which corrects the logic of which information to return in related appeals: `appealId` and `appealRef` are the identifiers for the related appeal, not the current one. `appealId` can be null if the related appeal is on Horizon, in which case the relationship will be marked as `externalSource=true`.

fix(appeals/api): correct the logic in showing related appeals

---

appeals/web/src/server/views/app/layouts/app.layout.njk
appeals/web/src/server/views/appeals/documents/document-upload.njk

[BOAT-865](https://pins-ds.atlassian.net/browse/BOAT-865)
[BOAT-865]: https://pins-ds.atlassian.net/browse/BOAT-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals/web): BOAT-865 service name missing from page titles on various pages

---

apps/api/src/server/applications/application/project-updates/project-updates.service.js
apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js

- Make sure the deadline subfolders are saved with the parent folder case stage
- Update the examination-timetable unit tests to handle and prove the above
https://pins-ds.atlassian.net/browse/BOAS-1558

fix(applications/api): case stage should be added to deadline sub folders (BOAS-1558)

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/views/applications/case-timetable/components/timetable-items-list.component.njk

- Make sure examination item types 'Procedural Deadline (Pre-Examination)' are displayed in the Pre-examination section
- Update unit test snap shots to match above correctly
https://pins-ds.atlassian.net/browse/BOAS-1563

fix(applications/web): pre-examination items not appearing in pre exam section (BOAS-1563)

---

apps/functions/applications-migration/nsip-representation-migration/src/nsip-representation-migration.js

Remove mapping of `status` field value from Horizon to BO value. This is now being done in ODW curated layer so no longer required

chore(functions): remove nsip-representation status field mapping

---

apps/api/src/server/repositories/__tests__/representation.repository.test.js
apps/api/src/server/repositories/representation.repository.js

- Make sure sorting relevant representations is [{ "status": "asc", "received": "desc", "id": "asc" }] 
https://pins-ds.atlassian.net/browse/BOAS-1559

fix(applications/api): relevant representations - issue with sorting (BOAS-1559)

---

apps/api/src/server/applications/application/documents/__tests__/create-document.test.js
apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/applications/s51advice/s51-advice.controller.js
apps/api/src/server/applications/s51advice/s51-advice.service.js
apps/web/src/client/components/file-uploader/_html.js
apps/web/src/client/components/file-uploader/_server-actions.js

- Split duplicate list into deleted and duplicates where the files have been previously deleted.
- Warn the user that a file has previously been deleted and will need to be renamed to upload
- Tested manually for both S51 Advice as well as other document uploads
https://pins-ds.atlassian.net/browse/BOAS-1568

fix(applications): warn on uploading existing deleted file (BOAS-1568)

---

apps/web/src/server/applications/applications.types.d.ts
apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
apps/web/src/server/applications/case/project-team/__tests__/applications-project-team.test.js
apps/web/src/server/applications/case/project-team/application-project-team.azure-service.js
apps/web/src/server/applications/case/project-team/applications-project-team.controller.js
apps/web/src/server/applications/case/project-team/applications-project-team.service.js
apps/web/src/server/views/applications/case-project-team/project-team-choose-role.njk
apps/web/testing/app/mocks/project-team.js
apps/web/testing/applications/factory/project-team.js

- Make sure unique roles are not available in the choose/change role page when they have already been filled within the team.
- Update unit tests to handle and prove support of unique roles
https://pins-ds.atlassian.net/browse/BOAS-1553

fix(applications/web): prevent duplicate unique roles in a project team (BOAS-1553)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js

add a11y text to manage folder and manage document action links
BOAT-675

fix(web): add a11y text to manage folder and manage document action links

---

appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js

remove awaiting transfer notification banner from transferred appeals
BOAT-916

fix(web): remove awaiting transfer notification banner from transferred appeals

---

appeals/api/src/message-schemas/pins-appellant-case.schema.json
appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js

Small fix in validating (and reusing) the original UUID for an imported document.

fix(appeals/api): importing documents was not validating UUIDs

---

appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js

Better detection of UUIDs in doc integrations: trying to preserve the original UUIDs from FO docs integrations.

fix(appeals/api): changed the UUID detection to use in service

---

apps/web/src/styles/7-components/app-header.scss

- Fixed styling in header
- Manually tested
https://pins-ds.atlassian.net/browse/BOAS-1609

fix(applications/web): header is broken when in mobile portrait format (BOAS-1609)

---

appeals/api/src/database/seed/data-test.js
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/repositories/integrations.repository.js
appeals/api/src/server/utils/appeal-reference.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/lib/mappers/appeal.mapper.js

Improvements for db:seed, and corrected the mapping for LPA `planningApplicationReference`:
- Creates references based on appeal ID
- Ensures references are numeric only, and are 6000000+
- Sort national list by `updatedAt DESC`
N/A

feat(appeals): mapping and seed improvements

---

appeals/api/src/server/repositories/appeal.repository.js

Removes the current final states from the personal list. Appeals in final states can only be found on the all cases.
`
status: {
notIn: [
STATE_TARGET_COMPLETE,
STATE_TARGET_CLOSED,
STATE_TARGET_TRANSFERRED,
STATE_TARGET_INVALID,
STATE_TARGET_WITHDRAWN
]
}
`
[BOAT-917](https://pins-ds.atlassian.net/browse/BOAT-917)
[BOAT-917]: https://pins-ds.atlassian.net/browse/BOAT-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals/api): remove final states from personal list

---

apps/api/src/server/applications/application/__tests__/update-application.test.js
apps/api/src/server/applications/application/application.mapper.js

- Make sure the caseEmail is set to null if an empty string is received before updating the application details
- Manually tested locally, checking event messages output in the terminal and the caseEmail column in the ApplicationDetails table
https://pins-ds.atlassian.net/browse/BOAS-1647

fix(applications/api): nsip-project projectEmailAddress can not be empty string (BOAS-1647)

---

appeals/api/src/server/utils/horizon-gateway.js
appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.validators.js
appeals/web/src/server/views/app/500.njk

fix(web): update transfer appeal flow to display custom error page when horizon is down
BOAT-920

fix(web): update transfer appeal flow to display custom error page when horizon is down

---

apps/api/src/server/applications/application/documents/document.js

The object included in the error message is showing up as `[object Object]`. Stringifying it should help with debugging.
[BOAS-1645](https://pins-ds.atlassian.net/browse/BOAS-1645)
[BOAS-1645]: https://pins-ds.atlassian.net/browse/BOAS-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): stringify object in error message in buildBlobUri

---

apps/e2e/cypress/page_objects/documentPropertiesPage.js
apps/e2e/cypress/page_objects/folderDocumentsPage.js
apps/e2e/cypress/page_objects/uploadFiles.js

The PR https://github.com/Planning-Inspectorate/back-office/pull/2268 failed the tests as the styling and structure of the buttons in the page had changed.  This PR amends the tests to cope with the new structure of the page.
- Updated e2e tests to target elements via contained text rather than nth elements
- Successfully run against the DEV environment
https://pins-ds.atlassian.net/browse/BOAS-1660

fix(applications/web): fix e2e tests for document properties page (BOAS-1660)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
apps/web/src/styles/7-components/_nav-button-group.scss
apps/web/src/styles/main.scss

- Changed Document properties layout and styling for the 'publishing queue' link
- Unit tests updated
https://pins-ds.atlassian.net/browse/BOAS-1282

fix(applications/web): publishing queue link incorrectly placed (BOAS-1282)

---

apps/api/src/database/seed/seed-clear.js

- Changed seeding so only those tables that are not interdependent are deleted in parallel and in the correct order of dependency
- Manually tested the functionality locally
https://pins-ds.atlassian.net/browse/BOAS-1613

fix(applications/api): fix seed error deleting in dependency order (BOAS-1613)

---

apps/api/src/database/seed/seed-clear.js

- Changed seeding so that the deletion of folders is retried until there are none left to delete or it fails 10 times
- Manually tested the functionality locally
https://pins-ds.atlassian.net/browse/BOAS-1613

fix(applications/api): fix seed error retry delete (BOAS-1613)

---

apps/api/src/database/migrations/20240228104443_reseed_tables_for_migration/migration.sql

Changes the value at which the ID column begins incrementing from, for tables which are having legacy data migrated in. New rows (i.e. those created via Back Office) will start from ID 100,000,000 and this allows manual insertion of migrated legacy data into rows 1 to 99,999,999.
Similar to https://github.com/Planning-Inspectorate/back-office/pull/1697/files
BOAS-1403

chore(applications/api): reseed tables for migration

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js
apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
apps/web/testing/applications/fixtures/documentation-files.js

- Update template to only show "Open" button when a preview available mime type
- Added web unit test
- Updated web unit test snapshots
https://pins-ds.atlassian.net/browse/BOAS-1485

fix(applications/web): hide open button in document properties correctly (BOAS-1485)

---

appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
appeals/api/src/server/endpoints/linkable-appeals/__tests__/linkable-appeal.test.js
appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.service.js
appeals/api/src/server/tests/horizon/mocks.js
appeals/api/src/server/utils/horizon-gateway.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/lib/display-page-formatter.js

Fix horizon appeal links for linked and related appeals. Also reverts the link for transferred appeals to plaintext (API fix required to return the horizon ID of transferred appeals - see BOAT-1079)
BOAT-1060

fix(appeals): fix horizon appeal links for linked and related appeals

---

apps/api/src/server/migration/migrators/s51-advice-migrator.js

updates to s51 migration
- map the `agent` value into `enquirer` field (organisation name)
- update `status` mapping with some non-standard values coming from ODW. To be removed once ODW does this mapping in curated

fix(functions): s51 status and agent mapping

---

apps/functions/applications-background-jobs/common/config.js
apps/functions/applications-background-jobs/publish-document/src/util.js

Allow blob URIs to include either the custom domain or the generated primary blob endpoint.
[BOAS-1693](https://pins-ds.atlassian.net/browse/BOAS-1693)
[BOAS-1693]: https://pins-ds.atlassian.net/browse/BOAS-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(functions): allow blob URIs to include custom domain

---

apps/web/src/server/applications/case/representations/application-representations.view-model.js

Currently the 'Date received' field shows 01/01/1970 if there is no date in the DB. This change leaves the field empty in this case.
[BOAS-1567](https://pins-ds.atlassian.net/browse/BOAS-1567)
[BOAS-1567]: https://pins-ds.atlassian.net/browse/BOAS-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): leave empty field if RR has no received date

---

apps/api/Dockerfile

Set API Docker build to `Node 18.19` as `Node 18.20` is currently creating issues
https://pins-ds.atlassian.net/browse/BOAS-1704

fix(applications/api): set api docker build to node 18.19 (BOAS-1704)

---

apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
apps/web/src/server/applications/case/project-updates/project-updates.view-model.js

- Removed the extra \<hr\> on preview/review pages by adding the class no-border
- Updated affected snapshots
- Tested manually, extra hr no longer appears
https://pins-ds.atlassian.net/browse/BOAS-1251

fix(applications/web): remove extra hr on preview review pages (BOAS-1251)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/views/applications/case-documentation/documentation-edit.njk

- Increased size of date input components with a class.
- Tested manually including changing the width of the browser
- Fixed the unit test snapshots
https://pins-ds.atlassian.net/browse/BOAS-1415

fix(applications/web): day and month date fields not big enough (BOAS-1415)

---

.gitignore
apps/web/.env.example
apps/web/environment/README.md
apps/web/environment/config.d.ts
apps/web/environment/config.js
apps/web/environment/schema.js
apps/web/src/server/applications/case/representations/representation/address-details/utils/get-address-list.js
apps/web/src/server/applications/common/components/form/form-applicant.component.js
apps/web/src/server/applications/common/services/address.service.js
docs/web-overview.md

These changes are also in part in preparation for allowing e2e tests to run locally as well as not requiring the developer to have the OS_PLACES_API_KEY set when running the application on localhost.
- Create wrapper around the address lookup function to allow simulation of address lookup
- Provide support for new DUMMY_ADDRESS_DATA environment variable
- Add documentation for how to use dummy data
- Tested manually 
https://pins-ds.atlassian.net/browse/BOAS-1721

feat(applications/web): allow developers to simulate address lookup (BOAS-1721)

---

apps/api/src/server/applications/application/__tests__/get-application-details.test.js
apps/api/src/server/applications/application/application.mapper.js
apps/api/src/server/utils/address-block-formtter.js
apps/api/src/server/utils/address-formatter-lowercase.js
apps/web/src/server/applications/common/components/form/form-applicant.component.js
apps/web/src/server/applications/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap
apps/web/src/server/views/applications/components/case-form/applicant/address.njk

- Added county and country to applicant address edit page
- Tested manually adding county and country details
- Updated unit tests
- Fixed the unit test snapshots
https://pins-ds.atlassian.net/browse/BOAS-1706

fix(applications): editing application address should show all address parts (BOAS-1706)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk

The alignment had already been done in a previous ticket as I could not reproduce.  I did remove the wrapper around the tabs to make sure the large gap between the buttons and the tabs is removed to match the image in the ticket.  
- Updated unit test snapshots
- Tested manually including changing the width of the browser
https://pins-ds.atlassian.net/browse/BOAS-1427

fix(applications/web): fix document properties button styling (BOAS-1427)

---

apps/functions/applications-command-handlers/deadline-submission-command/__tests__/deadline-submission-command.test.js
apps/functions/applications-command-handlers/deadline-submission-command/back-office-api-client.js
apps/functions/applications-command-handlers/deadline-submission-command/index.js
packages/event-client/src/generic-event-client.js

* fix(functions): add optional chaining to lineItemExists
* fix(packages/event-client): map deadline-submission-result to schema
* fix(functions): make sure errors are thrown in deadline-submission func
Currently we catch errors and just log them, but this leads to the
invocation been recorded as successful when it actually failed.
Tested this in dev.
[BOAS-1696](https://pins-ds.atlassian.net/browse/BOAS-1696)
[BOAS-1696]: https://pins-ds.atlassian.net/browse/BOAS-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix deadline-submissions handler

---

apps/e2e/cypress/e2e/back-office-applications/s51Advice.spec.js
apps/e2e/cypress/page_objects/s51AdvicePage.js
apps/e2e/cypress/support/utils/createS51Advice.js
apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/views/applications/case-s51/properties/s51-properties.njk
apps/web/src/styles/7-components/_properties-inset-text.scss
apps/web/src/styles/main.scss

- Updated buttons in view to use design system correctly like in the document properties view
- Added some CSS to fix the large gap between the inset text and the buttons while in desktop format 
- Updated unit test snapshots
- Tested manually including changing the width of the browser
- Fix S51 acceptance tests as title must be unique
https://pins-ds.atlassian.net/browse/BOAS-1718

fix(applications/web): fix broken button styling in S51 document properties page (BOAS-1718)

---

apps/api/src/server/applications/application/documents/document.controller.js
apps/api/src/server/config/config.js
apps/api/src/server/config/schema.js
apps/api/src/server/repositories/document-metadata.repository.js
apps/e2e/README.md

Allows unpublishing and publishing document e2e tests to run locally against http://localhost:8080
- Updated environment variables in e2e Readme
- Automatically set publishing to published and unpublishing to unpublished when NODE_ENV is development
- Tested manually 
See the description within the ticket below for the full setup for how to run the e2e tests locally against http://localhost:8080 in dev.
https://pins-ds.atlassian.net/browse/BOAS-1726
https://pins-ds.atlassian.net/browse/BOAS-1721

fix(test/e2e): allow e2e tests to pass on localhost (BOAS-1726)

---

apps/api/src/server/migration/migration.controller.js
apps/functions/applications-migration/common/constants.js
apps/functions/applications-migration/common/migrators/general-s51-advice-migration.js
apps/functions/applications-migration/common/migrators/s51-advice-migration.js
apps/functions/applications-migration/general-s51-advice-migration/debug.js
apps/functions/applications-migration/general-s51-advice-migration/function.json
apps/functions/applications-migration/general-s51-advice-migration/index.js
apps/functions/applications-migration/package.json
package-lock.json
packages/applications/index.d.ts
packages/applications/index.js
packages/applications/lib/application/constants.js
packages/applications/package.json

Adds capability to migrate general S51 advice from the curated db to the BO db.
Due to the high number of General S51 advices that need to be migrated (700-800), there is a paginated mechanism in place that returns (currently) 100 rows with each call. They are then sent to the api together to complete the migration before continuing with the rest of the advices.
This mechanism also allows for continuation of a migration process from the point it errored by noting the offset number and including it in the invocation request to the Azure Function.
Might not be necessary, but there is also a 'select' General S51 Advice migration function included in the same Azure Function, allowing for migration of a specific case.

feat(functions): add azure function for general s51 advice migration

---

apps/api/src/database/migrations/20240417160000_correct_migrated_case_stages/migration.sql
apps/api/src/server/utils/create-enums.js
apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js

There were invalid case stage values in the caseStatus table.  Believe this was caused when shell cases were created for Project Updates, possibly taking the values the the old NSIP website used.  An example is "Acceptance (review of the application)" - our db does not have this, it has "acceptance".
These invalid values stop the cases displaying in the dashboard, which filters to only display a selection from the valid list.  The bug was raised on the "Arundel" case in Prod, which had a value "Pre-application" where it should have been "pre_application".
- changed the project update migration code to set the correct db values
- added a DB migration script to update all incorrect values to the correct valid ones.  This will be run in each environment upon delivery.
**Developer …

fix(applications): correct invalid stage values in db (boas-1651)

---

apps/api/src/database/migrations/20240419120000_correct_multiple_valid_case_statuses/migration.sql
apps/api/src/server/migration/migrators/nsip-project-migrator.js

Case Migration, if run multiple times for a case, can create multiple case status records that are marked as valid.  This confuses the main app, as it expects only 1 CaseStatus record to be valid for any case.  The issue occurs in cases in Azure Prod and Test.
This fix does:
- add code to the migrator to set all previous CaseStatus records for a case to valid=0, before adding the latest CaseStatus record.
- SQL migration script to set all old CaseStatus records that are incorrectly marked as valid=1 to be 0.
https://pins-ds.atlassian.net/browse/BOAS-1737

fix(api/applications): correct multiple valid case statuses (boas-1737)

---

apps/web/src/server/applications/applications.locals.js
apps/web/src/server/views/applications/components/case-form/case-form-layout.njk

- Make back button return to project information when not in draft
- Tested manually 
https://pins-ds.atlassian.net/browse/BOAS-1739

fix(applications/web): back button fails to return to project information (BOAS-1739)

---

apps/e2e/cypress/page_objects/basePage.js
apps/e2e/cypress/page_objects/createCasePage.js
apps/e2e/cypress/page_objects/documentPropertiesPage.js
apps/e2e/cypress/page_objects/s51AdvicePage.js
apps/e2e/cypress/page_objects/uploadFiles.js
apps/e2e/package.json
package-lock.json

Changes made while making the tests run locally that improve the efficiency of the tests running both against local dev as well as DEV and TEST environments.
Essentially removed some "cy.wait" commands with timeout options.  In the case of the document uploads, the reload will continue once a second until the document link either exists or times out in 10 seconds.
Please note that my IDE automatically updated a small number of lines in the updated files to match the eslint formatting within the project and I was unable to prevent it from doing so.  The formatting does not affect the execution of the tests.

chore(e2e): improve e2e efficiency

---

apps/functions/applications-background-jobs/notify-subscribers/src/__tests__/notify-subscribers.test.js
apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
apps/functions/applications-background-jobs/notify-subscribers/src/util.js
apps/functions/applications-background-jobs/package.json
package-lock.json

- Only encode brackets and apostrophes in the links for markdown
- Tested via unit tests
- Will test sending email notification once deployed to DEV as it's the only way to test properly
https://pins-ds.atlassian.net/browse/BOAS-1720

fix(applications): only encode links for markup (BOAS-1720)

---

apps/web/src/server/applications/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap
apps/web/src/server/applications/case/edit/applicant/applications-edit-applicant.controller.js
apps/web/src/server/applications/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap
apps/web/src/server/applications/create-new-case/applicant/applications-create-applicant.controller.js

- Add optional to the pages for entering an Applicant's address
https://pins-ds.atlassian.net/browse/APPLICS-43

fix(applications/web): enter applicant address missing optional (APPLICS-43)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/lib/nunjucks-filters/status-name.js

- Display "Not checked" instead of "Unchecked" when status is "not_checked"
https://pins-ds.atlassian.net/browse/APPLICS-40

fix(applications/web): change unchecked to be not checked (APPLICS-40)

---

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk
apps/web/src/server/views/applications/components/folder/folder-actions.component.njk

- Override negative left margin with CSS class govuk-!-margin-left-0
https://pins-ds.atlassian.net/browse/APPLICS-41

fix(applications/web): align misaligned navigation menu (APPLICS-41)

---

apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
apps/web/src/server/applications/case/representations/__tests__/__snapshots__/applications-representaions.test.js.snap
apps/web/src/server/views/applications/components/pagination/results-per-page.component.njk

- Remove the unnecessary whitespace within the filter links
https://pins-ds.atlassian.net/browse/APPLICS-34

fix(applications/web): remove spaces from 25 and 50 links (APPLICS-34)

---

apps/api/src/server/migration/migrators/folder-migrator.js

Amends `folder` migrator function so an error is logged rather than thrown, if the case already has folders

fix(functions): allow migrate-case function to continue if folders exist

---

packages/feature-flags/src/is-feature-active.js

We want the app to continue working (and assume false for feature flags) if Azure App Config can't be reached for whatever reason.

fix(packages/feature-flags): catch errors when calling Azure App Config

---

apps/web/src/server/views/applications/case-s51/s51-table.njk

- Remove the unnecessary commas within the template
https://pins-ds.atlassian.net/browse/APPLICS-263

fix(applications/web): extra commas within s51 advice page (APPLICS-263)

---

apps/functions/applications-migration/common/migrators/exam-timetable-migration.js

The `mapTimetableFromItems` seemed to be expecting incorrect field names from ODW, there might have been a regression. When sent to our API, the validation failed due to the mismatch. This PR corrects this to solve the issue migrating exam timetables.

fix(functions): examtimetable function mapper

---

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk

- Change asterix to asterisk in the template
- Updated web unit test snapshots
https://pins-ds.atlassian.net/browse/APPLICS-315

fix(applications/web): spelling mistake in timetable item description (APPLICS-315)

---

packages/feature-flags/src/feature-flag-client.js
packages/feature-flags/src/list-flags.js

There was a piece of logic causing {} to be returned when there is no connection string, even when trying to fetch the static flags for which a connection string isn't required.
This change keeps the check but only if requesting the real flags from Azure App Config.

fix(packages/feature-flags): static flags don't require conxion string

---

apps/api/src/server/build-app.js

Migration requests are failing because express body limits any requests over 30mb, I have increased this to 100mb - this resolves the issue with requests with a large amount of documents.

fix(functions): increase express body limit

---

apps/api/src/server/build-app.js
apps/api/src/server/migration/migrators/folder-migrator.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-379
Folder migration was skipping if a case had existing folders which meant even if 1 folder was created, the rest would get skipped. This behaviour would cause document migration to fail as not all folders were created from folder migration. This PR adds a step to firstly check what folders are still not created and then only creates those.

fix(applications/api): folder migration creation

---

apps/api/src/server/migration/migrators/folder/folder.js

Folder migration for `EN010007` was failing as `consultation` was spelt incorrectly on the folder map.

fix(applications/api): folder migration map typo

---

apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
apps/e2e/cypress/page_objects/createCasePage.js

- Moved feature flag test to surround entire Welsh test spec
- Simplify checking the Welsh region by reusing the chooseRegion function
- Ran e2e test locally with the flag switched on and off
https://pins-ds.atlassian.net/browse/APPLICS-374

test(test/e2e): allow welsh spec to skip when feature flag is off (APPLICS-387)

---

apps/api/src/message-schemas/commands/new-deadline-submission.d.ts
apps/api/src/message-schemas/commands/register-nsip-subscription.d.ts
apps/api/src/message-schemas/commands/register-representation.d.ts
apps/functions/applications-command-handlers/deadline-submission-command/index.js
apps/functions/applications-command-handlers/handle-subscription-command/logging-utils.js
apps/functions/applications-command-handlers/register-representation-command/index.js

- Allow message schema reference to use pins-model-data and fallback to previous local schema
- Restore removed message schema files
https://pins-ds.atlassian.net/browse/APPLICS-117

chore(applications): default message schema to pins-data-model fallback to back-office (APPLICS-117)

---

apps/web/src/server/app/components/file-downloader.component.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-406
contentType for preview route is not retrieved from DB instead of blob storage metadata. This is because migrated cases from Aimi tool will not have the correct blob content type metadata.

feat(applications/web): preview content type retrieved from db 

---

apps/functions/applications-background-jobs/publish-document/__tests__/publish-document.test.js
apps/functions/applications-background-jobs/publish-document/index.js
packages/blob-storage-client/src/blob-storage-client.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-405
Blob content type is incorrect for migrated cases, this change retrieves the correct blob content type from the message in publish function and sets the new blob content type. This is done after copying because the source container blobs have a legal hold and therefore cannot be changed, but the destination container allows blobs to be updated.

feat(functions): change blob contentType on publish document

---

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
apps/web/src/server/applications/case/applications-case.controller.js
apps/web/src/server/applications/case/applications-case.locals.js
apps/web/src/server/applications/case/applications-case.router.js
apps/web/src/server/views/applications/case/components/case-info-table-preview.component.njk
apps/web/src/server/views/applications/case/preview-and-publish.njk

- Set caseIsWelsh flag in the case locals middleware so that it is available when required in other templates
- Include the Welsh fields in the Preview and Publish page only if Wales is included as a region
- Updated unit test snapshots
https://pins-ds.atlassian.net/browse/APPLICS-412

fix(applications/web): only display welsh fields in publish preview when welsh region (APPLICS-412)

---

apps/e2e/cypress/e2e/back-office-applications/s51Advice.spec.js
apps/e2e/cypress/page_objects/s51AdvicePage.js
apps/web/src/server/applications/case/s51/applications-s51.router.js
apps/web/src/server/applications/case/s51/applications-s51.validators.js
apps/web/src/server/views/applications/case-s51/s51-table.njk
apps/web/src/server/views/applications/components/folder/folder.njk
apps/web/src/styles/7-components/files-list.scss

- Add the validation of the Welsh properties in a s51 advice when marking ready to publish
- Added e2e tests to test the above
https://pins-ds.atlassian.net/browse/APPLICS-475

feat(applications/web): s51 advice properties: validate welsh properties (APPLICS-475)

---

apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
apps/e2e/cypress/e2e/back-office-applications/documentPropertiesWelsh.spec.js
apps/e2e/cypress/page_objects/documentPropertiesPage.js
apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js
apps/web/src/server/views/applications/case-documentation/documentation-edit-textarea.njk
apps/web/src/server/views/applications/layouts/document-edit-property.layout.njk

- Add new nunjucks templates to match figma designs
- Add config to use new nunjucks template
- Fixed web unit tests to test the above
- Fixed e2e tests to test the above
https://pins-ds.atlassian.net/browse/APPLICS-473

feat(applications/web): who document is for in welsh should match figma (APPLICS-473)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/views/applications/case-documentation/documentation-edit-textarea.njk
apps/web/src/server/views/applications/case-documentation/edit/max-length-input.njk

- Update nunjucks templates to display entered data if in error
- Fixed web unit test snapshots to test the above
https://pins-ds.atlassian.net/browse/APPLICS-474

feat(applications/web): entered data should be displayed when property is in error (APPLICS-474)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
apps/web/src/server/applications/case/key-dates/applications-key-dates.controller.js
apps/web/src/server/applications/case/s51/applications-s51.controller.js
apps/web/src/server/lib/__tests__/add-entered-date-to-validation-errors.test.js
apps/web/src/server/lib/add-entered-date-to-validation-errors.js
apps/web/src/server/views/applications/components/inputs/date-input.component.njk

The date validators do not return the entered date in the value field for the error, so this is done within the controller where required.
- Update nunjucks date-input.component.njk to display entered dates when in error
- Updated controllers for documentation, key dates, and s51 advice to include the entered date in the validation errors
- Fixed web unit test snapshots to test the above
https://pins-ds.atlassian.net/browse/APPLICS-501

fix(applications/web): date fields do not show entered data when in error (APPLICS-501)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js
apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk

Implement the ability to change s51 advice properties Welsh fields.
- Corrected the error messages to match those in the ticket for both "Who from" and "Who from in Welsh" pages
- Added the success banner when document properties are successfully updated
- Fixed unit tests to test changing s51 advice properties Welsh fields
https://pins-ds.atlassian.net/browse/APPLICS-497

fix(applications/web): document properties change from welsh functional changes (APPLICS-497)

---

apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
apps/e2e/cypress/page_objects/basePage.js
apps/web/src/server/applications/applications.types.d.ts
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
apps/web/src/server/applications/case/edit/case/applications-edit-case.controller.js
apps/web/src/server/applications/case/edit/case/applications-edit-case.router.js
apps/web/src/server/applications/common/components/error-handler/error-handler.component.js
apps/web/src/server/applications/create-new-case/applications-create.service.js
apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
apps/web/src/server/applications/create-new-case/case/applications-create-case.validators.js
apps/web/src/server/applications/create-new-case/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap
apps/web/src/server/applications/create-new-case/check-your-answers/__tests__/applications-create-check-your-answers.test.js
apps/web/src/server/views/applications/case/case-form/case-edit-textarea.njk
apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk
apps/web/src/server/views/applications/case/layouts/case-property.layout.njk
apps/web/src/server/views/applications/case/overview.njk
apps/web/src/server/views/applications/components/textarea-form-component.njk

Implement the content and template structure changes requested in the ticket.
- Corrected the error messages to match those in the ticket for both "Project location" and "Project location in Welsh" pages
- Created a new layout and template to accommodate the design changes and reuse the textarea component
- Extended the config for layouts to include english and welsh field names and template reference
- Moved the success banner when properties are successfully updated to match the figma design
- Fixed unit tests and snap shots to match new changes
https://pins-ds.atlassian.net/browse/APPLICS-499

fix(applications/web): project location in welsh content changes (APPLICS-499)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js

Correct the error shown to the user when the description entered is more than 800 characters.
[APPLICS-520](https://pins-ds.atlassian.net.mcas.ms/browse/APPLICS-520?McasTsid=20596&McasCtx=4)
[APPLICS-520]: https://pins-ds.atlassian.net/browse/APPLICS-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web/applications): correct error when document description too long

---

apps/api/src/server/applications/application/representations/publish/publish.service.js
apps/api/src/server/repositories/representation.repository.js

Fix to batch DB updates in batches of 1000 for representation updates.  This was causing failures on publishing over 2000 representations.
Unit test has was not originally done for the repository function setRepresentationsAsPublished.  Not added here as it would require a refactor and large amount of mocks of prisma representation object.
Batching has been tested locally and will be tested and validated in dev against case BC0110001 with 5000 reps.
https://pins-ds.atlassian.net/browse/APPLICS-270

fix(api): bach DB updates for  Reps to avoid Prisma limit

---

apps/e2e/cypress/e2e/back-office-applications/s51Advice.spec.js
apps/e2e/cypress/page_objects/s51AdvicePage.js
apps/web/src/server/applications/case/s51/applications-s51.controller.js

- Added missing step config for both Enquiry detail and Advice detail
- Added a new e2e test
https://pins-ds.atlassian.net/browse/APPLICS-518

fix(applications/web): s51 advice unable to update enquiry details (APPLICS-518)

---

apps/web/src/server/applications/create-new-case/case/applications-create-case.validators.js

- Corrected wording in validation text for Welsh
https://pins-ds.atlassian.net/browse/APPLICS-523

fix(applications/web): overview project description in welsh message is incorrect (APPLICS-523)

---

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js

- Corrected wording in validation text for Welsh
https://pins-ds.atlassian.net/browse/APPLICS-521

fix(applications/web): document description in welsh message is incorrect (APPLICS-521)

---

apps/web/src/server/applications/common/components/form/form-case.component.js

- Prevent update when validation fails
https://pins-ds.atlassian.net/browse/APPLICS-427

fix(applications/web): project location details not retained (APPLICS-427)

---

apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js

- Add labels for status and redaction.  Note that the labels form part of the success banner
https://pins-ds.atlassian.net/browse/APPLICS-522

fix(applications/web): success banner missing text when updating document status (APPLICS-522)

---

apps/web/src/server/applications/case/representations/__fixtures__/publishable-representations.fixture.js
apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/publish-valid-reps.test.js
apps/web/src/server/applications/case/representations/publish-valid-representations/publish-valid-reps.controller.js
apps/web/src/server/applications/case/representations/utils/publish-representations.js

Changes for BOAS web to publish representations in batches.  This is due to the slow publishing of over 1500 reps which causes the front end to timeout.
This will be rare but we need to handle the odd occasion when a large number of reps will be published.
Error handling for a publish error on a particular batch causes an exception and redirect to error page (as before).
This process is idempotent so the expectation is for user to retry.
https://pins-ds.atlassian.net/browse/APPLICS-270

fix(web): send publish representations in batches

---

apps/functions/applications-migration/common/back-office-api-client.js

Fix small bug with `constructUri` function where `params` is not passed in
```
// no 2nd arg causes error
> constructUri('/migration/validate')
Uncaught TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at constructUri (REPL17:4:9)
```
N/A

fix(functions): fix construct uri bug

---

apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
apps/web/src/server/views/applications/components/case-form/case/title.njk

- Remove hint from nunjucks template
https://pins-ds.atlassian.net/browse/APPLICS-567

fix(applications/web): static text is not required for project name in welsh field (APPLICS-567)

---

apps/functions/applications-migration/common/migrators/s51-advice-migration.js

ODW issue with `caseId` in `nsip_s51_advice` table causes schema validation to fail (should be number, is a string). This PR adds a workaround until it is fixed, which is being tracked ODW-1307
N/A

fix(functions): workaround for s51 caseid validation error

---

apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
apps/e2e/cypress/page_objects/basePage.js
apps/e2e/cypress/page_objects/examinationTimetablePage.js

This PR:
- deletes all the examination timetable items prior to running each test so that the items created in previous tests do not affect the results of the following tests.
- tidies up some of the functions within the tests.
https://pins-ds.atlassian.net/browse/APPLICS-556

fix(test/e2e): make examination timetable e2e tests more stable

---

apps/web/src/server/applications/case/project-updates/__tests__/project-updates.mapper.test.js
apps/web/src/server/applications/case/project-updates/project-updates.mapper.js

Fix project updates mapper to handle corrupt ampersands created through the rich editor
https://pins-ds.atlassian.net/browse/APPLICS-604

feat(applications/web): project update links contain corrupt ampersands (APPLICS-604)

---

apps/functions/applications-command-handlers/package.json
package-lock.json

Install pins-data-model in applications-command-hanlders. This was causing the `handle-subscription-command` function to fail.

fix(functions): install pins-data-model in applications-command-hanlders

---

apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.validators.js
apps/api/src/server/applications/s51advice/s51-advice.controller.js
apps/api/src/server/utils/is-case-welsh.js

When determining if an ETT is publishable, only check the Welsh fields have been populated if the case is Welsh and the feature flag for Welsh translation is on. 
- Move the solution to determine a Welsh case when publishing a S51 advice to a reusable utility function (IsCaseWelsh)
- Change both S51 advice and ETT publishing to use the same utility function IsCaseWelsh
- Run the api unit tests
- Run the e2e regression tests locally with Welsh feature flag on and off
https://pins-ds.atlassian.net/browse/APPLICS-663

fix(applications/api): unable to publish ETTs when Welsh selected (APPLICS-663)

---

apps/api/src/server/utils/prisma-middleware.js
azure-pipelines-remove-training-cases.yml
packages/scripts/package.json
packages/scripts/run/remove-all-training-cases-entry.js
packages/scripts/src/remove-training-cases.js

A new pipeline and script has been created to remove all training cases and associated records as described in the ticket APPLICS-605.  
Please note that without the environment variable REMOVE_ALL_CASES being set to 'true', the transaction for each case is aborted to prevent the removal from actually taking place. 
I have successfully run this locally on my own machine against my local DB with the env var set to true and not set to true.  When set to true, the training cases and all associated records are deleted successfully.
I have run this in the pipeline on DEV without REMOVE_ALL_CASES being set and each deletion is rolled back as each transaction is aborted by throwing a synthetic error as designed.
This has not yet been run in a pipeline without aborting the transactions. …

feat(tooling): create remove training cases script (APPLICS-605)

---

apps/api/src/server/utils/prisma-middleware.js

Fix a bug within the Prisma middleware to not assume that the args exist when checking for the hardDelete option
https://pins-ds.atlassian.net/browse/APPLICS-605

fix(tooling): fix hard delete bug (APPLICS-605)

---

apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
package-lock.json
package.json

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-703
PR adds new Welsh descriptions on the event line items, it will split and format them exactly the same as the standard description. Data model has been updated, and FO is already expecting this format. 
Example broadcast:
```json
{"examTimetablePayload":{"caseReference":"BC0110001","events":[{"type":"Accompanied Site Inspection","date":"2021-08-19T00:00:00.000","description":"hello\r\n* item 1\r\n* item 2\r\n* item 3","descriptionWelsh":"hellow\r\n* witem 1\r\n* witem 2\r\n* witem 3","eventTitle":"normal","eventTitleWelsh":"wnormal","eventId":1,"eventLineItems":[]},{"type":"Deadline","date":"2025-10-10T00:00:00.000","description":"deadline description something","descriptionWelsh":"welsh deadline description …
```

feat: examtimetable line item welsh description

---

azure-pipelines-remove-specified-cases.yml
azure-pipelines-remove-training-cases.yml
packages/scripts/package.json
packages/scripts/run/remove-all-training-cases-entry.js
packages/scripts/run/remove-specified-cases-entry.js
packages/scripts/src/remove-cases.js

A new entry script has been added to allow the ability to pass in a comma separated list of specified case numbers via the environment variable SPECIFIED_CASES to remove those specific cases and associated records as described in the ticket APPLICS-605.  
Please note that without the environment variable REMOVE_ALL_CASES being set to 'true', the transaction for each case is aborted to prevent the removal from actually taking place. 
I have successfully run this locally on my own machine against my local DB with the env var set to true and not set to true.  When set to true, the specified cases and all associated records are deleted successfully.
**Please note the environment variable SPECIFIED_CASES will only accept a comma separated list of case references that are prefixed "TRAIN" to …

chore(tooling): delete specified cases (APPLICS-605)

---

azure-pipelines-remove-specified-cases.yml

Fixed parameter display name for specified cases
https://pins-ds.atlassian.net/browse/APPLICS-605
A new entry script has been added to allow the ability to pass in a comma separated list of specified case numbers via the environment variable SPECIFIED_CASES to remove those specific cases and associated records as described in the ticket APPLICS-605.  
Please note that without the environment variable REMOVE_ALL_CASES being set to 'true', the transaction for each case is aborted to prevent the removal from actually taking place. 
I have successfully run this locally on my own machine against my local DB with the env var set to true and not set to true.  When set to true, the specified cases and all associated records are deleted successfully.
**Please note the environment variable …

feat(tooling): create remove training cases script fix parameter (APPLICS-605)

---

apps/functions/applications-migration/common/migrators/s51-advice-migration.js

When running the s51 migrator function, the validation is failing because `adviceId` is not an integer. It is currently a string as that is how Sequelize stores `bigint` data from SQL Server (which is the type ODW are using for this column in their curated DB). Therefore, we need to convert it to Number/int before sending the data to the API.

fix(functions): convert s51 adviceid to number

---

apps/api/src/server/applications/application/documents/__tests__/document-payload.test.js
apps/api/src/server/applications/application/documents/__tests__/document.service.test.js
apps/api/src/server/applications/application/documents/__tests__/unpublish-document.test.js
apps/api/src/server/applications/s51advice/__tests__/s51-advice.test.js
apps/api/src/server/infrastructure/payload-builders/nsip-document.js

* fix(api/applications): fix fetching of case stage from document
* test(api/applications): update tests to reflect CaseStatus change
We're currently trying to fetch `stage` from the DocumentVersion table, but this is always null. Instead the stage comes from a separate `CaseStage` table.
[APPLICS-749](https://pins-ds.atlassian.net/browse/APPLICS-749)
[APPLICS-749]: https://pins-ds.atlassian.net/browse/APPLICS-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api/applications): fix fetching of case stage from document

---

apps/web/src/server/applications/case/project-team/applications-project-team.service.js
apps/web/src/server/applications/common/services/azure-project-team.js
apps/web/src/server/lib/msGraphRequest.js

Use pagination to find partial matches of users in AD
- Based the solution on the pagination solution in appeals
- Added some logging to prove results are being returned from the Active Directory
- Filter on partial matches
https://pins-ds.atlassian.net/browse/APPLICS-365

fix(web): use pagination to find users in AD (APPLICS-365)

---

apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
apps/api/src/server/migration/migrators/nsip-representation-migrator.js
apps/functions/applications-migration/common/migrators/nsip-representation-migration.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-825
The exam-timetable and the representation entities were not being published after migration. This PR adds the missing broadcast. It also updates the table name for `representations` to the correct one after checking with ODW.
Note: Full e2e cannot be tested until the following tickets are complete: 
- https://pins-ds.atlassian.net/browse/ODW-1383 
- https://pins-ds.atlassian.net/browse/ODW-1378

fix: missing migration broadcasts

---

apps/api/src/server/applications/application/documents/__tests__/create-document.test.js
apps/api/src/server/applications/application/documents/document.service.js

- Allow uploading of duplicate filenames as long as they were uploaded from front office
- Added to the unit tests to make sure a document with a duplicate filename and the fromFrontOffice property set to true will not be recognised as a duplicate and will be placed in the failed list when the upload fails.
https://pins-ds.atlassian.net/browse/APPLICS-861

fix(api): submitted files and comments are lost (APPLICS-861)

---

apps/e2e/cypress/e2e/back-office-applications/editCase.spec.js

prevented the Material Changes test to run when the MC Feature Flag is disabled and the files is not rendered
https://pins-ds.atlassian.net/browse/APPLICS-878

fix(e2e): excluded material changes test when the feature flag is off

---

apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js
apps/api/src/server/applications/application/project-updates/project-updates.controller.js
apps/api/src/server/applications/application/project-updates/project-updates.routes.js
apps/api/src/server/applications/application/project-updates/project-updates.service.js
apps/api/src/server/repositories/project-update.respository.js
apps/api/src/server/swagger-output.json
apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js
apps/web/src/server/applications/case/project-updates/project-updates.controller.js
apps/web/src/server/applications/case/project-updates/project-updates.service.js

Allow project updates update events to be sent on every update.
Make sure duplicate publish and unpublish events are not sent.
API:
- created a new end point for finalising project updates
- updated unit tests for the new end point
WEB:
- call new end point when "Publish Changes" or "Unpublish Changes" buttons are pressed
- updated unit tests for above
https://pins-ds.atlassian.net/browse/APPLICS-885

fix(api): changes to project updates are not published to FO (APPLICS-885)

---

apps/web/src/client/components/file-uploader/_client-actions.js
apps/web/src/client/components/file-uploader/_html.js
apps/web/src/client/components/file-uploader/_server-actions.js
apps/web/src/server/app/app.router.js
apps/web/src/server/app/components/__tests__/file-uploader.component.test.js
apps/web/src/server/app/components/file-uploader.component.js

- Retrieve the hex signature from each uploaded file in web client side
- Make a request and test the hex signature of each file against a table web server side
- Display an error for each file that fails the signature test
- Add some unit tests 
- Fixed any type errors
https://pins-ds.atlassian.net/browse/APPLICS-517

fix(web): file upload validate content type and signature (APPLICS-517)

---

README.md

A documentation update for developers to include a section on adding a dummy user data file to the back office solution when running the solution locally.

chore(readme.md): added instructions on adding a dummy user data file when running locally

---

apps/e2e/cypress/e2e/back-office-applications/addTeam.spec.js
apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
apps/e2e/cypress/e2e/back-office-applications/documentPropertiesWelsh.spec.js
apps/e2e/cypress/page_objects/basePage.js
apps/e2e/cypress/page_objects/createCaseSections/caseCreated.js
apps/e2e/cypress/page_objects/projectTeamPage.js
apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js
apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/applications/case/s51/__tests__/applications-s51.test.js
apps/web/src/server/views/app/layouts/app.layout.njk
apps/web/src/server/views/applications/case-s51/s51-attachment-successfully-deleted.njk
apps/web/testing/util/title.js

- Changed the main nunjucks layout to prefix the title with "Error: " if the page contains errors.
- Created the "verifyPageTitle" function to check the title within e2e tests.
- Applied the "verifyPageTitle" function to several e2e specs to prove the title is prefixed with "Error: " only when required. 
- Created the "getTitle" and "buildTitle" within the jest utils to allow the unit tests to prove the title is prefixed with "Error: " only when required. 
- Applied the above to some of the unit tests to prove the functionality works.
https://pins-ds.atlassian.net/browse/APPLICS-828

fix(web): accessibility audit - validation error (APPLICS-828)

---

apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
apps/web/src/server/lib/nunjucks-filters/select-items.js

- Add default checked property to unredacted item in the redaction layouts config in the documentation meta controller
- Update the select-items filter to accept a default checked item
https://pins-ds.atlassian.net/browse/APPLICS-854

feat(web): radio button selection missing (APPLICS-854)

---

apps/api/src/server/migration/migrators/nsip-representation-migrator.js
apps/functions/applications-migration/common/migrators/nsip-representation-migration.js

[Ticket](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-779)
This change ensures that any empty `originalRepresentation` fields are handled and given either a placeholder string or the value of the `redactedRepresentation`.
Also there is a slight fix to how some of the date values are put to the db. Previously they were just put as strings where as now they are correctly formatted ISO strings in UTC

fix(functions): ensure originalRepresentation field cannot be empty

---

README.md

Updated the README documentation with the new SQL Server instance command and updated NPM run commands.  The previous SQL command used "mcr.microsoft.com/mssql/server:2019-latest" which introduced an issue with the change of path name for "mssql-tools".  The new command is considered to provide a stable SQL Server instance for future use.
NPM run commands have been updated with the removal of ":applications" as this is no longer necessary because of a recent change.
No ticket for this issue.

docs: update readme with new db setup and npm run updates

---

apps/functions/applications-migration/common/migrators/s51-advice-migration.js

adviceGivenBy is sometimes null or empty string in Horizon. This change adds a default value of 'Not recorded in Horizon' when migrating from ODW.

feat(functions): default text for adviceGivenBy in migration

---

apps/api/src/server/applications/application/representations/__tests__/get-representation.test.js
apps/api/src/server/applications/application/representations/__tests__/get-representations.test.js
apps/api/src/server/applications/application/representations/attachment/__tests__/delete-attachment.test.js
apps/api/src/server/applications/application/representations/attachment/__tests__/post-attachment.test.js
apps/api/src/server/applications/application/representations/attachment/attachment.route.js
apps/api/src/server/applications/application/representations/attachment/attachment.service.js
apps/api/src/server/applications/application/representations/representations.controller.js
apps/api/src/server/repositories/__tests__/representation.repository.test.js
apps/api/src/server/repositories/representation.repository.js
apps/api/src/server/swagger-output.json
apps/web/src/server/applications/case/s51/applications-s51.controller.js

When deleting a document attachment on a Relevant Rep, it says that is attachment has been deleted, but the page showing the rep still has the document, and it can be looked at, downloaded, etc.
Reason was that the doc was soft deleted, but the view rep page did not filter on undeleted only.
APPLICS-1025 Live bug: Deleting a document attached to a Relevant Representation did not delete the document
(https://pins-ds.atlassian.net/browse/APPLICS-1025)

fix(api): fix relevant rep delete attachment bug (applics-1025)

---

apps/api/package.json
apps/api/src/server/applications/all-applications/__tests__/get-applications.test.js
apps/api/src/server/applications/search/__tests__/case-search.test.js
apps/api/src/server/repositories/__tests__/case.repository.test.js
apps/api/src/server/repositories/case.repository.js
apps/web/package.json
apps/web/src/server/applications/common/components/form/form-case.component.js
packages/feature-flags/src/static-feature-flags.js

New feature flag to conditionally allow the Training Sector, and training cases
Specifically:
- on the main dashboard, the training sector and any training cases will not display unless the flag is enabled
- when searching for cases, any training cases will not be included in the results unless the flag is enabled
- when creating new cases, the training sector is not visible / selectable unless the flag is enabled
- The flag `applics-1036-training-sector` is disabled by default (no training cases display)
- note that training cases in draft status will appear in the draft list, but the option to continue with training sector is not available
- also added `npm run test:nocov` to allow for running a single test (eg for debugging in local dev) without the visual clutter of the coverage …

feat(api): new training cases feature flag (applics-1030)

---

apps/api/src/server/migration/migrators/service-user-migrator.js
apps/functions/applications-migration/common/migrators/service-user-migration.js
apps/functions/applications-migration/common/utils.js
apps/functions/applications-migration/common/utils.test.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1093
CBOS DB has a boolean field over18 to store if a representation service user is under 18 or over 18. There was no field for this in Horizon so this value was stored in address county. Either there would be a normal county value or it would store age information (under18 or over18).

feat(functions): migration under18 rep service users

---

apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js

- Added a label to the document type object to be rendered by the update success banner.
[APPLICS-1118](https://pins-ds.atlassian.net/browse/APPLICS-1118): Document property update success banner undefined for Document Type
[APPLICS-1118]: https://pins-ds.atlassian.net/browse/APPLICS-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): add document type label for update success banner (applics-1118)

---

apps/api/src/server/migration/migrators/nsip-representation-migrator.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1120
We were publishing after migrating representations, but we were using the `UPDATE` eventType. We need to use `PUBLISH` for the first representation publish as FO only uses `UPDATE` to change the status, not the consume the whole entity. This change will unblock FO and allow it to consume migrated representations as soon as they are published.

fix(api): publish reps on migration

---

apps/api/src/server/applications/constants.js
apps/api/src/server/migration/migrators/nsip-document-migrator.js
apps/functions/applications-migration/README.md
apps/functions/applications-migration/local.settings.json.example

- Migration: Correctly map the document types from Horizon to the correct subset for CBOS. Note that this is for the DocumentType in the DocumentVersion table
- also added a .example file for the migration:  local.settings.json file, and updated the README
https://pins-ds.atlassian.net/browse/APPLICS-1103

feat(functions): doc migration set doc version doc type correctly (applics-1103)

---

apps/api/src/server/migration/migrators/nsip-document-migrator.js
apps/api/src/server/utils/__tests__/file-fns.test.js
apps/api/src/server/utils/file-fns.js
apps/functions/applications-migration/common/migrators/nsip-document-migration.js

- Migrates all versions and renditions of a document to a single document in CBOS, intersplicing PDF renditions if any into the correct order.  This does make a new version numbering, ie 10 doc versions with 10 PDF renditions creates 20 versions in CBOS.
eg original v1 => v1, rendition v1 => v2, original v2 => v3, rendition v2 => v4 etc.
- corrects a bug with datePublished - if there is a NULL date in ODW, it was setting epoch date 1970 in CBOS, now correctly setting it to NULL.
- file display name is maintained from the previous version (as per CBOS UI), and the display name has the file suffix trimmed off (the same as CBOS UI currently does).
- file suffix trim fn `trimDocumentNameSuffix `created in utils in new file `utils/file-fns.js`, and unit tests added. …

feat(api): doc migration correctly handle versions and renditions (applics-1134)

---

apps/api/jsconfig.json
apps/api/package.json
apps/api/src/server/applications/constants.js
apps/api/src/server/infrastructure/payload-builders/nsip-document.js
apps/api/src/server/migration/migrators/nsip-document-migrator.js
apps/api/src/server/repositories/folder.repository.js
apps/api/src/server/utils/mapping/__tests__/map-case-status.test.js
apps/api/src/server/utils/mapping/map-case-status-string.js
apps/api/src/server/utils/mapping/map-case-status.js

- Correct the Document Case Stage mapping functions used to create the service bus broadcasts, to ensure it outputs the correct values for:
-- developers_application
-- post_decision
- note that this was already fixed in a Hotfix that went direct to Prod, this fix is into main trunk to ensure the fix persists
- additionally added an import shortcut `#api-constants` to make it easy to import the API constants file without having to get the correct pathing - eg `import { folderDocumentCaseStageMappings } from '#api-constants';`
https://pins-ds.atlassian.net/browse/APPLICS-1169

fix(api): doc case stages publish fail (applics-1169)

---

apps/web/src/server/views/applications/case-s51/properties/s51-properties.njk
apps/web/src/server/views/applications/case-s51/properties/tab-attachments.component.njk

Removing the option to delete S51 documents if the advice is published. Also added a note to explain to the user how to delete if the advice is published.
https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/269?selectedIssue=APPLICS-1111

fix(web): add note for deleting published s51 and remove delete button

---

apps/api/Dockerfile
apps/web/Dockerfile

we don't specify an alpine version in our dockerfiles and things have broken specifically for prisma.
node alpine has been updated, and openssl path has changed, setting node alpine to node:20-alpine3.20

fix(tooling): set node-alpine version to node:20-alpine3.20

---

apps/api/src/database/migrations/20241211144106_application_details_location_description_size_increase/migration.sql
apps/api/src/database/schema.prisma
apps/web/src/server/applications/create-new-case/case/applications-create-case.validators.js

- Increased location description character allowance to 2000 in validator function.
- Increased location description character allowance to 2000 in Prisma schema.
Manual testing of validation completed for creating a new case, check your answers page and updating the location for an existing case.
[APPLICS-1003](https://pins-ds.atlassian.net/browse/APPLICS-1033): Increase project location character limit
[APPLICS-1003]: https://pins-ds.atlassian.net/browse/APPLICS-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api): increase location description size in database and validator (applics-1033)

---

apps/web/src/server/applications/case/representations/__tests__/__snapshots__/applications-representaions.test.js.snap
apps/web/src/server/views/applications/representations/representations.njk

- Moved breadcrumbs to the top of the relevant representations folder page, in line with the layout in other folders.
- Regenerated the relevant representations snapshot.
[APPLICS-732](https://pins-ds.atlassian.net/browse/APPLICS-732): BO audit - Relevant reps page breadcrumbs
[APPLICS-732]: https://pins-ds.atlassian.net/browse/APPLICS-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(web): move breadcrumbs on relevant reps folder page (applics-732)

---

apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/applications/case/s51/__tests__/applications-s51.test.js
apps/web/src/server/views/applications/case-s51/s51-method.njk

- Removed S51 enquiry method hint text.
- Updated unit test.
- Regenerated S51 snapshot.
[APPLICS-1180](https://pins-ds.atlassian.net/browse/APPLICS-1180): C-BOS accessibility audit - S51 page
[APPLICS-1180]: https://pins-ds.atlassian.net/browse/APPLICS-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(web): remove s51 enquiry method hint text (applics-1180)

---

apps/e2e/cypress/page_objects/representationPage.js

Since the relevant representations breadcrumbs were moved to the top of the page, the relevant representations e2e test has not been able to locate the 'View publishing queue' link which is now further down the page. This PR replaces the viewPublishQueue method previously used in the test to locate the element with the clickLinkByText method, as this allows the test to scroll down the page to find the link. 
[APPLICS-1241](https://pins-ds.atlassian.net/browse/APPLICS-1241): Fix Relevant Representation E2E Test
[APPLICS-1241]: https://pins-ds.atlassian.net/browse/APPLICS-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): update relevant representation e2e test (applics-1241)

---

apps/web/src/client/components/files-list/_html.js
apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
apps/web/src/server/views/applications/components/folder/folder-actions.component.njk

https://pins-ds.atlassian.net/browse/APPLICS-1248
-update the documents folder page:
-- align the 'Clear Selected' link
-- make download error summary box same width as other errors
-add missing folder name to templates rendering on error

feat(web): documents page UI alignment (applics-1248)

---

apps/web/src/server/applications/case/representations/representation-details/representation-status/__tests__/__snapshots__/representation-status.test.js.snap
apps/web/src/server/applications/case/representations/representation-details/representation-status/representation-status.view-model.js
apps/web/src/server/views/applications/representations/representation-details/representation-status/representation-status.njk

- Removed the relevant reps status tag on the  change status screen.
- Changed the relevant reps status radio button logic to allow the selected button to display as checked. 
- Regenerated the relevant reps snapshot.
[APPLICS-1171](https://pins-ds.atlassian.net/browse/APPLICS-1171): C-BOS accessibility audit - 'Change status' of relevant rep
[APPLICS-1171]: https://pins-ds.atlassian.net/browse/APPLICS-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(web): remove relevant rep change status tag (applics-1171)

---

apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/views/applications/case-documentation/properties/tab-details.component.njk

https://pins-ds.atlassian.net/browse/APPLICS-1144
-Change 'Interested Party number' label text to 'IP number'

fix(web): fix interested party number label overlap (applics-1144)

---

apps/api/src/server/migration/archive-folder-info.controller.js
apps/api/src/server/migration/migration.routes.js
apps/functions/applications-migration/common/get-archive-folder-info.js
apps/functions/applications-migration/migrate-case/index.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1257
Show archive folder paths and counts after migration. Displayed like this:

feat(functions): display archive folder info post migration

---

apps/api/src/server/applications/application/representations/__tests__/create-representation.test.js
apps/api/src/server/applications/application/representations/__tests__/patch-representation.test.js
apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js
apps/api/src/server/applications/application/representations/status/__tests__/patch-status.test.js
apps/api/src/server/applications/constants.js
apps/api/src/server/infrastructure/payload-builders/nsip-representation.js

The representationFrom field in the service bus broadcast is currently being overridden if there is an agent, this is not correct, we should just be populating the value of the CBOS field Representation.representedType.
schema field representativeId - In the case where a rep was marked as having an agent, but later changed, we want to retain this information in CBOS in case they set the agent back again.  But we do not want to broadcast the agent id if they have not currently set the Representation.representedType field to be AGENT.  Therefore if Representation.representedTypeis AGENT, populate the schema field representativeId  with the agentId, else NULL.
Change the broadcast payload build to send NULL value for registerFor field.  This field is only used by Front Office when reps come …

fix(api): correct rel rep agent publishing (applics-1290)

---

apps/web/src/server/applications/case/representations/representation-details/__fixtures__/representation-details.fixture.js
apps/web/src/server/applications/case/representations/representation-details/applications-relevant-rep-details.view-model.js
apps/web/src/server/applications/case/representations/representation/representation-entity/__tests__/__snapshots__/represetation-entity.test.js.snap
apps/web/src/server/applications/case/representations/representation/representation-entity/entity.view-model.js
apps/web/src/server/views/applications/representations/representation-details/index.njk

https://pins-ds.atlassian.net/browse/APPLICS-1293
There was a disjoint between user actions and the state of the representation entity.
Current logic was depending on `representative.id` to display entity selection for the representation. This was a problem In a situation where there was an agent assigned to representation (`representedType`), and then this was changed to  PERSON or ORGANISATION later on. Since AGENT used to be selected, `representative.id` was still present in the data and the UI was defaulting to display AGENT version of the label on the radio UI, despite (`representedType`) currently saved for that representation being PERSON or ORGANISATION. 
This PR uses (`representedType`) do drive the display logic, allowing us to display the currently stored `representedType` …

fix(web): representation entity to display correct value (applics-1293)

---

apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
apps/e2e/cypress/page_objects/createCasePage.js
apps/e2e/cypress/support/utils/options.js
apps/e2e/cypress/support/utils/utils.js
apps/web/src/server/applications/common/components/form/form-applicant.component.js
apps/web/src/server/applications/common/services/session.service.js
apps/web/src/server/applications/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap
apps/web/src/server/applications/create-new-case/applicant/__tests__/applications-create-applicant.test.js
apps/web/src/server/applications/create-new-case/applicant/applications-create-applicant.controller.js
apps/web/src/server/applications/create-new-case/applicant/applications-create-applicant.router.js
apps/web/src/server/applications/create-new-case/applicant/applications-create-applicant.service.js
apps/web/src/server/applications/create-new-case/applicant/applications-create-applicant.validators.js
apps/web/src/server/applications/create-new-case/case/applications-create-case.controller.js
apps/web/src/server/views/applications/components/case-form/applicant/organisation-name.njk

- Moved the applicant organisation screen in the journey to be displayed before the applicant information checkbox screen.
- Removed applicant organisation from the applicant information checkbox screen.
- Added validation to the applicant organisation field.
- Updated the unit tests.
- Updated the e2e tests.
The above changes are covered by the following e2e tests: createCase, editCase, smokeTest
[APPLICS-1302](https://pins-ds.atlassian.net/browse/APPLICS-1302): Create case 'Applicant's Organisation' field - to be made mandatory
[APPLICS-1302]: https://pins-ds.atlassian.net/browse/APPLICS-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web): make applicant organisation name field mandatory (applics-1302)

---

apps/api/src/server/migration/migration.routes.js
apps/api/src/server/migration/migrators/migration-cleanup.controller.js
apps/functions/applications-migration/common/migration-cleanup.js
apps/functions/applications-migration/migrate-case/index.js

Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1288
When migrating EN010157 it was noticed that the S51 advice folder had some loose documents that were not tied to an advice.  Whilst these migrate okay they are not visible in C-BOS as docs can only be seen as attachments to advices. This ticket moves those to the archive folder `Archive Documentation/s51 Unattached` folder.
Can be tested with `TR050004` locally or on test env.

fix(functions): move loose s51 attachments to archive in migration

---

apps/api/src/server/applications/application/documents/document.service.js

when addind a new document version, the following fields are copied from the previous version, creating incorrect data - eg published blob paths etc:
- publishedBlobContainer 
- PublishedBlobPath 
- publishedStatusPrev 
- datePublished 
- redactedStatus 
These should all be reset to null.
https://pins-ds.atlassian.net/browse/APPLICS-1287

fix(api): fix db errors when adding new doc version (applics-1287)

---

apps/api/src/server/migration/migrators/folder/folder.js

Updates migration folder mapping. The issue was an inconsistency between a folder name used in the `folderMapping` map, and the map generated by `getFolderIdMap` and due to case sensitivity, an empty result being returned.
I've checked all the folders in `folderMapping` and only `Decision > SoS decision` was named inconsistently, so have just updated the name accordingly.
APPLICS-1381

fix(api): update folder mapping for sos decision folder

---

apps/web/src/server/applications/case/applications-case.router.js
apps/web/src/server/applications/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap
apps/web/src/server/applications/case/edit/applicant/applications-edit-applicant.controller.js
apps/web/src/server/applications/case/edit/applicant/applications-edit-applicant.router.js
apps/web/src/server/applications/create-new-case/case/applications-create-case.validators.js
apps/web/src/server/views/applications/case/overview.njk

- Added validation to the applicant organisation field on the project overview page and the edit applicant organisation page.
- Added validators to routers.
- Updated existing validators for Welsh fields on the project overview page so this validation is only applied to Welsh cases.
- Updated the project overview template to prevent validation being bypassed for non-Welsh cases on form submission and add the applicant organisation data to the request body.
- Regenerated the relevant snapshot.
[APPLICS-1306](https://pins-ds.atlassian.net/browse/APPLICS-1306): Overview page - Applicant's organisation field to be mandatory
[APPLICS-1306]: https://pins-ds.atlassian.net/browse/APPLICS-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web): make applicant organisation mandatory on project overview (applics-1306)

---

apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
apps/e2e/cypress/e2e/back-office-applications/smokeTests.spec.js
apps/e2e/cypress/page_objects/basePage.js
apps/e2e/cypress/support/utils/createTimetableItemInfo.js
apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
apps/web/src/server/applications/case/examination-timetable/applications-timetable.validators.js

- Added additional validation for exam timetable deadlines and procedural deadlines in English. This checks that the format for each deadline includes a description followed by a bullet point, denoted by an asterisk, for each deadline item. This then ensures that the information displays correctly in FO.
- Added additional validation to the above exam timetable item types in Welsh to ensure a description is included before any bullet points.
- Updated the end-to-end tests with the new exam timetable description format. 
- Changed how the end-to-end tests compare the entered exam timetable description with the text on the 'Check your answers page' as the former contains asterisks and the latter contains bullet point symbols.
[1403](https://pins-ds.atlassian.net/browse/APPLICS-1403): Able …

fix(web): add validation for exam timetable deadlines (applics-1403)

---

apps/api/src/server/applications/application/documents/__tests__/document.service.test.js
apps/api/src/server/applications/documents/documents.service.js
apps/api/src/server/applications/documents/youtube-html-template.js
apps/api/src/server/migration/migrators/cleanup/htmlTemplates.js

For Migrated HTML Template files, it was not adding the title in the new template.  
This is for migrated templates only, not for ones uploaded via the UI
https://pins-ds.atlassian.net/browse/APPLICS-1490

fix(api): migrate html template title (applics-1490)

---

apps/api/src/server/migration/migrators/nsip-document-migrator.js
apps/api/src/server/utils/__tests__/file-fns.test.js
apps/api/src/server/utils/file-fns.js

Document Migration - we identified that we were missing the document "title" from Horizon - ie the name that is displayed and editable by the user.  This is what is used to make the published doc in the blob storage, and therefore renaming is causing issues with NI redirection.  Also if a HZN user has renamed a document, that was lost - we only got the original filename.
HZN View and ODW have been changed to include both the originalFilename, and filename (the doc title).
This change is to amend CBOS to correctly ingest the filetitle, rather than cropping it from the original upload filename.
-Also noticed this:  CBOS functionality is, when a doc is uploaded, to take the original filename, copy it and remove the file suffix (eg .doc, pdf etc) and store that as the document title - the …

fix(api): migrated docs correctly use doc title from hzn (applics-1507)

---

apps/web/src/server/applications/case/applications-case.locals.js
apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk

- Updated existing case middleware to generate a URL for the front office project page to be accessed in the case overview banner template.
- Conditionally rendered a link to the project page in the banner template if the project is published.
[Applics 1504](https://pins-ds.atlassian.net/browse/APPLICS-1504): CBOS hyperlink to FO project page

feat(web): add front office project page link to case overview banner (applics 1504)

---

apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
apps/api/src/server/repositories/folder.repository.js

This PR sets the isCustom value to false for new exam timetable folders and subfolders on creation. This prevents the rename link and delete link being rendered in the browser for those folders. The default value for isCustom is set to true for custom folders created anywhere else. The relevant unit test has also been updated.
[APPLICS 1538](https://pins-ds.atlassian.net/browse/APPLICS-1538): Locking Exam timetable folders

feat(api): remove rename link and delete link for new exam timetable folders (applics 1538)

---

apps/functions/applications-command-handlers/deadline-submission-command/__tests__/deadline-submission-command.test.js
apps/functions/applications-command-handlers/deadline-submission-command/back-office-api-client.js
apps/functions/applications-command-handlers/deadline-submission-command/index.js
apps/functions/applications-command-handlers/deadline-submission-command/lib.js

Some "Have your Say" submissions from the Front Office were failing in CBOS (eg a submission against an Exam Timetable deadline/sub item), if it cannot find the correct folder to deliver the files to.
This ticket addresses this in CBOS by
- refactored code to more efficiently identify the exam item (deadline) and its folder
- added code when checking to find the sub-item (Line item) folder, if it does not exist, then to not fail, but instead put the files into an "Unassigned" folder in that deadline.
- If an Unassigned folder does not exist on that deadline, then create it, and use that for the files
https://pins-ds.atlassian.net/browse/APPLICS-1534

feat(functions): exam timetable unassigned folder (applics-1534)

---

apps/api/src/server/applications/application/documents/document.service.js
apps/api/src/server/repositories/document.repository.js
apps/api/src/server/repositories/s51-advice-document.repository.js
apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js
apps/web/src/server/applications/case/documentation/__tests__/generate-document-name-one-deletion.test.js
apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
apps/web/src/server/applications/case/documentation/utils/generate-document-name-on-deletion.js
apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
apps/web/src/server/applications/case/s51/__tests__/applications-s51.test.js
apps/web/src/server/applications/case/s51/applications-s51.controller.js
apps/web/src/server/applications/common/services/session.service.js
apps/web/src/server/views/applications/case-documentation/documentation-delete.njk
apps/web/src/server/views/applications/case-s51/s51-delete-attachment.njk

This PR makes the following changes to allow users to upload a document with the same name as a deleted document:
- Generates a new document name on deletion by creating a UTC timestamp and appending this to the existing document name.
- Displays the document name on deletion to the user before deletion.
- Replaces the existing fileName in the database with the newly generated document name  following successful deletion.
- Updates the code that checks whether a file name already exists so it removes the file extension from the new file name before comparing and checks against fileName rather than originalFileName.
- Updates existing unit tests and regenerates failing snapshots.
[APPLICS-1386](https://pins-ds.atlassian.net/browse/APPLICS-1386): Renaming documents upon deletion …

feat(web): rename documents on deletion (applics-1386)

---

package.json

There were two NPM test scripts, and one of them did not run all the tests. The duplicate has been removed.

chore(tooling): remove duplicate test script

---

apps/api/src/server/migration/migrators/nsip-document-migrator.js
apps/api/src/server/utils/__tests__/file-fns.test.js
apps/api/src/server/utils/file-fns.js

When migrating documents, the document title is created by taking the doc title from HZN, and stripping off any know file suffix - to be compatible with existing CBOS functionality.  This PR also removes any multiple spaces from the title, and also trims.  This is consistent with what old NSIP website did when it received published docs.
https://pins-ds.atlassian.net/browse/APPLICS-1598

feat(api): migration remove multiple spaces from filename (applics-1598)

---

apps/web/src/server/applications/case/representations/representation-details/__tests__/__snapshots__/applications-relevant-rep-details.test.js.snap
apps/web/src/server/views/applications/representations/representation-details/includes/change/representation.include.njk

A relevant representation comment submitted via Front Office was not visible on the CBOS relevant representation detail page. When the 'Redact' link was clicked, the full comment was visible.
Comments and their excerpts are wrapped in backticks and passed into a JavaScript function in the Nunjucks template as strings. The function allows users to toggle between the comment excerpt and full comment in the browser. Because this particular comment contained backticks, the function errored and the comment was not displayed.
This PR adds the comments directly to the template where they can be accessed in the function using the querySelector() method, rather than being passed in as strings. This allows the backticks to be rendered without causing errors. The associated snapshot has also been …

fix(web): remove comment text from javascript string and add to template (applics-1551)

---

infrastructure/front-door.tf

After the Front Door migration HTML uploads didn't work with the new rules, so some exclusions to support that.

fix(infrastructure): allow HTML file uploads (waf updates)

---

apps/api/src/server/applications/s51advice/s51-advice.controller.js
apps/api/src/server/repositories/__tests__/document.repository.test.js
apps/api/src/server/repositories/document.repository.js

This ticket fixes several issues:
- when an S51 Attachment is added to the case, rather than finding the latest document reference number on a case in order to make the next one, it is counting the latest S51 Advice reference number.  So if a case has 10 docs numbered 00001 … 00010, but 3 S51 Advice, adding an S51 Advice attachment makes a duplicate 00004.
- The issue is further compounded by another fault, this time in the document side.  The fn that gets the latest document on a case uses created date order, rather than document reference.  So in the case above where the S51 attachment is made with 00004, this becomes the latest doc ref, and all documents added after that start from 00005 onwards, duplicating all existing docs.
- There is a 3rd issue in that deleted docs are ignored. …

fix(api): fix document reference not unique (applics-1082)

---

apps/api/src/server/migration/migrators/cleanup/htmlTemplates.js
apps/api/src/server/migration/migrators/migration-cleanup.controller.js

- when checking HTML files for YouTube content, if the file does not contain a YouTube link, it reports out the whole html file - which is unnecessary
- when checking HTML files for YouTube content, if the file does not contain a YouTube link, it throws an error - this is not handled at the higher level, and so the cleanup completes at that point, before running the Exam Folder fixes (if selected)
- When fixing values for the Exam timetable folders, it assigns a stage “Examination” for all exam folders, but for the case of Exam Type id:10 (Procedural Deadline (Pre-Examination)), the stage should be set to 'Pre-examination'
- when creating new missing exam timetable folders, the code uses std fn createFolder which sets isCustom to true, this should be set to false - use underlying DB …

fix(api): fix migration cleanup bugs (applics-1635)

---

apps/api/src/server/applications/documents/documents.service.js
apps/api/src/server/migration/migrators/cleanup/htmlTemplates.js

When migrating cases, it converts HTML YouTube files from old HZN format to new CBOS format.
Previous code had attempted to extract the title and insert into the HTML.
However these are now failing to publish as the publish validation checks against a template that has a fixed string "Video title".
Note that HTMLs uploaded by UI are not affected by this issue.
This ticket reverts things so that the title remains "Video title", and the doc can then publish during migration.
https://pins-ds.atlassian.net/browse/APPLICS-1490

fix(api): revert migration fix for html video title (applics-1490)

---

apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
apps/web/src/server/applications/case/key-dates/applications-key-dates.controller.js
apps/web/src/server/lib/nunjucks-filters/key-dates-property.js
apps/web/src/server/views/applications/case-key-dates/key-dates-index.njk
apps/web/src/server/views/applications/case-key-dates/key-dates.component.njk

Refactored the Pre-application section in Key Dates management by splitting it into two logical groups for better user experience. The original single Pre-application section containing 9 date fields was divided into "Pre-application dates" (containing project initiation dates like first notification, website publication, submission dates, and Section 46 notification) and "Screening and scoping" (containing regulatory process dates for screening and scoping opinions). This change improves navigation and reduces cognitive load for case officers while maintaining full functionality - each section retains its individual "Manage dates" capability and all existing data storage/validation logic remains intact. The implementation uses a splitPreApplicationSection() function that transforms the …

fix(web): make Screening and scoping its own group (applics-1553)
