Planning-Inspectorate/back-office

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
> feat(api): replace all params

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
> fix(api): cast automatic update IDs to numbers

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
> fix(api): fix update status

- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.routes.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/document.repository.js
- appeals/api/src/server/tests/documents/mocks.js
Update the GET Document API endpoint to return the Redaction status
https://pins-ds.atlassian.net/browse/BOAT-531
> feat(appeals/api): return the redaction status from the get appeals document endpoint

- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/testing/app/fixtures/referencedata.js
fix 404 error when scheduling site visit
BOAT-559
> fix(web): fix 404 error when scheduling site visit

- apps/api/src/server/repositories/document-activity-log.repository.js
Correct the `.create()` Prisma call to specify the connection from the activity log row and the document version row.
Will have to test in dev.
[BOAS-1226](https://pins-ds.atlassian.net/browse/BOAS-1226)
[BOAS-1226]: https://pins-ds.atlassian.net/browse/BOAS-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(api/applications): set up connection from log to doc version

- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/index.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.service.js
- appeals/api/src/server/repositories/integrations.repository.js
Fixes a bug on questionnaire import
Imports nearby case references
> fix(appeals/api): questionnaire import nearby

- apps/e2e/cypress/fixtures/sample-doc.pdf
> test(e2e): Added PDF File

- apps/web/src/server/app/app.router.js
Assert access to one of the three groups to get access to any pages.
[https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-1242](https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-1242)
> fix(applications/web): assert group membership for all routes

- appeals/web/environment/config.d.ts
- appeals/web/src/server/app/app.controller.js
- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/app/auth/__tests__/auth.test.js
Ensures only configured AD groups can access the application
> fix(appeals/web): assert group access

- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/documents/documents.mapper.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/api/src/server/tests/data.js
> fix(appeals/api): mapping of LPAQ documents

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.validators.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.validators.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/outcome-incomplete/outcome-incomplete.validators.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/validators/checkbox-text-items.validator.js
appellant case and lpaq not valid flows character limit fix
BOAT-325
> fix(web): appellant case and lpaq not valid flows character limit fix

- appeals/web/src/client/components/add-another/add-another.js
fix add another component bug allowing more items than maximum to be added
BOAT-590
> fix(web): fix add another component bug allowing more items than maximum to be added

- apps/api/src/message-schemas/events/interested-party.schema.json
- apps/api/src/message-schemas/events/service-user.schema.json
> feat(api): boas-1245 impement service user schema

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.router.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
separate routes for appellant case and lpaq document upload
BOAT-456
> fix(web): separate routes for appellant case and lpaq document upload

- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.router.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.validators.js
- appeals/web/src/server/lib/validators/time-input.validator.js
add validation to ensure site visit start time is before end time
BOAT-426
> fix(web): add validation to ensure site visit start time is before end time

- apps/web/src/server/applications/case/representations/__tests__/__snapshots__/applications-representaions.test.js.snap
- apps/web/src/server/applications/case/representations/__tests__/applications-representaions.test.js
- apps/web/src/server/applications/case/representations/applications-relevant-reps.controller.js
- apps/web/src/server/applications/case/representations/applications-relevant-reps.service.js
- apps/web/src/server/applications/case/representations/relevant-representation.types.d.ts
- apps/web/src/server/applications/case/representations/utils/has-unpublished-rep-updates.js
- apps/web/src/server/views/applications/representations/representations.njk
https://pins-ds.atlassian.net/browse/ASB-1808?atlOrigin=eyJpIjoiYjY5MGYwYWM3MmFhNDU4ZThiMmM0N2JhZTIzODVjYjMiLCJwIjoiaiJ9
> feat(web/applications): add unpublished rep updates banner

- apps/api/src/server/applications/application/documents/__tests__/unpublish-document.test.js
- apps/api/src/server/applications/application/documents/document.controller.js
- apps/api/src/server/applications/application/documents/document.routes.js
- apps/api/src/server/repositories/document-metadata.repository.js
- apps/api/src/server/swagger-output.json
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.router.js
- apps/web/src/server/applications/case/documentation/applications-documentation.service.js
- apps/web/src/server/applications/case/documentation/applications-documentation.validators.js
- apps/web/src/server/views/applications/case-documentation/documentation-unpublish.njk
- apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
- apps/web/src/server/views/applications/case-timetable/timetable-check-your-answers.njk
- apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk
- apps/web/src/server/views/applications/components/folder/folder-actions.component.njk
> feat(web/applications): add documentation-unpublish page (boas-1054)

- apps/api/src/server/applications/application/documents/document.service.js
Emit an event when documents are unpublished.
[BOAS-1265](https://pins-ds.atlassian.net/browse/BOAS-1265)
[BOAS-1265]: https://pins-ds.atlassian.net/browse/BOAS-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api/applications): emit an event when documents are unpublished

- apps/api/src/database/migrations/20231016175637_remove_circular_dependency/migration.sql
> fix(api): add db migration for schema changes

- appeals/web/src/server/app/config/session.js
- apps/web/src/server/app/config/session.js
Revert Redis cache change for now, until infra is fixed.
N/A
> fix(web): revert to in memory session storage until infra is fixed

- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
Display an error if trying to unpublish a document that is not published.
[BOAS-1288](https://pins-ds.atlassian.net/browse/BOAS-1288)
[BOAS-1288]: https://pins-ds.atlassian.net/browse/BOAS-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web/applications): unpublishing a non-published file produces error

- appeals/api/src/message-schemas/pins-appeal.schema.json
- appeals/api/src/message-schemas/pins-appellant-case.schema.json
- appeals/api/src/message-schemas/pins-root.schema.json
- appeals/api/src/server/endpoints/appeal-allocation/appeal-allocation-controller.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/appellant-case.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/index.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.middleware.js
- appeals/api/src/server/endpoints/integrations/integrations.service.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
- appeals/api/src/server/infrastructure/topics.js
- appeals/api/src/server/repositories/integrations.repository.js
- Introduce publishing to topic for service users (appellants, agents, etc).
- Validation of messages with schemas
- Broadcasts appeal updates to SB as a result of updating appeal data in the BO (still work to do here).
[BOAT-611](https://pins-ds.atlassian.net/browse/BOAT-611)
[BOAT-611]: https://pins-ds.atlassian.net/browse/BOAT-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): publishes service users

- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
Use case reference stored in response.locals instead of attempting to take it from one of the fetched files.
[BOAS-1294](https://pins-ds.atlassian.net/browse/BOAS-1294)
[BOAS-1294]: https://pins-ds.atlassian.net/browse/BOAS-1294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web/applications): use case reference stored in response.locals

- appeals/api/src/server/infrastructure/topics.js
Renamed appeal and appeal-document topic to align to ODW.
> feat(appeals): renamed ODW topics

- apps/web/src/server/applications/case/representations/applications-relevant-reps.router.js
- apps/web/src/server/applications/case/representations/config.js
- apps/web/src/server/applications/case/representations/publish-representations-error/__tests__/__snapshots__/publish-representations-error.test.js.snap
- apps/web/src/server/applications/case/representations/publish-representations-error/__tests__/publish-representations-error.test.js
- apps/web/src/server/applications/case/representations/publish-representations-error/publish-representations-error.controller.js
- apps/web/src/server/applications/case/representations/publish-representations-error/publish-representations-error.router.js
- apps/web/src/server/applications/case/representations/publish-updated-representations/__tests__/__snapshots__/publish-updated-representations.test.js.snap
- apps/web/src/server/applications/case/representations/publish-updated-representations/__tests__/publish-updated-representations.test.js
- apps/web/src/server/applications/case/representations/publish-updated-representations/publish-updated-representations.controller.js
- apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/publish-valid-reps.test.js
- apps/web/src/server/applications/case/representations/publish-valid-representations/publish-valid-reps.controller.js
- apps/web/src/server/applications/case/representations/utils/publish-representations.js
- apps/web/src/server/views/applications/representations/publish-representations-error.njk
- apps/web/src/server/views/applications/representations/publish-updated-representations.njk
https://pins-ds.atlassian.net/browse/ASB-1917?atlOrigin=eyJpIjoiMmZhYWUzMDg1YTJhNDI2OGFiNzhlYzcyMGQ2YTcyYjAiLCJwIjoiaiJ9
> feat(web/applications): Publish representations error page

- apps/web/src/server/applications/case/representations/publish-updated-representations/__tests__/__snapshots__/publish-updated-representations.test.js.snap
- apps/web/src/server/applications/case/representations/publish-updated-representations/__tests__/publish-updated-representations.test.js
- apps/web/src/server/applications/case/representations/publish-updated-representations/publish-updated-representations.controller.js
- apps/web/src/server/applications/case/representations/publish-updated-representations/publish-updated-representations.controller.validators.js
- apps/web/src/server/applications/case/representations/publish-updated-representations/publish-updated-representations.router.js
- apps/web/src/server/views/applications/representations/publish-updated-representations.njk
https://pins-ds.atlassian.net/browse/ASB-1852?atlOrigin=eyJpIjoiYmMzZDY5OGIwZjdkNDJmNjk4YjgwZjdmNDFlODBkMjYiLCJwIjoiaiJ9
> feat(web/applications): Add validation for select representations to publish

- apps/api/src/database/migrations/20231020074907_seed_service_user_table/migration.sql
> feat(api): seed service users

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Fixes site visit schedule, prepopulates with exisiting values, saves data, and redirects correctly
> fix(appeals): fix site-visit

- apps/api/.env.example
Environment setting to ensure that we don't get the Prisma-MSSQL > 2100 parameters error.  
**Devs:** This needs to be applied to .env files in all local dev apps/api.
And will need to be added to Application Settings in the Azure environments for the BOAS API
> fix(api/applications): prisma 2100 db issue (boas-1236)

- appeals/api/setup-tests.js
- appeals/api/src/database/migrations/20231020085722_docs_audit_trail_extension/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/seed-clear.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/audit-trails/audit-trails.service.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/endpoints/documents/documents.mapper.js
- appeals/api/src/server/endpoints/documents/documents.middleware.js
- appeals/api/src/server/endpoints/documents/documents.routes.js
- appeals/api/src/server/endpoints/documents/documents.service.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/audit-trail.repository.js
- appeals/api/src/server/repositories/document-metadata.repository.js
- appeals/api/src/server/repositories/document.repository.js
- appeals/api/src/server/tests/documents/mocks.js
- appeals/api/src/server/utils/__tests__/find-previous-version.test.js
- appeals/api/src/server/utils/find-previous-version.js
- packages/appeals/types/document.d.ts
Deletes document versions, logs in the audit.
Returns document history with versions and audits.
TODO: mapping API output to simplify for WEB.
[BOAT-566](https://pins-ds.atlassian.net/browse/BOAT-566)
[BOAT-567](https://pins-ds.atlassian.net/browse/BOAT-567)
[BOAT-566]: https://pins-ds.atlassian.net/browse/BOAT-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BOAT-567]: https://pins-ds.atlassian.net/browse/BOAT-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): delete versions and list doc history

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/lib/mappers/validation-outcome-reasons.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-596
> fix(web): fix/BOAT-596-fix-add-another-blank-field

- apps/api/src/server/applications/application/representations/representation.mapper.js
- apps/api/src/server/repositories/__tests__/representation.repository.test.js
- apps/api/src/server/repositories/representation.repository.js
Add missing filename for representation attachments to `GET /applications/{id}/representations/{repId}` endpoint
ASB-1702
> fix(applications/api): add filename to get representation endpoint

- apps/e2e/cypress/page_objects/casePage.js
- apps/e2e/cypress/page_objects/createCaseSections/checkYourAnswers.js
- apps/e2e/cypress/support/utils/createProjectInformation.js
> test(e2e): fixed failed test scripts

- appeals/web/src/client/components/add-another/add-another.js
https://pins-ds.atlassian.net/browse/BOAT-594
> fix(web): fix/BOAT-594-fix-add-remove-line

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/appeals/appeals.routes.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/__tests__/sort-appeals.test.js
- appeals/api/src/server/utils/appeal-sorter.js
- Adds an API endpoint to get a personal list by Active Directory ID
- Implements a sorting algo based on dates and status
[BOAT-573](https://pins-ds.atlassian.net/browse/BOAT-573)
[BOAT-573]: https://pins-ds.atlassian.net/browse/BOAT-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): add personal list API

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/appeals/question-page/question-page.controller.js
- appeals/web/src/server/appeals/question-page/question-page.mapper.js
- appeals/web/src/server/appeals/question-page/question-page.router.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/global-mapper-formatter.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/views/app/components/document-upload-info.njk
- appeals/web/src/server/views/app/components/file-uploader.component.njk
- appeals/web/src/server/views/patterns/question-page.pattern.njk
- appeals/web/testing/app/fixtures/referencedata.js
- appeals/web/testing/lib/testMappers.js
> feat(appeals): add dynamic rendering to question pages

- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/times.js
- appeals/web/src/server/lib/validators/time-input.validator.js
time before time validation fix
BOAT-426
> fix(web): time before time validation fix

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
> fix(web): fix/BOAT-622-623-624-various-copy-fixes

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/appeals/appeals.routes.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/utils/__tests__/sort-appeals.test.js
- appeals/api/src/server/utils/appeal-sorter.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/appeals-formatter.js
- Improves sorting of personal list API
- Improve the structure of test data
- Changes the appealShortRef function to allow any number of parts
> feat(appeals): improved sorting and seed data

- apps/e2e/cypress/support/cypressUtils.js
> test(e2e): fixed session time related issues

- apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/__snapshots__/publish-valid-reps.test.js.snap
- apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/publish-valid-reps.test.js
- apps/web/src/server/views/applications/representations/publish-valid-representations/index.njk
> refactor(applications/web): change CTA button text

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/views/app/components/file-uploader.component.njk
- appeals/web/src/server/views/appeals/documents/add-document-details.njk
fix document details page: add capitalization and legends
Add capitalization to Day Month Year
Add legends as seen in prototype
[Ticket](https://pins-ds.atlassian.net/jira/software/projects/BOAT/boards/207?selectedIssue=BOAT-630)
> fix(appeals/web): fix document details page

- apps/api/src/message-schemas/commands/register-representation.schema.json
- apps/api/src/message-schemas/events/interested-party.schema.json
Updating `register-representation` message schema to include fields captured by Applications Front Office service
[ASB-1922](https://pins-ds.atlassian.net/browse/ASB-1922)
[ASB-1922]: https://pins-ds.atlassian.net/browse/ASB-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update register-representation message schema

- apps/web/src/server/applications/applications.types.d.ts
- apps/web/src/server/applications/case/applications-case.router.js
- apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
- apps/web/src/server/applications/case/project-team/__tests__/applications-project-team.test.js
- apps/web/src/server/applications/case/project-team/applications-project-team.controller.js
- apps/web/src/server/applications/case/project-team/applications-project-team.router.js
- apps/web/src/server/applications/case/project-team/applications-project-team.service.js
- apps/web/src/server/applications/case/project-team/applications-project-team.validators.js
- apps/web/src/server/lib/nunjucks-filters/url.js
- apps/web/src/server/views/applications/case-project-team/project-team-list.njk
- apps/web/src/server/views/applications/case-project-team/project-team-search.njk
- apps/web/src/styles/4-generic/_generic.align-items.scss
- apps/web/src/styles/main.scss
- apps/web/testing/applications/factory/project-team.js
- apps/web/testing/applications/fixtures/project-team.js
> feat(web/applications): add project team list and search page (boas-975)

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
> feat(api): migrate automatic updates

- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.validator.js
- appeals/api/src/server/endpoints/constants.js
> fix(appeals/api): correct definition for outcome:dismissed

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/views/appeals/components/govuk-details.njk
- appeals/web/testing/app/fixtures/referencedata.js
Updates to not valid validation outcome notification banners on appellant case and lpaq pages to align with design
BOAT-439
> fix(web): appellant case and lpaq notification banners fix

- appeals/api/src/server/endpoints/addresses/addresses.controller.js
- appeals/api/src/server/endpoints/addresses/addresses.routes.js
- appeals/api/src/server/endpoints/audit-trails/audit-trails.controller.js
- appeals/api/src/server/middleware/async-handler.js
- All API controller methods async
- AsyncHandler suggestions
[BOAT-597](https://pins-ds.atlassian.net/browse/BOAT-597)
[BOAT-597]: https://pins-ds.atlassian.net/browse/BOAT-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): asynchandler errors

- apps/api/src/message-schemas/events/s51-advice.schema.json
> chore(api/applications): add case reference to schema

- apps/e2e/cypress/e2e/back-office-applications/unpublishDocuments.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/e2e/cypress/page_objects/folderDocumentsPage.js
- apps/e2e/cypress/page_objects/uploadFiles.js
> test(e2e): added negative scenarios

- apps/api/src/database/seed/data-test.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1999
As part of testing publishing a large number of relevant representation, the seed script is updated to 5000 reps with valid statues.
> feat(applications/api): updated relevant reps seeding

- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
Small fix, handles null agent in FO appeal submission
> fix(appeals/api): handle null agent in appeal submission

- apps/api/src/database/seed/seed-clear.js
Small fix to DB Seeding - includes handling code for recent CasePublishedState table
https://pins-ds.atlassian.net/browse/BOAS-1325
> fix(api/applications): fix db seed casepublishedstate (boas-1325)

- apps/e2e/cypress/e2e/back-office-applications/documentUpload.spec.js
- apps/e2e/cypress/fixtures/sample-error-file.html
- apps/e2e/cypress/support/cypressUtils.js
> test(e2e): added html file for error test case

- docs/azurite-blob-emulator-windows.md
- docs/azurite-blob-emulator.md
- docs/self-signed-ssl.md
> docs(appeals/web): add documentation for Azurite Blob Emulator on Windows

- appeals/api/src/server/endpoints/audit-trails/audit-trails.service.js
Doesn't fix bug as unable to reproduce consistently. Adding logs to suspected location of bug.
> fix(appeals/api): add logging to auditTrail to identify source of upload doc bug

- apps/api/src/message-schemas/events/interested-party.schema.json
Add `country` and `jobTitle` to `interested-party` schema
Rename `emailAddress` to `email`, and `telephone` to `phoneNumber`, to match naming used in Back office database
> chore(applications): update interested-party.schema.json

- apps/web/src/client/components/file-uploader/_server-actions.js
Strip out all HTML apart from iframe with src.
[BOAS-1085](https://pins-ds.atlassian.net/browse/BOAS-1085)
[BOAS-1085]: https://pins-ds.atlassian.net/browse/BOAS-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): strip out all HTML apart from iframe with src

- apps/api/src/server/applications/documents/documents.controller.js
- apps/api/src/server/applications/documents/documents.service.js
- apps/web/src/client/components/file-uploader/_client-actions.js
- apps/web/src/client/components/file-uploader/_html.js
- apps/web/src/client/components/file-uploader/_server-actions.js
- apps/web/src/server/app/components/file-uploader.component.js
Display informative errors for bad HTML files
[BOAS-1085](https://pins-ds.atlassian.net/browse/BOAS-1085)
[BOAS-1085]: https://pins-ds.atlassian.net/browse/BOAS-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): display informative errors for bad HTML files

- apps/web/src/client/components/file-uploader/_server-actions.js
Upload is failing for HTML files but debugging is difficult locally because we can't access blob storage. Improving logging to try to debug in dev.
> chore(web/applications): improve client side error logging for uploading

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.controller.js
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.middleware.js
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.routes.js
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.service.js
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.validator.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
Small improvements to appeal decision API
> fix(appeals/api): better handling of decision requests

- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/applications/case/__tests__/applications-case.test.js
- apps/web/src/server/applications/case/applications-case.controller.js
- apps/web/src/server/applications/case/applications-case.router.js
- apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
- apps/web/src/server/applications/case/project-team/applications-project-team.controller.js
- apps/web/src/server/applications/case/project-team/applications-project-team.service.js
- apps/web/src/server/views/applications/case-project-team/project-team-list.njk
- apps/web/src/server/views/applications/case/overview.njk
- apps/web/src/styles/7-components/_table.scss
> feat(web/applications): show team members in overview page (boas-977)

- apps/web/src/client/components/file-uploader/_client-actions.js
re-throw file submit errors after catching
> chore(web/applications): re-throw file submit errors after catching

- appeals/api/src/message-schemas/pins-root.schema.json
> feat(appeals/api): relaxing mandatory fields in schema

- apps/e2e/cypress/e2e/back-office-applications/addTeam.spec.js
- apps/e2e/cypress/page_objects/projectTeamPage.js
> test(e2e): added team member related scenarios

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.router.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk
- appeals/web/src/server/views/appeals/appeal/site-visit-booked.njk
[BOAT-538](https://pins-ds.atlassian.net/browse/BOAT-538)
[BOAT-538]: https://pins-ds.atlassian.net/browse/BOAT-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): feature/BOAT-538-site-visit-manage

- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/views/applications/case/overview.njk
Fixed "Update project information" link url - Case id was missing
> fix(applications/web): fixed url missing case ID (BOAS-1352)

- apps/functions/applications-migration/common/config.js
- apps/functions/applications-migration/common/synapse-db.js
- apps/functions/applications-migration/package.json
- apps/functions/applications-migration/service-user-migration/debug.js
- apps/functions/applications-migration/service-user-migration/function.json
- apps/functions/applications-migration/service-user-migration/index.js
- apps/functions/applications-migration/service-user-migration/src/service-user-migration.js
- package-lock.json
> feat(api): poc for querying service users directly from synapse

- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.validators.js
[BOAT-700](https://pins-ds.atlassian.net/browse/BOAT-700)
[BOAT-700]: https://pins-ds.atlassian.net/browse/BOAT-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): feature/BOAT-538-site-visit-manage-allow-empty-time-slot-update-for-unaccompanied-visit

- apps/api/package.json
- apps/api/setup-tests.js
- apps/api/src/server/app.js
- apps/api/src/server/config/config.js
- apps/api/src/server/config/schema.js
- package-lock.json
* chore(api/applications): install applicationinsights npm package
* chore(api/applications): add App Insights connection string to config
* feat(api/applications): initialise App Insights in back office API
[BOAS-481](https://pins-ds.atlassian.net/browse/BOAS-481)
[BOAS-481]: https://pins-ds.atlassian.net/browse/BOAS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set up Application Insights

- apps/functions/applications-migration/package.json
- azure-pipelines-build.yml
- package-lock.json
> fix(api): standardise identity version

- appeals/functions/document-processing/document-copy/config.js
- appeals/functions/document-processing/document-copy/function.json
- appeals/functions/document-processing/document-copy/index.js
- appeals/functions/document-processing/document-copy/todo.txt
- appeals/functions/document-processing/host.json
- appeals/functions/document-processing/local.settings.json
- appeals/functions/document-processing/malware-detection/config.js
- appeals/functions/document-processing/malware-detection/function.json
- appeals/functions/document-processing/malware-detection/index.js
- appeals/functions/document-processing/malware-detection/todo.txt
- appeals/functions/document-processing/package.json
- azure-pipelines-deploy-appeals.yml
- package-lock.json
Fixes incorrect infra ID when deploying doc processing function
> fix(appeals): rename func artifact to deploy

- azure-pipelines-build.yml
- package-lock.json
> fix(appeals): renamed user import

- appeals/api/src/database/migrations/20231128131711_optional_decision_letter_guid_in_inspector_decision/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.validator.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.controller.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.middleware.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.routes.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.service.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.validator.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/swagger.js
[BOAT-653](https://pins-ds.atlassian.net/browse/BOAT-653)
[BOAT-653]: https://pins-ds.atlassian.net/browse/BOAT-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): feature/BOAT-653 API - Publish appeal decision (Invalid)

- apps/api/src/server/applications/s51advice/s51-advice.controller.js
Remove nesting of S51 events inside array
[BOAS-1360](https://pins-ds.atlassian.net/browse/BOAS-1360)
[BOAS-1360]: https://pins-ds.atlassian.net/browse/BOAS-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api/applications): remove nesting of S51 events inside array

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/repositories/document.repository.js
- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/app/components/file-downloader.component.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/views/appeals/documents/document-upload.njk
- appeals/web/src/server/views/appeals/documents/manage-document.njk
add upload new version,
add change document details
add download by version
add new document fix (clicking add now adds a new document not a new version)
> feat(appeals): add manage documents

- apps/api/src/server/build-app.js
Add a health check endpoint to the API.
[BOAS-481](https://pins-ds.atlassian.net/browse/BOAS-481)
[BOAS-481]: https://pins-ds.atlassian.net/browse/BOAS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(api/applications): add a health check endpoint to the API

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/endpoints/documents/documents.service.js
- appeals/web/src/client/components/file-uploader/_html.js
- appeals/web/src/client/components/file-uploader/_server-actions.js
- appeals/web/src/server/app/components/file-uploader.component.js
> fix(appeals): handle duplicate document upload error

- apps/api/src/server/app.js
**Application Insights change:** Switch on auto collection of dependencies and enable W3C headers.
Different node apps have different instances of App Insights, so I'm hoping the W3C headers will allow correlation/tracing across service boundaries.
[BOAS-481](https://pins-ds.atlassian.net/browse/BOAS-481)
[BOAS-481]: https://pins-ds.atlassian.net/browse/BOAS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api/applications): auto collect dependencies and use W3C headers

- appeals/web/src/server/app/config/session.js
Re-enabled Redis sessions if in local config or production
> feat(appeals): redis session config

- apps/api/src/server/applications/project-team/project-team.controller.js
- apps/api/src/server/applications/project-team/project-team.routes.js
- apps/api/src/server/swagger-output.json
- apps/api/src/server/swagger-types.ts
- apps/api/src/server/swagger.js
> fix(api): return removed member on team member remove api (boas-1309)

- appeals/functions/document-processing/malware-detection/back-office-api-client.js
- appeals/functions/document-processing/malware-detection/index.js
- appeals/web/src/server/app/config/session.js
Comment out Redis session implementation and resset to in-memory...
More logging on AV scan function
> fix(appeals): remove redis, more logging on AV scan

- apps/web/src/server/lib/nunjucks-filters/format-name-org.js
- apps/web/src/server/lib/nunjucks-filters/index.js
- apps/web/src/server/views/applications/case-s51/s51-unpublish.njk
Render name and organisation under S51 enquirer.
[BOAS-1259](https://pins-ds.atlassian.net/browse/BOAS-1259)
[BOAS-1259]: https://pins-ds.atlassian.net/browse/BOAS-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web/applications): render name and organisation under S51 enquirer

- appeals/web/src/server/app/components/file-downloader.component.js
Fixes for download component
[BOAT-734](https://pins-ds.atlassian.net/browse/BOAT-734)
[BOAT-734]: https://pins-ds.atlassian.net/browse/BOAT-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): download a specific version of a file fix

- appeals/web/src/server/appeals/appeal-details/allocation-details/__tests__/__snapshots__/allocation-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.types.d.ts
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js
- appeals/web/src/server/lib/nunjucks-template-builders/page-component-rendering.js
- appeals/web/src/server/views/appeals/appeal/assign-user.njk
- appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk
- appeals/web/src/server/views/appeals/appeal/set-site-visit-type.njk
- appeals/web/src/server/views/appeals/components/page-component.njk
- appeals/web/src/server/views/appeals/components/status-tag.njk
- appeals/web/src/server/views/appeals/documents/add-document-details.njk
- appeals/web/src/server/views/appeals/documents/manage-document.njk
- appeals/web/src/server/views/appeals/documents/manage-folder.njk
- appeals/web/src/server/views/patterns/change-page.pattern.njk
- appeals/web/src/server/views/patterns/check-and-confirm-page.pattern.njk
- appeals/web/src/server/views/patterns/display-page.pattern.njk
- appeals/web/testing/app/fixtures/referencedata.js
document virus scan labels and ctas
BOAT-563
> feat(web): document virus scan labels and ctas

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/lib/display-page-formatter.js
virus scan labels and ctas - design review amends
BOAT-563
> feat(web): virus scan labels and ctas - design review amends

- apps/web/src/server/lib/nunjucks-filters/index.js
- apps/web/src/server/lib/nunjucks-filters/sanitize.js
- apps/web/src/server/views/applications/components/excerpt.component.njk
> feat(web/applications): add sanitize filter (boas-1244)

- apps/api/Dockerfile
Install OpenSSL in the Dockerfile.
> fix(api/applications): install OpenSSL in the Dockerfile

- appeals/web/environment/config.d.ts
- appeals/web/environment/config.js
- appeals/web/environment/schema.js
- appeals/web/src/server/server.js
App Insights on new AI BO appeals
> feat(appeals/web): app insights config

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js
- appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/views/appeals/documents/delete-document.njk
https://pins-ds.atlassian.net/browse/BOAT-548
> feat(web): feature/BOAT-548-document-removal-3

- apps/api/src/message-schemas/events/nsip-representation.schema.json
https://pins-ds.atlassian.net/browse/ASB-2137
- [] I have referenced the ticket number above
> docs(api): update representation schema

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
update case timetable schedule site visit action link copy
BOAT-638
> fix(web): update case timetable schedule site visit action link copy

- appeals/api/src/server/repositories/document-metadata.repository.js
- appeals/web/src/server/lib/display-page-formatter.js
> fix(appeals): add button should always add a new document

- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/repositories/integrations.repository.js
- appeals/functions/document-processing/document-move/blob.js
Copies documents imported by integrations to the BO blob storage.
> feat(appeals): integration of FO documents

- appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js
- appeals/api/src/server/repositories/integrations.repository.js
> fix(appeals/api): import lpaq docs DB and validation fixes

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add visuallyHiddenText to lpaq and appellant case summary action links
BOAT-526
> fix(web): add visuallyHiddenText to lpaq and appellant case summary action links

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/accessibility.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/nunjucks-filters/index.js
- appeals/web/src/server/views/appeals/components/appeals-table.njk
accessibility improvements to appeal ID number reading
BOAT-527
> fix(web): accessibility improvements to appeal ID number reading

- appeals/api/src/database/migrations/20231212091313_default_status_assign_case_officer/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-test.js
Improvements to seed data, so the samples match process and state machine rules
> feat(appeals/api): improving seed data to match process and states

- apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
- apps/api/src/server/applications/application/representations/publish/publish.service.js
- apps/api/src/server/applications/application/representations/publish/representation.js
- apps/api/src/server/repositories/representation.repository.js
- apps/web/src/server/applications/case/representations/relevant-representation.types.d.ts
ASB-2136
When publishing Representations to the `nsip-representation` topic, also publish the contacts/service-users for that Representation to the `service-user` topic with `entityType = RepresentationContact` 
Requires #1789 to be merged first as this branch is based off that
> feat(applications/api): publish rep service user

- appeals/api/src/server/endpoints/integrations/integrations.service.js
Small fix - generate new GUIDs if imported documents have existing GUIDs.
> fix(appeals/api): import of case data with existing doc guids

- appeals/api/src/server/build-app.js
Adds an `OK` response on `/` and `/health` to reduce errors in app insights
> feat(appeals/api): healthcheck on / and /health

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
https://pins-ds.atlassian.net/browse/BOAT-770
> fix(web): bugfix/BOAT-770-fix-web-jest-test

- apps/api/src/server/utils/logger.js
* chore(api/applications): get operation ID directly from AI context
[BOAS-1184](https://pins-ds.atlassian.net/browse/BOAS-1184)
[BOAS-1184]: https://pins-ds.atlassian.net/browse/BOAS-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(api/applications): get operation ID directly from AI context

- apps/api/src/message-schemas/commands/register-representation.d.ts
- apps/api/src/message-schemas/commands/register-representation.schema.json
- apps/api/src/server/applications/application/representations/representation.mapper.js
- apps/functions/register-representation/.funcignore
- apps/functions/register-representation/host.json
- apps/functions/register-representation/jest.config.js
- apps/functions/register-representation/package.json
- apps/functions/register-representation/register-representation-command/__tests__/register-representation-command.test.js
- apps/functions/register-representation/register-representation-command/back-office-api-client.js
- apps/functions/register-representation/register-representation-command/config.js
- apps/functions/register-representation/register-representation-command/function.json
- apps/functions/register-representation/register-representation-command/index.js
- azure-pipelines-build.yml
- azure-pipelines-deploy.yml
- package-lock.json
- packages/applications/types/representation.d.ts
ASB-2069
Inclues:
- New function to consume events on the register-representation topic. Takes the message, which contains information about a Representation submitted by the Applications Front Office, and adds it to the Back Office database.
- Minor amendment to the POST /representations endpoint to allowing passing the `type` property
- [] I have made corresponding changes to the documentation
> feat(functions): register-representation function

- apps/functions/applications-migration/nsip-project-migration/index.js
> fix(functions): copy-paste import naming error

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
[BOAT-722](https://pins-ds.atlassian.net/browse/BOAT-722)
[BOAT-722]: https://pins-ds.atlassian.net/browse/BOAT-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): fix order of document versions in version list

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
> fix(appeals/web): reversed order

- apps/functions/applications-migration/common/validation.js
- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
- apps/functions/applications-migration/package.json
- apps/functions/applications-migration/service-user-migration/src/service-user-migration.js
- package-lock.json
Validate entities from ODW curated layer, and print out any errors.
N/A
> feat(functions): validate curated odw entities

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
update appellant case page labels for appellant name and applicant name
BOAT-721
> fix(web): update appellant case page labels for appellant name and applicant name

- apps/api/src/database/prisma.truncate.js
- apps/api/src/database/seed/data-static.js
- apps/api/src/database/seed/data-test.js
- apps/api/src/database/seed/seed-development.js
- apps/api/src/database/seed/seed-production.js
Non breaking changes to fix red-lining issues in the seeding scripts, such as incorrect obj typedef definitions
https://pins-ds.atlassian.net/browse/BOAS-1393
> fix(api/applications): fix seeding typing issues (boas-1393)

- appeals/web/src/server/appeals/national-list/national-list.controller.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.controller.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/pagination.mapper.js
- appeals/web/src/server/lib/pagination-utilities.js
- appeals/web/src/server/views/patterns/display-page.pattern.njk
- appeals/web/testing/app/fixtures/referencedata.js
add pagination for personal list (also includes refactoring of national list to make pagination reusable)
BOAT-782
> fix/BOAT-782 - add pagination for personal list

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/appeal-sorter.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
fix personal list pagination issues due to complete cases being counted but not displayed
BOAT-809
> fix(web): fix personal list pagination issues due to complete cases being counted but not displayed

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/repositories/folder.repository.js
- appeals/web/src/server/app/components/file-uploader.component.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/issue-decision/issue-decision.service.js
- appeals/web/src/server/appeals/issue-decision/issue-decision.types.d.ts
- appeals/web/src/server/appeals/issue-decision/issue-decision.validators.js
- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/validators/date-input.validator.js
- appeals/web/src/server/views/appeals/appeal/issue-decision.njk
- appeals/web/src/server/views/appeals/documents/decision-letter-upload.njk
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-209](https://pins-ds.atlassian.net/browse/BOAT-209)
[BOAT-209]: https://pins-ds.atlassian.net/browse/BOAT-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): feature/BOAT-209 Publish appeal decision (Allowed / Dismissed / Split-decision) 

- apps/api/src/server/utils/__tests__/published-case-fields-changed.test.js
- apps/api/src/server/utils/published-case-fields-changed.js
Make sure the Unpublished message appears when specified application, applicant and key date fields that should trigger republishing are updated.
https://pins-ds.atlassian.net/browse/BOAS-1384
> fix(api/applications): fix republish message appearing (boas 1384)

- apps/api/src/database/migrations/20240105141100_seed_case_tables/migration.sql
- apps/api/src/server/migration/migrators/nsip-project-migrator.js
- apps/api/src/server/migration/migrators/sql-tools.js
- apps/api/src/server/migration/migrators/utils.js
- apps/functions/applications-migration/README.md
- apps/functions/applications-migration/nsip-project-migration/index.js
- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
> feat(api): migration for nsip project

- apps/functions/applications-migration/nsip-project-migration/src/back-office-api-client.js
- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
> fix(api): fix import

- apps/api/src/database/migrations/20240105154333_case_description_length/migration.sql
- apps/api/src/database/schema.prisma
* chore(api/applications): change Case description max length to 2000
[BOAS-1411](https://pins-ds.atlassian.net/browse/BOAS-1411)
[BOAS-1411]: https://pins-ds.atlassian.net/browse/BOAS-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(api/applications): change Case description max length to 2000

- apps/functions/applications-migration/common/synapse-db.js
- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
> fix(api): fix expiring tokens and remove null values

- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
> fix(api): add logging

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- [] I have made corresponding changes to the documentation
> Feature/content changes - case details

- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
> fix(api): fix reference from projects to project

- azure-pipelines-package-function.yml
> ci: function build only copy if node_modules exists

- apps/web/src/client/components/file-uploader/_client-actions.js
Add a hash of the file name to the fileRowId to make it unique when a copy of a file is uploaded simultaneously with the original file.
https://pins-ds.atlassian.net/browse/BOAS-1382
> fix(web/applications): fix multiple file upload (BOAS-1382)

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/session-utilities.js
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-819](https://pins-ds.atlassian.net/browse/BOAT-819)
[BOAT-819]: https://pins-ds.atlassian.net/browse/BOAT-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): feature/BOAT-819 Build entry points for issue decision

- apps/web/src/client/components/file-uploader/_client-actions.js
The previous PR [fix multiple file upload](https://github.com/Planning-Inspectorate/back-office/pull/1931) used crypto.createHash to create a hash of the file name.  This was then added to the file row id to make sure it was unique.  
This PR replaces crypto.createHash with crypto.digest and bespoke code because createHash can only run in a node environment.
This has been tested to make sure the file row id is generated correctly within the browser using the web inspector debugger.
https://pins-ds.atlassian.net/browse/BOAS-1382
> fix(web/applications): crypto create hash fails in browser (BOAS-1382)

- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js
- apps/web/src/server/views/applications/case-timetable/timetable-success-banner.njk
> fix(web): correct copy on timetable success page and fix tests

- packages/express/middleware/async-handler.js
Change default error handler to catch unhandled exceptions from both asynchronous and synchronous route handlers
- Fix the type definition in the previous [PR](https://github.com/Planning-Inspectorate/back-office/pull/1955) with this amendment to the new async-handler to fix the pipeline
This has been tested manually to make sure the routes functionality has not regressed.
https://pins-ds.atlassian.net/browse/BOAS-1255
> fix(applications): fix type definition to fix pipeline (BOAS-1255)

- appeals/api/src/database/seed/data-test.js
Removes FPA appeals from seed data
> feat(appeals/api): modifies the test seed to include only HAS appeals

- appeals/api/src/database/seed/data-static.js
Restores the original HAS appeal name to 'Householder'
> fix(appeals/api): reset the HAS appeal name to Householder

- packages/express/middleware/async-handler.js
- packages/express/types/express.d.ts
Fix the types for the shared async handler
> fix(tooling): specific types for async handler

- apps/api/src/server/applications/application/documents/__tests__/document-payload.test.js
- apps/api/src/server/applications/application/documents/__tests__/mark-as-published.test.js
- apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js
- apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js
- apps/api/src/server/applications/application/documents/document.js
- apps/api/src/server/applications/application/project-updates/project-updates.mapper.js
- apps/api/src/server/applications/documents/documents.service.js
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
- apps/api/src/server/applications/subscriptions/__tests__/subscriptions.test.js
- apps/api/src/server/applications/subscriptions/subscriptions.js
- apps/api/src/server/infrastructure/payload-builders/applicant.js
- apps/api/src/server/infrastructure/payload-builders/nsip-project.js
- apps/api/src/server/migration/migrators/nsip-project-migrator.js
- apps/api/src/server/migration/migrators/nsip-project-update-migrator.js
- apps/api/src/server/migration/migrators/nsip-subscription-migrator.js
- apps/api/src/server/migration/migrators/utils.js
- apps/functions/document-check/check-document/event-client.js
- apps/functions/notify-subscribers/notify-subscribers/index.js
- apps/functions/notify-subscribers/notify-subscribers/src/notify-subscribers.js
- apps/functions/register-representation/register-representation-command/index.js
Update to use Typescript types generated in the data-model repo.
* refactor(api/applications): use generated types from pins-data-model
* test(api/applications): fix tests broken by type changes
> Update to use Typescript types generated in the data-model repo

- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk
- Added hint text to description input
- Updated the affected web unit tests
This has been tested manually to make sure the hint appears as expected.
https://pins-ds.atlassian.net/browse/BOAS-1350
> feat(applications/web): Description hint text on examination timetable (BOAS-1350)

- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/assign-user.test.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.controller.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.router.js
- appeals/web/src/server/views/appeals/appeal/assign-user.njk
- appeals/web/src/server/views/appeals/appeal/confirm-assign-unassign-user.njk
remove unassign case officer
BOAT-702
> feat(web): remove unassign case officer

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/__tests__/sort-appeals.test.js
- appeals/api/src/server/utils/appeal-sorter.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- packages/appeals/types/appeal.d.ts
[BOAT-783](https://pins-ds.atlassian.net/browse/BOAT-783)
[BOAT-783]: https://pins-ds.atlassian.net/browse/BOAT-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): feature/BOAT-783 Action required CTAs incorrect on personal list

- apps/api/src/server/utils/logger.js
When logging an error object, ensure it is serialised correctly before passing to Pino, whilst retaining the decorated properties (operationId, traceId)
> fix(api/applications): ensure error message and stack are logged

- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- packages/appeals/types/appeal.d.ts
[BOAT-783](https://pins-ds.atlassian.net/browse/BOAT-783)
[BOAT-783]: https://pins-ds.atlassian.net/browse/BOAT-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): feature/BOAT-783 Action required CTAs incorrect on personal list swagger

- apps/functions/applications-migration/service-user-migration/src/service-user-migration.js
Fix assignment of Synapse query results to correct variable
> fix(functions): synapse query assignment

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.types.d.ts
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.service.js
- appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/lib/mappers/validation-outcome-reasons.mapper.js
- appeals/web/src/server/lib/ts-utilities.js
fix issues with document and folder typescript definitions
BOAT-835
> fix(appeals): fix issues with document and folder typescript definitions

- apps/functions/applications-migration/common/utils.js
- apps/functions/applications-migration/nsip-project-migration/src/nsip-project-migration.js
- apps/functions/applications-migration/service-user-migration/src/service-user-migration.js
- Move `removeNullValues` function to util file
- Use util in service-user migrator function to ensure payload matches schema (null values omitted)
> fix(functions): remove null values from service-user payload

- apps/api/package.json
- apps/functions/applications-migration/package.json
- package-lock.json
Pull in latest changes to pins-data-model
> fix(functions): upgrade pins-data-model version

- apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
- apps/e2e/cypress/support/utils/createS51Advice.js
> test(e2e): fixed S51 test failures

- apps/api/src/database/migrations/20240117104411_rename_column_suffix_from_developer_to_applicant/migration.sql
- apps/api/src/database/schema.prisma
- apps/api/src/server/applications/key-dates/key-dates.utils.js
- apps/api/src/server/swagger-output.json
- apps/api/src/server/swagger-types.ts
- apps/api/src/server/swagger.js
- apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
- apps/web/src/server/lib/nunjucks-filters/key-dates-property.js
- apps/web/testing/applications/fixtures/key-dates.js
- Create migration to rename column in ApplicationDetails table
- Replace each occurrence of notificationDateForEventsDeveloper with notificationDateForEventsApplicant
- Fix affected unit tests
This has been tested manually for regression.
https://pins-ds.atlassian.net/browse/BOAS-1448
> feat(applications): rename field notificationDateForEventsDeveloper (BOAS-1448)

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.controller.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.controller.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/appeals/personal-list/personal-list.service.js
- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/pagination.mapper.js
- appeals/web/src/server/lib/nunjucks-filters/status-tag.js
- appeals/web/src/server/lib/string-utilities.js
- appeals/web/testing/app/fixtures/referencedata.js
- packages/appeals/types/appeal.d.ts
> feat(web): feature/BOAT-591-personal-list-filters-1

- apps/api/src/server/migration/migrators/service-user-migrator.js
- apps/functions/applications-migration/common/back-office-api-client.js
- apps/functions/applications-migration/service-user-migration/debug.js
- apps/functions/applications-migration/service-user-migration/src/service-user-migration.js
- Fix logging when running via debug.js
- Incorporate missed suggestion from PR feedback
- Fix removeNullValues being called on array not each object
> fix(functions): fix logging and null value removal

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js
- appeals/web/src/server/lib/nunjucks-template-builders/page-component-rendering.js
- appeals/web/src/server/views/appeals/appeal/assign-user.njk
- appeals/web/src/server/views/appeals/documents/add-document-details.njk
- appeals/web/src/server/views/appeals/documents/delete-document.njk
- appeals/web/src/server/views/appeals/documents/manage-document.njk
- appeals/web/src/server/views/appeals/documents/manage-folder.njk
- appeals/web/src/server/views/patterns/display-page.pattern.njk
refactor to remove page component groups in favour of just page components, which simplifies the supporting code, as well as making the system easier to understand
BOAT-824
> refactor(web): refactor to remove page component groups

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.router.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.service.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.types.d.ts
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/appeals/change-page/change-page.controller.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/views/appeals/confirmation.njk
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-654](https://pins-ds.atlassian.net/browse/BOAT-654)
[BOAT-654]: https://pins-ds.atlassian.net/browse/BOAT-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/web): feature/BOAT 654 changing appeal type by resubmission

- appeals/api/src/database/migrations/20240123121654_service_users_refactor/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/database/seed/seed-clear.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/repositories/integrations.repository.js
- appeals/api/src/server/tests/appeals/expectation.js
- appeals/api/src/server/tests/appeals/mocks.js
Service users table refactoring
Removed appellant and agent tables. Appeals linked to service users, which may not have an email address.
> refactor(api): service users

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add case contacts accordion
BOAT-694
> feat(appeals): case contacts accordion

- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js
- apps/web/src/server/applications/case/project-updates/project-updates.controller.js
- Default sortBy to "-publishDate" to force descending date-published order
- Updated the web unit tests to match
This has also been tested manually
https://pins-ds.atlassian.net/browse/BOAS-1252
> fix(applications/web): fix descending date published order (BOAS-1252)

- appeals/web/.env.test
- appeals/web/environment/config.d.ts
- appeals/web/environment/config.js
- appeals/web/environment/schema.js
- appeals/web/src/server/app/auth/auth.controller.js
- appeals/web/src/server/app/auth/auth.guards.js
- appeals/web/src/server/app/auth/auth.service.js
- appeals/web/src/server/app/config/session.js
- appeals/web/src/server/lib/active-directory-token.js
- appeals/web/src/server/lib/msal.js
- appeals/web/src/server/lib/redis.js
Implementation of `redis sessions`,  ported from the [work](https://github.com/Planning-Inspectorate/back-office/pull/2008) of @HadrianHughesKC on applications.
> feat(appeals/web): redis implementation

- apps/web/src/server/views/applications/case-timetable/timetable-success-banner.njk
Replace created with amended in the success banner
https://pins-ds.atlassian.net/browse/BOAS-1327
> fix(applications/web): amend created as added (BOAS-1327)

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/tests/appeals/expectation.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Fixes the current error rendering the appellant case, result of service user restructuring.
> fix(appeals/web): fixes appellant case rendering

- apps/scripts/regenerate-api-keys.js
- azure-pipelines-regenerate-api-key.yml
- package.json
Create pipeline and node script to regenerate api key in key vault
> feat(tooling): add pipeline to regenerate api key

- appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.middleware.js
[BOAT-332](https://pins-ds.atlassian.net/browse/BOAT-332)
[BOAT-332]: https://pins-ds.atlassian.net/browse/BOAT-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/web): feature/BOAT 332 changing appeal type by resubmission status validation

- appeals/web/src/server/app/auth/__tests__/auth.test.js
- appeals/web/src/server/app/auth/auth.controller.js
Ported from https://github.com/Planning-Inspectorate/back-office/pull/2027/commits/954c5bddd5313aa80a39596e17bc375b1b031ead
> fix(appeals/web): fixes logout from session

- azure-pipelines-regenerate-api-key.yml
> fix(tooling): fix missing sections of pipeline cofig

- apps/web/src/server/app/auth/__tests__/auth.test.js
- apps/web/src/server/app/auth/auth.controller.js
* fix(web/applications): fix and reenable test for sign out
[BOAS-1468](https://pins-ds.atlassian.net/browse/BOAS-1468)
[BOAS-1468]: https://pins-ds.atlassian.net/browse/BOAS-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> pfix(web/applications): fix and reenable test for sign out

- apps/api/src/server/applications/s51advice/s51-advice.controller.js
- apps/api/src/server/applications/s51advice/s51-advice.service.js
* fix(api/applications): unpublish attachments when unpublishing S51
[BOAS-1469](https://pins-ds.atlassian.net/browse/BOAS-1469)
[BOAS-1469]: https://pins-ds.atlassian.net/browse/BOAS-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api/applications): unpublish attachments when unpublishing S51

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.middleware.js
- appeals/api/src/server/endpoints/appeals/appeals.routes.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal.repository.js
[BOAT-706](https://pins-ds.atlassian.net/browse/BOAT-706)
[BOAT-706]: https://pins-ds.atlassian.net/browse/BOAT-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): feature/BOAT-706 API - National List Filters

- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/__tests__/sort-appeals.test.js
- appeals/api/src/server/utils/appeal-sorter.js
- packages/platform/http/hooks.js
[BOAT-844](https://pins-ds.atlassian.net/browse/BOAT-844)
[BOAT-844]: https://pins-ds.atlassian.net/browse/BOAT-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): BOAT-844 viewing personal list - shows page not found error

- appeals/api/src/server/repositories/appeal.repository.js
[BOAT-844](https://pins-ds.atlassian.net/browse/BOAT-844)
[BOAT-844]: https://pins-ds.atlassian.net/browse/BOAT-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): BOAT-844 viewing personal list - shows page not found error

- apps/api/src/server/build-app.js
- azure-pipelines-regenerate-api-key.yml
- package-lock.json
- package.json
- packages/scripts/jsconfig.json
- packages/scripts/package.json
- packages/scripts/run/regenerate-api-keys-entry.js
- packages/scripts/src/regenerate-api-keys.js
> fix(tooling): correct schedule property

- azure-pipelines-regenerate-api-key.yml
> fix(tooling): add env param to apikey gen pipeline

- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.controller.js
update national list search hint text to ensure spaces are included in postcode
BOAT-688
> fix(web): update national list search hint text to ensure spaces are included in postcode

- apps/e2e/cypress/e2e/back-office-applications/search.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/uploadFiles.js
- apps/e2e/cypress/support/utils/createProjectInformation.js
- apps/e2e/cypress/support/utils/createS51Advice.js
> test(e2e): removed faker data for project description

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-858](https://pins-ds.atlassian.net/browse/BOAT-858)
[BOAT-858]: https://pins-ds.atlassian.net/browse/BOAT-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): BOAT-858 personal list filter dropdown ordering

- apps/api/src/server/applications/application/application.validators.js
- apps/api/src/server/applications/application/representations/__tests__/create-representation.test.js
- apps/functions/applications-command-handlers/register-representation-command/__tests__/register-representation-command.test.js
- apps/functions/applications-command-handlers/register-representation-command/index.js
Fixes for bugs found during integration testing of representations
1) It is possible for Front Office to send an empty surname, this fails due to surname being mandatory in the API.  This validation has been relaxed to allow an empty surname.
2) contactMethod was not being picked up and stored in the BO subscriber function.
https://pins-ds.atlassian.net/browse/ASB-2242
https://pins-ds.atlassian.net/browse/ASB-2243
> fix(api): fix bugs following reps integration testing

- apps/api/src/server/repositories/document-metadata.repository.js
Return Document with DocumentVersion from `publishMany` database method.
[BOAS-1489](https://pins-ds.atlassian.net/browse/BOAS-1489)
[BOAS-1489]: https://pins-ds.atlassian.net/browse/BOAS-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api/applications): return Document with DocumentVersion on publish

- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.controller.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.types.d.ts
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.types.d.ts
- appeals/web/src/server/views/appeals/documents/decision-letter-upload.njk
add mappers to decouple web app from API data structures
BOAT-696
> refactor(web): add mappers to decouple web app from API data structures

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/repositories/appeal.repository.js
[BOAT-866](https://pins-ds.atlassian.net/browse/BOAT-866)
[BOAT-866]: https://pins-ds.atlassian.net/browse/BOAT-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): BOAT-866 national list filter statuses

- apps/api/src/server/middleware/authorise-request.js
> fix(api): return empty object if key with status 'oldest' not found

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.middleware.js
- appeals/api/src/server/repositories/appeal-type.repository.js
Refining appeal types for transfers
> feat(appeals/api): introduce an appeal type repository for transfers

- appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/change-page/change-page.controller.js
- appeals/web/src/server/appeals/change-page/change-page.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
refactor sequential async calls to run in parallel where possible
BOAT-532
> refactor(web): refactor sequential async calls to run in parallel where possible

- azure-pipelines-build.yml
- azure-pipelines-package-function-merge.yml
- azure-pipelines-package-function.yml
> ci: merge function builds

- apps/e2e/cypress/support/utils/createS51Advice.js
> test(e2e): s51 changes

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/format-linked-appeals.js
[BOAT-662](https://pins-ds.atlassian.net/browse/BOAT-662)
[BOAT-662]: https://pins-ds.atlassian.net/browse/BOAT-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): BOAT-662 Managing Linked Appeal appealType in get appeals appealId endpoint

- appeals/api/.env.test
- appeals/api/src/server/config/config.js
Adjust the config name for SRV_HORIZON_URL / fixes dev
> fix(appeals/api): corrects the name of the horizon setting

- apps/e2e/cypress/support/utils/options.js
> test(e2e): new sector added

- apps/e2e/cypress/support/utils/options.js
> test(e2e): updated scripts to make it pass

- apps/api/src/server/utils/mapping/map-key-dates.js
The key date mapping has been updated so that the cleared dates are updated with null.
I tested the above manually to make sure the dates can be added and cleared correctly as expected.
https://pins-ds.atlassian.net/browse/BOAS-1508
> fix(applications/api): allow clearing dates and save change (BOAS-1508)

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/mappers/documents.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add draft documents notification banner
BOAT-761
> add draft documents notification banner

- apps/README.md
C4 Diagrams describing context at different levels of detail for Back Office Applications.
> feat(api): mermaid c4 docs

- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/project-updates-views.d.ts
- apps/web/src/server/applications/case/project-updates/project-updates.controller.js
- apps/web/src/server/applications/case/project-updates/project-updates.view-model.js
- apps/web/src/server/views/applications/case/project-updates/project-updates-details.njk
- Amended project updates view to have a customizable warning text if required
- Updated web tests
Tested the above manually.
https://pins-ds.atlassian.net/browse/BOAS-1492
[BOAS-1452]: https://pins-ds.atlassian.net/browse/BOAS-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(applications/web): amend project updates warning text (BOAS-1492)

- apps/api/src/server/applications/application/representations/redact/redact.controller.js
Bug fix to ensure representation Id is converted to a number during patch /representation/redact.
https://pins-ds.atlassian.net/browse/ASB-2258
> fix(api): ensure repId is converted to a number

- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/views/applications/case/components/case-info-table-preview.component.njk
- Amended the "Preview and Publish project page" to display the case stage correctly
- Updated the snapshots in the web unit tests 
I tested the above manually to make sure the case stage is displayed as expected.
https://pins-ds.atlassian.net/browse/BOAS-1504
> fix(applications/web): changing the case stage does not filter through (BOAS-1504)

- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/endpoints/transferred-appeals/__tests__/transferred-appeal.test.js
- appeals/api/src/server/endpoints/transferred-appeals/transferred-appeal.controller.js
- appeals/api/src/server/endpoints/transferred-appeals/transferred-appeal.routes.js
- appeals/api/src/server/endpoints/transferred-appeals/transferred-appeal.services.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
https://pins-ds.atlassian.net/browse/BOAT-881
> feat(appeals/api): add transferred appeal api

- apps/e2e/cypress/support/utils/utils.js
> test(e2e): updated with value

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.router.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.service.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.validators.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/session-utilities.js
- appeals/web/src/server/views/appeals/components/status-tag.njk
- appeals/web/src/server/views/patterns/check-and-confirm-page.pattern.njk
changing appeal type by transfer
BOAT-660
> feat(appeals): changing appeal type by transfer

- apps/api/src/server/infrastructure/event-client.js
- apps/api/src/server/migration/migrators/nsip-project-update-migrator.js
- apps/api/src/server/migration/migrators/s51-advice-migrator.js
- apps/api/src/server/migration/migrators/service-user-migrator.js
When migrating S51 Advice and Service User entities, publish the migrated data to the Service Bus
> feat(functions): publish s51 and service user migration events

- appeals/web/.env.example
- apps/web/.env.example
- packages/event-client/src/service-bus-event-client.js
> feat(api): add retry options to service bus event (boas-1473)

- apps/e2e/cypress/e2e/back-office-applications/addRepresentation.spec.js
- apps/e2e/cypress/page_objects/representationPage.js
- apps/e2e/cypress/support/utils/createProjectInformation.js
- apps/e2e/cypress/support/utils/createTimetableItemInfo.js
> test(e2e): added representation scenarios

- apps/e2e/cypress/support/utils/createS51Advice.js
> test(e2e): changed dynamic test data to static data

- appeals/api/src/database/seed/data-test.js
https://pins-ds.atlassian.net/browse/BOAT-915
> fix(appeals/api): fix caseReference so as not to use slash

- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.controller.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
Adds audit trails for incomplete appellant case and lpaq validation.
Fix audit trails for appeal transfers.
> feat(appeals/api): add/fix audit trails

- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/views/appeals/confirmation.njk
- appeals/web/src/server/views/patterns/display-page.pattern.njk
refactor confirmation pages to use PageComponents
BOAT-849
> refactor confirmation pages to use PageComponents

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
add overdue status for appellant case
BOAT-868
> feat(web): add overdue status for appellant case

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
> feat(web): feature/BOAT-636-assign-co-from-nl

- appeals/api/src/server/endpoints/business-days/__tests__/business-days.test.js
- appeals/api/src/server/utils/business-days.js
Fixes business dates calculations.
[BOAT-921](https://pins-ds.atlassian.net/browse/BOAT-921)
[BOAT-921]: https://pins-ds.atlassian.net/browse/BOAT-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): calculation of business dates

- apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/casePage.js
- apps/e2e/cypress/page_objects/createCaseSections/sector.js
- apps/e2e/cypress/support/utils/utils.js
> test(e2e): added sector as training scenarios

- appeals/web/src/server/appeals/appeals.copy.js
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.mapper.js
- appeals/web/src/server/views/app/dashboard.njk
> feat(appeals/web): rename national list to `all cases`

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
> fix(web): bugfix/BOAT-636-style-fix

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/swagger.js
- appeals/api/src/server/tests/appeals/mocks.js
- appeals/api/src/server/tests/linked-appeals/mocks.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.router.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.service.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/appeals-formatter.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
[BOAT-662](https://pins-ds.atlassian.net/browse/BOAT-662)
[BOAT-662]: https://pins-ds.atlassian.net/browse/BOAT-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/web): managing linked appeal linkedAppealStatus

- apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
- Amended the examination timetable service
- Amended unit tests to match the changes.
- Manually tested publishing the exam timetable.
https://pins-ds.atlassian.net/browse/BOAS-1528
> fix(applications/api): send text for all items other than Deadline Items (BOAS-1528)

- appeals/web/src/server/lib/dates.js
> fix(web): bugfix/BOAT-942-fix-date-to-locale

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/display-page-formatter.js
date fix for appellant case overdue status
BOAT-868
> feat(web): date fix for appellant case overdue status

- apps/web/src/server/applications/case/project-team/application-project-team.azure-service.js
- Fixed retrieving users from azure when auth has not been disabled.
- Tested locally with dummy user data.
- Will test on DEV when azure user data is used.
https://pins-ds.atlassian.net/browse/BOAS-1434
> feat(applications): fix retrieving users from azure (BOAS-1434)

- apps/e2e/cypress/page_objects/uploadFiles.js
> test(e2e): increased wait time

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/api/src/server/tests/appeals/mocks.js
- appeals/api/src/server/utils/format-linked-appeals.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.router.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
[BOAT-662](https://pins-ds.atlassian.net/browse/BOAT-662)
[BOAT-662]: https://pins-ds.atlassian.net/browse/BOAT-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): managing linked appeal relationshipid

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
[BOAT-842](https://pins-ds.atlassian.net/browse/BOAT-842)
[BOAT-842]: https://pins-ds.atlassian.net/browse/BOAT-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): BOAT-842  "NO"is highlighted by default when first landing on "Should the appellant be asked to resubmit this appeal?" page

- apps/api/src/server/config/config.js
- apps/api/src/server/config/schema.js
- Removed unused msal variable from api config.
- Unit tests have been rerun to prove no regression
https://pins-ds.atlassian.net/browse/BOAS-1180
> chore(applications/api): remove unused msal environment variable (BOAS-1180)

- appeals/api/src/server/endpoints/appellants/appellants.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
[BOAT-601](https://pins-ds.atlassian.net/browse/BOAT-601)
[BOAT-601]: https://pins-ds.atlassian.net/browse/BOAT-601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/api): BOAT-601  async api controller methods

- azure-pipelines-db-seed.yml
- azure-pipelines-deploy.yml
- azure-pipelines-release.yml
Update to match new secret name for db connection string
> fix(api/applications): update secret name for db connection string

- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
Disable the test usage of govnotify (appellant case). The template was changed leading to errors in the appellant case validation. The code has been commented out temporarily.
> fix(appeals/api): disable govnotify

- appeals/api/src/server/endpoints/appeal-allocation/appeal-allocation-controller.js
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellants/appellants.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/middleware/version-routes.js
Codescanning alert fixes:
- https://github.com/Planning-Inspectorate/back-office/security/code-scanning/1
- https://github.com/Planning-Inspectorate/back-office/security/code-scanning/31
- https://github.com/Planning-Inspectorate/back-office/security/code-scanning/32
- https://github.com/Planning-Inspectorate/back-office/security/code-scanning/33
- https://github.com/Planning-Inspectorate/back-office/security/code-scanning/34
Additional TO DO:
- https://pins-ds.atlassian.net/browse/BOAT-995
- https://pins-ds.atlassian.net/browse/BOAT-996
- https://pins-ds.atlassian.net/browse/BOAT-997
- https://pins-ds.atlassian.net/browse/BOAT-998
- https://pins-ds.atlassian.net/browse/BOAT-999
[BOAT-898](https://pins-ds.atlassian.net/browse/BOAT-898)
[BOAT-898]: …
> fix(appeals/api): security alerts 1

- apps/api/src/database/seed/data-static.js
- apps/api/src/database/seed/seed-clear.js
- fixed seed script creates multiple BC01 cases with same reference
- also fixed seed script fail if has ProjectTeam records
https://pins-ds.atlassian.net/browse/BOAS-1569
> fix(api/applications): seed script duplicate references (boas-1569)

- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/dates.js
[BOAT-981](https://pins-ds.atlassian.net/browse/BOAT-981)
[BOAT-981]: https://pins-ds.atlassian.net/browse/BOAT-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): BOAT-981 review and refactor date logic and related utility functions to use date-fns package

- apps/e2e/cypress/e2e/back-office-applications/documentDownload.spec.js
- apps/e2e/cypress/page_objects/uploadFiles.js
> test(e2e): changed download document code

- apps/api/src/database/migrations/20240215140602_create_foreign_key_on_project_team_for_case/migration.sql
- apps/api/src/database/schema.prisma
- Temporarily remove relation between case and project team tables
- Tested on my local machine
INSTRUCTIONS
- Run db:seed after deployment to test
https://pins-ds.atlassian.net/browse/BOAS-1576
> fix(applications/api): deploy to test fails prisma issue project team (BOAS-1576)

- apps/api/src/database/migrations/20240221133814_recreate_case_and_project_team_relationship/migration.sql
- apps/api/src/database/schema.prisma
- Reapply relationship between case and project team
- Tested on my local machine
https://pins-ds.atlassian.net/browse/BOAS-1576
> fix(applications/api): reapply case and project team relationship (BOAS-1576)

- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
[BOAT-529](https://pins-ds.atlassian.net/browse/BOAT-529)
[BOAT-529]: https://pins-ds.atlassian.net/browse/BOAT-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/web): BOAT-529 Start Journey Navigation - No Assigned Cases

- apps/web/src/server/app/app.router.js
- apps/web/src/server/app/components/file-uploader.component.js
This fix catches the error that caused the app crash during pen testing
> fix(web): catch error if upload doc call returns a bad request

- .vscode/settings.json
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-721
> fix(appeals/web): fix duplication of names

- appeals/api/setup-tests.js
- appeals/api/src/database/migrations/20240221170144_neighbouring_sites/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/database/seed/seed-clear.js
- appeals/api/src/server/common/validators/number-parameter.js
- appeals/api/src/server/common/validators/regex-parameter.js
- appeals/api/src/server/common/validators/string-parameter.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.controller.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.routes.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.validators.js
- appeals/api/src/server/endpoints/transferred-appeals/transferred-appeal.routes.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/repositories/neighbouring-sites.repository.js
- appeals/api/src/server/repositories/service-customer.repository.js
- appeals/api/src/server/swagger.js
Endpoints for neighbouring sites:
- add
- update
- delete
[BOAT-677](https://pins-ds.atlassian.net/browse/BOAT-677)
[BOAT-945](https://pins-ds.atlassian.net/browse/BOAT-945)
[BOAT-677]: https://pins-ds.atlassian.net/browse/BOAT-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BOAT-945]: https://pins-ds.atlassian.net/browse/BOAT-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals/api): neighbouring sites api

- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentUpload.spec.js
> test(e2e): removed inspector related tests

- apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
- apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
- apps/web/src/server/views/applications/case-project-team/project-team-choose-role.njk
- apps/web/src/server/views/applications/case-s51/components/enquirer-string.njk
Some Jest Web tests fail under Windows only, not Linux/Mac, to do with how Jest handles new lines in Nunjucks.
https://pins-ds.atlassian.net/browse/BOAS-1583
> fix(web/applications): web tests fail windows only (boas-1583)

- appeals/api/src/server/repositories/folder.repository.js
fix(appeals/api): aligns the sort order of documents (by creation date, desc)
> fix(appeals/api): aligns the sort order of documents

- apps/web/src/server/app/components/file-uploader.component.js
- Tested manually
https://pins-ds.atlassian.net/browse/BOAS-1593
> fix(applications/web): display correct duplicates or deleted messages (BOAS-1593)

- appeals/web/src/server/views/app/components/document-link.component.njk
[BOAT-997](https://pins-ds.atlassian.net/browse/BOAT-997)
[BOAT-997]: https://pins-ds.atlassian.net/browse/BOAT-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): BOAT-997 Potentially unsafe external link

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/views/app/layouts/app.layout.njk
Removes Crown copyright and OGL footer elements
[BOAT-1030](https://pins-ds.atlassian.net/browse/BOAT-1030)
[BOAT-1030]: https://pins-ds.atlassian.net/browse/BOAT-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): remove elements from footer

- appeals/web/package.json
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/url-utilities.js
- package-lock.json
[BOAT-998](https://pins-ds.atlassian.net/browse/BOAT-998)
[BOAT-998]: https://pins-ds.atlassian.net/browse/BOAT-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): BOAT-BOAT-998 User-generated redirect User-generated redirect

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/views/app/components/file-uploader.component.njk
https://pins-ds.atlassian.net/browse/BOAT-984
https://pins-ds.atlassian.net/browse/BOAT-986
https://pins-ds.atlassian.net/browse/BOAT-987
> feat(appeals/web): content changes for document process

- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.router.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.router.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.router.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.router.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.router.js
- appeals/web/src/server/appeals/change-page/change-page.router.js
- appeals/web/src/server/appeals/national-list/national-list.router.js
- appeals/web/src/server/appeals/personal-list/personal-list.router.js
Modified all web routes to use the async wrapper when calling controllers.
[BOAT-600](https://pins-ds.atlassian.net/browse/BOAT-600)
[BOAT-600]: https://pins-ds.atlassian.net/browse/BOAT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals/web): async route handlers

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
add a11y text to case details page action links
BOAT-621
> fix(web): add a11y text to case details page action links

- apps/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap
- apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap
- apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
- apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/__snapshots__/publish-valid-reps.test.js.snap
- apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
- apps/web/src/server/views/app/500.njk
- Amend error message as specified
- Fix the link as specified
- Updated unit tests where necessary
https://pins-ds.atlassian.net/browse/BOAS-1523
> fix(applications/web): amend broken error message link (BOAS-1523)

- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/lib/nunjucks-filters/status-tag.js
rename "LPA questionnaire due" appeal status to "LPA questionnaire" for UI only
BOAT-606
> fix(web): lpa questionnaire wording alignment

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/other-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.router.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.service.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/address-formatter.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
> feat(web): feature/BOAT-333-adding-related-appeals

- apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
- Timetable item type Procedural Deadline (Pre-Examination) changed to have a Document case stage of Pre-examination
- Added unit tests for above
https://pins-ds.atlassian.net/browse/BOAS-1565
> fix(applications/api): procedural deadline should be pre-examination (BOAS-1565)

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/appeals/change-page/change-page.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
refactor appeal data mapper to optionally avoid async calls
BOAT-869
> fix(web): refactor appeal data mapper to optionally avoid async calls

- appeals/web/src/server/app/app.express.js
- apps/web/src/server/app/app.express.js
- Amended both appeals and apps to create a nonce on every request
https://pins-ds.atlassian.net/browse/BOAS-1597
> fix(web): generate nonce on every request (BOAS-1597)

- apps/api/setup-tests.js
- apps/api/src/database/seed/data-test.js
- apps/api/src/server/applications/_utils/batch-send-events.js
- apps/api/src/server/applications/application/representations/publish/__tests__/publish-representation.test.js
- apps/api/src/server/applications/application/representations/publish/publish.service.js
- apps/api/src/server/applications/application/representations/publishable/__tests__/publishable-representations.test.js
- apps/api/src/server/repositories/__tests__/representation.repository.test.js
- apps/api/src/server/repositories/representation.repository.js
- apps/web/src/server/applications/case/representations/publish-valid-representations/__tests__/__snapshots__/publish-valid-reps.test.js.snap
- apps/web/src/server/views/applications/representations/publish-valid-representations/index.njk
Ticket: https://pins-ds.atlassian.net/browse/ASB-2078
fixes:
-introduce batching when loading large amounts of reps to avoid 'too many parameters' error
-batch the send event
> fix(api/applications): fix issues when publishing >5k representations

- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
fix character limit on issue decision invalid reason textarea
BOAT-1011
> fix(web): fix character limit on issue decision invalid reason textarea

- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
- apps/web/src/server/lib/nunjucks-globals/index.js
- apps/web/src/server/views/applications/case-documentation/search/document-search-results.njk
- apps/web/src/server/views/applications/case-timetable/components/timetable-item-summary.component.njk
- apps/web/src/server/views/applications/case/components/case-applicant-table.component.njk
- apps/web/src/server/views/applications/case/components/case-details-table.component.njk
- apps/web/src/server/views/applications/case/components/case-info-table-preview.component.njk
- apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk
- apps/web/src/server/views/applications/representations/representation-details/components/representation-summary-list.component.njk
- Amend to use text property instead of the html property when unnecessary
- Sanitize user created html where possible
- Updated unit tests where necessary
https://pins-ds.atlassian.net/browse/BOAS-1594
> feat(applications/web): apply html encode consistently (BOAS-1594)

- azure-pipelines-e2e-applications.yml
> test(e2e): adding test-suite

- azure-pipelines-e2e-applications.yml
> test(e2e): taking out new tests due to error on pipeline

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/audit-trails/__tests__/audit-trails.test.js
- appeals/api/src/server/endpoints/audit-trails/audit-trails.controller.js
- appeals/api/src/server/endpoints/audit-trails/audit-trails.formatter.js
- appeals/api/src/server/endpoints/audit-trails/audit-trails.routes.js
- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/repositories/audit-trail.repository.js
- appeals/api/src/server/tests/appeals/mocks.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/audit/audit.controller.js
- appeals/web/src/server/appeals/appeal-details/audit/audit.router.js
- appeals/web/src/server/appeals/appeal-details/audit/audit.service.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-users/users-service.js
- appeals/web/src/server/views/appeals/appeal/audit.njk
Audit trails showing in appeal details...
BOAT-482
> feat(appeals/web): appeals audit trails

- appeals/web/src/server/appeals/appeal-details/audit/audit.service.js
Fixes the colours of the appeal states...
> fix(appeals/web): audit, alignment of case statuses

- apps/api/src/server/applications/subscriptions/subscriptions.js
- apps/api/src/server/gen-api-spec.js
- apps/api/src/server/migration/migration.routes.js
- apps/api/src/server/migration/migrators/nsip-subscription-migrator.js
- apps/api/src/server/swagger-output.json
https://pins-ds.atlassian.net/browse/BOAS-1607
Fix nsip-subscription migrator
> fix(applications/api): nsip-subscription migrator map subscription types

- azure-pipelines-e2e-applications.yml
> test(e2e): creating options for test suite in run pipeline

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.formatter.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
fix for duplicated agent name in linked appeals
BOAT-1040
> feat(appeals): fix for duplicated agent name in linked appeals

- azure-pipelines-e2e-applications.yml
> test(e2e): testing-suite-option-removal

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.controller.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.router.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.service.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/address-formatter.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/error-handlers/__tests__/error-handlers.test.js
- appeals/web/src/server/lib/error-handlers/address-error-handler.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/BOAT-944
> feat(appeals/web): add neighbouring sites for inspectors and 3rd party

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.controller.js
- appeals/api/src/server/repositories/appeal.repository.js
Adds audit trails for controller actions on:
- linked appeals
- related appeals
- neighbouring sites
N/A
> feat(appeals/api): adds audit trails for linked, related and neighbours

- apps/e2e/cypress/support/utils/utils.js
> test(e2e): updated change link code for postcode

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/sanitizers/textarea-sanitizer.js
- appeals/web/src/server/lib/validators/textarea-validator.js
fix character count validation issue on issue decision invalid reason textarea
BOAT-1011
> fix/BOAT-1011-b: fix character count validation issue on issue decision invalid reason textarea

- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
fix back link on unlink appeal page
> fix(web): fix back link on unlink appeal page

- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
add code to prevent linking appeals to themselves
BOAT-1047
> fix(web): prevent linking appeal to itself

- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
> test(e2e): updated dynamic data in spec file

- apps/e2e/cypress/page_objects/createCasePage.js
> test(e2e): updated locator for postcode lookup

- appeals/api/src/server/endpoints/appeals/appeals.controller.js
fix personal list displaying lead and child tags for related appeals
BOAT-1045
> fix(api): fix personal list displaying lead and child tags for related appeals

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/validators/textarea-validator.js
add not empty validation to issue decision invalid textarea
BOAT-1013
> fix(web): add not empty validation to issue decision invalid textarea

- apps/api/src/server/applications/application/documents/__tests__/document.service.test.js
- apps/api/src/server/applications/documents/documents.service.js
- Fixed the extraction of iframe src without the use of a regex
- Added several unit tests to catch the various possible issues when extracting the src
- Added several unit tests to prove the extraction is successful
- Re-run api unit tests
https://pins-ds.atlassian.net/browse/BOAS-1649
> fix(applications/api): iframe src should be extracted correctly (BOAS-1649)

- apps/functions/applications-background-jobs/malware-detected/__tests__/html-validation.test.js
- apps/functions/applications-background-jobs/malware-detected/index.js
- apps/functions/applications-background-jobs/malware-detected/src/config.js
- apps/functions/applications-background-jobs/malware-detected/src/html-validation.js
- apps/functions/applications-background-jobs/setup-tests.js
> fix config to ensure blob account is included and add logging

- apps/api/src/server/applications/application/documents/document.js
- package-lock.json
* fix(api/applications): log an error if a blob URI fails to be built
[BOAS-1645](https://pins-ds.atlassian.net/browse/BOAS-1645)
[BOAS-1645]: https://pins-ds.atlassian.net/browse/BOAS-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api/applications): log an error if a blob URI fails to be built

- apps/functions/applications-background-jobs/.gitignore
- apps/functions/applications-background-jobs/host.json
- apps/functions/applications-background-jobs/local.settings.json
- apps/functions/applications-background-jobs/malware-detected/__tests__/html-validation.test.js
- apps/functions/applications-background-jobs/malware-detected/src/html-validation.js
- apps/functions/applications-background-jobs/malware-detected/src/util.js
> fix(functions): fix blob querying by replacing uri with name

- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.router.js
fix unlink appeal back link when unlinking from child
BOAT-1062
> fix(web): fix unlink appeal back link when unlinking from child

- apps/e2e/cypress/e2e/back-office-applications/addRepresentation.spec.js
- apps/e2e/cypress/e2e/back-office-applications/addTeam.spec.js
- apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentDownload.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentUpload.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentVersioning.spec.js
- apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
- apps/e2e/cypress/e2e/back-office-applications/keyDates.spec.js
- apps/e2e/cypress/e2e/back-office-applications/publishDocuments.spec.js
- apps/e2e/cypress/e2e/back-office-applications/s51Advice.spec.js
- apps/e2e/cypress/e2e/back-office-applications/search.spec.js
- apps/e2e/cypress/e2e/back-office-applications/searchDocuments.spec.js
- apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
- apps/e2e/cypress/e2e/back-office-applications/unpublishDocuments.spec.js
- apps/e2e/cypress/e2e/back-office-applications/updateAndRemoveTeam.spec.js
- apps/e2e/cypress/e2e/back-office-applications/updateProjectInformation.spec.js
- apps/e2e/cypress/page_objects/basePage.js
> test(e2e): updated examtimetable and publishdocs

- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
- Changed using Gov.UK Design System button and button group components
- Unit tests updated
https://pins-ds.atlassian.net/browse/BOAS-1660
> fix(applications/web): correct styling in document properties page (BOAS-1615)

- appeals/api/src/server/utils/mapping/map-horizon.js
- appeals/web/src/server/app/app.express.js
Removes mobile-specific permissions returning warnings: accelerometer, fullscreen, gamepad, etc...
BOAT-619
> fix(appeals/web): removes mobile-specific headers

- apps/api/src/database/seed/seed-clear.js
- Reverted last attempt back to deleting tables that are not interdependent in parallel and in the correct order of dependency
- Manually tested the functionality locally
- This should be ok on TEST, but I suggest building the DB from scratch in DEV to get it to work correctly there 
https://pins-ds.atlassian.net/browse/BOAS-1613
> fix(applications/api): fix seed error (BOAS-1613)

- azure-pipelines-db-reset-apps.yml
- Added new yaml for a pipeline to run db:reset in only DEV or TEST
https://pins-ds.atlassian.net/browse/BOAS-1613
> fix(applications/api): add db:reset pipeline for dev and test (BOAS-1613)

- apps/api/src/server/applications/key-dates/key-dates.utils.js
- apps/api/src/server/swagger-output.json
- apps/api/src/server/swagger-types.ts
- apps/api/src/server/swagger.js
PR adds the new relevant reps reopen start and close date fields to the key date GET endpoint response.
Ticket: https://pins-ds.atlassian.net/browse/ASB-2321
> feat(api/applications): rr reopen start + close dates to key-dates ep

- apps/api/src/database/migrations/20240312131256_alter_document_reference_column/migration.sql
- apps/api/src/database/schema.prisma
- apps/api/src/server/applications/application/documents/__tests__/delete-document.test.js
- apps/api/src/server/applications/application/documents/__tests__/get-document.test.js
- apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js
- apps/api/src/server/applications/application/documents/__tests__/store-document-metadata.test.js
- apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js
- apps/api/src/server/applications/application/documents/document.controller.js
- apps/api/src/server/applications/application/documents/document.js
- apps/api/src/server/applications/application/documents/document.service.js
- apps/api/src/server/applications/documents/documents.service.js
- apps/api/src/server/repositories/document-metadata.repository.js
- apps/api/src/server/repositories/document.repository.js
- apps/api/src/server/utils/mapping/map-document-details.js
- apps/functions/applications-background-jobs/publish-document/index.js
> fix(api): change document reference property to documentReference

- apps/e2e/cypress/e2e/back-office-applications/search.spec.js
> test(e2e): removed it blocks which are not required

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/utils/format-linked-appeals.js
Adds the appeal types of referenced appeals (both linked and related)
> fix(appeals/api): returns the types of related and linked appeals

- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
disallow relating appeals to themselves or already related appeals
BOAT-1047
> fix(web): disallow relating appeals to themselves or already related appeals

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
rename LPA reference (appeal details page) and application reference (appellant case page) to LPA application reference
BOAT-1082
> fix(web): rename LPA reference and application reference to LPA application reference

- apps/api/src/server/migration/migrators/nsip-project-migrator.js
- apps/api/src/server/migration/migrators/utils.js
- apps/functions/applications-migration/common/back-office-api-client.js
- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- allow project without zoomlevel to be migrated as it is a non-mandatory field
- update how `nsip-project` payload is sent, to match new schema (all fields required / send null value - https://github.com/Planning-Inspectorate/data-model/pull/13)
- small QoL change to use `http` when running function locally so you don't have to change it manually
> fix(functions): nsip-project-migrator bug fixes

- appeals/api/src/server/common/validators/string-parameter.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.validators.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.controller.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.router.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.service.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-695
> feat(appeals/web): add manage and delete inspector and third party neighbouring sites

- apps/functions/applications-background-jobs/notify-subscribers/src/__tests__/notify-subscribers.test.js
- apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
- Set strong and em delimiters in turndown options to blank
- Create additional unit tests
https://pins-ds.atlassian.net/browse/BOAS-1671
> fix(applications): email notification - issue with bold text (BOAS-1671)

- apps/functions/applications-background-jobs/notify-subscribers/src/__tests__/notify-subscribers.test.js
- apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
- Decode the content returned when converting html into markup
- Fix the affected unit test
https://pins-ds.atlassian.net/browse/BOAS-1659
> fix(applications): project updates email notification parsing (BOAS-1659)

- apps/web/src/server/app/config/session.js
> fix(web): terminate session cookie after 8 hours

- apps/api/src/server/middleware/authorise-request.js
Removed unnecessary logs
https://pins-ds.atlassian.net/browse/BOAS-1690
> fix(applications/api): removed unnecessary logs (BOAS-1690)

- apps/e2e/cypress/e2e/back-office-applications/smokeTests.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/examinationTimetablePage.js
- apps/e2e/cypress/page_objects/s51AdvicePage.js
> test(e2e): updated smoke pack with delete scenarios

- apps/e2e/cypress/page_objects/createCasePage.js
> test(e2e): increase the time for postcode lookup

- azure-pipelines-package-function-merge.yml
> ci: fix function merge

- apps/functions/applications-background-jobs/notify-subscribers/src/back-office-api-client.js
- apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
Fix for https://pins-ds.atlassian.net/browse/ASB-2337
Getting case by reference was failing.
> fix(functions): get case by reference using /applications/reference endpoint

- apps/functions/applications-background-jobs/publish-document/src/__tests__/util.test.js
- apps/functions/applications-background-jobs/publish-document/src/util.js
https://pins-ds.atlassian.net/browse/BOAS-1697
> fix(functions): don't assume source container for storage account check

- apps/functions/applications-command-handlers/deadline-submission-command/blob-client.js
- apps/functions/applications-command-handlers/deadline-submission-command/config.js
- apps/functions/applications-command-handlers/test-deadline-submission/config.js
* fix(functions): use custom domain to connect to blob store
* fix(functions): use copyFileFromUrl in deadline-submission-command
[BOAS-1696](https://pins-ds.atlassian.net.mcas.ms/browse/BOAS-1696)
[BOAS-1696]: https://pins-ds.atlassian.net/browse/BOAS-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(functions): use custom domain to connect to blob store

- apps/web/src/server/applications/case/s51/applications-s51.controller.js
- apps/web/src/server/applications/case/s51/applications-s51.router.js
- apps/web/src/server/applications/case/s51/applications-s51.validators.js
> fix(web/applications): fix ss request forgery on S51

- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
- apps/web/src/server/views/applications/components/folder/folder.njk
Move the breadcrumb to the top of the page, before the folder banner.
[BOAS-1511](https://pins-ds.atlassian.net/browse/BOAS-1511)
[BOAS-1511]: https://pins-ds.atlassian.net/browse/BOAS-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): move breadcrumb to before the folder banner

- apps/web/src/server/applications/case/s51/applications-s51.controller.js
- apps/web/src/server/applications/case/s51/applications-s51.router.js
> fix(web/applications): add validation on s51 edit pages (boas-1592)

- apps/api/package.json
- apps/functions/applications-migration/package.json
- package-lock.json
- package.json
> chore(api): bump data model version to allow for node/npm upgrades

- apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap
- apps/web/src/server/applications/__tests__/applications.test.js
- apps/web/src/server/lib/nunjucks-filters/url.js
- apps/web/src/server/views/applications/dashboard.njk
- apps/web/src/styles/7-components/DashboardBox/DashboardBox.scss
https://pins-ds.atlassian.net/browse/ASB-2271
-update dashboard and introduce general section 51 link
> feat(web/applications): update dashboard and introduce general section 51 link

- apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
- apps/e2e/cypress/page_objects/applicationsHomePage.js
- apps/e2e/cypress/page_objects/createCasePage.js
> test(e2e): updated tests with dev changes

- apps/api/src/database/seed/data-gs51.js
- apps/api/src/server/repositories/case.repository.js
- apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
- apps/web/environment/config.d.ts
- apps/web/environment/config.js
- apps/web/environment/schema.js
- apps/web/src/server/applications/__tests__/applications.test.js
- apps/web/src/server/applications/case/applications-case.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/general-s51/__tests__/applications-general-s51.controller.test.js
- apps/web/src/server/applications/case/general-s51/applications-general-s51.config.js
- apps/web/src/server/applications/case/general-s51/applications-general-s51.controller.js
- apps/web/src/server/applications/case/general-s51/utils/get-general-section-51-URL.js
- apps/web/src/server/applications/case/general-s51/utils/get-general-section-51-data.js
- apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
- apps/web/src/server/applications/case/key-dates/__tests__/applications-key-dates.utils.test.js
- apps/web/src/server/applications/case/key-dates/applications-key-dates.controller.js
- apps/web/src/server/applications/case/key-dates/applications-key-dates.utils.js
- apps/web/src/server/applications/case/s51/applications-s51.controller.js
- apps/web/src/server/lib/dates.js
- apps/web/src/server/lib/nunjucks-filters/key-dates-property.js
- apps/web/src/server/views/applications/case-key-dates/includes/pre-examination/pre-examination-key-dates.include.njk
- apps/web/src/server/views/applications/case-key-dates/includes/pre-examination/pre-examination-manage-dates.include.njk
- apps/web/src/server/views/applications/case-key-dates/key-dates-index.njk
- apps/web/src/server/views/applications/case-key-dates/key-dates-section.njk
- apps/web/src/styles/7-components/key-dates-section.scss
- https://pins-ds.atlassian.net/browse/ASB-2333?atlOrigin=eyJpIjoiMzhkMGEyMmVlYzQ1NDA3MGEzOTY3MzRhNzAzZmY5NTUiLCJwIjoiaiJ9
- https://pins-ds.atlassian.net/browse/ASB-2325?atlOrigin=eyJpIjoiYjNmMzBmNjQxY2Q5NDI5Y2FjYzk5NjJlYzdlNTQ4YTgiLCJwIjoiaiJ9
- https://pins-ds.atlassian.net/browse/ASB-2319?atlOrigin=eyJpIjoiMjJiMmI0NjRiODViNDY0NGFiMmJjNDM1YTEyMDM1MzQiLCJwIjoiaiJ9
> feat(web/applications): Re-opening the Registration Journey

- apps/api/src/server/applications/application/__tests__/publish-application.test.js
- apps/api/src/server/applications/application/application.controller.js
- apps/api/src/server/repositories/case.repository.js
https://pins-ds.atlassian.net/browse/ASB-2378?atlOrigin=eyJpIjoiODIyMDYxMDFkYmE2NGRiZGI1MmMzMzhhZmY0NzQwMjkiLCJwIjoiaiJ9
> feat(applications/api): ASB-2378 - General S51 Advice: BO API disable publish

- apps/e2e/package.json
- package-lock.json
- Add missing lodash-es dependency for e2e tests
https://pins-ds.atlassian.net/browse/BOAS-1718
> fix(applications/web): add missing lodash-es dependency (BOAS-1718)

- apps/api/src/server/applications/application/application.config.js
- apps/api/src/server/applications/application/application.controller.js
- apps/api/src/server/repositories/case.repository.js
https://pins-ds.atlassian.net/browse/ASB-2378?atlOrigin=eyJpIjoiNmNkYjY5MjFlYmI2NGIyMjljMTIwYTlkNmM4YWQ1ODgiLCJwIjoiaiJ9
> fix(applications/web): remove imported web config file

- apps/api/package.json
- apps/api/src/database/seed/data-gs51.js
- apps/api/src/database/seed/data-test.js
- apps/api/src/database/seed/seed-gs51.js
- azure-pipelines-db-create-gs51.yml
Pipeline creating general section 51 case
> feat(api): create gs51 pipeline

- apps/e2e/cypress/e2e/back-office-applications/addRepresentation.spec.js
- apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentUpload.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentVersioning.spec.js
- apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
- apps/e2e/cypress/e2e/back-office-applications/s51Advice.spec.js
- apps/e2e/cypress/e2e/back-office-applications/smokeTests.spec.js
- apps/e2e/cypress/e2e/back-office-applications/updateAndRemoveTeam.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/e2e/cypress/page_objects/representationPage.js
- apps/e2e/cypress/page_objects/s51AdvicePage.js
- apps/e2e/cypress/page_objects/s51AdviceProperties.js
- apps/e2e/cypress/page_objects/uploadFiles.js
- package.json
> test(e2e): e2e test changes

- apps/api/src/server/applications/application/representations/representations.controller.js
- apps/api/src/server/applications/application/representations/representations.routes.js
- apps/api/src/server/swagger-output.json
- apps/api/src/server/utils/query/__tests__/sort-by.test.js
- apps/api/src/server/utils/query/sort-by.js
- Changed as described
- Unit tests as described
- Manually tested the functionality with Swagger
https://pins-ds.atlassian.net/browse/BOAS-1571
> feat(applications/api): allow sortBy to include multiple fields (BOAS-1571)

- apps/api/src/database/migrations/20240422160000_rename_mail_merges_folder/migration.sql
- apps/api/src/server/applications/application/__tests__/start-case.test.js
- apps/api/src/server/migration/migrators/folder/__tests__/folder.test.js
- apps/api/src/server/migration/migrators/folder/folder.js
- apps/api/src/server/repositories/folder.repository.js
- apps/e2e/cypress/fixtures/folder-structure.json
Change name of the folder Mail merge spreadsheet to Mail merges
- applies to newly created cases, and migrated cases
- add SQL migrate script to correct all old folders on existing cases
- also amended E2E scripts
https://pins-ds.atlassian.net/browse/BOAS-1719
> feat(api/applications): change folder name mail merges (boas-1719)

- apps/e2e/cypress/support/utils/createProjectInformation.js
- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/applications/common/components/form/form-applicant.component.js
- apps/web/src/server/lib/address-formatter.js
- apps/web/src/server/lib/nunjucks-filters/format-address.js
- apps/web/src/server/lib/nunjucks-filters/index.js
- apps/web/src/server/views/applications/case/components/case-applicant-table.component.njk
- Correct the address formatting algorithm
- Make the address formatting happen in one place
- Add a format address filter 
- Fix the unit tests
- Test Manually
https://pins-ds.atlassian.net/browse/BOAS-1706
- [x ] I have included unit tests to cover any testable code changes
> fix(applications/web): edit application address does not show all address parts (BOAS-1706)

- apps/functions/applications-background-jobs/notify-subscribers/src/__tests__/notify-subscribers.test.js
- apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
- apps/functions/applications-background-jobs/notify-subscribers/src/util.js
- apps/functions/applications-background-jobs/package.json
- package-lock.json
- Do not decode the links when decoding the HTML
- Tested via unit tests
https://pins-ds.atlassian.net/browse/BOAS-1720
- [x ] I have included unit tests to cover any testable code changes
> fix(functions): email notification - issue with hyphens, apostrophe and brackets (BOAS-1720)

- apps/functions/applications-migration/host.json
Sets high timeout value for migration Function App
> chore(functions): increase timeout for migration function

- .vscode/extensions.json
- .vscode/settings.json
> feat(tooling): add jest-runner extension and settings

- apps/functions/applications-background-jobs/notify-subscribers/src/__tests__/notify-subscribers.test.js
- apps/functions/applications-background-jobs/notify-subscribers/src/notify-subscribers.js
- apps/functions/applications-background-jobs/notify-subscribers/src/util.js
- apps/functions/applications-background-jobs/package.json
- package-lock.json
- Backout decoding
- Tested via unit tests
- Will tests sending email notification once deployed to DEV as it's the only way to test properly
https://pins-ds.atlassian.net/browse/BOAS-1720
- [x ] I have included unit tests to cover any testable code changes
> fix(functions): email notification - formatting issues (BOAS-1720)

- apps/web/src/server/app/__tests__/__snapshots__/app.test.js.snap
- apps/web/src/server/app/__tests__/app.test.js
- apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap
- apps/web/src/server/applications/__tests__/applications.test.js
- apps/web/src/server/views/app/401.njk
- apps/web/src/server/views/app/403.njk
- apps/web/src/server/views/app/404.njk
- Fix all broken support links in nunjucks templates
- Added unit tests
- Tested manually
https://pins-ds.atlassian.net/browse/APPLICS-69
- [x ] I have included unit tests to cover any testable code changes
> fix(applications/web): fix broken link (APPLICS-69)

- apps/web/src/server/applications/common/components/__tests__/build-query-string.unit.test.js
- apps/web/src/server/applications/common/components/build-query-string.js
- encode the query string parameters to allow the values to be prefixed with "+" for sorting purposes
- Added unit tests
- Tested manually
https://pins-ds.atlassian.net/browse/APPLICS-46
> fix(applications/web): fix project updates sorting (APPLICS-46)

- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/views/applications/case/components/case-info-table.component.njk
https://pins-ds.atlassian.net/browse/APPLICS-36
Align change link in project information to section to other change links on the page
> fix(applications/web): align change link on project information page

- apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
- apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
- apps/web/src/server/views/applications/components/case-form/case/team-email.njk
- Changed sample email from NIEnquiries@planninginspectorate.gsi.gov.uk to NIEnquiries@planninginspectorate.gov.uk as requested.
https://pins-ds.atlassian.net/browse/APPLICS-42
> fix(applications/web): gsi email in sample text (APPLICS-42)

- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- apps/functions/applications-migration/nsip-project-migration/debug.js
Update the `nsip-project-migration` function to fix a couple of issues with transforming the ODW data into a JSON object that conforms to the schema
- Transform string/null values into array (`nsipOfficerIds`, `nsipAdministrationOfficerIds`, etc)
- e.g. id of `"12345"` becomes `["12345"]` and `null` becomes `[]`
- Remove some values for required fields which were hardcoded to `null` (`jRPeriodEndDate`, `dateIAPIDue`, etc). These are now being returned by ODW so no longer need to be hardcoded to pass the schema validation.
https://pins-ds.atlassian.net/browse/APPLICS-225
> fix(functions): fix array validation for nsip-project

- apps/api/src/database/migrations/20240503090633_add_migrationstatus_to_case_table/migration.sql
- apps/api/src/database/schema.prisma
- apps/api/src/server/migration/migration.controller.js
- apps/api/src/server/migration/migrators/nsip-project-migrator.js
- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- apps/functions/applications-migration/migrate-case/debug.js
- apps/functions/applications-migration/migrate-case/index.js
Tickets:
- https://pins-ds.atlassian.net/browse/APPLICS-152 - Add `migrationStatus` to `migrate-case` function and endpoints
- https://pins-ds.atlassian.net/browse/APPLICS-224 - Add validation error reporting to migration endpoints
Ticket has been tested via swagger because data from ODW is failing validation and therefore the whole migrate-case function cannot be tested e2e.
> feat(applications/api): Add migrationStatus 

- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- add additional scope the `nsip_data` query to avoid capturing non-horizon data
- add error response logging to migrator functions which were lacking it
- add temporary workaround for ODW mapping issue for `projectType` field in `nsip_data`
> fix(functions): nsip-project fixes

- packages/feature-flags/src/is-feature-active.js
Errors are not caught by `catch` if they were produced by `reject`.
> fix(packages/feature-flags): use a promise instead of async/await

- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/views/applications/case-timetable/timetable-success-banner.njk
Remove typo in exam timetable unpublish banner.
APPLICS-38: https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-38
> fix(web): remove typo in exam timetable banner

- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.mapper.test.js
- apps/web/src/server/applications/case/project-updates/project-updates.mapper.js
- Remove the italics tags `<em></em>` 
- Make sure all `<br>` tags are converted correctly to `</ br>`
- Add unit tests
- Tested manually, however emails will need to be tested when deployed to DEV
https://pins-ds.atlassian.net/browse/APPLICS-275
> fix(applications/web): projects update italics issue (APPLICS-275)

- apps/web/src/styles/5-elements/_elements.form-group.scss
#https://pins-ds.atlassian.net/browse/APPLICS-37
adjust spacing on dateInput component
> style(web): adjust dateInput spacing

- apps/api/src/database/schema.d.ts
- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
- apps/api/src/server/repositories/representation.repository.js
- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
Creates a representationAttachment entry in the BO db on representation migration. I haven't been able to find a way to test this properly due to a lack of available data along with foreign key constraints.
> feat(api): create representation attachment entries

- apps/functions/applications-migration/.gitignore
- apps/functions/applications-migration/common/handle-migration-with-response.js
- apps/functions/applications-migration/common/migration-function-wrapper.js
- apps/functions/applications-migration/exam-timetable-migration/index.js
- apps/functions/applications-migration/folder-migration/index.js
- apps/functions/applications-migration/local.settings.json
- apps/functions/applications-migration/migrate-case/function.json
- apps/functions/applications-migration/migrate-case/index.js
- apps/functions/applications-migration/nsip-document-migration/index.js
- apps/functions/applications-migration/nsip-project-migration/index.js
- apps/functions/applications-migration/nsip-representation-migration/index.js
- apps/functions/applications-migration/project-updates-migration/index.js
- apps/functions/applications-migration/s51-advice-migration/index.js
- apps/functions/applications-migration/service-user-migration/index.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-366
Migration functions currently don't return a response to confirm, or provide useful error messages when an error occurs. This PR adds `handleMigrationWithResponse`, which is used in all functions that will handle this.
> feat(functions): migration error handling and response

- azure-pipelines-deploy-release.yml
https://pins-ds.atlassian.net/browse/DEV-241
A new pipeline - very similar to deploy - just with blue/green deployments by deploying to a slot.
> feat(tooling): add release pipeline with blue/green deployments

- azure-pipelines-deploy-release.yml
> fix(tooling): don't auto trigger release on merge

- azure-pipelines-deploy-release.yml
> fix(tooling): artefacts are already downloaded for pipeline resources

- apps/api/src/server/migration/migrators/nsip-document-migrator.js
> feat(api): call service bus with publish doc function post migration

- azure-pipelines-deploy-release.yml
> fix(tooling): release pipeline

- azure-pipelines-e2e-applications.yml
Add FEATURE_FLAG_CONNECTION_STRING variable to e2e pipeline
> feat(e2e): add FEATURE_FLAG_CONNECTION_STRING variable to e2e pipeline

- apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
- apps/e2e/cypress/page_objects/createCasePage.js
- apps/e2e/cypress/page_objects/createCaseSections/checkYourAnswers.js
- apps/e2e/cypress/support/utils/utils.js
> test(e2e): added welsh test

- apps/api/src/server/migration/migrators/nsip-document-migrator.js
> fix(api): pass correct parameters to SB call for migrated docs

- azure-pipelines-deploy-release.yml
The new Release pipeline has been tested on the TEST environment and now needs to pint to PROD
https://pins-ds.atlassian.net/browse/APPLICS-382
> Point Release pipeline to PROD

- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
- apps/api/src/server/migration/migrators/s51-advice-migrator.js
- apps/api/src/server/repositories/representation.repository.js
- apps/api/src/server/repositories/s51-advice-document.repository.js
> feat(api): populate s51document relational table

- packages/feature-flags/src/feature-flag-client.js
Prevent a crash if the provided connection string is invalid.
> fix(packages/feature-flags): prevent crash if connection string invalid

- apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
- apps/e2e/cypress/support/utils/utils.js
> test(e2e): added more scenarios for welsh tests

- apps/api/src/server/migration/migration.routes.js
- apps/api/src/server/migration/validate-migration.controller.js
- apps/api/src/server/repositories/service-user.repository.js
- apps/functions/applications-migration/common/back-office-api-client.js
- apps/functions/applications-migration/common/handle-migration-with-response.js
- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
- apps/functions/applications-migration/common/migrators/s51-advice-migration.js
- apps/functions/applications-migration/common/migrators/service-user-migration.js
- apps/functions/applications-migration/common/validate-migration.js
- apps/functions/applications-migration/package.json
- package-lock.json
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-145
Adds a migration validation set to case migration function. For the project entity, the JSON difference is shown between the ODW and BO data. However for the rest of the entities, due to too many items, counts are shown. Counts are calculated, not just by length but by ensuring the same Ids exist between both sets of data. An example response for `EN010049` would be:
```json
{
"migration": "Successfully ran migration for case",
"validation": {
"EN010049": {
"project": {
"CaseNodeId__missing_in_BO": "15275489",
"ExamTimetablePublishStatus__missing_in_BO": null,
"SourceSystem": {
"ODW": "horizon",
"BO": "back-office-applications"
},
"DateProjectAppearsOnWebsite": {
"ODW": "2009-10-01 00:00:00.0000000",
"BO": "2009-09-30T23:00:00.000Z" …
```
> feat(functions): migration validation

- apps/e2e/cypress/e2e/back-office-applications/examTimetable.spec.js
- apps/e2e/cypress/e2e/back-office-applications/smokeTests.spec.js
- apps/e2e/cypress/e2e/back-office-applications/updateProjectInformation.spec.js
- apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/casePage.js
- apps/e2e/cypress/support/utils/createS51Advice.js
- apps/e2e/cypress/support/utils/createTimetableItemInfo.js
- apps/e2e/cypress/support/utils/utils.js
- apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap
- apps/web/src/server/views/applications/case/components/case-applicant-table.component.njk
- apps/web/src/server/views/applications/case/overview.njk
* e2e test now cope with changes to publish button text to match new design
* allow rendering the applicant website as blank when null
* e2e tests date issue fixed
[APPLICS-423](https://pins-ds.atlassian.net/browse/APPLICS-423)
[APPLICS-423]: https://pins-ds.atlassian.net/browse/APPLICS-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix/e2e tests failing in applics-423

- apps/api/package.json
- package-lock.json
added missing `App Configuration client library` to API
Hotfix
> added missing package to API

- azure-pipelines-deploy.yml
https://pins-ds.atlassian.net/browse/DEV-93
Add training environment to deployment pipeline
> ci: add training environment to deploy

- azure-pipelines-deploy.yml
To fix an issue with the training key vault reference.
> chore: update deploy pipeline template

- azure-pipelines-e2e-applications.yml
Removed E2E tests from PR checks pipeline
https://pins-ds.atlassian.net/browse/APPLICS-448
> fix(applications): stop running e2e on pr checks (applics-448)

- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentPropertiesWelsh.spec.js
- apps/e2e/cypress/e2e/back-office-applications/publishDocuments.spec.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/e2e/cypress/page_objects/publishingQueue.js
> test(e2e): updated the tests for dev work

- azure-pipelines-regenerate-api-key.yml
> chore(tooling): add training option to regen-api-key

- README.md
Updated README file with documentation on how to setup Feature Flags
https://pins-ds.atlassian.net/browse/APPLICS-460
> chore(applications): updated Feature Flags setup documentation

- azure-pipelines-db-seed.yml
Test env was added twice, now replaced with Training as expected
https://pins-ds.atlassian.net/browse/APPLICS-460
> chore(applications): corrected duplicated environment name

- README.md
> chore(applications): fixed readme formatting (applics-432)

- apps/api/src/server/migration/migrators/folder/__tests__/folder.test.js
- apps/api/src/server/migration/migrators/folder/folder.js
Amend nsip-document migrator to migrate 'Exam Timetable' documents, creating subfolders within the Examination timetable directory
APPLICS-149
> feat(api): migrate exam timetable docs

- apps/e2e/cypress/e2e/back-office-applications/documentPropertiesWelsh.spec.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
- apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
- apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
- apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js
- apps/web/src/server/views/applications/case-documentation/documentation-edit.njk
> fix(web): add validation to welsh doc description (applics-452)

- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
- apps/api/src/server/utils/mapping/map-examination-timetable-item.js
- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.router.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.types.d.ts
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.validators.js
- apps/web/src/server/views/applications/case-timetable/components/timetable-item-summary.component.njk
- apps/web/src/server/views/applications/case-timetable/timetable-item-name-welsh.njk
- apps/web/src/server/views/applications/case-timetable/timetable-list.njk
https://pins-ds.atlassian.net/browse/APPLICS-14
-add item name in welsh page
-ensure blank welsh fields render on main examination-timetable page
-e2e all pass
> feat(web): add 'item name in welsh' page to examination timetable

- apps/functions/applications-migration/common/migrators/folder-migration.js
- apps/functions/applications-migration/migrate-case/index.js
Fix import in the `migrate-case` function
N/A
> fix(functions): fix migrate-case import statement

- apps/api/package.json
- apps/functions/applications-background-jobs/package.json
- apps/functions/applications-migration/package.json
- package-lock.json
- package.json
- packages/blob-storage-client/package.json
- packages/event-client/package.json
- packages/key-vault-secrets-client/package.json
- packages/scripts/package.json
Updated azure-identity from 4.2.0 to 4.2.1
https://pins-ds.atlassian.net/browse/APPLICS-495
> chore(applications): updated azure-identity to 4.2.1 (applics-495)

- apps/e2e/cypress/e2e/back-office-applications/createCase.spec.js
- apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
- apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
- apps/web/src/server/applications/case/edit/case/__tests__/applications-edit-case.test.js
- apps/web/src/server/applications/case/edit/case/applications-edit-case.controller.js
- apps/web/src/server/applications/case/edit/case/applications-edit-case.router.js
- apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
- apps/web/src/server/applications/create-new-case/case/applications-create-case.validators.js
Implement the content and template structure changes requested in the ticket.
- Corrected the error messages to match those in the ticket for both "Project description" and "Project description in Welsh" pages
- Extended the config for layouts to include english and welsh field names and template reference
- Fixed unit tests and snap shots to match new changes
https://pins-ds.atlassian.net/browse/APPLICS-500
> fix(applications/web): project description in welsh content changes (APPLICS-500)

- apps/functions/applications-migration/common/back-office-api-client.js
- apps/functions/applications-migration/validate-migration/function.json
- apps/functions/applications-migration/validate-migration/index.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-508
Creates a new function to wrap the validation functionality. This is to get faster feedback on validation without having to rerun migrate-case function which can take a long time and even time out in certain cases.
> feat(functions): created migration validation function

- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
- apps/e2e/cypress/e2e/back-office-applications/documentPropertiesWelsh.spec.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap
- apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js
- apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
- apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js
- apps/web/src/server/views/applications/case-documentation/documentation-edit-textinput.njk
- apps/web/src/server/views/applications/components/english-value-component.njk
- apps/web/src/server/views/applications/components/textinput-form-component.njk
- apps/web/src/server/views/applications/layouts/document-edit-property.layout.njk
The wording and design has been corrected for the following document property edit pages:
- File name
- Document description
- Document description in Welsh
- Webfilter
- Webfilter in Welsh
- Agent name (optional)
- Transcript (optional)
Changes made:
- Additional textinput nunjucks component has been created for the new design
- Config has been updated to match correct wording for each property
- Validators have been updated to the correct wording
- jest web tests have been updated
- e2e tests have been updated
https://pins-ds.atlassian.net/browse/APPLICS-533
> feat(applications/web): follow design convention for editing properties in the document properties pages (Applics-533)

- apps/e2e/cypress/e2e/back-office-applications/sectorAsTraing.spec.js
- apps/e2e/cypress/e2e/back-office-applications/welsh.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/casePage.js
- apps/e2e/cypress/page_objects/examinationTimetablePage.js
- apps/e2e/cypress/support/utils/createTimetableItemInfo.js
- apps/e2e/cypress/support/utils/utils.js
- apps/web/src/server/views/applications/case-timetable/components/timetable-items-list.component.njk
- Make sure tests can cope with old style tables and new style summary lists
- Use more existing page object functions in welsh tests
> fix(test/e2e): improve welsh feature flag functionality in e2e page objects

- apps/e2e/cypress.config.js
- apps/e2e/cypress/support/cypressUtils.js
- apps/e2e/cypress/support/e2e.js
This PR just helps to make the feature flag issue visible within the pipeline.
It doesn't actually resolve the issue itself.
- Make sure e2e tests report the status of the feature flags to the terminal
https://pins-ds.atlassian.net/browse/APPLICS-587
> fix(test/e2e): report feature flags in cypress terminal logs (APPLICS-587)

- apps/functions/applications-background-jobs/package.json
Functions temporarily reverted to Node 18 while an Infra release to PROD takes place on 04/07/2024 - the functions will be upgraded to node 20 again shortly after.
https://pins-ds.atlassian.net/browse/APPLICS-455
> chore(applications): revert backgound jobs to node 18 (APPLICS-455)

- apps/functions/applications-background-jobs/package.json
I upgrade the `backgound jobs` functions to node 20
https://pins-ds.atlassian.net/browse/APPLICS-455
> chore(applications): upgrade backgound jobs to node 20 (applics-455)

- apps/e2e/cypress/e2e/back-office-applications/projectUpdates.spec.js
- apps/e2e/cypress/page_objects/projectUpdatesPage.js
- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.mapper.test.js
- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js
- apps/web/src/server/applications/case/project-updates/project-updates.controller.js
- apps/web/src/server/applications/case/project-updates/project-updates.mapper.js
- apps/web/src/server/applications/case/project-updates/project-updates.router.js
- apps/web/src/server/applications/case/project-updates/project-updates.validators.js
- apps/web/src/server/applications/case/project-updates/project-updates.view-model.js
- apps/web/src/server/views/applications/components/html-content-editor.njk
Add Welsh project update field as per design in the ticket
- Update the project update controller, router, validator, and view model
- Update the unit tests and snapshots
- Create e2e tests for project update including tests for English and Welsh project updates
https://pins-ds.atlassian.net/browse/APPLICS-30
> feat(applications/web): create welsh project update (APPLICS-30)

- apps/e2e/cypress/e2e/back-office-applications/projectUpdates.spec.js
- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js
- apps/web/src/server/applications/case/project-updates/project-updates.validators.js
Fix project update validation
- Update the project update validation
- Update the unit tests and snapshots
- Update e2e tests for project update validation
https://pins-ds.atlassian.net/browse/APPLICS-30
> fix(applications/web): fix welsh project update validation (APPLICS-30)

- apps/e2e/cypress/e2e/back-office-applications/projectUpdates.spec.js
- apps/e2e/cypress/page_objects/projectUpdatesPage.js
- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js
- apps/web/src/server/applications/case/project-updates/project-updates-views.d.ts
- apps/web/src/server/applications/case/project-updates/project-updates.controller.js
- apps/web/src/server/applications/case/project-updates/project-updates.mapper.js
- apps/web/src/server/applications/case/project-updates/project-updates.router.js
- apps/web/src/server/applications/case/project-updates/project-updates.view-model.js
- apps/web/src/server/views/applications/case/project-updates/project-updates-details.njk
- packages/applications/lib/application/project-update.js
Add Welsh fields and design changes to project update preview
- Update the project update preview
- Update the unit tests and snapshots
- Update e2e tests for project update preview
https://pins-ds.atlassian.net/browse/APPLICS-31
> feat(applications/web): create welsh project update preview (APPLICS-31)

- azure-pipelines-regenerate-api-key.yml
> fix(api): add wildcard value to apikey generation pipeline

- apps/e2e/cypress/e2e/back-office-applications/projectUpdates.spec.js
Fix project updates e2e tests so they run with feature flags both on and off.
https://pins-ds.atlassian.net/browse/APPLICS-31
> feat(test/e2e): fix project updates e2e tests (APPLICS-31)

- apps/api/src/server/config/config.js
- apps/api/src/server/config/schema.js
- apps/api/src/server/utils/logger.js
- apps/web/environment/config.js
- apps/web/environment/schema.js
- apps/web/src/server/lib/logger.js
Relates to: https://pins-ds.atlassian.net/browse/APPLICS-601
> chore(applications): setup loggers to only pretty print in dev

- packages/feature-flags/src/static-feature-flags.js
Add `applic-625-custom-folders` to static flags.
[APPLICS-640](https://pins-ds.atlassian.net/browse/APPLICS-640)
[APPLICS-640]: https://pins-ds.atlassian.net/browse/APPLICS-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tooling): add applic-625-custom-folders to static flags

- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.router.js
- apps/web/src/server/applications/case/documentation/applications-documentation.validators.js
> feat(web): add validation for folder creation

- apps/api/src/server/applications/application/file-folders/folders.controller.js
- apps/api/src/server/applications/application/file-folders/folders.service.js
- apps/api/src/server/repositories/folder.repository.js
Prevent creating duplicate folders.
> feat(api/applications): prevent creating duplicate folders

- apps/api/src/server/applications/application/file-folders/folders.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.service.js
- apps/web/src/server/applications/case/documentation/applications-documentation.types.d.ts
- apps/web/src/server/views/applications/components/folder/folder.njk
> feat(web): add banner text for folder creation success

- apps/e2e/cypress/page_objects/uploadFiles.js
Update E2E test to look for `Create folder` rather than `Create Folder`.
> fix(e2e): 'Create Folder' -> 'Create folder'

- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
> feat(web): ensure create folder success does not persist

- apps/api/src/server/utils/mapping/map-folder-details.js
- apps/e2e/cypress/e2e/back-office-applications/folders.spec.js
- apps/e2e/cypress/page_objects/uploadFiles.js
- apps/web/src/server/applications/applications.types.d.ts
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.router.js
- apps/web/src/server/applications/case/documentation/applications-documentation.service.js
- apps/web/src/server/applications/case/documentation/applications-documentation.types.d.ts
- apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
- apps/web/src/server/lib/nunjucks-filters/url.js
- apps/web/src/server/views/applications/components/folder/folder-header.component.njk
- apps/web/src/server/views/applications/components/folder/folder-rename.njk
- apps/web/src/server/views/applications/components/folder/folder.njk
* fix(api/applications): include isCustom field in folder mapping function
* feat(web/applications): implement UI changes for folder renaming
- Point rename folder link to rename page
- Create folder rename page
- Perform request to rename folder
- Only render folder rename link on custom folders
- Update test snapshots
* test(e2e): add E2E tests for folder rename workflow
[APPLICS-626](https://pins-ds.atlassian.net/browse/APPLICS-626)
[APPLICS-626]: https://pins-ds.atlassian.net/browse/APPLICS-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature/applics 626 rename UI

- apps/web/src/server/views/applications/components/folder/folder-create.njk
- apps/web/src/server/views/applications/components/folder/folder-rename.njk
- apps/web/src/server/views/applications/components/textinput-form-component.njk
feat(web/applications): add a context label to the create rename fields
* feat(web/applications): add an optional 'context label' to text input
feat(web/applications): add a context label to the create rename fields
[APPLICS-749](https://pins-ds.atlassian.net/browse/APPLICS-749)
[APPLICS-749]: https://pins-ds.atlassian.net/browse/APPLICS-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): add an optional 'context label' to text input

- apps/api/src/server/migration/migration.controller.js
- apps/functions/applications-migration/common/handle-migration-with-response.js
- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
- apps/functions/applications-migration/common/migrators/folder-migration.js
- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
- apps/functions/applications-migration/common/migrators/nsip-project-migration.js
- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
- apps/functions/applications-migration/common/migrators/s51-advice-migration.js
- apps/functions/applications-migration/common/migrators/service-user-migration.js
Amends the migration Function to include errors from the API in its HTTP response, to assist troubleshooting a fault in the API when invoking the Function app.
Errors produced by the `ajv` library are return in the API response in JSON format. This response is parsed by the Function, and then included in its own response body.
Non-validation errors continue to be returned as a string containing the error message.
> feat(functions): function errors in response

- apps/web/src/server/views/applications/components/folder/folder-create.njk
Change 'Enter folder name' to 'Folder name'
[APPLICS-749](https://pins-ds.atlassian.net/browse/APPLICS-749)
[APPLICS-749]: https://pins-ds.atlassian.net/browse/APPLICS-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web/applications): change 'Enter folder name' to 'Folder name'

- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/views/applications/components/folder/folder-rename.njk
Prepopulate folder rename field with current name.
[APPLICS-771](https://pins-ds.atlassian.net/browse/APPLICS-771)
[APPLICS-771]: https://pins-ds.atlassian.net/browse/APPLICS-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): prepopulate with rename field with current name

- apps/api/src/server/applications/application/file-folders/__tests__/get-folder-details.test.js
- apps/api/src/server/utils/mapping/map-folder-details.js
- apps/web/src/server/applications/applications.types.d.ts
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.router.js
- apps/web/src/server/applications/case/documentation/applications-documentation.service.js
- apps/web/src/server/lib/nunjucks-filters/url.js
- apps/web/src/server/views/applications/components/folder/folder-create.njk
- apps/web/src/server/views/applications/components/folder/folder-delete.njk
- apps/web/src/server/views/applications/components/folder/folder-header.component.njk
- apps/web/src/server/views/applications/components/folder/folder-rename.njk
- apps/web/src/server/views/applications/layouts/folder-edit-property.layout.njk
- apps/web/src/styles/7-components/_button-group.scss
> Feature/applics 715 build UI delete folders

- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
- apps/web/src/server/applications/case/applications-case.locals.js
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
* feat(web/applications): add case overview link to start of breadcrumb
test(web/applications): update test snapshots
[APPLICS-694](https://pins-ds.atlassian.net/browse/APPLICS-694)
[APPLICS-694]: https://pins-ds.atlassian.net/browse/APPLICS-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web/applications): add case overview link to start of breadcrumb

- apps/e2e/cypress/e2e/back-office-applications/folders.spec.js
- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/uploadFiles.js
- apps/web/src/server/views/applications/components/folder/folder-delete.njk
> feat(e2e): add delete folder e2e test

- apps/e2e/cypress/page_objects/searchResultsPage.js
- apps/e2e/cypress/page_objects/uploadFiles.js
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/views/applications/case-documentation/search/document-search-results.njk
- Clean up some of the paths for finding elements
- Added an ID attribute to search documents results table to aid in e2e tests
- Use existing functions for the error summary
- Fixed snapshot
- Ran e2e tests flags on and off
https://pins-ds.atlassian.net/browse/APPLICS-780
> fix(test/e2e): fix some bugs in automated e2e tests (APPLICS-780)

- apps/web/src/styles/7-components/project-details-table.scss
Remove css attribute from class details__project-description.
Please note this is a complete reversal of what was done for ticket [BOAS-1680](https://pins-ds.atlassian.net.mcas.ms/browse/BOAS-1680)
https://pins-ds.atlassian.net/browse/APPLICS-759
[BOAS-1680]: https://pins-ds.atlassian.net/browse/BOAS-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(applications/web): overview page incorrect attribute property (APPLICS-759)

- apps/api/src/server/repositories/document-metadata.repository.js
- apps/e2e/cypress/page_objects/basePage.js
A problem was discovered when running the e2e smoke tests in relation to the original APPLICS-588 PR.
- Fix parameter when calling training case
- Fix e2e tests for smoke test
https://pins-ds.atlassian.net/browse/APPLICS-588
> fix(applications/web): fix is training bug and e2e smoke tests (APPLICS-588)

- docs/test-deployment.noop.js
This script is just an interactive runbook for running a TEST deployment.
* feat(tooling): create a do-nothing script for TEST deployments
This script is just an interactive runbook for running a TEST
deployment.
> feat(tooling): create a do-nothing script for TEST deployments

- apps/functions/applications-migration/common/validate-migration.js
- apps/functions/applications-migration/odw-curated-layer-healthcheck/function.json
- apps/functions/applications-migration/odw-curated-layer-healthcheck/index.js
- azure-pipelines-odw-curated-layer-healthcheck.yml
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-786
Adds ODW curated layer healthcheck function which retrieves data, applies the mappings and validates against the [data-model schema](https://github.com/Planning-Inspectorate/data-model). Its triggered via cron daily at 7am using the [Azure Trigger Function Action.](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-v1?view=azure-pipelines)
A successful response will be code `200` whereas a failed response will be code `400` or `500` with the errors returned by entity e.g.
```json
{
"project": [],
"serviceUsers": [],
"documents": [],
"s51Advice": [],
"representations": [],
"examTimetableItems": [
{
"instancePath": "",
"schemaPath": "#/required",
"keyword": "required",
"params": { …
```
> feat(functions): odw curated layer healthcheck 

- README.md
- Added troubleshooting section to README with instructions for installing dependencies
- Added Node.js section to README with Node installation instructions
[APPLICS 687](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-687): Review and update technical onboarding documentation
> docs: add installation instructions to readme

- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
- apps/functions/applications-migration/common/migrators/service-user-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-824
1. Service users and document metadata tables on ODW have a field called “sourceSystem”. We need to update our migration scripts for these entities to limit results to sourceSystem = “Horizon”
2. Service user on ODW uses caseId instead of caseReference. We need to update the migration scripts to firstly grab the caseId from the project table using caseReference, then query the service user table with the caseId.
> feat(functions): service user migration updates

- docs/test-deployment.noop.js
Updates to the Runbook script to aid developers deploying CBOS to Azure Test
> feat(tooling): runbook for cbos deploy to azure test - updates

- apps/web/src/server/applications/common/services/azure-project-team.js
Use the transitiveMembers url to find nested group members
https://pins-ds.atlassian.net/browse/APPLICS-833
> fix(web): get all entra group members (APPLICS-833)

- apps/functions/applications-migration/common/validate-migration.js
- apps/functions/applications-migration/odw-curated-layer-healthcheck/index.js
- azure-pipelines-odw-curated-layer-healthcheck.yml
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-786
> fix(functions): odw health check updates

- azure-pipelines-odw-curated-layer-healthcheck.yml
ODW healthcheck was running daily, but there is no need to run on weekends. Schedule updated to only run weekdays.
> chore(tooling): odw healthcheck cron schedule update

- README.md
- apps/api/README.md
- apps/web/README.md
* docs(tooling): expand Structure section of the README
docs(api): add a README file to document the app structure
docs(web): add a README file to document app structure
[APPLICS-688](https://pins-ds.atlassian.net/browse/APPLICS-688)
[APPLICS-688]: https://pins-ds.atlassian.net/browse/APPLICS-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(tooling): expand Structure section of the README

- apps/web/src/server/views/applications/case-timetable/components/timetable-item-summary.component.njk
- Changed the timetable item summary component to ignore the change links if submissions exist
https://pins-ds.atlassian.net/browse/APPLICS-782
> fix(web): examination timetable change options error (APPLICS-782)

- apps/web/src/server/applications/common/services/azure-project-team.js
> chore(web): log the full error when Azure AD fails

- apps/functions/applications-migration/common/handle-migration-with-response.js
- azure-pipelines-odw-curated-layer-healthcheck.yml
Quick changes to throw the migration errors correctly and to correctly handle the ODW health check pipeline (wasn't handling successful response correctly).
> fix(functions): migration minor fixes

- apps/web/src/server/applications/common/services/azure-project-team.js
- Added logging to determine exact nature of the "Error retrieving the Active Directory token"
https://pins-ds.atlassian.net/browse/APPLICS-849
> fix(web): temporary log of active directory token issue (APPLICS-849)

- README.md
- apps/api/.env.example
- apps/e2e/README.md
The following changes were made following discussion with Francesco Brenci:
- Updated README instructions regarding who to contact to request environment variable values.
- Added instructions to E2E README for adding additional JSON files.
- Updated environment variables in API .env.example file and E2E README.
[APPLICS 687](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-687): Review technical onboarding documentation
> docs: update environment variable instructions

- packages/feature-flags/src/static-feature-flags.js
Add a material changes feature flag to the static flags.
[APPLICS-859](https://pins-ds.atlassian.net/browse/APPLICS-859)
[APPLICS-859]: https://pins-ds.atlassian.net/browse/APPLICS-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(packages/feature-flags): add a material changes feature flag

- apps/functions/applications-migration/common/validate-migration.js
- apps/functions/applications-migration/odw-curated-layer-healthcheck/index.js
> fix(functions): validate migration examtimetable error

- apps/functions/applications-command-handlers/deadline-submission-command/index.js
- apps/functions/applications-command-handlers/deadline-submission-command/lib.js
Stringify timetableItem when including it in an error
> fix(functions): stringify timetableItem when including it in an error

- apps/functions/applications-command-handlers/deadline-submission-command/lib.js
Trim the incoming submissionType of whitespace
[APPLICS-847](https://pins-ds.atlassian.net/browse/APPLICS-847)
[APPLICS-847]: https://pins-ds.atlassian.net/browse/APPLICS-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(functions): trim the incoming submissionType of whitespace

- apps/functions/applications-command-handlers/deadline-submission-command/lib.js
> fix(functions): ensure no leading or trailing whitespace in lienItems

- apps/web/src/styles/7-components/project-update.scss
https://pins-ds.atlassian.net/browse/APPLICS-676?atlOrigin=eyJpIjoiZGM4Y2I0YmJmZTJkNDBiMjlhOTI1NzE1NzVjYjNkMWUiLCJwIjoiaiJ9
> fix(web): APPLICS-676 - Project updates text formatting

- apps/e2e/cypress/e2e/back-office-applications/editCase.spec.js
* feat(e2e): add tests for editing a case
feat(e2e): add case edit test cases for when the feature flags are off
[APPLICS-878](https://pins-ds.atlassian.net/browse/APPLICS-878)
[APPLICS-878]: https://pins-ds.atlassian.net/browse/APPLICS-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(e2e): add tests for editing a case

- apps/api/src/server/infrastructure/payload-builders/nsip-project.js
> fix(api): add isMaterialChange to the project schema object builder

- apps/api/src/server/applications/application/documents/__tests__/create-document.test.js
- apps/api/src/server/applications/application/documents/document.service.js
- packages/feature-flags/src/static-feature-flags.js
- Put all applics-861 functionality behind a new feature flag
https://pins-ds.atlassian.net/browse/APPLICS-861
> fix(api): create a feature flag for fo submissions (APPLICS-861)

- apps/e2e/cypress/e2e/back-office-applications/smokeTests.spec.js
Added missing caseRef declaration in smokeTests.spec
> fix(e2e): allow smoke tests spec to pass

- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
ODW have deployed examtimetable changes to ODW, this updates our migration scripts to update the table name and consume the new structure of data.
> feat(functions): examtimetable migration new format

- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
> fix(functions): correct migration examtimetable event type

- apps/api/src/server/applications/application/project-updates/project-updates.service.js
Allow project updates update events to be sent on every update.
Make sure duplicate publish and unpublish events are not sent.
API:
- fixed both logging the error BackOfficeAppError and the cause of the error by allowing "published" as a valid status
https://pins-ds.atlassian.net/browse/APPLICS-885
> fix(api): fix publish issue (APPLICS-885)

- azure-pipelines-deploy.yml
This should allow commits to be deployed by their tags.
[APPLICS-602](https://pins-ds.atlassian.net.mcas.ms/browse/APPLICS-602?McasTsid=20596&McasCtx=4)
[APPLICS-602]: https://pins-ds.atlassian.net/browse/APPLICS-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: change function deployment config to match release config

- apps/functions/applications-command-handlers/deadline-submission-command/back-office-api-client.js
- Add missing fromFrontOffice property to the post request when submitting a document for deadline submissions.
https://pins-ds.atlassian.net/browse/APPLICS-861
> fix(functions): add fromFrontOffice to deadline submissions (APPLICS-861)

- packages/event-client/src/service-bus-event-client.js
To prove the nsip-project-updates event is being sent with the correctly from back office, the logging is improved by making the additional properties visible within the log.
https://pins-ds.atlassian.net/browse/APPLICS-885
> fix(api): improve-service-bus-event-logging (APPLICS-885)

- apps/api/src/server/applications/application/project-updates/project-updates.service.js
Amend the project updates service to allow published project updates to send published events when changed 
https://pins-ds.atlassian.net/browse/APPLICS-885
> fix(api): allow published status to send event in project updates (APPLICS-885)

- apps/api/src/server/utils/mapping/map-case-details.js
- apps/functions/applications-migration/common/handle-migration-with-response.js
- apps/functions/applications-migration/exam-timetable-migration/index.js
- apps/functions/applications-migration/migrate-case/index.js
- apps/functions/applications-migration/nsip-document-migration/index.js
- apps/functions/applications-migration/nsip-project-migration/index.js
- apps/functions/applications-migration/nsip-representation-migration/index.js
- apps/functions/applications-migration/project-updates-migration/index.js
- apps/functions/applications-migration/s51-advice-migration/index.js
- apps/functions/applications-migration/service-user-migration/index.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-899
- Default migration behaviour changed to SKIP migration if the case already exists and is migrated to BO. This is to ensure we don't consume stale data from ODW when BO might have fresh data.
- Migration can be forced by passing a parameter `"migrationOverwrite": true"` to any requests which will force migration even if its already been migrated.
> feat(functions): add a check for migrationStatus

- apps/web/src/server/applications/common/services/azure-project-team.js
- Increase page limit to 1000 as suggested 
https://pins-ds.atlassian.net/browse/APPLICS-887
> fix(web): increase page limit when fetching team members (APPLICS-887)

- apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
- apps/functions/applications-migration/common/migrators/exam-timetable-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-919
Older PR: https://github.com/Planning-Inspectorate/back-office/pull/2644
- PR turns default date from 00:00 to 23:59
- Also removes events with type "Site Visit (Unaccompanied)" as they are not supposed to be migrated
> fix(functions): examtimetable migration default dates

- apps/e2e/cypress/page_objects/basePage.js
- apps/e2e/cypress/page_objects/documentPropertiesPage.js
Allow e2e tests to pass when Transcript is on a different line than expected.
> fix(e2e): fix e2e test failure in documents updates

- apps/web/src/server/applications/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap
- apps/web/src/server/applications/case/edit/case/__tests__/applications-edit-case.test.js
- apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap
- apps/web/src/server/applications/case/project-updates/project-updates.controller.js
- apps/web/src/server/applications/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap
- apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap
- apps/web/src/server/applications/create-new-case/case/__tests__/applications-create-case.test.js
- apps/web/src/server/views/applications/case/project-updates/project-updates-form.njk
- apps/web/src/server/views/applications/components/case-form/applicant/info-types.njk
- apps/web/src/server/views/applications/components/case-form/case-form-layout.njk
- apps/web/src/server/views/applications/components/case-form/case/regions.njk
- Add fieldset to the occurrences of the govukCheckboxes macro when it is the only question on a page to allow the rendering of the accessible legend tag
- Update web unit tests including snap shots
https://pins-ds.atlassian.net/browse/APPLICS-534
> feat(web): accessibility audit checkboxes (APPLICS-534)

- apps/web/src/server/views/applications/case/components/case-details-table.component.njk
https://pins-ds.atlassian.net/browse/APPLICS-966?atlOrigin=eyJpIjoiNjBiMDYzMDkwMmY0NGY0MGI0ZTQ3NGU3OWNkMzNmOTYiLCJwIjoiaiJ9
> fix(web): APPLICS-966 - Project overview description column width

- .github/workflows/deploy-c4-diagrams.yml
- .gitignore
- README.md
- architecture/index.md
- package.json
- workspace.dsl
Introduces [Structurizr](https://structurizr.com/) to capture the software architecture as code 
This is not ready to merge and this PR is raised just for visibility at this stage
The current implementation of the Applications BO architecture is incomplete and inaccurate and requires attention in at least the following areas:
- Modeling of entity change broadcasting to capture exactly how this happens 
- Description for file storage container
- Consider adding component level detail (e.g. what's inside the BO Web and BO API containers?)
- Consider if custom views would be benefical as the [Application FO have done](https://github.com/Planning-Inspectorate/applications-service/blob/main/workspace.dsl) or if it's acceptable to use dynamic views 
- General validation and adding of more …
> feat: introduce Structurizr architecture as code diagrams

- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
> feat(functions): migration doc table namechange

- apps/e2e/package.json
Reinstated Puppeteer as it's a required dependency of the Regression pack
https://pins-ds.atlassian.net/browse/APPLICS-850
> fix(e2e): restore puppeteer package (applics-850)

- apps/web/src/styles/7-components/filter-box.scss
Use CSS grid to keep filter checkboxes in their columns.
[APPLICS-305](https://pins-ds.atlassian.net/browse/APPLICS-305)
[APPLICS-305]: https://pins-ds.atlassian.net/browse/APPLICS-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): use CSS grid to keep filter checkboxes in their columns

- apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap
- apps/web/src/server/lib/nunjucks-filters/key-dates-property.js
- apps/web/src/server/views/applications/case-key-dates/key-dates-section.njk
- Remove the duplicate hint
- Do not display hint if not set (note a blank hint appears to have a minimum of 3 characters so this is taken into account)
https://pins-ds.atlassian.net/browse/APPLICS-927
> feat(web): manage key dates remove duplicate hint (APPLICS-872)

- apps/web/src/server/app/__tests__/app.locals.test.js
- apps/web/src/server/app/app.locals.js
- apps/web/src/server/app/app.router.js
- apps/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap
- apps/web/src/server/views/app/components/global-header.njk
- apps/web/src/server/views/app/layouts/app.layout.njk
- apps/web/src/server/views/applications/layouts/applications.layout.njk
- apps/web/src/styles/7-components/app-header.scss
https://pins-ds.atlassian.net/browse/APPLICS-963?atlOrigin=eyJpIjoiOTA5MWU4NDNhYjhmNGJiN2JlYWM4ZTkzYmE2NTBiYWMiLCJwIjoiaiJ9
> feat(web): APPLICS-963 - Training header attributes

- docs/test-deployment.noop.js
Updated Release docs file
https://pins-ds.atlassian.net/browse/APPLICS-673
> chore(tooling): update release docs (applics-673)

- apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
- apps/web/nodemon.json
- apps/web/package.json
- apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap
- apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.mappers.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.types.d.ts
- apps/web/src/server/lib/nunjucks-filters/date.js
- apps/web/testing/applications/fixtures/timetable-types.js
- package-lock.json
- package.json
- packages/examination-timetable-utils/index.d.ts
- packages/examination-timetable-utils/index.js
- packages/examination-timetable-utils/jsconfig.json
- packages/examination-timetable-utils/package.json
- packages/examination-timetable-utils/src/constants.js
- packages/examination-timetable-utils/src/map-examination-timetable-item-datetime.js
- packages/examination-timetable-utils/src/map-examination-timetable-item-datetime.test.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-994
> feat(api): exam timetable item date time handling in UTC

- apps/api/package.json
- apps/web/package.json
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js
- apps/web/src/server/applications/case/examination-timetable/applications-timetable.mappers.js
- packages/examination-timetable-utils/src/map-examination-timetable-item-datetime.js
Server time on deployed was UTC which was behaving differently to local environment. This PR handles the time currently and updates env variables to emulate UTC timezone when working locally.
> fix(api): examtimetable utc handling bug

- apps/api/package.json
Add cross-env cpmmand to api dev script
> fix(api): add cross-env command to dev script

- apps/api/package.json
> fix(api): add missing date-fns-tz package to package.json

- apps/web/environment/config.d.ts
- apps/web/environment/config.js
- apps/web/environment/schema.js
- apps/web/src/server/app/app.express.js
Ensure static assets have a non-zero max-age applied. To be improved in the future with immutable assets and cache-busting techniques.
> chore(web): add cache control max-age

- apps/api/Dockerfile
- apps/api/src/server/build-app.js
- apps/api/src/server/config/config.js
- apps/api/src/server/config/schema.js
- apps/web/Dockerfile
- apps/web/environment/base-config.js
- apps/web/environment/config.d.ts
- apps/web/environment/schema.js
- apps/web/src/server/app/app.controller.js
- azure-pipelines-build.yml
- azure-pipelines-deploy-release.yml
- azure-pipelines-deploy.yml
- packages/scripts/verify_commit_hash.sh
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-981 
This PR updates the existing `/health` endpoints in `web` and `api` to return the git commit hash. This will be added as an env variables through the build stage. On the release stage, we will call this endpoint and validate the hash matches the source hash. If not we will fail the deployment. 
Working Pipeline: https://dev.azure.com/planninginspectorate/back-office/_build/results?buildId=94865&view=logs&j=958678d9-e9b0-5d8b-c2bb-219cf8dbba62&t=32104dc2-1ef4-589c-25f8-c953b3c13546
> chore(tooling): verify git hash to deployment

- packages/scripts/verify_commit_hash.sh
> fix(api): increase sleep time during verify git hash

- azure-pipelines-deploy-release.yml
Reverting change until this is working correctly on test to avoid issues on prod release today
> chore(tooling): remove verify git hash from release pipeline

- apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
> fix(api): add bullet point character to examtt item migration regex

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
> fix(functions): add required properties to subscription migration

- docs/test-deployment.noop.js
Fix the non-working CBOS Deploy to Test runbook
> docs: fix broken deploy to test runbook

- apps/functions/applications-migration/migrate-case/index.js
Updates the `migrate-case` orchestrator with a new body paramter `isWelshCase` which when sent as `true` will also trigger the `project-updates` migration from NI. 
Documentation Update: 
- https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1699971104/Individual+Entity+Runbook
- https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1531576321/Case+Migration+Runbook
> feat(functions): update migrate-case to do projectupdate for welsh cases

- apps/functions/applications-migration/nsip-folder-creation/function.json
- apps/functions/applications-migration/nsip-folder-creation/index.js
> feat(functions): folder creation func for migration

- apps/api/package.json
- apps/api/src/database/schema.prisma
- apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
- apps/api/src/server/utils/__tests__/migration-dates.test.js
- apps/api/src/server/utils/migration-dates.js
- package-lock.json
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1091
Correclty handle the start and end times for certain event times when migrating examination timetable
> feat(functions): migrate event date times correctly

- apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
Last commit wasn't pushed in PR
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1091
Previous PR: https://github.com/Planning-Inspectorate/back-office/pull/2708
> feat(functions): migrate deadline types correctly

- apps/functions/applications-migration/common/migrators/s51-advice-migration.js
> fix(functions): dedeuplicate s51 attachment ids

- apps/api/src/server/migration/migrators/s51-advice-migrator.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1106
We had functionality to generate title but it was only being used for storing, and not for publishing to FO. This PR reuses the same functionality. We also move the firstName, lastName creation to a seperate util for reusability.
> fix(api): migration s51 advice correct title publish to FO

- apps/api/src/server/applications/application/documents/document.controller.js
- apps/api/src/server/applications/application/documents/document.validators.js
- apps/api/src/server/migration/migrators/nsip-document-migrator.js
- apps/functions/applications-background-jobs/publish-document/index.js
> fix(functions): send migration flag to publishing azure function

- apps/web/environment/base-config.js
- apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/views/applications/case-documentation/properties/tab-details.component.njk
- Updated interested party field content
- Updated styling to prevent text wrapping
- Updated snapshot
[APPLICS 1077](https://pins-ds.atlassian.net/browse/APPLICS-1077): Content update - interested party field
> feat(web): update interested party field content (applics-1077)

- apps/api/src/server/migration/migrators/nsip-exam-timetable-migrator.js
Ticket: https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-1119
> fix(functions): add condition for exam publishing during migration

- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
Ticket: https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-1113
> fix(api): odw representation status correctly formatted

- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-779
Fixing as per Chris's comment on 13/11/24
> fix(functions): correct original and redacted reps mapping logic

- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
> fix(functions): extra space in reps migration fallbackText

- apps/api/src/server/infrastructure/payload-builders/nsip-document.js
- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1125
- Converts empty space to null on doc migration function to avoid consumer validation
- Converts document stage correctly to pass publishing validation (change have been done in a mimimal way to avoid impacting existing non-migration code).
> fix(functions): migration publish docs

- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
> fix(functions): map empty originalRepresentation to empty string

- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
handle data with a single space - " " in the document origin and securityClassification fields from ODW
https://pins-ds.atlassian.net/browse/APPLICS-1135
> feat(functions): doc migration handle single space blank data (applics-1135)

- apps/api/src/server/migration/migrators/service-user-migrator.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1127
> feat(api): add contactMethod to migrated service users

- apps/api/src/server/migration/migrators/nsip-document-migrator.js
> fix(api): add a documentActivityLog for upload and published documents

- apps/functions/applications-migration/common/migrators/nsip-representation-migration.js
> fix(functions): fix use of trim on original and redacted reps

- apps/api/src/server/applications/application/file-folders/folders.service.js
> fix(api): custom folders to inherit parent stage

- azure-pipelines-deploy-release.yml
- azure-pipelines-deploy.yml
Disabling continuous deployment fore web.
Comparisons between 3.18.1 and 3.18.2 version: https://github.com/Planning-Inspectorate/common-pipeline-templates/compare/release/3.18.1...release/3.18.2
Ticket: https://pins-ds.atlassian.net/browse/DEV-273
> fix(tooling): updating pipeline version to 3.18.2 

- azure-pipelines-deploy.yml
This reverts commit 65310212150ed3b4e2a8c84367d88a3ede331667.
undo pipeline upgrade from 3.18.1 to 3.18.2 - as it may be causing run fails
> Revert "fix(tooling): updating pipeline version to 3.18.2"

- azure-pipelines-deploy.yml
Put back the pipeline version change
> chore(tooling): put back the pipeline version update

- apps/api/src/server/applications/application/documents/document.controller.js
- apps/api/src/server/applications/application/documents/document.service.js
- apps/api/src/server/migration/migrators/nsip-document-migrator.js
- apps/api/src/server/repositories/document.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1192
Functions create a new reference for migrated documents which do NOT already have a documentReference. The format will be {caseReference}-M-{documentGuid}. e.g. BC010001-M-3000001. CBOS UI will ignore these references when finding the latest document reference to generate (by incrementing) the next one.
> feat(api): create doc reference for migrated documents

- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
- apps/api/src/server/migration/migrators/s51-advice-migrator.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1202
> feat(api): publish reps attachments correctly on migration

- apps/e2e/cypress/e2e/back-office-applications/editCase.spec.js
- apps/web/src/server/applications/case/edit/case/applications-edit-case.controller.js
- apps/web/src/server/lib/nunjucks-globals/__tests__/build-case-information.test.js
- apps/web/src/server/lib/nunjucks-globals/build-case-information.js
- apps/web/src/server/views/applications/case/components/case-info-table.component.njk
- packages/feature-flags/src/static-feature-flags.js
- Removed static material changes feature flag
- Removed conditional logic related to the flag
- Updated unit test
- Updated e2e test
[APPLICS-978](https://pins-ds.atlassian.net/browse/APPLICS-978): Remove Feature Flag code for Material Changes
[APPLICS-978]: https://pins-ds.atlassian.net/browse/APPLICS-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(web): remove material changes feature flag logic (applics-978)

- apps/e2e/cypress/page_objects/representationPage.js
Amended the getMonth function to add 1 to the returned value, so that it cannot return 0. The value needs to be between 1 and 12 so that the numeric date can be entered into a form as part of the test.
[APPLICS-1228](https://pins-ds.atlassian.net/browse/APPLICS-1228): Fix Relevant Representation E2E Test
[APPLICS-1228]: https://pins-ds.atlassian.net/browse/APPLICS-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(e2e): fix relevant representations e2e test (applics-1228)

- apps/web/src/server/applications/case/representations/representation-details/redact-representation/__tests__/__snapshots__/redact-representation.test.js.snap
- apps/web/src/server/applications/case/representations/representation-details/redact-representation/__tests__/redact-representation.test.view-model.unit.test.js
- apps/web/src/server/applications/case/representations/representation-details/redact-representation/redact-representation.view-model.js
- apps/web/src/server/views/applications/representations/representation-details/redact-representation/redact-representation.njk
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1238
> fix(web): correct name on redact reps page

- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/views/applications/case-documentation/search/document-search-results.njk
- Added visually hidden text to the 'View' hyperlink on the document search results page.
- Regenerated the documentation snapshot.
[APPLICS-1175](https://pins-ds.atlassian.net/browse/APPLICS-1175): CBOS accessibility audit - 'View' hyperlink
[APPLICS-1175]: https://pins-ds.atlassian.net/browse/APPLICS-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(web): add visually hidden text to view hyperlinks (applics-1175)

- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
- apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap
- apps/web/src/server/views/applications/case-documentation/documentation-publish.njk
- apps/web/src/server/views/applications/case-project-team/project-team-list.njk
- apps/web/src/server/views/applications/case-s51/s51-publishing-queue.njk
- Added visually hidden text to all 'Remove' hyperlinks.
- Updated relevant snapshots.
[APPLICS-1173](https://pins-ds.atlassian.net/browse/APPLICS-1173): CBOS accessibility audit - 'Remove' hyperlinks
[APPLICS-1173]: https://pins-ds.atlassian.net/browse/APPLICS-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(web): add visually hidden text for remove hyperlinks (applics-1173)

- apps/api/src/server/applications/application/representations/attachment/__tests__/post-attachment.test.js
- apps/api/src/server/applications/application/representations/attachment/attachment.service.js
- apps/api/src/server/applications/application/representations/download/__tests__/map-rep-to-csv.test.js
- apps/api/src/server/applications/application/representations/download/utils/map-rep-to-csv.js
- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
- apps/api/src/server/repositories/document-metadata.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1216
Add default values to documentVersion when uploading representation attachments
> feat(api): added default values for reps attachment metadata

- azure-pipelines-build.yml
- azure-pipelines-deploy-release.yml
- azure-pipelines-deploy.yml
Switch to newer versions of the Build & Deploy pipelines, to use git commit hash for docker image tags
NOTE: this does not change the release pipeline
More [docs here](https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1719861253/App+Service+Deployments)
[Ticket](https://pins-ds.atlassian.net/browse/DEV-337)
> ci: use git commit hash for deployments

- apps/e2e/cypress/e2e/back-office-applications/documentProperties.spec.js
- Changed value being searched for in the browser from 'Interested Party number' to 'IP number'.
[APPLICS-1264](https://pins-ds.atlassian.net/browse/APPLICS-1264): Fix Document Properties E2E Test
- [ x I have double checked this work does not include any hardcoded secrets or passwords
[APPLICS-1264]: https://pins-ds.atlassian.net/browse/APPLICS-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(e2e): fix document properties e2e test (applics-1264)

- apps/web/src/server/applications/case/representations/representation-details/representation-status/representation-status-notes/__tests__/representation-status-notes.test.js
- apps/web/src/server/applications/case/representations/representation-details/representation-status/representation-status-notes/representation-status-notes.validators.js
- Updated validation error message for referred and invalid relevant reps changes status screens.
- Updated unit tests.
[APPLICS-1178](https://pins-ds.atlassian.net/browse/APPLICS-1178): CBOS accessibility audit - error summary update
[APPLICS-1178]: https://pins-ds.atlassian.net/browse/APPLICS-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(web): change error message for relevant reps status screens (applics-1178)

- apps/api/src/server/migration/migrators/nsip-document-migrator.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1265
Ensures if x version is unpublished when migrating then all versions below that version which are still incorrectly marked as published will be marked as unpublished.
> feat(api): unpublish previous published versions on migration

- apps/web/src/server/applications/case/project-team/__tests__/__snapshots__/applications-project-team.test.js.snap
- apps/web/src/server/views/applications/case-project-team/project-team-list.njk
- Added visually hidden text for 'Change role' hyperlinks.
- Regenerated the project team snapshot.
[APPLICS-1174](https://pins-ds.atlassian.net/browse/APPLICS-1174): CBOS accessibility - 'Change role' hyperlinks
[APPLICS-1174]: https://pins-ds.atlassian.net/browse/APPLICS-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(web): add visually hidden text for change role hyperlinks (applics-1174)

- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
Update field mapping used during migration of Representation entity
If a representation has a `representativeId`, then the representedType should be "AGENT"
APPLICS-1339
> fix(api): update field mapping for migrating reps from agent

- apps/api/src/server/migration/migrators/nsip-representation-migrator.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1202
> fix(api): rep attachment broadcast on migration

- apps/functions/applications-migration/common/migrators/nsip-document-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1375
> fix(functions): migration correct document publishedStatus

- apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1380
We were only doing sub migiration if project-updates existed. This PR ensures both are ran regardless.
> fix(functions): subscription migration run correctly

- .github/dependabot.yml
Enable dependabot package updates, weekly
> chore(tooling): enable dependabot version updates

- apps/api/src/server/applications/application/file-folders/__tests__/get-folder-details.test.js
- apps/api/src/server/applications/application/file-folders/folders.controller.js
- apps/api/src/server/applications/application/file-folders/folders.routes.js
- apps/api/src/server/applications/application/file-folders/folders.service.js
- apps/api/src/server/applications/application/file-folders/folders.validation.js
- apps/api/src/server/repositories/document.repository.js
- apps/api/src/server/swagger-output.json
- apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap
- apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js
- apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
- apps/web/src/server/applications/case/documentation/applications-documentation.service.js
- apps/web/src/server/applications/case/documentation/utils/table.js
- apps/web/src/server/views/applications/case-documentation/documentation-table.njk
- apps/web/src/server/views/applications/components/folder/folder.njk
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1229
- Adds document sorting (FE+API)
- Changed endpoint from POST to GET for consistency
> feat: sort documents in folder

- apps/web/environment/config.d.ts
- apps/web/environment/config.js
- apps/web/environment/schema.js
- apps/web/src/server/app/app.locals.js
- apps/web/src/server/app/app.router.js
- apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk
https://pins-ds.atlassian.net/browse/APPLICS-1405
Add warning to cases deemed to be sensitive, configurable via environmental variable/flag: `SENSITIVE_APPLICATION_CASE_REFERENCES`
> feat(web): sensitive cases warning text (applics-1405)

- apps/api/src/server/migration/migrators/migration-cleanup.controller.js
Fixes to the post case migration code to correct exam timetables and exam timetable folders:
- the code that tries to find a matching folder for an exam time used UTC to get the date to compare the folder name, but the folders are in locale time, eg BST for Summer dates.
- updating the folder to correctly set the displayOrder passed a string, should be a number
- updating the folder to correctly set isCustom passed a boolean false, should be a 0 (bitfield)
https://pins-ds.atlassian.net/browse/APPLICS-1482
> fix(api): correct exam folder bugs in migration cleanup (applics-1482)

- apps/api/src/server/migration/migrators/migration-cleanup.controller.js
Small fixes for migration clean up code - exam folders
- send displayOrder as a Number to the createFolder fn
- tweak and more output on the folder update call
https://pins-ds.atlassian.net/browse/APPLICS-1482
> fix(api): exam folder bugs in migration cleanup fix2 (applics-1482)

- apps/api/package.json
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js
- apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.service.js
- package-lock.json
- package.json
> fix(web): batch exam timetable retrieval

- infrastructure/.pre-commit-config.yaml
- infrastructure/.terraform.lock.hcl
- infrastructure/.tflint.hcl
- infrastructure/data.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/front-door.tf
- infrastructure/locals.tf
- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/pipelines/terraform-ci.yaml
- infrastructure/providers.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
> feat(infrastructure): add infra pipelines and frontdoor

- .github/dependabot.yml
> feat(infrastructure): adding in dependabot terraform weekly updates

- azure-pipelines-e2e-applications.yml
> fix(infrastructure): increasing timeout on the pipeline

- azure-pipelines-e2e-applications.yml
> feat(infrastructure): changing E2E VM Image to test pool

- apps/web/package.json
- package-lock.json
> fix(web): include @azure/ai-text-analytics in web package.json

- apps/web/src/server/applications/case/representations/representation-details/redact-representation/__tests__/__snapshots__/redact-representation.test.js.snap
- apps/web/src/server/views/applications/representations/representation-details/redact-representation/redact-representation.njk
> fix(web): update redaction js after design changes

- package-lock.json
- package.json
- packages/event-client/package.json
- packages/event-client/src/event-type.js
- packages/event-client/src/event-type.test.js
Use the data-model definition for message event type.
https://pins-ds.atlassian.net/browse/RDSD-146
> chore(packages/event-client): use the data-model enum values for message event types

- azure-pipelines-ci.yml
adding a condition to run commitlint only in branches and not in main branch
> fix(tooling): adding a condition for commitlint test
