Planning-Inspectorate/back-office

e2e-tests/cypress/cucumber-json/vo-landing-page.cucumber.json, e2e-tests/package-lock.json, package-lock.json, package.json
=> fix cypress

e2e-tests/package.json
fix cypress issue with package.json by running npm install
=> run npm install as change to package.json

docker-compose.yml, e2e-tests/cypress.json, e2e-tests/cypress/support/PageObjects/vo-landing-page-po.js, e2e-tests/cypress/support/PageObjects/vo-review-appeal-submission-page-po.js, package-lock.json, package.json, packages/api/package-lock.json, packages/web-app/package-lock.json, packages/web-app/package.json
as-3250
Amend ports for web app
=> fix(as-3250): amend ports

Makefile
as-3251
fix make install issue
=> fix(as-3251): fix make install

e2e-tests/cypress/integration/vo-e2e-journey.feature, e2e-tests/cypress/integration/vo-e2e-journey/vo-e2e-journey.js, e2e-tests/cypress/integration/vo-landing-page.feature, e2e-tests/cypress/integration/vo-landing-page/vo-landing-page.js, e2e-tests/cypress/integration/vo-review-appeal-submission-page.feature, e2e-tests/cypress/support/PageObjects/vo-e2e-journey-po.js, e2e-tests/package-lock.json, package.json
Write scenarios to cover the positive paths for the validation officer e2e journey
=> create feature file for validation officer e2e journey

e2e-tests/cypress/integration/vo-review-appeal-submission-page.feature, e2e-tests/cypress/integration/vo-review-appeal-submission-page/vo-review-appeal-submission-page.js, e2e-tests/cypress/plugins/index.js, e2e-tests/cypress/support/PageObjects/vo-review-appeal-submission-page-po.js, e2e-tests/cypress/support/index.js, e2e-tests/package-lock.json, e2e-tests/package.json
add file download tests.
Local is broken so unable to run the tests. Once this has been merged to master, I will create another branch and run the tests
=> test: add file download tests

packages/api/database/migrations/00017-amend-has-appeal-submission-table.js, packages/api/database/migrations/00018-amend-has-appeal-table.js, packages/api/database/migrations/00019-amend-appeal-link-table.js, packages/api/database/migrations/00020-amend-has-lpa-submission-table.js, packages/api/database/migrations/00021-amend-message-queue-table-.js, packages/api/src/models/has-appeal-submission.js, packages/api/src/models/has-appeal-submission.spec.js
as-3564
implement new migrations for sql changes
=> fix(as-3564): implement new migrations for sql changes

packages/api/database/migrations/00021-amend-message-queue-table-.js
fix(as-3565): fix sql message queue table
=> fix(as-3565): fix sql message queue table

packages/api/database/migrations/00013-create-has-appeal-table.js, packages/api/database/migrations/00016-create-message-queue-table.js, packages/api/database/migrations/00021-amend-message-queue-table-.js, packages/api/src/models/has-appeal-submission.js, packages/api/src/models/has-appeal-submission.spec.js, packages/api/test/data/hasAppealSubmissionDbRecord.js
fix(as-3564): sql migration tables
=> fix(as-3564): sql migration tables

packages/api/database/migrations/00022-amend-message-queue-table-as-2883.js
fix(as-2883): submitted appeals have status set to 'Appeal Received'
=> fix(as-2883): submitted appeals have status set to 'Appeal Received'

packages/web-app/src/controllers/questionnaire-already-reviewed.js, packages/web-app/src/controllers/questionnaire-check-and-confirm.js, packages/web-app/src/controllers/questionnaire-check-and-confirm.spec.js, packages/web-app/src/routes/index.js, packages/web-app/src/routes/index.spec.js
A pr to to revert URL's to agreed structure.
=> feat(as-3677): remove prefix from URL's

packages/api/database/migrations/00025-amend-message-queue-table-as-2506.js
set appeal type on appeal creation
=> fix(as-2506): set appeal type on appeal creation

packages/api/database/migrations/00026-create-group-access-table.js.js
create group access table for back office
=> fix(as-3605): create group table

packages/api/database/migrations/00027-create-group-user-table.js
feat(as-3605): back office group user table
=> feat(as-3605): back office group user table

packages/api/database/migrations/00028-create-group-lpa-table.js
feat(as-3605): create back office group lpa table
=> feat(as-3605): create back office group lpa table

packages/api/package.json
Corrected the start command as it's looking for a non-existent file and can't start the service.
=> fix(api): correct the start command of the api

packages/api/database/migrations/00029-create-group-access-table.js
feat(as-3605): create group access table for back office
=> feat(as-3605): create group access table for back office

packages/api/database/migrations/00030-amend-message-queue-table-create-guid.js
fix(as-3564): fix latestevent in message queue trigger
=> fix(as-3564): fix latestevent in message queue trigger

packages/api/database/migrations/00032-default-eventdatetime.js
fix(as-3605): populate eventdatetime in sql tables
=> fix(as-3605): populate eventdatetime in sql tables

packages/api/database/migrations/00033-amend appeal-data-view.js, packages/api/src/lib/db-wrapper.js
fix(as-3802): amend appeal data view
=> fix(as-3802): amend appeal data view

packages/api/database/migrations/00043-create-sp-view-appeal-search.js
fix(as-3680): creation of sp viewappealsearch
=> fix(as-3680): creation of sp viewappealsearch

packages/api/database/migrations/00050-amend-message-queue-trigger.js
fix(as-3802): amend messagequeue trigger
=> fix(as-3802): amend messagequeue trigger

docker-compose.yml, packages/api/database/migrations/00051-amend-sp-view-appeal-search.js, packages/api/src/controllers/appeal-search.js, packages/api/src/lib/db-wrapper.js, packages/api/src/routes/appeal-search.js, packages/api/src/routes/index.js
=> fix(as-3680): search appeal

packages/api/database/migrations/00052-amend-message-queue-trigger.js
fix(as-3680): fix duplicate data migration
=> fix(as-3680): fix duplicate data migration

packages/api/src/controllers/appeal-search.spec.js, packages/api/src/routes/appeal-search.spec.js, packages/api/test/data/appeal-search-db-record.js
=> fix(as-3680): jest tests api

e2e-tests/cypress/integration/validation-officer/vo-landing-page/vo-landing-page.js, e2e-tests/cypress/integration/validation-officer/vo-missing-or-wrong-check-confirm-page/vo-missing-or-wrong-check-confirm-page.js, e2e-tests/cypress/integration/validation-officer/vo-review-appeal-submission-page.feature, e2e-tests/cypress/integration/validation-officer/vo-review-appeal-submission-page/vo-review-appeal-submission-page.js, e2e-tests/cypress/integration/validation-officer/vo-valid-check-confirm-page.feature, e2e-tests/cypress/integration/validation-officer/vo-valid-check-confirm-page/vo-valid-check-confirm-page.js, e2e-tests/cypress/integration/validation-officer/vo-valid-review-complete/vo-valid-review-complete.js, e2e-tests/cypress/integration/validation-officer/vo-validappeal-description-of-development/vo-validappeal-description-of-development.js, e2e-tests/cypress/support/PageObjects/vo-landing-page-po.js, e2e-tests/cypress/support/PageObjects/vo-review-appeal-submission-page-po.js, e2e-tests/cypress/support/PageObjects/vo-valid-check-confirm-page-po.js, e2e-tests/cypress/support/PageObjects/vo-validappeal-description-of-development-po.js, e2e-tests/cypress/support/common/date-format.js, e2e-tests/cypress/support/db-queries/select-appeal-id-for-validation-officer-from-db.js
Validation Officer - update Valid outcome journey to retrieve data from SQL database
=> feat: update tests to use data from SQL database - Validation Officer

packages/api/database/migrations/00057-amend-date-time-stored-procedures.js
fix(as-3875): fix datetime on sql database
=> fix(as-3875): fix datetime on sql database

packages/web-app/src/controllers/review-questionnaire-submission.js
https://pins-ds.atlassian.net/browse/AS-4030
Fixed the issue where child element information is passed to next page while its parent is not checked
=> fix(as-4030): fix the issue - Remove redundant data

e2e-tests/cypress/integration/customer-support-team/cst-appeal-details.feature, e2e-tests/cypress/integration/customer-support-team/cst-appeal-details/cst-appeal-details.js, e2e-tests/cypress/integration/customer-support-team/cst-search-page.feature, e2e-tests/cypress/integration/customer-support-team/cst-search-page/cst-search-page.js, e2e-tests/cypress/support/PageObjects/cst-appeal-details-po.js, e2e-tests/cypress/support/db-queries/select-case-details-search-page.js, e2e-tests/cypress/support/db-queries/select-case-file-details.js
update existing tests for View Appeals CST journey
=> test: create and update existing tests for AS3607 and AS-3899

packages/api/api/openapi.yaml, packages/web-app/src/config/db-fields.js, packages/web-app/src/config/views.js, packages/web-app/src/controllers/appeal-details/case-officer.js, packages/web-app/src/controllers/appeal-details/case-officer.spec.js, packages/web-app/src/routes/appeal-details.js, packages/web-app/src/routes/appeal-details.spec.js, packages/web-app/src/routes/appeal-details/case-officer.js, packages/web-app/src/routes/appeal-details/case-officer.spec.js, packages/web-app/src/validation/appeal-details/case-officer-details.js, packages/web-app/src/validation/appeal-details/case-officer-details.spec.js, packages/web-app/src/views/appeal-details.njk, packages/web-app/src/views/appeal-details/case-officer.njk
=> feat(as-3615): case officer

e2e-tests/cypress/integration/customer-support-team/cst-appeal-details/cst-appeal-details.js, e2e-tests/cypress/integration/customer-support-team/cst-edit-name-email.feature, e2e-tests/cypress/integration/customer-support-team/cst-edit-name-email/cst-edit-name-email.js, e2e-tests/cypress/support/PageObjects/common-po.js, e2e-tests/cypress/support/PageObjects/cst-appeal-details-po.js, e2e-tests/cypress/support/PageObjects/cst-edit-name-email-po.js, e2e-tests/cypress/support/common/validate-name-email.js, e2e-tests/cypress/support/common/verify-error-message.js, e2e-tests/cypress/support/db-queries/select-case-details-from-appeallink.js
AS-3601 - Edit name and email
Write e2e tests for change name and email address
=> feat: write e2e tests for change name and email address

packages/api/database/migrations/00059-amend-has-appeal-table.js
Ticket
https://pins-ds.atlassian.net/browse/AS-4033
Description
Alter MissingOrWrongReasons column
=> feat(as-4033): update HasAppeal table schema

packages/web-app/src/controllers/questionnaire-check-and-confirm.js, packages/web-app/src/controllers/questionnaire-check-and-confirm.spec.js, packages/web-app/src/views/review-questionnaire-complete.njk
fix(as-4026): add confirmation of outcome
=> fix(as-4026): add confirmation of outcome

e2e-tests/cypress/integration/customer-support-team/cst-appeal-details/cst-appeal-details.js, e2e-tests/cypress/integration/customer-support-team/cst-edit-decision-date.feature, e2e-tests/cypress/integration/customer-support-team/cst-edit-decision-date/cst-edit-decision-date.js, e2e-tests/cypress/integration/customer-support-team/cst-edit-name-email/cst-edit-name-email.js, e2e-tests/cypress/integration/customer-support-team/cst-search-page.feature, e2e-tests/cypress/support/PageObjects/cst-appeal-details-po.js, e2e-tests/cypress/support/PageObjects/cst-edit-decision-date-po.js, e2e-tests/cypress/support/common/validate-day-month-year.js
add e2e tests for decision date- AS-3624 (Editing Application Decision date)
=> feat: add e2e tests for decision date in back office

e2e-tests/cypress/integration/customer-support-team/cst-edit-site-address.feature, e2e-tests/cypress/integration/customer-support-team/cst-edit-site-address/cst-edit-site-address.js, e2e-tests/cypress/support/PageObjects/cst-edit-site-address-po.js, e2e-tests/cypress/support/common/accessibility.js, e2e-tests/cypress/support/common/validate-site-address.js, e2e-tests/cypress/support/common/verify-error-message.js
AS-3616 - e2e tests for site address
=> feat: add e2e tests for site address

apps/web/.env.development, apps/web/src/server/app/validation/validation.service.js, apps/web/src/server/config/config.js, apps/web/src/server/lib/request.js, apps/web/src/server/views/validation/dashboard.njk
I have added an example for the validation flow on how the routing, controller, and service for calling the API should work.
=> Add api request libraries

apps/api/src/server/app.js, apps/api/src/server/app/home/home.test.js, apps/api/src/server/app/state_machine/household-appeal.machine.js, apps/api/src/server/app/state_machine/validate-appeal.test.js, apps/api/src/server/app/validation/validation.test.js, apps/api/src/server/swagger.js
Corrected the issues pointed by Lint in the Apps/api side
- [ √] Other (please explain in the description section above)
- [√ ] I have performed a self-review of my own code
- [√] I have double checked this work does not include any hardcoded secrets or passwords
- [ √] I have referenced the ticket number above
- [ √] I have provided a description of the ticket
=> BOCM-36 last review done

apps/api/package.json, apps/web/package.json, package-lock.json, package.json, packages/eslint-config/package.json, packages/planning-inspectorate-libs/package.json
Bumping all modules versions and updating the lock file.
=> chore: bump deps

apps/web/src/server/app/validation/validation.controller.js, apps/web/src/server/app/validation/validation.pipes.js, apps/web/src/server/app/validation/validation.route.js, apps/web/src/server/config/routes.js, apps/web/src/server/views/validation/check-and-confirm.njk, apps/web/src/server/views/validation/incomplete-appeal-outcome.njk, apps/web/src/server/views/validation/invalid-appeal-outcome.njk
=> BOCM-15 - Valid appeal journey

azure-pipelines.yml
=> BOCM-191 - adds sources directory bo azure pipeline

apps/api/prisma/seed.js
adds more appeal use cases to seed file
=> BOCM-193 - adds more new appeal cases in new and missing details state

apps/api/.env.development, apps/api/Dockerfile, apps/api/init.sh, apps/api/package.json, apps/api/src/server/app.js, apps/api/src/server/config/config.js, apps/api/ssh_setup.sh, apps/api/sshd_config, azure-pipelines.yml, docker-compose.yml, package-lock.json
=> BOCM-191 - adds latest tag to build

apps/web/src/server/app/validation/validation.config.js, apps/web/src/server/app/validation/validation.controller.js, apps/web/src/server/app/validation/validation.pipes.js, apps/web/src/server/app/validation/validation.route.js, apps/web/src/server/app/validation/validation.service.js, apps/web/src/server/config/routes.js, apps/web/src/server/views/app/404.njk, apps/web/src/server/views/app/error.njk, apps/web/src/server/views/validation/check-and-confirm.njk, apps/web/src/server/views/validation/invalid-appeal-outcome.njk, apps/web/src/server/views/validation/review-appeal-complete.njk, apps/web/src/server/views/validation/review-appeal.njk, apps/web/src/typings/express-session/index.d.ts
Missing pages for all 3 type of outcomes.
- https://pins-ds.atlassian.net/browse/BOCM-13
- https://pins-ds.atlassian.net/browse/BOCM-15
- https://pins-ds.atlassian.net/browse/BOCM-16
=> BOCM-15 - Valid appeal part 3

azure-web-pipeline.yml
=> adds web pipeline

apps/web/src/server/app/validation/validation.config.js, apps/web/src/server/app/validation/validation.controller.js, apps/web/src/server/app/validation/validation.pipes.js, apps/web/src/server/app/validation/validation.service.js, apps/web/src/server/views/validation/check-and-confirm.njk, apps/web/src/server/views/validation/incomplete-appeal-outcome.njk, apps/web/src/server/views/validation/invalid-appeal-outcome.njk, apps/web/src/typings/express-session/index.d.ts
Submit appeal outcome changes.
https://pins-ds.atlassian.net/browse/BOCM-13
=> BOCM-13 - Appeal data submit

apps/api/src/server/app/validation/validate-request.js, apps/api/src/server/app/validation/validation.appeal-validated.test.js, apps/api/src/server/app/validation/validation.controller.js
- [ √] Bug fix (non-breaking change which fixes an issue)
- [ √] I have performed a self-review of my own code
- [v] I have double checked this work does not include any hardcoded secrets or passwords
- [ √] I have referenced the ticket number above
- [ √] I have provided a description of the ticket
- [ √] I have included unit tests to cover any testable code changes
=> BOCM-213 info_missing chaged to incomplete and working

apps/api/src/server/app/repositories/validation-decision.repository.test.js, apps/api/src/server/app/validation/validate-request.js, apps/api/src/server/app/validation/validation.appeal-validated.test.js, apps/api/src/server/app/validation/validation.controller.js
BOCM-215
- [ √] Bug fix (non-breaking change which fixes an issue)
- [ √] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ √] Documentation update
- [√ ] I have performed a self-review of my own code
- [ √] I have double checked this work does not include any hardcoded secrets or passwords
- [√ ] I have made corresponding changes to the documentation
- [√ ] I have provided details on how I have tested my code
- [ √] I have referenced the ticket number above
- [ v] I have provided a description of the ticket
- [√ ] I have included unit tests to cover any testable code changes
=> BOCM-215 exchange of valid and incomplete reasons

apps/api/src/server/app/repositories/validation-decision.repository.js, apps/api/src/server/app/repositories/validation-decision.repository.test.js, apps/api/src/server/app/state-machine/household-appeal.machine.js, apps/api/src/server/app/validation/validate-request.js, apps/api/src/server/app/validation/validation.appeal-validated.test.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
fixes bug to accept noRightOfAppeal instead of noRightOfappeal for invalid appeal reason
=> fixes no right of appeal typo

apps/web/src/server/app/validation/validation.controller.js
Extends the change made to the 'Back' link for valid journeys to also cater for invalid and incomplete journeys.
https://pins-ds.atlassian.net/browse/BOCM-202
=> BOCM-202: derive back link based on validation journey

apps/api/src/server/app/validation/validate-request.js
=> Fixes bug for inflammatory typo

apps/api/src/server/app/validation/validate-request.js, apps/api/src/server/app/validation/validation.submit-validation-decision.test.js
further fix for mismatched appeal validation outcome reason keys
N/A
=> further fix for mismatched appeal validation outcome reason keys

apps/api/src/server/app/state-machine/household-appeal.machine.test.js, apps/api/src/server/app/state-machine/inspector-states.js, apps/api/src/server/app/state-machine/inspector.actions.js
Appeal transitions for appeal from 'decision_due' to 'appeal_decided'
=> BOCM-106 - adds transition for appeal decision being made by inspector

apps/api/prisma/schema.prisma
=> fixes prisma schema bug

apps/api/src/server/app/validation/validation.controller.js
Fix 500 issue on /validation/lpa-list
https://pins-ds.atlassian.net/browse/BOCM-346
=> BOCM-346: fix issue with 500 status on /validation/lpa-list

apps/api/src/server/app/validation/validation.get-lpa-list.test.js
=> BOCM-346: fix failing test

apps/api/src/server/app/case-officer/case-officer-review.js, apps/web/src/server/app/lpa/lpa-session.service.js, apps/web/src/server/app/lpa/lpa.config.js, apps/web/src/server/app/lpa/lpa.controller.js, apps/web/src/server/app/lpa/lpa.guards.js, apps/web/src/server/app/lpa/lpa.pipes.js, apps/web/src/server/app/lpa/lpa.router.js, apps/web/src/server/app/lpa/lpa.service.js, apps/web/src/server/lib/nunjucks-filters/ends-with.js, apps/web/src/server/lib/nunjucks-filters/index.js, apps/web/src/server/views/lpa/check-and-confirm.njk, apps/web/src/server/views/lpa/review-questionnaire.njk
- Integrating case officer review outcome POST with API endpoint
- Refactoring to bring LPA code in line with new patterns and conventions introduced since work on this domain began (+ associated updates to templates
N/A
=> LPA code refactoring + endpoint integration

apps/web/src/server/app/inspector/inspector-session.service.js, apps/web/src/server/app/inspector/inspector.controller.js, apps/web/src/server/app/inspector/inspector.pipes.js, apps/web/src/server/views/inspector/components/appeal-table.component.njk, apps/web/src/server/views/inspector/dashboard.njk
https://pins-ds.atlassian.net/browse/BOCM-127
=> BOCM-127: (inspector) add 'NEW' status to dashboard for recently assigned appeals

apps/api/prisma/seed.js, apps/api/src/server/app/case-officer/case-officer.controller.js, apps/api/src/server/app/case-officer/case-officer.get-appeals.test.js, apps/api/src/server/swagger-output.json
- [√ ] Bug fix (non-breaking change which fixes an issue)
- [ √] New feature (non-breaking change which adds functionality)
- [√ ] Documentation update
- [√ ] I have performed a self-review of my own code
- [√ ] I have double checked this work does not include any hardcoded secrets or passwords
- [√ ] I have made corresponding changes to the documentation
- [√ ] I have provided details on how I have tested my code
- [√ ] I have referenced the ticket number above
- [√ ] I have provided a description of the ticket
- [√ ] I have included unit tests to cover any testable code changes
=> BOCM-357 seed for incomplete & overdue appeals added

apps/web/src/server/views/lpa/dashboard.njk
https://github.com/Planning-Inspectorate/back-office/tree/BOCM-360
=> BOCM-360: fix info box message display in lpa domain

apps/web/src/server/app/lpa/lpa.service.js
=> fix incorrect status within web/lpa

apps/api/src/server/app/case-officer/case-officer.controller.js
bug fix to allow case officer to see incomplete appeals
=> fix to allow case officer to see appeals with incomplete questionnaire

apps/web/src/server/views/lpa/review-questionnaire.njk
https://pins-ds.atlassian.net/browse/BOCM-277
=> BOCM-383: fix missing/incorrect labels on lpa dashboard

.gitignore, apps/web/src/server/views/app/components/info-box.njk, apps/web/src/server/views/inspector/dashboard.njk, apps/web/src/server/views/lpa/dashboard.njk, apps/web/src/server/views/validation/dashboard.njk
=> fix info-box file case

apps/api/src/server/app/case-officer/appeal-formatter.js, apps/api/src/server/app/case-officer/case-officer.controller.js, apps/api/src/server/app/utils/review-questionnaire-formatter.js
https://pins-ds.atlassian.net/browse/BOCM-218
=> BOCM-218: add reviewQuestionnaire details to case-officer appeal response

apps/api/src/server/app.js, apps/api/src/server/app/case-officer/appeal-formatter.js, apps/api/src/server/app/case-officer/case-officer.confirm.test.js, apps/api/src/server/app/case-officer/case-officer.get-appeal-details.test.js, apps/api/src/server/app/inspector/__tests__/issue-decision.test.js, apps/api/src/server/app/inspector/inspector.routes.js, apps/api/src/server/app/inspector/inspector.service.js, apps/api/src/server/app/inspector/inspector.validators.js, apps/api/src/server/app/middleware/error-handler.js, apps/api/src/server/app/state-machine/household-appeal.machine.js
Add explicit exception to failed state transitions, and accompanying middleware.
=> add transition state error handler

apps/api/src/server/app/validation/validation.routes.js
=> BOCM-396: remove special characters restriction on appellant name

apps/web/src/server/app/validation/validation.pipes.js
Fix for planning application reference validaation.
https://pins-ds.atlassian.net/browse/BOCM-421
=> BOCM-421: increase character limit when validating planning application reference

apps/api/prisma/seed.js
- [√ ] Other (please explain in the description section above)
- [√ ] I have performed a self-review of my own code
- [√ ] I have double checked this work does not include any hardcoded secrets or passwords
- [√ ] I have referenced the ticket number above
- [√ ] I have provided a description of the ticket
=> BOCM-424 added seeding for appealsReadyForConfirmationFromCaseOfficer

apps/api/package.json, package-lock.json, packages/express/package.json, packages/platform/package.json
=> update workspace dependencies

apps/web/src/server/views/lpa/questionnaire.njk
=> fix planning application reference for lpa

apps/api/src/server/app/inspector/__tests__/get-appeal-details.test.js, apps/api/src/server/app/inspector/appeal-formatter.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
=> BOCM-277 - adds appeal status to response

apps/api/src/server/app/case-officer/__tests__/case-officer.confirm.test.js, apps/api/src/server/app/case-officer/__tests__/case-officer.get-appeal-details.test.js, apps/api/src/server/app/inspector/inspector.validators.js, apps/api/src/server/app/middleware/async-handler.js, apps/api/src/server/app/middleware/validate-appeal-status.js, apps/api/src/server/app/utils/array-of-statuses-contains-string.js, apps/api/src/server/app/validation/__tests__/validation.get-appeal-details.test.js, apps/api/src/server/app/validation/__tests__/validation.submit-validation-decision.test.js, apps/api/src/server/app/validation/validation.routes.js, apps/api/src/server/app/validation/validation.validators.js, apps/web/src/server/app/validation/validation.guards.js, apps/web/src/server/app/validation/validation.router.js, apps/web/src/server/app/validation/validation.service.js, apps/web/src/server/views/validation/appeal-error.njk, packages/appeals/types/appeal.d.ts
https://pins-ds.atlassian.net/browse/BOCM-400
=> BOCM-400: add appeal status error page to validation

apps/api/src/server/app/case-officer/__tests__/case-officer.confirm.test.js, apps/api/src/server/app/case-officer/__tests__/case-officer.get-appeal-details.test.js, apps/api/src/server/app/inspector/__tests__/inspector.assign-appeals.test.js, apps/api/src/server/app/inspector/inspector.controller.js, apps/api/src/server/app/repositories/appeal.repository.js, apps/api/src/server/app/validation/__tests__/validation.get-appeal-details.test.js, apps/api/src/server/app/validation/__tests__/validation.submit-validation-decision.test.js, apps/api/src/server/app/validation/__tests__/validation.update-appeal.test.js
=> BOCM-277 - adds site visit data to response for appeal details

apps/api/src/server/app/repositories/appeal.repository.js
fixes finding appeals for case officer to view
=> BOCM-437 - fixes finding appeals that are incomplete

apps/api/src/server/app/inspector/inspector.controller.js
bug fix for get appeal details
=> fixes get appeal details for inspector

apps/web/src/server/app/lpa/lpa.pipes.js, apps/web/src/server/views/inspector/components/appeal-evidence.component.njk, apps/web/src/server/views/lpa/questionnaire-confirmation.njk
Bug fixes identified on dev
https://pins-ds.atlassian.net/browse/BOCM-431
https://pins-ds.atlassian.net/browse/BOCM-440
=> BOCM-431 / BOCM-440

apps/api/prisma/migrations/20220421140955_makes_appeal_type_optional/migration.sql, apps/api/prisma/schema.prisma
=> BOCM-450 - makes appeal type optional

apps/web/src/server/app/inspector/inspector.controller.js, apps/web/src/server/app/inspector/inspector.service.js, apps/web/src/server/views/inspector/assign-appeals-error.njk, apps/web/src/server/views/inspector/assign-appeals-success.njk, apps/web/src/server/views/inspector/components/appeal-table.component.njk
Finalise tickets based on api endpoint becoming available.
https://pins-ds.atlassian.net/browse/BOCM-192
https://pins-ds.atlassian.net/browse/BOCM-376
=> BOCM-192 – integrate inspector available appeals with api

apps/api/pipelines/azure-pipelines-db-seed.yml
Reverts Planning-Inspectorate/back-office#292
=> Revert "Update azure-pipelines-db-seed.yml for Azure Pipelines"

apps/api/prisma/seed.js
=> tries to fix seeding issues

apps/web/package.json, apps/web/src/server/app/app.express.js, apps/web/src/server/views/app/includes/csrf.njk, apps/web/src/server/views/inspector/assign-appeals.njk, apps/web/src/server/views/inspector/book-site-visit-confirmation.njk, apps/web/src/server/views/inspector/book-site-visit.njk, apps/web/src/server/views/inspector/issue-decision-confirmation.njk, apps/web/src/server/views/inspector/issue-decision.njk, apps/web/src/server/views/lpa/appeal-documents.njk, apps/web/src/server/views/lpa/edit-listed-building-description.njk, apps/web/src/server/views/lpa/questionnaire-confirmation.njk, apps/web/src/server/views/lpa/questionnaire-incomplete.njk, apps/web/src/server/views/lpa/questionnaire.njk, apps/web/src/server/views/validation/appeal-details.njk, apps/web/src/server/views/validation/appeal-documents.njk, apps/web/src/server/views/validation/edit-appeal-site.njk, apps/web/src/server/views/validation/edit-appellant-name.njk, apps/web/src/server/views/validation/edit-local-planning-department.njk, apps/web/src/server/views/validation/edit-planning-application-reference.njk, apps/web/src/server/views/validation/outcome-incomplete-confirmation.njk, apps/web/src/server/views/validation/outcome-incomplete.njk, apps/web/src/server/views/validation/outcome-invalid-confirmation.njk, apps/web/src/server/views/validation/outcome-invalid.njk, apps/web/src/server/views/validation/outcome-valid-confirmation.njk, apps/web/src/server/views/validation/outcome-valid.njk, package-lock.json
Add csrf protection to web.
https://pins-ds.atlassian.net/browse/BOCM-474
=> BOCM-474: add csrf prevention to web

README.md, apps/web/.env.development, apps/web/.env.production, apps/web/src/server/app/app.express.js, apps/web/src/server/app/auth/auth.local.js, apps/web/src/server/config/config.js
=> add support for running locally without authentication

package-lock.json, packages/platform/package.json
=> Fix the missing @azure/msal-common

apps/web/Dockerfile
=> fix: patch docker file to remove .git folder

apps/web/Dockerfile, package-lock.json, package.json
=> Fix turbo pipeline git hash issue

apps/web/src/server/app/app.express.js
=> Disable csurf

apps/web/src/server/app/app.express.js
=> Enable csurf

apps/api/pipelines/azure-pipelines-build.yml, apps/api/pipelines/azure-pipelines-release.yml, apps/web/pipelines/azure-pipelines-build.yml, apps/web/pipelines/azure-pipelines-release.yml
Pin the version of the pipeline templates so changes in the repo do not affect pipelines.
Pipelines running and showing the source for the templates as the specified tag - https://dev.azure.com/planninginspectorate/back-office/_build/results?buildId=28159&view=results
N/A
=> Pin version of pipeline templates

apps/web/src/server/__tests__/validation.test.js, apps/web/src/server/app/app.express.js, apps/web/src/server/app/inspector/inspector.guards.js, apps/web/src/server/app/inspector/inspector.router.js, apps/web/src/server/app/inspector/inspector.service.js, apps/web/src/server/app/lpa/lpa.controller.js, apps/web/src/server/app/lpa/lpa.filters.js, apps/web/src/server/app/lpa/lpa.guards.js, apps/web/src/server/app/lpa/lpa.pipes.js, apps/web/src/server/app/lpa/lpa.router.js, apps/web/src/server/app/lpa/lpa.service.js, apps/web/src/server/app/validation/validation.guards.js, apps/web/src/server/app/validation/validation.router.js, apps/web/src/server/app/validation/validation.service.js, apps/web/src/server/config/locals.js, apps/web/src/server/views/app/components/file-uploader.njk, apps/web/src/server/views/inspector/appeal-details.njk, apps/web/src/server/views/lpa/appeal-documents.njk, apps/web/src/server/views/lpa/dashboard.njk, apps/web/src/server/views/lpa/fpa-documents-success.njk, apps/web/src/server/views/lpa/fpa-documents.njk, apps/web/src/server/views/validation/appeal-documents.njk, packages/appeals/types/inspector.d.ts, packages/appeals/types/lpa.d.ts, packages/platform/index.d.ts, packages/platform/index.js, packages/platform/util/formdata.js
Integration of web app with full planning appeal.
Also minor refactoring to inspector and validation domains.
https://pins-ds.atlassian.net/browse/BOCM-324
https://pins-ds.atlassian.net/browse/BOCM-326
https://pins-ds.atlassian.net/browse/BOCM-333
=> integrate FPA into case-officer & inspector domains

apps/web/src/server/views/inspector/dashboard.njk
=> BOCM-482 - Add some margin above get more appeals button

apps/web/src/server/app/inspector/inspector.pipes.js
=> Update inspector paths page title

apps/web/src/server/__tests__/__snapshots__/validation.test.js.snap, apps/web/src/server/views/app/components/info-box.njk, apps/web/src/styles/7-components/InfoBox/InfoBox.scss, apps/web/src/styles/7-components/_autocomplete.scss, apps/web/src/styles/7-components/_masthead.scss, apps/web/src/styles/7-components/_related.scss, apps/web/src/styles/7-components/_table.scss
=> Update table col sizes to match designs

apps/api/src/server/app/inspector/__tests__/get-appeals.test.js, apps/api/src/server/app/repositories/appeal.repository.js
- fixes bug when searching for appeals assigned to user
=> BOCM-483 - filters appeals based on azure reference instead of id

apps/web/index.js, apps/web/src/server/__tests__/__snapshots__/lpa.test.js.snap, apps/web/src/server/__tests__/__snapshots__/validation.test.js.snap, apps/web/src/server/__tests__/lpa.test.js, apps/web/src/server/__tests__/validation.test.js, apps/web/src/server/app/lpa/lpa.guards.js, apps/web/src/server/app/lpa/lpa.pipes.js, apps/web/src/server/app/lpa/lpa.router.js, apps/web/src/server/views/lpa/questionnaire-incomplete.njk, apps/web/src/server/views/lpa/questionnaire.njk, apps/web/testing/factory/lpa-questionnaire.js, apps/web/testing/factory/review-questionnaire.js, apps/web/testing/fixtures/case-officer.js, apps/web/testing/fixtures/validation.js, apps/web/testing/formatters/appeal.js, apps/web/testing/index.js, packages/appeals/types/lpa.d.ts
Add integration tests for case officer domain.
https://pins-ds.atlassian.net/browse/BOCM-484
=> add lpa integration tests to web

apps/web/.env.development, apps/web/.env.test, apps/web/.eslintrc.cjs, apps/web/environment/config.d.ts, apps/web/environment/config.js, apps/web/environment/schema.js, apps/web/package.json, apps/web/scripts/bundle-js.js, apps/web/scripts/compile-css.js, apps/web/src/server/app/app.controller.js, apps/web/src/server/app/app.express.js, apps/web/src/server/app/app.router.js, apps/web/src/server/app/auth/auth.controller.js, apps/web/src/server/app/auth/auth.local.js, apps/web/src/server/app/routes.js, apps/web/src/server/config/locals.js, apps/web/src/server/config/session.js, apps/web/src/server/lib/nunjucks-filters/strip-query-parameters.js, apps/web/src/server/lib/request.js, apps/web/src/server/lib/sso.js, apps/web/src/server/server.js, package-lock.json
=> add joi environment schema checking

apps/api/src/server/config/config.js, apps/api/src/server/config/schema.js
=> fixes database_url env var parsing to config

apps/api/package.json, apps/web/src/server/config/locals.js, package.json, turbo.json
=> apply fixes to linting process

apps/web/src/server/lib/msal.js
=> build: loosen requirements when deriving msal redirectUri

apps/web/src/server/lib/msal.js
=> chore(web): restore original MSAL redirectUri implementation

apps/web/environment/config.js, apps/web/environment/schema.js, apps/web/src/server/lib/msal.js
=> chore(web): refactor msal redirectUri derivation

apps/web/.env.test, azure-pipelines-build.yml
=> ci: block merges based on failed checks

apps/api/pipelines/azure-pipelines-build.yml, apps/api/pipelines/azure-pipelines-db-seed.yml, apps/api/pipelines/azure-pipelines-release.yml, apps/web/pipelines/azure-pipelines-build.yml, apps/web/pipelines/azure-pipelines-release.yml, azure-pipelines-build.yml
Update common pipeline templates version reference to 2.5.2 to make use of fixed Key Vault secret retrieval step.
N/A
=> Fix Key Vault secret retrieval 

apps/web/src/server/lib/msal.js
=> build: set azure redirect_uri on every request

apps/api/prisma/seed.js
=> fix(api): fix database seeding (BOAS-118)

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/__tests__/applications.test.js, apps/web/src/server/applications/applications-session.service.js, apps/web/src/server/applications/applications.filters.js, apps/web/src/server/applications/applications.guards.js, apps/web/src/server/applications/applications.locals.js, apps/web/src/server/applications/applications.router.js, apps/web/src/server/applications/create-new/applications-create-new.controller.js, apps/web/src/server/applications/create-new/applications-create-new.guards.js, apps/web/src/server/applications/create-new/applications-create-new.router.js, apps/web/src/server/applications/search/applications-search.controller.js, apps/web/src/server/applications/search/applications-search.types.d.ts, apps/web/src/server/views/applications/components/application-search.component.njk, apps/web/src/server/views/applications/create-new.njk, apps/web/src/server/views/applications/dashboard.njk, apps/web/src/server/views/applications/search-results.njk, apps/web/src/styles/7-components/DashboardBox/DashboardBox.scss
1. New link in the dashboard page that goes to the "create-new-case" page (+ some custom css for styling the link). The button is only visible to officers and admin-officers
2. "create-new-case" page created with a blank template. Page is only visible to officers and admin-officers
3. new directory in the applications domain named "create-new". At the moment this is highly redudant as the whole scope contains no more than 2 functions. In the future it should become more meaningful.
4. new Nunjuck filter that maps the URLs, including the new "create-new-case' page.
Also contains:
- refactoring of a pre-existing filter not related with the button or the new-case page. It was moved from the registerLocal function to the more appropriate registerFilter.
- since now we have the url filter, it …
=> feat(web/applications): controller and view for create-new-case button

apps/api/prisma/migrations/20220628100706_make_sector_and_subsector_names_unique/migration.sql, apps/api/prisma/schema.prisma, apps/api/prisma/seed-samples.js, apps/api/prisma/seed.js
- adds more applications seeds
- adds sectors and sub-sectors seeds
- deletes all sectors, sub-sectors and applications before seeding afresh
- makes sector and sub-sector names unique
=> chore(api/applications): adding more applications seeds (BOAS-163)

apps/api/prisma/migrations/20220628104552_creates_regions_table/migration.sql, apps/api/prisma/schema.d.ts, apps/api/prisma/schema.prisma, apps/api/prisma/seed-samples.js, apps/api/prisma/seed.js, apps/api/src/server/applications/applications.routes.js, apps/api/src/server/applications/region/__tests__/get-regions.test.js, apps/api/src/server/applications/region/region.controller.js, apps/api/src/server/applications/region/region.routes.js, apps/api/src/server/repositories/region.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/api/src/server/utils/mapping/map-region.js
- creates new endpoint to get all regions
- seeds database with regions
=> feat(api/applications): adds endpoint to get all regions (BOAS-136)

apps/api/.env.test, package.json
=> test(api): enables running tests when building

azure-pipelines-build.yml, azure-pipelines-deploy.yml, azure-pipelines-release.yml
- Restores DB migrations in deploy and release pipeline
- Make sure all apps build on `main` branch
=> ci: restore migrations in pipeline

apps/api/src/server/applications/applications.routes.js, apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/create/__tests__/__snapshots__/applications-create.test.js.snap, apps/web/src/server/applications/create/__tests__/applications-create.test.js, apps/web/src/server/applications/create/applications-create.controller.js, apps/web/src/server/applications/create/applications-create.router.js, apps/web/src/server/applications/create/applications-create.service.js, apps/web/src/server/applications/create/applications-create.types.d.ts, apps/web/src/server/applications/create/applications-create.validators.js, apps/web/src/server/views/applications/create/_region.njk, apps/web/src/server/views/applications/create/_sector.njk, apps/web/src/server/views/applications/create/_sub-sector.njk, apps/web/src/server/views/applications/create/_zoom-level.njk, apps/web/testing/applications/factory/application.js, apps/web/testing/applications/factory/region.js, apps/web/testing/applications/factory/sector.js, apps/web/testing/applications/factory/util.js, apps/web/testing/applications/fixtures/regions.js
- View, controller and validator for regions page
- Service for the regions API
- Tests for the regions page
Also includes:
- a blank template for the zoom-level page (for testing)
- a fixture function for test descriptions
https://pins-ds.atlassian.net/browse/BOAS-174
=> feat(web/applications): create regions page (boas-174)

apps/api/prisma/seed-samples.js
- adds railways sub-sector to seed data
=> fix(api/applications): adds new railsways subsector (BOAS-183)

apps/web/src/server/applications/create/__tests__/__snapshots__/applications-create.test.js.snap, apps/web/src/server/applications/create/__tests__/applications-create.test.js, apps/web/src/server/applications/create/applications-create.controller.js, apps/web/src/server/applications/create/applications-create.router.js, apps/web/src/server/applications/create/applications-create.types.d.ts, apps/web/src/server/applications/create/applications-create.validators.js, apps/web/src/server/views/applications/create/_region.njk, apps/web/src/server/views/applications/create/_sector.njk, apps/web/src/server/views/applications/create/_sub-sector.njk, apps/web/src/server/views/applications/create/_team-email.njk
- template, controller and validator for the team email page
- tests
also includes:
- a bug fix for the regions page
- changes in the text of the errors for the whole create-new-case form
https://pins-ds.atlassian.net/browse/BOAS-134
=> feat(web/applications): case team email page (boas-134)

apps/api/prisma/seed.js
updating seeding code to add application title and description, and good reference (BOAS-92)
=> feat(api/applications): updating seeding code to add application fields

azure-pipelines-release.yml
- Stop each job in release pipeline from skipping due to incorrect dependency format
=> ci: fix dependency reference in release pipeline

apps/api/prisma/migrations/20220630142155_migrate_schema_to_use_cases/migration.sql, apps/api/prisma/schema.prisma
- fixing migration, making null values for sub-sector and region allowed
=> fix(api): fixes not null restriction in migration

azure-pipelines-build.yml, azure-pipelines-db-seed.yml, azure-pipelines-deploy.yml, azure-pipelines-release.yml, azure-pipelines-variables.yml
- Bump templates version to enable git tags on the `main` branch so release pipeline can be run from a point in time
=> ci: bump templates version and re-enable git tagging on main branch

package.json
=> ci: allow releases from release/* branches

azure-pipelines-build.yml
=> ci: skip commitlint on release branches

apps/api/src/server/config/config.js, apps/web/.env.test, apps/web/src/server/app/app.express.js, apps/web/src/server/applications/applications.guards.js, apps/web/src/server/applications/create/applications-create.guards.js, apps/web/src/server/applications/create/applications-create.locals.js, apps/web/src/server/lib/logger.js, apps/web/src/server/lib/request.js, apps/web/src/server/views/applications/create/case/_zoom-level.njk, packages/platform/http/hooks.js
- removed too detailed logs (req parameters, complete response body)
- added relevant information logs on guards, errors from API and generic errors from the web-app
- changed rules about logging on test env
Also contains:
- the zoom level page reverted to work in progress
https://pins-ds.atlassian.net/browse/BOAS-125
=> chore(web/applications): clean logs for the test environment (boas-125)

azure-pipelines-build.yml
- skips commitlinting if building main
=> fix(tooling): skips commitlint when building main

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/applications.controller.js, apps/web/src/server/applications/applications.service.js, apps/web/src/server/views/applications/dashboard.njk, apps/web/src/styles/4-generic/_generic.text-align.scss, apps/web/src/styles/main.scss
- add component for the stage in the dashboard
- add third column in the dashboard page
https://pins-ds.atlassian.net/browse/BOAS-226
=> feat(web/applications): add stage tag in dashboard page (boas-226)

apps/web/src/server/applications/create/applicant/applications-create-applicant.controller.js
fix applicant information type step
=> fix(web/applications): handle empty applicant info types (boas-148)

apps/web/src/server/applications/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/views/applications/create/applicant/_types.njk
Add "of" in the applicant types info page
=> fix(web/applications): change title of applicant info type page

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/views/applications/dashboard.njk
Renamed application list labels in Dashboard fro Application Reference to Name
=> fix(web/applications): updated application list labels (BOAS-173)

apps/web/src/server/applications/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/create/applicant/__tests__/applications-create-applicant.test.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.controller.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.types.d.ts, apps/web/src/server/views/applications/create/applicant/_organisation-name.njk
add input box to get Applicant Organisation Name
=> feat(web/applications): applicant organisation name page (BOAS-150)

apps/web/src/server/applications/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/create/applicant/__tests__/applications-create-applicant.test.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.controller.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.types.d.ts, apps/web/src/server/views/applications/create/applicant/_full-name.njk
Allow input of Applicant first name, middle name, and last name in teh case create process. Page amended, and tests added.
=> feat(web/applications): applicant-full-name page and tests (BOAS-151)

apps/api/.env.production
=> chore(api): adds prod env file to api

azure-pipelines-release.yml
- temporarily comment out db migration step when releasing to prod for testing of the release process
=> chore(api): temporarily comment out db migration for testing

apps/web/.env.production
Added completed list of Vars needed in the env.production file
=> chore(web): added full list of vars to env production file

apps/web/src/server/applications/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/create/applicant/applications-create-applicant.service.js, apps/web/src/server/applications/create/applications-create.router.js, apps/web/src/server/applications/create/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap, apps/web/src/server/applications/create/key-dates/__tests__/applications-create-key-dates.test.js, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.controller.js, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.router.js, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.types.d.ts, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.validators.js, apps/web/src/server/lib/dates.js, apps/web/src/server/lib/nunjucks-filters/date.js, apps/web/src/server/views/applications/create/key-dates/_key-dates.njk, apps/web/src/styles/5-elements/_elements.form-group.scss
Add UI for the key dates step + validators
=> feat(web/applications): key dates step

azure-pipelines-release.yml
- return db migration to release pipeline
=> ci: returns db migration for release pipeline

azure-pipelines-release.yml
- increases semantic release timeout to 200 mins
=> ci: increases release timeout to 200 mins

azure-pipelines-release.yml
- sets 2 minute semantic release timeout
=> ci: sets very short semantic release timeout

azure-pipelines-build.yml, azure-pipelines-db-seed.yml, azure-pipelines-deploy.yml, azure-pipelines-release.yml
- sets infinite time for semantic release timeout
=> ci: sets infinite timeout for semantic release

apps/api/prisma/schema.d.ts, apps/api/src/server/appeals/state-machine/__tests__/full-planning-appeal.machine.test.js, apps/api/src/server/applications/case-officer/case-officer.controller.js, apps/api/src/server/applications/inspector/inspector.controller.js, apps/api/src/server/applications/search/__tests__/case-search.test.js, apps/api/src/server/applications/search/case-search.controller.js, apps/api/src/server/applications/search/case-search.routes.js, apps/api/src/server/applications/search/case-search.services.js, apps/api/src/server/applications/search/case-search.validators.js, apps/api/src/server/middleware/error-handler.js, apps/api/src/server/utils/mapping/map-application-with-search-criteria.js, apps/api/src/server/utils/mapping/map-application-with-sector-and-subsector.js, apps/api/src/server/utils/mapping/map-application.js, apps/api/src/server/utils/mapping/map-sector.js
- checks all ACs
- refactors
- sets default page size to 50
=> chore(api): refactoring (BOAS-264)

azure-pipelines-release.yml
Fix a typo in the release pipeline causing the Azure App Service slot swap step of the Back Office API deployment to fail.
https://pins-ds.atlassian.net/browse/BOAS-314
=> Fix resource ID type in release pipeline

apps/api/src/server/applications/application/__tests__/get-application-details.test.js, apps/api/src/server/utils/mapping/map-service-customer.js, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/create/applicant/__tests__/applications-create-applicant.test.js, apps/web/src/server/applications/create/applicant/applications-create-applicant-session.service.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.controller.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.guards.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.service.js, apps/web/src/server/applications/create/applicant/applications-create-applicant.types.d.ts, apps/web/src/server/applications/create/applications-create.service.js, apps/web/src/server/applications/create/case/__tests__/applications-create-case.test.js, apps/web/src/server/applications/create/case/applications-create-case-session.service.js, apps/web/src/server/applications/create/case/applications-create-case.controller.js, apps/web/src/server/applications/create/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.controller.js, apps/web/src/server/views/applications/create/key-dates/_key-dates.njk, apps/web/testing/applications/factory/application.js, apps/web/testing/applications/fixtures/applications.js
Use the resume api on the applicant steps
=> feat(web/applications): resume applicant steps

apps/web/src/server/applications/create/applications-create.router.js, apps/web/src/server/applications/create/check-your-answers/applications-create-check-your-answers.controller.js, apps/web/src/server/applications/create/check-your-answers/applications-create-check-your-answers.router.js, apps/web/src/server/applications/create/check-your-answers/applications-create-check-your-answers.types.d.ts, apps/web/src/server/applications/create/key-dates/applications-create-key-dates.controller.js, apps/web/src/server/views/applications/create/confirmation.njk
confirmation page after check your answers page
=> feat(web/applications): create confirmation page for case creation

apps/web/environment/config.js
fix to check determining if the app is running in dev mode when ENV = "local"
=> fix(web/applications): fixed local env check (BOAS-257)

apps/api/src/server/applications/case-admin-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/case-admin-officer/case-admin-officer.controller.js, apps/api/src/server/applications/case-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/case-officer/case-officer.controller.js, apps/api/src/server/applications/inspector/__tests__/get-applications.test.js, apps/api/src/server/applications/inspector/inspector.controller.js, apps/api/src/server/applications/state-machine/application.machine.js, apps/api/src/server/repositories/case.repository.js, apps/api/src/server/utils/map-states-to-strings.js
- ensures no draft cases are returned to inspectors
=> feat(api/applications): return non-draft cases for inspector (BOAS-267)

apps/api/src/server/applications/case-admin-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/case-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/inspector/__tests__/get-applications.test.js, apps/api/src/server/utils/mapping/map-application-with-sector-and-subsector.js, apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/applications.controller.js, apps/web/src/server/applications/create/case/applications-create-case.controller.js, apps/web/src/server/views/applications/dashboard.njk, apps/web/src/styles/7-components/_table.scss
- Show draft cases in the dashboard
https://pins-ds.atlassian.net/browse/BOAS-227
=> feat(web/applications): show draft cases on dashboard

apps/api/src/server/applications/case-admin-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/case-admin-officer/case-admin-officer.controller.js, apps/api/src/server/applications/case-officer/__tests__/get-applications.test.js, apps/api/src/server/applications/case-officer/case-officer.controller.js, apps/api/src/server/applications/inspector/__tests__/get-applications.test.js, apps/api/src/server/applications/inspector/inspector.controller.js, apps/api/src/server/applications/state-machine/application.machine.js, apps/api/src/server/repositories/case.repository.js, apps/api/src/server/utils/map-states-to-strings.js, apps/api/src/server/utils/mapping/map-application-with-sector-and-subsector.js, apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/applications.controller.js, apps/web/src/server/applications/create/case/applications-create-case.controller.js, apps/web/src/server/views/applications/dashboard.njk, apps/web/src/styles/7-components/_table.scss
=> feat(api/applications): draft cases

apps/web/src/server/lib/nunjucks-filters/date.js
- key dates show 1/1/1970. fixed that
=> fix(web/applications): wrong pre-filled key dates field

apps/web/src/server/applications/create/case/__tests__/__snapshots__/applications-create-case.test.js.snap, apps/web/src/server/applications/create/case/__tests__/applications-create-case.test.js, apps/web/src/server/applications/create/case/applications-create-case.controller.js, apps/web/src/server/applications/create/case/applications-create-case.validators.js, apps/web/src/server/lib/nunjucks-filters/date.js
- make team-email non mandatory
- key dates small fix
=> feat(web/applications): make team-email non mandatory

apps/web/src/server/applications/create/key-dates/applications-create-key-dates.controller.js
=> fix(web/applications): do not send keydates if empty

apps/web/src/server/app/auth/auth.controller.js
=> fix(web/applications): fix session storage

apps/web/src/server/app/auth/auth.controller.js, apps/web/src/server/app/config/session.js, packages/express/middleware/session.js
=> fix(web/applications): set unset to destroy

apps/web/src/server/app/auth/auth.controller.js
removed regenerate session after login
=> fix(web/applications): removed regenerate session after login (BOAS-24)

apps/web/environment/config.d.ts, apps/web/environment/config.js, apps/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap, apps/web/src/server/app/auth/auth.controller.js, apps/web/src/server/views/app/layouts/app.layout.njk
=> feat(web/applications): change logout mechanism

apps/web/src/server/app/app.router.js, apps/web/src/server/app/auth/auth.router.js, apps/web/src/server/app/config/session.js
- move the auth/signout route behind the authentication guard
- set expire date for login cookie to 24h
=> feat(web/applications): set session expire date

apps/web/src/server/applications/create/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap, apps/web/src/server/views/applications/create/check-your-answers/_check-your-answers.njk
Correct the back link in Check-your-answers page to go to key-dates.
(raised against BOAS-166)
https://pins-ds.atlassian.net/browse/BOAS-377
=> fix(web/applications): check-your-answers correct back link (BOAS-377)

apps/web/src/server/applications/search/__tests/__snapshots__/applications-search.test.js.snap, apps/web/src/server/views/applications/search/search-results.njk
Removed Date Modified column from search results page
=> fix(web/applications): removed Date Modified column from search results (BOAS-379)

apps/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap, apps/web/src/server/app/auth/__tests__/auth.test.js, apps/web/src/server/app/auth/auth.controller.js, apps/web/src/server/app/auth/auth.guards.js, packages/express/middleware/session.js
- destroyed session if access token expired
- regenerated session after login
=> fix(web/applications): destroyed session if access token expired

apps/web/src/server/app/auth/auth.controller.js, apps/web/src/server/app/auth/auth.guards.js, apps/web/src/server/app/auth/auth.service.js
Rerverted refactored log out code
=> fix(web/applications): fixed issue with logout refactoring (BOAS-367)

apps/web/src/server/app/auth/auth.guards.js, apps/web/src/server/applications/applications.router.js, apps/web/src/server/applications/pages/case/applications-case.router.js, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/applications-edit-applicant.test.js, apps/web/src/server/applications/pages/case/edit/applicant/applications-edit-applicant.controller.js, apps/web/src/server/applications/pages/case/edit/applicant/applications-edit-applicant.router.js, apps/web/src/server/applications/pages/case/edit/applications-edit.locals.js, apps/web/src/server/applications/pages/case/edit/applications-edit.router.js, apps/web/src/server/applications/pages/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap, apps/web/src/server/applications/pages/case/edit/case/__tests__/applications-edit-case.test.js, apps/web/src/server/applications/pages/case/edit/case/applications-edit-case.controller.js, apps/web/src/server/applications/pages/case/edit/case/applications-edit-case.router.js, apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.locals.js, apps/web/src/server/applications/pages/create/applications-create.locals.js, apps/web/src/server/applications/pages/create/applications-create.service.js, apps/web/src/server/applications/pages/create/case/__tests__/__snapshots__/applications-create-case.test.js.snap, apps/web/src/server/applications/pages/create/case/applications-create-case.controller.js, apps/web/src/server/applications/pages/create/case/applications-create-case.validators.js, apps/web/src/server/applications/pages/create/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap, apps/web/src/server/applications/pages/create/check-your-answers/__tests__/applications-create-check-your-answers.test.js, apps/web/src/server/lib/nunjucks-filters/url.js, apps/web/src/server/views/applications/case-form/applicant/full-name.njk, apps/web/src/server/views/applications/case-form/case-form-layout.njk, apps/web/src/server/views/applications/case-form/case/project-location.njk, apps/web/src/server/views/applications/case/key-dates.njk, apps/web/src/server/views/applications/create/check-your-answers.njk
Edit pages added:
- description
- name
- zoom level
- regions
- grid refs
- projct location
- team email
- applicant name
- applicant organisation
- applicant email
- applicant website
- applicant phone
=> feat(web/applications): add edit pages for case section

apps/web/src/server/views/applications/search/search-results.njk
changed word "cases" to "applications"
BOAS-393
=> style(web/applications): changed cases to applications (BOAS-393)

apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.controller.js, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.service.js
changed wording
BOAS-298 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-298
=> feat(web/applications): changed wording and updated snapshot (BOAS-298)

apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.controller.js
changed wording
BOAS-307 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-307
=> style(web/applications): changed wording (BOAS-307)

apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.controller.js
changed wording
BOAS-299 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-299
=> style(web/applications): changed wording (BOAS-299)

apps/web/src/server/applications/components/form/form-applicant-components.controller.js, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/applications-edit-applicant.test.js, apps/web/src/server/applications/pages/case/edit/applicant/applications-edit-applicant.controller.js, apps/web/src/server/applications/pages/case/edit/applicant/applications-edit-applicant.router.js, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.types.d.ts, apps/web/src/server/views/applications/case-form/applicant/address-view.njk, apps/web/src/server/views/applications/case-form/case-form-layout.njk
=> feat(web/applications): add address edit page

apps/web/src/server/applications/pages/create/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap, apps/web/src/server/applications/pages/create/check-your-answers/__tests__/applications-create-check-your-answers.test.js, apps/web/src/server/applications/pages/create/check-your-answers/applications-create-check-your-answers.service.js, apps/web/src/server/lib/person-name-formatter.js, apps/web/src/server/views/applications/create/check-your-answers.njk
Amendments to the Check Your Answers page:
1. change references to "case" to "project"
2. row re-ordering
3. change contact name display to a single field combining firstName and lastName, without middleName
4. other small textual changes
5. adding a gds std warning note to base of page
6. change from 2/3 width to full 3-column width
https://pins-ds.atlassian.net/browse/BOAS-302
=> feat(web/applications): check your answers page amendments (BOAS-302)

apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.controller.js
changed wording
BOAS-306 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-306
=> style(web/applications): changed wording (BOAS-306

apps/web/src/server/applications/pages/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/applications-edit-applicant.test.js, apps/web/src/server/views/applications/case-form/applicant/address-view.njk
=> fix(web/applications): fix url on edit address page

apps/web/src/server/applications/pages/create/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create/applicant/applications-create-applicant.controller.js
removed hanging question mark in amended title:
Enter the applicant’s contact name?
https://pins-ds.atlassian.net/browse/BOAS-305
=> fix(web/applications): create case applicant name question (BOAS-305)

apps/api/src/server/applications/application/application.validators.js, apps/web/src/server/applications/components/form/form-case-components.controller.js
allowed blank email validation
BOAS-420 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-420
=> fix(api/applications): allowed blank email validation (BOAS-420)

README.md, docs/database-migration.md
No deliverable changes - just updates to add some missing documentation I discovered during initial project setup.
N/A
=> docs(tooling): update database docs for m1 macs

apps/web/src/server/views/applications/create/check-your-answers.njk
removed back link 
BOAS-443 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-443
=> fix(web/applications): removed back link (BOAS-443)

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/views/applications/dashboard.njk
reworded applications page
BOAs-447 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-447
=> fix(web/applications): reworded applications page (BOAS-447)

apps/web/src/server/applications/applications.locals.js, apps/web/src/server/applications/pages/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk, apps/web/src/styles/1-settings/_settings.global.scss, apps/web/src/styles/7-components/_masthead.scss
changed colour added case ref
BOAS-436 https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?selectedIssue=BOAS-436
=> feat(web/applications): changed colour added case ref (BOAS-436)

apps/api/prisma/migrations/20221018101250_create_folders_table/migration.sql, apps/api/prisma/schema.d.ts, apps/api/prisma/schema.prisma, apps/api/src/server/repositories/__tests__/folder.repository.test.js, apps/api/src/server/repositories/folder.repository.js
=> feat(api): creates folders for documents (BOAS-463)

apps/web/src/server/applications/pages/case/edit/applicant/applications-edit-applicant.router.js, apps/web/src/server/views/applications/components/case-form/applicant/address-view.njk
Editing applicant address goes to error page if it's first time adding a postcode. i fixed that.
=> fix(web/applications): address edit

apps/api/src/server/applications/application/application.controller.js, apps/api/src/server/applications/application/application.service.js, apps/api/src/server/applications/applications.routes.js, apps/api/src/server/utils/mapping/map-folder-details.js, package-lock.json
created endpoint for documents
BOAS-458 https://pins-ds.atlassian.net/browse/BOAS-458
=> feat(api/applications): created endpoint for documents (BOAS-458)

apps/api/src/server/applications/application/__tests__/get-folder-details.test.js, apps/api/src/server/applications/applications.routes.js, apps/api/src/server/swagger-output.json, apps/api/src/server/utils/mapping/map-folder-details.js
added type folder, and linked the db and endpoint
BOAS-458 https://pins-ds.atlassian.net/browse/BOAS-458
=> feat(api/applications): added type folder (BOAS-458)

apps/web/package.json, package-lock.json, package.json, packages/platform/package.json
fixed npm vulnerabilities via npm audit fix
=> fix(platform): fixed npm vilnerabilities via npm audit (BOAS-494)

apps/web/src/server/applications/pages/create-new-case/applicant/applications-create-applicant.validators.js
=> fix(web/applications): change postcode validator

apps/web/src/server/applications/pages/case/edit/applications-edit.locals.js
=> fix(web/applications): fix broken backlink on edit pages

apps/api/src/server/applications/application/__tests__/start-case.test.js, apps/api/src/server/repositories/folder.repository.js
Recommendation was missing from the list of top level document folders on a case.  Added.
This change will only affect new cases made from now on.
=> fix(api/applications): added recommendation folder (BOAS-516)

apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/lib/nunjucks-filters/url.js, apps/web/src/server/views/applications/dashboard.njk
fixed issue with slashed in URL builder NJK helper
=> fix(web/applications): fixed issue with slashed in URL builder helper

apps/document-storage/src/server/app/__tests__/document-storage.test.js, apps/document-storage/src/server/app/blob-store/service.js, apps/document-storage/src/server/app/controller.js, apps/document-storage/src/server/app/middleware/trim-unexpected-request-parameters.js, apps/document-storage/src/server/app/routes.js, apps/document-storage/src/server/app/validator.js, apps/document-storage/src/server/swagger-output.json, apps/document-storage/src/server/swagger.js
created post endpoint to create blobStoreUrl 
BOAS-504 https://pins-ds.atlassian.net/browse/BOAS-504
=> feat(storage): created post endpoint to create blobStoreUrl (BOAS-504)

azure-pipelines-build.yml, azure-pipelines-deploy.yml, azure-pipelines-release.yml
- adds document storage api to pipelines
=> ci: adds document storage api to pipielines (BOAS-514)

apps/web/jsconfig.json, apps/web/package.json, apps/web/scripts/rollup/bundle-js.js, apps/web/src/client/app.js, apps/web/src/client/components/file-uploader/_server-actions.js, package-lock.json
Import ES modules in the client javascript bundle and solve the runtime-generator issue
=> chore(web/applications): fix the rollup js bundler (boas-560)

apps/document-storage/.env.development, apps/web/environment/config.d.ts, apps/web/environment/config.js, apps/web/environment/schema.js, apps/web/src/client/components/file-uploader/_client-actions.js, apps/web/src/client/components/file-uploader/_errors.js, apps/web/src/client/components/file-uploader/_html.js, apps/web/src/client/components/file-uploader/_server-actions.js, apps/web/src/server/app/app.express.js, apps/web/src/server/app/components/file-uploader.component.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.types.d.ts, apps/web/src/server/views/app/components/file-uploader.component.njk, apps/web/src/server/views/applications/case-documentation/upload.njk, apps/web/src/styles/4-generic/_generic.colours.scss, apps/web/src/styles/7-components/file-upload.scss
=> feat(web/applications): add blob storage upload (boas-553)

apps/web/src/server/app/app.router.js, apps/web/src/server/app/auth/auth-session.service.js, apps/web/src/server/app/auth/auth.controller.js
create session get/set methods for access token and return it as a json in /session-token route
=> feat(web/applications): create session get/set methods for access token

apps/web/src/server/app/app.router.js, apps/web/src/server/app/auth/__tests__/auth.test.js, apps/web/src/server/app/auth/auth.controller.js, packages/platform/types/account.d.ts
=> fix(web/applications): retrieve access token

apps/web/src/server/app/auth/auth.guards.js
=> feat(web/applications): add loggers to auth.guard (boas-574)

azure-pipelines-deploy.yml
- fixes document storage api deployment typo
=> fix(api): fixes typo in doc storage deployment pipeline (BOAS-460)

apps/api/src/server/utils/document-storage-api-client.js
- removes unnecessary port declaration
=> fix(api): removes unnecessary port from doc store api calls (BOAS-460)

apps/api/package.json, apps/api/src/server/applications/application/__tests__/start-case.test.js, apps/api/src/server/applications/application/application.service.js, apps/api/src/server/config/config.js, apps/api/src/server/config/schema.js, apps/api/src/server/infrastructure/event-client.js, apps/api/src/server/infrastructure/local-event-client.js, apps/api/src/server/infrastructure/service-bus-event-client.js, apps/api/src/server/infrastructure/topics.js, apps/api/src/server/utils/application-factory-for-tests.js, package-lock.json
=> BOAS-32 Proof of concept for broadcasting events

apps/api/src/server/config/config.js, apps/api/src/server/utils/__tests__/feature-flags.test.js, apps/api/src/server/utils/feature-flags.js, apps/document-storage/src/server/app/lib/feature-flags.js, apps/document-storage/src/server/config/config.js, apps/web/.env.test, apps/web/environment/config.js, apps/web/src/common/__tests__/feature-flags.test.js, apps/web/src/common/feature-flags.js
Improved Feature Flags handling
Added Tests for function checking flag value
=> Improved Feature Flags handling (BOAS-521)

apps/api/src/server/utils/logger.js
=> fix(api): fix logging configuration for pino BOAS-532

apps/api/src/server/applications/application/application.service.js, apps/api/src/server/config/config.js, apps/api/src/server/infrastructure/local-event-client.js, apps/api/src/server/infrastructure/service-bus-event-client.js
=> fix(api): add some more logging, fix config file (boas-532)

apps/web/jest.config.js, apps/web/package.json, apps/web/setup-tests.js, apps/web/src/client/components/file-uploader/__tests__/file-uploader.test.js, package-lock.json
Added JSDOm library to be able to test Client side scripts in isolation
=> Added dom testing capabilities 

apps/web/src/server/applications/applications.controller.js, apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/pages/case/documentation/__tests__/applications-documentation.test.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.router.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.service.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.types.d.ts, apps/web/src/server/applications/pages/case/documentation/applications-documentation.validators.js, apps/web/src/server/views/applications/case-documentation/documentation-folder.njk, apps/web/src/styles/7-components/files-list.scss, apps/web/testing/applications/factory/documentation-file.js
Add panel on the documentation list
=> feat(web/applications): add panel UI (boas-608)

apps/web/src/client/components/file-uploader/_client-actions.js, apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/views/applications/case-documentation/documentation-folder.njk
fixed issue not allowing to re-upload a file
=> fix(web/applications): fixed issue not allowing to re-upload a file (BOAS-623)

apps/api/Dockerfile
Set Docker node version to node:16-alpine3.16 to avoid issues with Prisma
=> fix(web/applications): fix Docker node version (BOAS-659)

docs/adrs/2022-12-20_front-office-query-integration.md, docs/adrs/_template.md
=> docs(tooling): adr for integration between front office and back office

apps/web/src/server/app/components/file-uploader.component.js
=> chore(web/applications): log sessionaccount and AD access token

apps/web/src/client/components/file-uploader/_html.js, apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/pages/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/pages/case/edit/applicant/__tests__/__snapshots__/applications-edit-applicant.test.js.snap, apps/web/src/server/applications/pages/case/edit/case/__tests__/__snapshots__/applications-edit-case.test.js.snap, apps/web/src/server/applications/pages/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/pages/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap, apps/web/src/server/applications/pages/create-new-case/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap, apps/web/src/server/applications/pages/create-new-case/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap, apps/web/src/server/applications/pages/search-results/__tests/__snapshots__/applications-search.test.js.snap, apps/web/src/server/views/app/components/file-uploader.component.njk, apps/web/src/server/views/applications/case-documentation/documentation-folder.njk, apps/web/src/server/views/applications/case/components/applications-case-menu.component.njk, apps/web/src/server/views/applications/components/case-form/applicant/address.njk, apps/web/src/server/views/applications/components/case-form/applicant/applicant-email.njk, apps/web/src/server/views/applications/components/case-form/applicant/organisation-name.njk, apps/web/src/server/views/applications/components/case-form/applicant/telephone-number.njk, apps/web/src/server/views/applications/components/case-form/applicant/website.njk, apps/web/src/server/views/applications/components/case-form/case-form-layout.njk, apps/web/src/server/views/applications/components/case-form/case/team-email.njk, apps/web/src/server/views/applications/components/case-form/key-dates/date-internal.njk, apps/web/src/server/views/applications/create-new-case/check-your-answers.njk, apps/web/src/server/views/applications/dashboard.njk, apps/web/src/server/views/applications/search-results/search-results.njk
Small Accessibility improvements across the whole UI
BOAS-700: https://pins-ds.atlassian.net/browse/BOAS-700
=> chore(api/applications): minor accessibility improvements (BOAS-700)

apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/lib/nunjucks-filters/url.js, apps/web/src/server/views/applications/case-documentation/documentation-folder.njk
Bug fix of the url to download files from the documentation list page
=> fix(web/applications): set proper url to download files page (boas-694)

apps/web/package.json, apps/web/src/server/app/app.router.js, apps/web/src/server/app/auth/auth.router.js, apps/web/src/server/applications/applications.locals.js, apps/web/src/server/applications/pages/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap, apps/web/src/server/applications/pages/create-new-case/case/__tests__/applications-create-case.test.js, package-lock.json
Upgrade express and MSAL + fix jest timeout problems due to `Throw New Error` usage
=> build(web/applications): upgrade msal and express

apps/api/src/server/applications/application/__tests__/update-application.test.js, apps/api/src/server/repositories/case.repository.js
update regions on case - fixed the code that deleted the existing regions on the case before applying the new selection
https://pins-ds.atlassian.net/browse/BOAS-713
=> fix(api/applications): fix unable to update regions on case (BOAS-713)

apps/api/package.json, apps/api/src/event-schemas/document.schema.json, apps/api/src/event-schemas/exam-timetable.schema.json, apps/api/src/event-schemas/nsip-project.schema.json, apps/api/src/event-schemas/relevant-representation.schema.json, apps/api/src/event-schemas/s51-advice.schema.json, apps/api/src/event-schemas/staff.schema.json, apps/api/src/server/applications/application/__tests__/application.test.js, apps/api/src/server/applications/application/__tests__/create-application.test.js, apps/api/src/server/applications/application/__tests__/schema-test-utils.js, apps/api/src/server/applications/application/__tests__/start-case.test.js, apps/api/src/server/applications/application/__tests__/update-application.test.js, apps/api/src/server/applications/application/application.js, docs/event-repository.md, package-lock.json
=> docs(api): add schema tests

apps/web/src/server/app/components/file-downloader.component.js
=> feat(web/applications): preview files through proxy (boas-694)

apps/web/src/server/applications/pages/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/pages/case/documentation/__tests__/applications-documentation.test.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.router.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.service.js, apps/web/src/server/applications/pages/case/documentation/applications-documentation.validators.js, apps/web/src/server/views/applications/case-documentation/documentation-delete.njk, apps/web/src/server/views/applications/case-documentation/documentation-properties.njk, apps/web/src/server/views/applications/case-documentation/documentation-success-banner.njk
=> feat(web/applications): add template for deleting documents (boas-738)

apps/web/src/styles/7-components/files-list.scss
BOAS-744
https://pins-ds.atlassian.net/browse/BOAS-744
=> Long file name fix

azure-pipelines-deploy.yml
=> fix(api): fix deploy

apps/web/src/server/applications/lib/services/case.service.js, apps/web/src/server/applications/pages/case/applications-case.locals.js
https://pins-ds.atlassian.net/browse/BOAS-758
=> fix(web/applications): handle errors when caseId is wrong (boas-758)

apps/document-check-function/package.json, azure-pipelines-build.yml, package-lock.json, package.json
=> fix(document-check-function): fixes got package import (BOAS-723)

apps/web/src/server/applications/pages/case/applications-case.locals.js
=> fix(web/applications): 404 if draft case on nondraft page (boas-758)

apps/web/nodemon.json, apps/web/package.json, package-lock.json
=> feat(web/applications): kill port 8080 to allow nodemon restart

apps/api/src/message-schemas/commands/register-representation.schema.json, apps/api/src/message-schemas/events/_appeal-document.schema.json, apps/api/src/message-schemas/events/_appeal.schema.json, apps/api/src/message-schemas/events/_final-comment.schema.json, apps/api/src/message-schemas/events/case-schedule.schema.json, apps/api/src/message-schemas/events/employee.schema.json, apps/api/src/message-schemas/events/exam-timetable.schema.json, apps/api/src/message-schemas/events/interested-party.schema.json, apps/api/src/message-schemas/events/nsip-document.schema.json, apps/api/src/message-schemas/events/nsip-project.schema.json, apps/api/src/message-schemas/events/nsip-update.schema.json, apps/api/src/message-schemas/events/representation.schema.json, apps/api/src/message-schemas/events/s51-advice.schema.json, apps/api/src/server/applications/application/__tests__/schema-test-utils.js, docs/event-repository.md
=> docs(api): schema specification

apps/api/src/server/applications/state-machine/document.machine.js, apps/web/src/client/components/file-uploader/_server-actions.js, package-lock.json, packages/blob-storage-client/index.js, packages/eslint/configs/node.js, packages/event-client/index.js
- refactors web to use share blob storage client
=> refactor(web): uses shared blob storage client package (BOAS-745)

apps/api/prisma/migrations/20230228135327_add_document_metadata/migration.sql
=> feat(api/applications): add metadata sql migration (boas-740)

apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap, apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.locals.js, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.service.js, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.validators.js, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/case/documentation/applications-documentation.service.js, apps/web/src/server/views/applications/case-documentation/documentation-edit.njk, apps/web/src/server/views/applications/case-documentation/documentation-properties.njk, apps/web/src/server/views/applications/case-documentation/edit/character-count-input.njk, apps/web/src/server/views/applications/case-documentation/edit/text-input.njk, apps/web/testing/applications/factory/documentation-file.js
=> feat(web/applications): name and description metadata templates

azure-pipelines-deploy.yml
=> temp updates to deploy pipeline

apps/api/package.json, apps/api/prisma/migrations/20230308143957_test/migration.sql, apps/api/prisma/schema.d.ts, apps/api/prisma/schema.prisma, apps/api/setup-tests.js, apps/api/src/server/applications/application/documents/__tests__/delete-document.test.js, apps/api/src/server/applications/application/documents/__tests__/document.test.js, apps/api/src/server/applications/application/documents/__tests__/provide-document-upload-urls.test.js, apps/api/src/server/applications/application/documents/__tests__/store-document-metadata.test.js, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.routes.js, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/applications/application/documents/document.validators.js, apps/api/src/server/applications/application/file-folders/__tests__/get-folder-details.test.js, apps/api/src/server/applications/application/file-folders/folders.service.js, apps/api/src/server/config/config.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/api/src/server/repositories/document.repository.js, apps/api/src/server/swagger.js, apps/api/src/server/utils/__tests__/prisma-middleware.test.js, apps/api/src/server/utils/mapping/map-document-details.js, apps/api/src/server/utils/prisma-middleware/index.js, apps/web/environment/config.js, azure-pipelines-deploy.yml, package-lock.json
=> feat(api): get metadata(BOAS-766)

apps/api/src/message-schemas/events/nsip-document.schema.json, azure-pipelines-deploy.yml
This change adds the NSIP document event message schema based on the definition agreed by the 
integration team. Schema matches the agreed confluence - 
https://pins-ds.atlassian.net/wiki/spaces/BO/pages/1064730651/Document+Metadata+-+DRAFT
Schema was tested to be valid via the test file  schema-test-utils.js
=> feat(api): create NSIP document message schema

apps/api/prisma/migrations/20230228135327_add_document_metadata/migration.sql
=> fix(web/applications): attempting to fix migration (BOAS-713)

azure-pipelines-deploy.yml
=> fix(web/applications): reset DB (BOAS-713)

azure-pipelines-deploy.yml
=> fix(web/applications): revert reset DB (BOAS-713)

apps/api/prisma/seed-samples.js, apps/api/prisma/seed.js
Initial Rel Reps test data - largely taken from existing NI test DB
=> feat(api/applications): test data for reps

azure-pipelines-deploy.yml
=> feat(api/applications): reverting back to normal pipeline structure

apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js, apps/api/src/server/applications/documents/documents.controller.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/api/src/server/repositories/document.repository.js
=> feat(api/applications): fix update document status

apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js, apps/api/src/server/applications/documents/documents.controller.js
=> feat(api/applications): 

apps/web/src/server/app/components/file-uploader.component.js
=> fix(web/applications): fix frontend uploading script (boas-810)

apps/api/src/server/applications/application/documents/__tests__/get-ready-to-publish-documents.test.js, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.routes.js, apps/api/src/server/applications/application/file-folders/folders.routes.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/api/src/server/repositories/document.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
=> boas-796 ready-to-publish docs API

apps/web/src/server/app/components/file-downloader.component.js, apps/web/src/server/applications/applications.types.d.ts
=> fix(web): consume correct property for file download

apps/api/src/server/applications/application/documents/document.controller.js
Undo code that stopped the doc update api working
https://pins-ds.atlassian.net/browse/BOAS-825
=> fix(api/applications): fix doc status update api (BOAS-825)

packages/event-client/src/service-bus-event-client.js
=> fix(api): don't stringify payload

apps/api/src/server/applications/application/application.controller.js
=> fix(api/applications): representations 404 error

apps/web/src/server/appeals/appeals.router.js, apps/web/src/server/views/appeals/all-appeals/dashboard.njk, apps/web/src/server/views/appeals/case-officer/dashboard.njk, apps/web/src/server/views/appeals/components/appeals-table.njk, apps/web/src/server/views/appeals/components/status-tag.njk
add nunjucks template for national list dashboard
BOAT-53
BOAT-54
=> BOAT-53 and BOAT-54: add nunjucks template for national list dashboard

apps/document-check-function/check-document/function.json, apps/document-check-function/check-document/index.js
=> fix(api): change trigger to event grid

apps/api/prisma/schema.prisma
- adds annotations on db models
=> docs(api): adds annotations to models (BOAS-844)

apps/document-check-function/package.json, azure-pipelines-build.yml, package-lock.json
=> fix(api): consolidate azure identity version

apps/web/src/server/appeals/appeals.router.js, apps/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, apps/web/src/server/appeals/national-list/__tests__/national-list.test.js, apps/web/src/server/appeals/national-list/national-list.controller.js, apps/web/src/server/appeals/national-list/national-list.router.js, apps/web/src/server/appeals/national-list/national-list.service.js, apps/web/src/server/views/appeals/components/appeals-table.njk, apps/web/testing/app/fixtures/referencedata.js, apps/web/testing/appeals/mocks/api.js
https://pins-ds.atlassian.net/browse/BOAT-55
https://pins-ds.atlassian.net/browse/BOAT-56
=> feat(web): add web router controller for national list

apps/web/src/server/appeals/appeals.router.js, apps/web/src/server/lib/nunjucks-filters/actions-parameter-for-document-status.js, apps/web/src/server/lib/nunjucks-filters/index.js, apps/web/src/server/views/appeals/all-appeals/appeal-details.njk, apps/web/src/server/views/appeals/components/status-tag.njk
add case details page template
BOAT-65
=> feat(web): add case details page template (BOAT-65)

README.md
The README has been updated to fix some formatting issues, have a clearer structure, and update out of date instructions.
N/A
=> docs: update readme, fix formatting, clearer structure

packages/blob-storage-client/package.json
Fix node dep0151 warning for blob-storage-client
N/A
=> chore(tooling): add main entry point to fix node dep0151 warning

package-lock.json
lock date-fns-tz version (remove wildcard)
N/A
=> build: lock date-fns-tz version (remove wildcard)

docs/types.md
Some brief docs about how we use and check types.
N/A
=> docs: add dev type docs

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js, apps/web/src/server/appeals/appeal-details/appeal-details.controller.js, apps/web/src/server/appeals/appeal-details/appeal-details.router.js, apps/web/src/server/appeals/appeal-details/appeal-details.service.js, apps/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, apps/web/src/server/appeals/appeals.router.js, apps/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, apps/web/src/server/views/app/layouts/app.layout.njk, apps/web/src/server/views/appeals/all-appeals/appeal-details.njk, apps/web/src/server/views/appeals/components/appeals-table.njk, apps/web/testing/app/fixtures/referencedata.js, apps/web/testing/appeals/mocks/api.js, package-lock.json
Added the router, controller, and service to populate the select and view appeal details page. Made some updates to the template to accommodate for data structure. Added tests for valid and invalid AppealIds.
The unit tests use a mocked appeal fixture for a valid appealId and a failed (500) for an invalid appealId. The test then reviews the page to make sure it matches the expected html.
#BOAT-63, #BOAT-64, #BOAT-65, #BOAT-66, #BOAT-102
Added the router, controller, and service to populate the select and view appeal details page. Made some updates to the template to accommodate for data structure. Added tests for valid and invalid AppealIds
https://pins-ds.atlassian.net/browse/BOAT-3
=> feat(web/appeals): add router, controller, service, tests for appeal details + fix template

apps/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, apps/web/src/server/appeals/national-list/national-list.controller.js, apps/web/src/server/appeals/national-list/national-list.service.js, apps/web/src/server/lib/__tests__/libraries.test.js, apps/web/src/server/lib/nunjucks-filters/appeals.js, apps/web/src/server/lib/nunjucks-filters/index.js, apps/web/src/server/views/appeals/components/appeals-table.njk, packages/appeals/types/appeal.d.ts
Use the short appeal reference on the national-list table, instead of the full reference.
[BOAT-99](https://pins-ds.atlassian.net/jira/software/projects/BOAT/boards/207?selectedIssue=BOAT-99)
[BOAT-99]: https://pins-ds.atlassian.net/browse/BOAT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(web/appeals): use short appeal ref on national-list table

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/appeal-details.controller.js, apps/web/src/server/appeals/appeal-details/appeal-details.router.js, apps/web/src/server/appeals/enter-start-date/__tests__/__snapshots__/enter-start-date.test.js.snap, apps/web/src/server/appeals/enter-start-date/__tests__/enter-start-date.test.js, apps/web/src/server/views/app/layouts/app-two-column.layout.njk, apps/web/src/server/views/appeals/appeal/appeal-details.njk, apps/web/src/server/views/appeals/appeal/enter-start-date.njk
=> feat(web): template for enter start date page

apps/web/src/server/appeals/appeal-details/appeal-details.router.js, apps/web/src/server/appeals/start-date-entered/__tests__/__snapshots__/start-date-entered.test.js.snap, apps/web/src/server/appeals/start-date-entered/__tests__/start-date-entered.test.js, apps/web/src/server/views/appeals/appeal/start-date-entered.njk
Nunjucks template for enter start date confirmation page + temporary router code to render the page
BOAT-107
=> feat(web): add page template for enter start date confirmation page

apps/web/src/server/applications/create-new-case/check-your-answers/applications-create-check-your-answers.service.js
correct the display of unexpected error messages on case create (check your answers) page
https://pins-ds.atlassian.net/browse/BOAS-868
=> fix(web/applications): unreadable error message case create (BOAS-868)

apps/web/src/server/applications/case/representations/representation-details/__tests__/__snapshots__/application-representation-details.test.js.snap, apps/web/src/server/views/applications/representations/representation-details/components/agent-contact.njk
-agent contact details should not have 'job title' section
=> fix(web/applications): remove unnecessary template section

apps/web/src/server/appeals/national-list/__tests__/national-list.test.js, apps/web/src/server/views/appeals/all-appeals/dashboard.njk, apps/web/testing/app/fixtures/referencedata.js
- Fix rendering of national list page
- Fix unit tests
=> fix(web): appeal list page rendering

apps/e2e/cypress/e2e/back-office-applications/documentDownload.spec.js, apps/e2e/cypress/page_objects/uploadFiles.js, apps/e2e/cypress/support/commands.js, apps/e2e/cypress/support/utils/utils.js, azure-pipelines-e2e.yml
=> fix(e2e): fix download click when using button

apps/web/src/server/applications/case/representations/__tests__/__snapshots__/applications-representaions.test.js.snap, apps/web/src/server/views/applications/representations/components/table/representations-table.component.njk
=> fix(web/applications): fix page jump on table sort

apps/web/src/server/applications/case/representations/representation-details/__tests__/__snapshots__/application-representation-details.test.js.snap, apps/web/src/server/views/applications/representations/representation-details/components/representation-status-tag.njk, apps/web/src/server/views/applications/representations/representation-details/components/workflow.njk, apps/web/src/server/views/applications/representations/representation-details/representation-details.njk
=> fix(web/applications): use representation status instead of case status

apps/web/src/server/applications/case/representations/__tests__/applications-representaions.test.js, apps/web/src/server/applications/case/representations/applications-relevant-reps.controller.js, apps/web/src/server/applications/case/representations/utils/filter/filter-view-model.js
-filtering by 'invalid' status was also checking the 'valid' checkbox in the UI
=> fix(web/applications): fix filtering by 'invalid' issue [ASB1476]

apps/web/src/server/views/appeals/appeal/appeal-details.njk
back button should redirect to national list not validation page
[https://pins-ds.atlassian.net/browse/BOAT-135](https://pins-ds.atlassian.net/browse/BOAT-135)
=> fix(web/appeals): fix back button not going to correct url

apps/web/src/server/app/auth/__tests__/auth.test.js, apps/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, apps/web/src/server/appeals/national-list/__tests__/national-list.test.js, apps/web/src/server/appeals/national-list/national-list.controller.js, apps/web/src/server/appeals/national-list/national-list.service.js, apps/web/src/server/views/appeals/all-appeals/dashboard.njk, packages/appeals/types/appeal.d.ts
https://pins-ds.atlassian.net/browse/BOAT-41
=> feat(web): pagination web functionality

apps/web/src/server/appeals/appeal.constants.js, apps/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, apps/web/src/server/appeals/national-list/national-list.controller.js, apps/web/src/server/appeals/national-list/national-list.service.js
Ability to pass a querystring parameter to the national list, indicating the desired page size. A way of making pagination testable with the current data set.
N/A
=> fix(web): pagination settings BOAT National list

docs/uploading-files.md
This is the current process as-is, it's messy and hopefully we can make lots of it obsolete.
=> docs(api): add instructions for how to upload files locally

apps/api/setup-tests.js, apps/api/src/server/applications/application/application.controller.js, apps/api/src/server/applications/application/application.routes.js, apps/api/src/server/applications/application/application.service.js, apps/api/src/server/applications/application/representations/__tests__/create-representation.test.js, apps/api/src/server/applications/application/representations/__tests__/get-representation.test.js, apps/api/src/server/applications/application/representations/__tests__/get-representations.test.js, apps/api/src/server/applications/application/representations/__tests__/patch-representation.test.js, apps/api/src/server/applications/application/representations/representaions.service.js, apps/api/src/server/applications/application/representations/representation.mapper.js, apps/api/src/server/applications/application/representations/representations.controller.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/repositories/representation.repository.js, apps/api/src/server/swagger-output.json
refactor representations to representations folder
refactor representations router
=> feat(api/representations): patch representation

apps/e2e/cypress/e2e/back-office-appeals/appealsList.spec.js, apps/e2e/cypress/page_objects/appealsListPage.js
=> test(e2e): add some scaffolding for appeals

apps/api/src/database/migrations/20230519123437_representations_actions_table/migration.sql, apps/api/src/database/schema.prisma, apps/api/src/database/seed/data-samples.js, apps/api/src/database/seed/data-test.js, apps/api/src/database/seed/seed-clear.js
add 101 seed data item for the first case
=> feat(api/applications): add representations actions table

apps/web/src/server/appeals/appeal-details/appeal-details.router.js, apps/web/src/server/appeals/appeals.router.js, apps/web/src/server/appeals/enter-start-date/__tests__/__snapshots__/enter-start-date.test.js.snap, apps/web/src/server/appeals/enter-start-date/__tests__/enter-start-date.test.js, apps/web/src/server/appeals/enter-start-date/enter-start-date.controller.js, apps/web/src/server/appeals/enter-start-date/enter-start-date.router.js, apps/web/src/server/appeals/enter-start-date/enter-start-date.validators.js, apps/web/src/server/appeals/start-date-entered/start-date-entered.controller.js, apps/web/src/server/appeals/start-date-entered/start-date-entered.router.js, apps/web/src/server/lib/__tests__/libraries.test.js, apps/web/src/server/lib/middleware/__tests__/skip-middleware-if-errors-in-body.test.js, apps/web/src/server/lib/middleware/skip-middleware-if-errors-in-body.js
router and controller for set start date
BOAT-103
BOAT-104
=> feat(web): BOAT-103 and 104 - router and controller for set start date

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/appeal-details.controller.js, apps/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, apps/web/src/server/lib/nunjucks-filters/date.js, apps/web/src/server/views/appeals/appeal/appeal-details.njk, apps/web/testing/app/fixtures/referencedata.js
code to populate case timetable on appeal-details page
BOAT-153
=> feat(web): code to populate case timetable on appeal-details page (BOAT-153)

apps/api/setup-tests.js, apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js, apps/api/src/server/applications/application/representations/redact/redact.controller.js, apps/api/src/server/applications/application/representations/redact/redact.mapper.js, apps/api/src/server/applications/application/representations/redact/redact.route.js, apps/api/src/server/applications/application/representations/redact/redact.service.js, apps/api/src/server/applications/application/representations/redact/redact.validators.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/repositories/representation.repository.js, apps/api/src/server/swagger-output.json
=> feat(api/applications): add representations redact path endpoint

packages/blob-storage-client/package.json, packages/event-client/package.json, packages/express/package.json, packages/platform/package.json
Change slipped through that I didn't intend.
N/A
=> chore(tooling): revert accidental change (lint-js -> lint:js)

apps/web/src/server/appeals/enter-start-date/__tests__/enter-start-date.test.js, apps/web/src/server/appeals/enter-start-date/enter-start-date.controller.js, apps/web/src/server/appeals/enter-start-date/enter-start-date.service.js
adds service for start date
updates tests
https://pins-ds.atlassian.net/browse/BOAT-105
=> feat(web/appeals): add start date service

apps/web/src/server/applications/case/applications-case.locals.js, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js, apps/web/src/server/applications/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/case/documentation/applications-documentation.router.js, apps/web/src/server/applications/case/documentation/applications-documentation.service.js, apps/web/src/server/applications/case/documentation/applications-documentation.validators.js, apps/web/src/server/views/applications/case-documentation/documentation-success-banner.njk
=> feat(web/applications): publish documents ui (BOAS-736)

apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js, apps/api/src/server/applications/application/representations/redact/redact.route.js, apps/api/src/server/applications/application/representations/redact/redact.validators.js, apps/api/src/server/applications/application/representations/representation.validators.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/repositories/representation.repository.js
=> feat(web/applications): fix representation patch validation

apps/api/src/database/migrations/20230518104003_move_coulmn_from_document_to_document_versions/migration.sql
=> fix(platform): default latestVersionId to 1 before adding constraint

apps/api/src/database/seed/seed-clear.js
Ensure table dependencies for appeal are cleared with db:seed.
N/A
=> fix(api): clear appeal data with timetables

apps/api/src/database/migrations/20230526092956_update_lpa_questionnaire/migration.sql
Migration error with ALTER TABLE.
=> fix(api): fix migration of LPAQ data

apps/api/src/database/migrations/20230526092956_update_lpa_questionnaire/migration.sql
Adds additional columns to LPAQ tables, using NULL values
=> fix(api): fix migration of LPAQ data (NULL COLUMNS)

apps/api/src/database/migrations/20230530093928_correct_schema_drift/migration.sql, apps/api/src/database/schema.prisma
=> fix(tooling): fix schema drift

azure-pipelines-build.yml, azure-pipelines-ci.yml
Fail fast on CI steps to save time if any previous checks don't succeed.
=> fix(platform): fail fast for ci pipeline

apps/api/src/server/appeals/appeals.d.ts, apps/api/src/server/appeals/appeals/__tests__/appeals.test.js, apps/api/src/server/appeals/appeals/appeals.formatter.js, apps/api/src/server/appeals/constants.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
API - fetch documents according to appeal type
BOAT-157
=> feat(api): fetch documents according to appeal type

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/appeal-details.controller.js, apps/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, apps/web/src/server/views/appeals/appeal/appeal-details.njk, apps/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/BOAT-118
=> feat(web): display has documentation appelant case and lpa questionnaire

apps/api/src/server/applications/application/representations/representation.mapper.js, apps/api/src/server/repositories/__tests__/representation.repository.test.js, apps/api/src/server/repositories/representation.repository.js, apps/web/src/server/applications/case/representations/__fixtures__/representations.fixture.js, apps/web/src/server/applications/case/representations/applications-relevant-reps.router.js, apps/web/src/server/applications/case/representations/representation/representation-type/__tests__/__snapshots__/represetation-type.test.js.snap, apps/web/src/server/applications/case/representations/representation/representation-type/__tests__/represetation-type.test.js, apps/web/src/server/applications/case/representations/representation/representation-type/representation-type.controller.js, apps/web/src/server/applications/case/representations/representation/representation-type/representation-type.router.js, apps/web/src/server/applications/case/representations/representation/representation-type/representation-type.validators.js, apps/web/src/server/applications/case/representations/representation/representation-type/representation-type.view-model.js, apps/web/src/server/applications/case/representations/representation/representation.middleware.js, apps/web/src/server/applications/case/representations/representation/representation.service.js, apps/web/src/server/views/applications/representations/representation/representation-type.njk
=> feat(web/applications): add representation type page

apps/api/src/server/repositories/__tests__/representation.repository.test.js, apps/api/src/server/repositories/representation.repository.js, apps/web/src/server/applications/case/representations/applications-relevant-reps.router.js, apps/web/src/server/applications/case/representations/representation-details/application-representation-details.router.js, apps/web/src/server/applications/case/representations/representation/contact-method/__tests__/__snapshots__/rr-contact-method.test.js.snap, apps/web/src/server/applications/case/representations/representation/contact-method/__tests__/rr-contact-method.test.js, apps/web/src/server/applications/case/representations/representation/contact-method/contact-method.controller.js, apps/web/src/server/applications/case/representations/representation/contact-method/contact-method.router.js, apps/web/src/server/applications/case/representations/representation/contact-method/contact-method.validators.js, apps/web/src/server/applications/case/representations/representation/contact-method/contact-method.view-model.js, apps/web/src/server/applications/case/representations/representation/representation.utilities.js, apps/web/src/server/views/applications/representations/representation/contact-method.njk
=> feat(web/applications): add contact method page

apps/web/package.json, apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/enter-start-date/__tests__/__snapshots__/enter-start-date.test.js.snap, apps/web/src/server/applications/__tests__/__snapshots__/applications.test.js.snap, apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap, apps/web/src/server/applications/case/representations/representation/contact-method/__tests__/__snapshots__/rr-contact-method.test.js.snap, apps/web/src/server/applications/case/representations/representation/representation-type/__tests__/__snapshots__/represetation-type.test.js.snap, apps/web/src/server/applications/create-new-case/applicant/__tests__/__snapshots__/applications-create-applicant.test.js.snap, apps/web/src/server/applications/create-new-case/applicant/__tests__/applications-create-applicant.test.js, apps/web/src/server/applications/create-new-case/case/__tests__/__snapshots__/applications-create-case.test.js.snap, apps/web/src/server/applications/create-new-case/check-your-answers/__tests__/__snapshots__/applications-create-check-your-answers.test.js.snap, apps/web/src/server/applications/create-new-case/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap, package-lock.json
Updated govuk-frontend NPM dependency to latest version, associated updates to unit tests
BOAT-182
=> build: BOAT-182 - update govuk-frontend dependency

apps/api/src/database/seed/seed-clear.js
Fix issues that stop the seeding script running - clearing the Document and DocumentVersion records, and the Exam Timetable Item records.
https://pins-ds.atlassian.net/browse/BOAS-940
=> fix(api/applications): fix seed script doc tables delete (BOAS-940)

apps/api/src/database/migrations/20230605140153_/migration.sql, apps/api/src/database/schema.d.ts, apps/api/src/database/schema.prisma, apps/api/src/server/appeals/appeals.d.ts, apps/api/src/server/appeals/appeals/__tests__/appeals.test.js, apps/api/src/server/appeals/appeals/appeals.formatter.js, apps/api/src/server/appeals/config.js, apps/api/src/server/repositories/appeal.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/appeal-details.controller.js, apps/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, apps/web/src/server/views/appeals/appeal/appeal-details.njk
Update the appeals timetable deadlines so they are calculated correctly for HAS and FPA appeal types.
This change covers both the API update and the renaming in the Web app.
https://pins-ds.atlassian.net/browse/BOAT-62
=> fix(api): update the appeals timetable deadlines

apps/web/src/client/components/excerpts/__tests__/excerpt.test.js, apps/web/src/client/components/excerpts/excerpt.js, apps/web/src/server/views/applications/components/__tests__/__snapshots__/excerpt.component.test.js.snap, apps/web/src/server/views/applications/components/__tests__/excerpt.component.test.js, apps/web/src/server/views/applications/components/excerpt.component.njk
A reusable web component for handling excerpts - showing truncated content, with an option to show more. Uses client-side JS, but uses the [Details](https://design-system.service.gov.uk/components/details/) component as a fallback.
Developed for Project updates feature, but also useful for other features.
N/A
=> feat(web): add excerpt component

apps/web/src/client/app.js
Previous PR didn't include the code to actually initialise the excerpt module
N/A
=> fix(web): init excerpt module

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js, apps/web/src/server/views/appeals/appeal/appeal-details.njk
Change copy and date of "start date"
https://pins-ds.atlassian.net/browse/BOAT-216
=> feat(web): change "Add start date" to "Review appeal" for a case that has not been started

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap, apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js, apps/web/src/server/applications/case/examination-timetable/applications-timetable.service.js, apps/web/src/server/views/applications/case-timetable/components/timetable-items.component.njk, apps/web/src/server/views/applications/case-timetable/timetable-preview.njk, apps/web/src/server/views/applications/case/examination-timetable.njk
=> fix(web/applications): handle missing dates in timetable view (boas-937)

apps/api/src/database/seed/data-samples.js
=> fix(api): fix seed script

apps/functions/README.md
We are going to be adding more Azure Functions as we create more integrations. I've added general documentation in a new `apps/functions` folder - where functions will live going forward.
N/A
=> docs: add docs for getting started with functions

apps/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, apps/web/src/server/views/appeals/appeal/appeal-details.njk
https://pins-ds.atlassian.net/browse/BOAT-216
=> fix(web): fix typo

apps/api/setup-tests.js, apps/api/src/server/applications/application/representations/contacts/__tests___/delete-contact.test.js, apps/api/src/server/applications/application/representations/contacts/contacts.controller.js, apps/api/src/server/applications/application/representations/contacts/contacts.route.js, apps/api/src/server/applications/application/representations/contacts/contacts.service.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/repositories/__tests__/representation.repository.test.js, apps/api/src/server/repositories/representation.repository.js, apps/api/src/server/swagger-output.json
=> feat(api/applications): add delete representations contacts

apps/document-publish-function/publish-document/function.json
=> fix(api): fix topic name

apps/web/src/server/applications/case/representations/representation-details/__tests__/__snapshots__/application-representation-details.test.js.snap, apps/web/src/server/applications/case/representations/representation-details/application-representation-details.router.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/__tests__/__snapshots__/change-redaction.test.js.snap, apps/web/src/server/applications/case/representations/representation-details/change-redaction/__tests__/change-redaction.test.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.controller.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.service.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.validator.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.view-model.js, apps/web/src/server/views/applications/representations/representation-details/change-redaction.njk, apps/web/src/server/views/applications/representations/representation-details/components/workflow.njk, apps/web/src/server/views/applications/representations/representation-details/representation-details.njk
=> feat(web/applications): add representation redaction change

apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/__snapshots__/lpa-questionnaire-review.test.js.snap, apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/lpa-questionnaire-review.test.js, apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.controller.js, apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.router.js, apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.service.js, apps/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.validators.js, apps/web/src/server/views/appeals/appeal/lpa-questionnaire-view.njk, apps/web/testing/app/fixtures/referencedata.js
Ability to review LPAQ with "Complete" review outcome
https://pins-ds.atlassian.net/browse/BOAT-133
=> feat(web): lpaq review complete path

apps/api/setup-tests.js, apps/api/src/database/migrations/20230620101631_save_appellant_case_outcome/migration.sql, apps/api/src/database/schema.d.ts, apps/api/src/database/schema.prisma, apps/api/src/database/seed/data-static.js, apps/api/src/database/seed/data-test.js, apps/api/src/database/seed/seed-clear.js, apps/api/src/server/appeals/appeals.d.ts, apps/api/src/server/appeals/appeals.routes.js, apps/api/src/server/appeals/appeals/__tests__/appellant-cases.test.js, apps/api/src/server/appeals/appeals/appeals.controller.js, apps/api/src/server/appeals/appeals/appeals.routes.js, apps/api/src/server/appeals/appeals/appeals.service.js, apps/api/src/server/appeals/appeals/appeals.validators.js, apps/api/src/server/appeals/appellant-case-incomplete-reasons/__tests__/appellant-case-incomplete-reasons.test.js, apps/api/src/server/appeals/appellant-case-incomplete-reasons/appellant-case-incomplete-reasons.routes.js, apps/api/src/server/appeals/appellant-case-invalid-reasons/__tests__/appellant-case-invalid-reasons.test.js, apps/api/src/server/appeals/appellant-case-invalid-reasons/appellant-case-invalid-reasons.routes.js, apps/api/src/server/appeals/common/controllers/lookup-data.controller.js, apps/api/src/server/appeals/constants.js, apps/api/src/server/appeals/tests/data.js, apps/api/src/server/repositories/appeal.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
Create new endpoint to save the appellant case validation outcome.
- Add PATCH endpoint to save the outcome - `http://localhost:3000/appeals/:appealId/appellant-cases/:appellantCaseId`
- Update the following fields:
- validation outcome
- other not valid reasons
- incomplete reasons when outcome is incomplete
- invalid reasons when outcome is invalid
- Add validation
- Add unit tests to test scenarios for success and validation errors
- Add test data
- Add GET endpoint to fetch the appellant case incomplete reasons - `http://localhost:3000/appeals/appellant-case-incomplete-reasons`
- Add GET endpoint to fetch the appellant case invalid reasons - `http://localhost:3000/appeals/appellant-case-invalid-reasons`
- Update swagger - [http://localhost:3000/api-docs](http://localhost:3000/api-docs) …
=> feat(api): update appeals api to add the saving of appellant case outome

apps/web/.env.development, apps/web/.env.production, apps/web/.env.test, apps/web/environment/config.d.ts, apps/web/environment/config.js, apps/web/environment/schema.js, apps/web/src/server/lib/msal.js
=> fix(web): provide host from env variable

apps/web/environment/config.d.ts, apps/web/environment/schema.js
=> fix(web): hostname validation

.eslintignore, appeals/api/.gitignore, appeals/api/package.json, appeals/api/setup-tests.js, appeals/api/src/database/schema.d.ts, appeals/api/src/database/schema.prisma, appeals/api/src/database/seed/data-static.js, appeals/api/src/database/seed/data-test.js, appeals/api/src/database/seed/seed-clear.js, appeals/api/src/server/repositories/appeal.repository.js, appeals/api/src/server/repositories/case.repository.js, appeals/api/src/server/repositories/document-metadata.repository.js, appeals/api/src/server/repositories/document.repository.js, appeals/api/src/server/repositories/examination-timetable-items.repository.js, appeals/api/src/server/utils/__tests__/prisma-middleware.test.js, appeals/api/src/server/utils/database-connector.js, appeals/api/src/server/utils/prisma-middleware.js, appeals/api/src/server/utils/prisma-middleware/index.js
Generates prisma client in ./appeals/api/src/server/utils and maps it in package.json
=> chore(appeals/api): local prisma client

azure-pipelines-build.yml, azure-pipelines-deploy-appeals.yml
Updated build pipeline to include appeals api and web conditional builds.
Added deploy pipeline for appeals web and api.
=> chore(appeals): azure build and deploy pipelines

apps/web/src/server/appeals/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, apps/web/src/server/appeals/appellant-case/__tests__/appellant-case.test.js, apps/web/src/server/appeals/appellant-case/appellant-case.controller.js, apps/web/src/server/appeals/appellant-case/appellant-case.router.js, apps/web/src/server/appeals/appellant-case/appellant-case.service.js, apps/web/src/server/appeals/appellant-case/appellant-case.validators.js, apps/web/src/server/views/app/confirmation.njk, apps/web/src/server/views/appeals/appeal/appellant-case.njk
Issue decision functionality for view appellant case page (+ reusable confirmation template)
=> feat(web): issuing appellant case decision (BOAT-186)

apps/api/setup-tests.js, apps/api/src/server/applications/application/representations/attachment/__tests__/delete-attachment.test.js, apps/api/src/server/applications/application/representations/attachment/__tests__/post-attachment.test.js, apps/api/src/server/applications/application/representations/attachment/attachment.controller.js, apps/api/src/server/applications/application/representations/attachment/attachment.route.js, apps/api/src/server/applications/application/representations/attachment/attachment.service.js, apps/api/src/server/applications/application/representations/attachment/attachment.validator.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/repositories/representation.repository.js, apps/api/src/server/swagger-output.json
=> feat(web/applications): add/ delete representations attachment

apps/web/src/server/applications/case/representations/representation/address-details/__tests__/__snapshots__/address-details.test.js.snap, apps/web/src/server/applications/case/representations/representation/address-details/address-details.view-model.js, apps/web/src/server/applications/case/representations/representation/address-details/utils/common-validators.js, apps/web/src/server/applications/case/representations/representation/address-details/utils/get-back-link-url.js, apps/web/src/server/applications/case/representations/representation/address-details/utils/get-stage-params.js, apps/web/src/server/views/applications/representations/representation/address-details/includes/lookup.include.njk
https://pins-ds.atlassian.net/browse/ASB-1545?atlOrigin=eyJpIjoiOWMxZTM1N2U5MGM2NDAwZmI0ZmQ1ZjNhZDJjYWQ3NjQiLCJwIjoiaiJ9
=> ASB-1545: Address details - Don't have a UK postcode?

apps/web/src/styles/7-components/_table.scss
=> fix(web/applications): fix css breaking build

appeals/api/src/database/seed/data-test.js
Updated appellant case validation outcome model and field naming in the test data used for seeding
=> fix(api): update appellant case validation outcome model and field naming in test data script

appeals/web/scripts/rollup/get-logger.js
Same as https://github.com/Planning-Inspectorate/back-office/pull/1079, for appeals. (yes we need some shared code...)
N/A
=> fix(appeals/web): change colour for warning log to one that exists

appeals/web/src/server/appeals/appeals.router.js
Incorrect reference left after split...
=> fix(web/appeals): deps imports

apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap, apps/web/src/server/views/applications/case-timetable/components/timetable-items-list.component.njk
Change the big E to a little e
=> fix(web): fix typo in pre-exam timetable (#921)

azure-pipelines-deploy.yml
Pipeline fix and aligned naming conventions
=> chore(appeals): pipeline fixes

appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/__snapshots__/lpa-questionnaire-review.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/lpa-questionnaire-review.test.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.controller.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.router.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.service.js
Updated the Appeals LPAQ Review journey for the 'Complete' path to integrate with the API to save the data
Updated unit tests
https://pins-ds.atlassian.net/browse/BOAT-133
=> feat(appeals/web): integrate lpa review complete process with the api to save the outcome

apps/api/src/server/applications/application/project-updates/project-updates.controller.js, apps/api/src/server/utils/query/__tests__/sort-by.test.js, apps/api/src/server/utils/query/sort-by.js
Project updates bug slipped through, sortBy became 'undefined' as a string, which breaks things.
N/A
=> fix(api): don't convert undefined to a string

apps/api/src/database/seed/seed-clear.js
=> fix(api/applications): seed delete representation attachment

apps/functions/handle-subscriptions/handle-subscription-command/__tests__/handle-subscription-command.test.js, apps/functions/handle-subscriptions/handle-subscription-command/function.json, apps/functions/handle-subscriptions/handle-subscription-command/index.js
handle-subscription function needs a connection string of `ServiceBusConnection`. Also, use `.js` for imports.
N/A
=> fix(functions): subscription connection string

azure-pipelines-build.yml
More fixes... we'll sort the function build process properly soon.
N/A
=> build: don't fail on mv if already exists

apps/functions/handle-subscriptions/handle-subscription-command/__tests__/handle-subscription-command.test.js, apps/functions/handle-subscriptions/handle-subscription-command/index.js
I misunderstood how the function context and message types worked. This should fix that.
Application properties are in `context.bindingData`, and the message is just the raw message.
N/A
=> fix(functions): handle subscription context correctly

.gitignore, .vscode/settings.json
`.vscode/settings.json` is designed to be shared, don't gitignore it.
Also fix an issue where vscode won't add file extensions to imports by defaults, but node module resolution requires it for imports.
N/A
=> chore(tooling): share vscode project settings

apps/api/src/server/applications/documents/documents.service.js, apps/functions/document-publish/publish-document/__tests__/publish-document.test.js
=> fix(api): add trailing extension to imports

apps/functions/document-publish/publish-document/index.js
=> fix(api): fix import for blob client

apps/api/src/server/applications/application/representations/redact/redact.controller.js, apps/api/src/server/applications/application/representations/redact/redact.mapper.js, apps/api/src/server/applications/application/representations/redact/redact.route.js, apps/api/src/server/applications/application/representations/redact/redact.validators.js, apps/api/src/server/swagger-output.json, apps/web/src/server/applications/case/representations/representation-details/change-redaction/__tests__/change-redaction.test.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.controller.js, apps/web/src/server/applications/case/representations/representation-details/change-redaction/change-redaction.service.js
=> feat(api/applications): representation redact status patch

apps/web/src/server/applications/case/representations/representation-details/__fixtures__/representation-details.fixture.js, apps/web/src/server/applications/case/representations/representation-details/__tests__/application-representation-details.view-model.unit.test.js, apps/web/src/server/applications/case/representations/representation-details/application-representation-details.view-model.js, apps/web/src/server/applications/case/representations/representation-details/applications-relevant-rep-details.controller.js, apps/web/src/server/views/applications/representations/representation-details/components/agent-contact.njk, apps/web/src/server/views/applications/representations/representation-details/components/represented-section.njk, apps/web/src/server/views/applications/representations/representation-details/representation-details.njk
https://pins-ds.atlassian.net/browse/ASB-1476?atlOrigin=eyJpIjoiNzAwNmNkMTNkMDk4NDA0MThiZGIxNDczMWY2M2FjZTAiLCJwIjoiaiJ9
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1299
=> ASB-1476: Change order of data items on RR summary/check your answers page (Under 18 and on behalf of)

apps/api/src/server/applications/application/representations/redact/__tests__/patch-redact.test.js, apps/api/src/server/applications/application/representations/representation.validators.js, apps/api/src/server/applications/application/representations/representations.routes.js, apps/api/src/server/applications/application/representations/status/__tests__/patch-status.test.js, apps/api/src/server/applications/application/representations/status/status.controller.js, apps/api/src/server/applications/application/representations/status/status.mapper.js, apps/api/src/server/applications/application/representations/status/status.route.js, apps/api/src/server/applications/application/representations/status/status.service.js, apps/api/src/server/applications/application/representations/status/status.validator.js, apps/api/src/server/repositories/representation.repository.js, apps/api/src/server/swagger-output.json
=> feat(api/applications): representation status patch

apps/api/src/server/applications/application/representations/status/status.route.js, apps/api/src/server/swagger-output.json
=> feat(web/applications): representation status swagger doc fix

apps/functions/document-publish/publish-document/__tests__/publish-document.test.js, apps/functions/document-publish/publish-document/index.js
=> fix(api): remove prefix forward-slash

apps/api/src/server/applications/examination-timetable-items/__tests__/examination-timetable-items.test.js, apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.controller.js, apps/api/src/server/applications/examination-timetable-items/examination-timetable-items.routes.js, apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap, apps/web/src/server/applications/case/examination-timetable/__tests__/applications-timetable.test.js, apps/web/src/server/applications/case/examination-timetable/applications-timetable.controller.js, apps/web/src/server/applications/case/examination-timetable/applications-timetable.router.js, apps/web/src/server/applications/case/examination-timetable/applications-timetable.service.js, apps/web/src/server/views/applications/case-timetable/timetable-list.njk, apps/web/src/server/views/applications/case-timetable/timetable-preview.njk
Unpublish timetable screens, api updates and tests
https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?isInsightsOpen=true&selectedIssue=BOAS-968
https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?isInsightsOpen=true&selectedIssue=BOAS-969
=> Feature/boas 968 unpublish examination timetable and BOAS-969 (success screen)

apps/web/src/server/applications/case/representations/representation-details/__fixtures__/representation-details.fixture.js, apps/web/src/server/applications/case/representations/representation-details/__tests__/application-representation-details.view-model.unit.test.js, apps/web/src/server/applications/case/representations/representation-details/application-representation-details.view-model.js, apps/web/src/server/applications/case/representations/representation-details/applications-relevant-rep-details.controller.js, apps/web/src/server/applications/case/representations/representation-details/applications-relevant-rep-details.service.js, apps/web/src/server/views/applications/representations/representation-details/components/attachments.njk, apps/web/src/server/views/applications/representations/representation-details/representation-details.njk
=> feat(web/applications): representation upload change link

apps/web/src/server/applications/case/representations/representation-details/__fixtures__/representation-details.fixture.js, apps/web/src/server/applications/case/representations/representation-details/__tests__/application-representation-details.view-model.unit.test.js, apps/web/src/server/applications/case/representations/representation-details/application-representation-details.view-model.js, apps/web/src/server/views/applications/representations/representation-details/components/represented-section.njk
…ls page
https://pins-ds.atlassian.net/browse/ASB-1582?atlOrigin=eyJpIjoiYmRmMGI5NjNkNzMzNDA2NDg1YWM4NDk2ZWQ5ZWY1NWYiLCJwIjoiaiJ9
=> ASB-1582: Address not being updated fully when changing address details 

apps/web/src/server/applications/case/representations/__tests__/__snapshots__/applications-representaions.test.js.snap, apps/web/src/server/applications/case/representations/__tests__/application-representations.view-model.unit.test.js, apps/web/src/server/applications/case/representations/application-representations.view-model.js, apps/web/src/server/applications/case/representations/applications-relevant-reps.controller.js, apps/web/src/server/applications/case/representations/representation-details/applications-relevant-rep-details.controller.js, apps/web/src/server/applications/case/representations/representation/attachment-upload/__tests__/__snapshots__/attachment-upload.controller.test.js.snap, apps/web/src/server/applications/case/representations/representation/attachment-upload/__tests__/attachment-upload.controller.test.js, apps/web/src/server/applications/case/representations/representation/attachment-upload/attachment-upload.controller.js, apps/web/src/server/applications/case/representations/representation/attachment-upload/attachment-upload.router.js, apps/web/src/server/applications/case/representations/representation/check-answers/check-answers.controller.js, apps/web/src/server/applications/case/representations/representation/check-answers/check-answers.view-model.js, apps/web/src/server/applications/case/representations/representation/utils/get-page-links.js, apps/web/src/server/applications/case/representations/utils/get-final-rep-page-url.js, apps/web/src/server/applications/case/representations/utils/get-rep-mode-links.js, apps/web/src/server/views/applications/representations/components/table/representations-table.component.njk
https://pins-ds.atlassian.net/browse/ASB-1586?atlOrigin=eyJpIjoiNDI2MGFkN2FiYWRlNGZmNmIyYjg4MjBjMmQ1ZDA3ZmUiLCJwIjoiaiJ9
=> ASB-1586 Representation Routing

apps/web/src/server/applications/case/examination-timetable/applications-timetable.service.js
Error state added for publish and unpublish: 
https://pins-ds.atlassian.net/jira/software/projects/BOAS/boards/172?isInsightsOpen=true&selectedIssue=BOAS-969
=> feat(web): boas-968 - ensure error message correct

apps/web/src/server/applications/case/representations/representation/check-answers/check-answers.validators.js
https://pins-ds.atlassian.net/browse/ASB-1595?atlOrigin=eyJpIjoiOTljMjAzMjRmYjc5NGUzZDkyY2ZiZmZhNmE4NjkyZTkiLCJwIjoiaiJ9
=> Fix: Check if person or agent type exist

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/views/appeals/appeal/appeal-details.njk, appeals/web/src/server/views/appeals/components/status-tag.njk
=> fix(web): amend spacing of text and status tag below case details heading

apps/web/src/server/applications/case/representations/representation/attachment-upload/__tests__/__snapshots__/attachment-upload.controller.test.js.snap, apps/web/src/server/views/applications/representations/representation/attachment-upload.njk
=> fix(web/applications): text changes on attachment upload page

apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/case/documentation/applications-documentation.router.js, apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk, apps/web/src/server/views/applications/case-documentation/properties/tab-details.component.njk, apps/web/src/server/views/applications/case-documentation/properties/tab-history.component.njk, apps/web/src/styles/7-components/_table.scss, apps/web/testing/applications/fixtures/documentation-files.js
=> feat(web/applications): add table for versions history (boas-904)

appeals/api/src/server/endpoints/appeals/__tests__/appellant-cases.test.js
Update the unit tests for the timetable calculation
=> fix(appeals/api): update timetable calculation unit tests

.vscode/launch.json, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/__snapshots__/lpa-questionnaire-review.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.controller.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.mapper.js, appeals/web/src/server/appeals/appeals.types.d.ts, appeals/web/src/server/appeals/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appellant-case/__tests__/appellant-case.test.js, appeals/web/src/server/appeals/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appellant-case/appellant-case.mapper.js, appeals/web/src/server/appeals/appellant-case/appellant-case.router.js, appeals/web/src/server/appeals/appellant-case/appellant-case.service.js, appeals/web/src/server/appeals/appellant-case/appellant-case.validators.js, appeals/web/src/server/lib/__tests__/libraries.test.js, appeals/web/src/server/lib/nunjucks-filters/checkbox-item-parameter-add-conditional-html.js, appeals/web/src/server/lib/nunjucks-filters/index.js, appeals/web/src/server/lib/nunjucks-template-builders/summary-list-builder.js, appeals/web/src/server/lib/object-utilities.js, appeals/web/src/server/views/app/check-and-confirm.njk, appeals/web/src/server/views/app/confirmation.njk, appeals/web/src/server/views/appeals/appeal/appellant-case-invalid.njk, appeals/web/testing/app/fixtures/referencedata.js, appeals/web/typings.d.ts
appellant case issuing valid decision (BOAT-234)
BOAT-234
=> feat(web): appellant case issuing invalid decision (BOAT-234)

appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js, appeals/web/src/server/appeals/national-list/national-list.controller.js, appeals/web/src/server/appeals/national-list/national-list.service.js, appeals/web/src/server/views/appeals/all-appeals/dashboard.njk
national list search
https://pins-ds.atlassian.net/browse/BOAT-240
=> feat(web): BOAT-240 national list search

apps/web/src/server/app/auth/auth-session.service.js, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/views/applications/case-documentation/properties/tab-history.component.njk, apps/web/testing/applications/fixtures/documentation-files.js
=> feat(web/applications): change structure for versioning data (boas-1009)

apps/web/src/client/components/html-content-editor/__tests__/html-content-editor.test.js, apps/web/src/client/components/html-content-editor/html-content-editor.js, apps/web/src/server/applications/case/project-updates/project-updates.mapper.js
Bug fix for creating a project update. The HTML form data was blocked by the firewall. Instead, we send it uri-encoded (which form data should be).
[ASB-1517](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1517)
[ASB-1517]: https://pins-ds.atlassian.net/browse/ASB-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(web): uri-encode html form data

apps/web/src/client/components/html-content-editor/html-content-editor.js, apps/web/src/server/applications/case/project-updates/project-updates.validators.js
Previous fix (https://github.com/Planning-Inspectorate/back-office/pull/1172) forgot to take validation & errors into account.
=> fix(web): decode form contents before validation

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/views/appeals/appeal/appeal-details.njk
https://pins-ds.atlassian.net/browse/BOAT-216
=> BOAT-216 fixed typo

apps/web/src/server/applications/applications.router.js, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/case/documentation/__tests__/__snapshots__/applications-documentation.test.js.snap, apps/web/src/server/applications/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/case/documentation/applications-documentation.guard.js, apps/web/src/server/applications/case/documentation/applications-documentation.router.js, apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap, apps/web/src/server/applications/case/s51/__tests__/applications-s51.test.js, apps/web/src/server/applications/case/s51/applications-s51.controller.js, apps/web/src/server/applications/case/s51/applications-s51.router.js, apps/web/src/server/applications/case/s51/applications-s51.session.js, apps/web/src/server/applications/case/s51/applications-s51.validators.js, apps/web/src/server/lib/nunjucks-filters/url.js, apps/web/src/server/views/applications/case-documentation/folder/documentation-folder.njk, apps/web/src/server/views/applications/case-documentation/folder/folder-header.component.njk, apps/web/src/server/views/applications/case-documentation/folder/folder-status.component.njk, apps/web/src/server/views/applications/case-s51/s51-advice-details.njk, apps/web/src/server/views/applications/case-s51/s51-enquirer.njk, apps/web/src/server/views/applications/case-s51/s51-enquiry-details.njk, apps/web/src/server/views/applications/case-s51/s51-method.njk, apps/web/src/server/views/applications/case-s51/s51-person.njk, apps/web/src/server/views/applications/case-s51/s51-title.njk, apps/web/testing/applications/fixtures/options-item.js
=> feat(web/applications): create s51 pages (boas-981)

appeals/web/src/server/app/components/file-downloader.component.js
Fix the download URL after changes to the documentURI full path.
=> fix(appeals/web): document download storage path

commitlint.config.cjs
Update commit scopes:
- to reflect new structure (e.g. `applications/api`)
- to remove specific package names (in favour of `packages/*`)
- to add new test scopes: `test/api`, `test/e2e`
- to support chore(deps) dependabot commits
N/A
=> chore(tooling): update commit scopes for new format

apps/api/setup-tests.js, apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js, apps/api/src/server/applications/application/project-updates/project-updates.controller.js, apps/api/src/server/applications/application/project-updates/project-updates.mapper.js, apps/api/src/server/applications/application/project-updates/project-updates.service.js, apps/api/src/server/repositories/project-update.respository.js, packages/applications/lib/application/project-update.js
Send publish (and unpublish) events when the status is set to publish.
[ASB-1527](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1527)
[ASB-1527]: https://pins-ds.atlassian.net/browse/ASB-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(api): publish project-updates api

apps/api/src/database/migrations/20230718132204_unique_document_reference/migration.sql, apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js, apps/api/src/server/applications/application/documents/__tests__/store-document-metadata.test.js, apps/api/src/server/applications/application/file-folders/__tests__/get-folder-details.test.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/api/src/server/utils/mapping/map-document-details.js, apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
Add document reference to the document properties page
* chore(api/applications): add documentReference to document properties
* feat(web): render the document reference to the document properties page
* chore(api/applications): generate a migration from the Prisma changes
* chore(api/applications): fix failing unit tests caused by documentRef
[BOAS-770](https://pins-ds.atlassian.net/browse/BOAS-770)
[BOAS-770]: https://pins-ds.atlassian.net/browse/BOAS-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature(web): add document reference to the document properties page

apps/api/src/database/migrations/20230719092654_non_unique_reference/migration.sql, apps/api/src/database/schema.prisma, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/applications/documents/documents.service.js, apps/api/src/server/repositories/document.repository.js
* fix(api/applications): remove unique constraint from Document reference
* chore(api/applications): obtain documents by caseid directly
* fix(api/applications): fix logic error when finding next doc reference
The unique constraint can be added back later
=> fix(api/applications): remove unique constraint from Document reference

apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js, apps/api/src/server/applications/application/project-updates/project-updates.controller.js, apps/api/src/server/applications/application/project-updates/project-updates.mapper.js
Check content immediately before sending any events.
N/A
=> fix(applications/api): check project-update content is safe

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
Fix for issue where appellant case review outcome data was incorrectly persisted from session to other appealIds and outcomes
BOAT-320
=> fix(web): fix for BOAT-320

appeals/api/src/database/schema.d.ts, appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js, appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js, appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js, appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js, appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js, appeals/api/src/server/openapi.json, appeals/api/src/server/repositories/appeal.repository.js, appeals/api/src/server/swagger.js, appeals/api/src/server/tests/data.js, appeals/api/src/server/utils/create-validation-outcome-response.js
Added validation outcome to the Appellant Case GET endpoint response
Also updated the validation outcome in the LPAQ GET endpoint response to be consistant with the Appellant Case
https://pins-ds.atlassian.net/browse/BOAT-335
=> feat(appeals/api): return appellant case validation outcome

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
fix for BOAT-336 - add review outcome notification banner to appellant case page
BOAT-336
=> fix(web): add review outcome notification banner to appellant case page

appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js, appeals/web/src/server/appeals/national-list/national-list.controller.js, appeals/web/src/server/views/app/dashboard.njk, appeals/web/src/server/views/app/layouts/app.layout.njk, appeals/web/src/server/views/appeals/all-appeals/dashboard.njk, packages/appeals/types/appeal.d.ts
https://pins-ds.atlassian.net/browse/BOAT-240
=> BOAT-240: feat(web): search misc functionality

apps/api/src/database/seed/util.js
Fixes to the DB seeding script in Project Updates
-- random dates sometimes fail on month 0
-- random dates fail on single digit day
=> fix(api/applications): seeding invalid dates error (boas-1018)

appeals/web/jsconfig.json, appeals/web/types-session.d.ts, appeals/web/typings.d.ts
Type definition to extend `express-session` data to specify custom session values.
N/A
=> fix(appeals/web): sort out SessionData type definition

commitlint.config.cjs
Allow deps-dev scope so that dependabot commits using this scope are allowed through, e.g. https://github.com/Planning-Inspectorate/back-office/pull/1201
N/A
=> fix(tooling): allow deps-dev scope for depandabot

apps/web/src/client/components/file-uploader/_client-actions.js
=> fix(web): upload file

apps/api/package.json, package-lock.json
=> feat(web/applications): add csv package

appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js, appeals/web/src/server/appeals/national-list/national-list.controller.js
=> fix(web): change 80 char limit to 8

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js, appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js, appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.controller.js, appeals/web/src/server/lib/__tests__/libraries.test.js, appeals/web/src/server/lib/address-formatter.js, appeals/web/src/server/lib/dates.js, appeals/web/src/server/lib/nunjucks-filters/date.js, appeals/web/src/server/lib/nunjucks-template-builders/summary-list-builder.js, appeals/web/src/server/lib/nunjucks-template-builders/table-builder.js, appeals/web/src/server/lib/nunjucks-template-builders/tag-builders.js, appeals/web/src/server/views/appeals/appeal/appeal-details.njk, appeals/web/testing/app/fixtures/referencedata.js, packages/appeals/types/appeal.d.ts
Refactor appeal details page view to use summary list builder
BOAT-313
=> refactor(web): refactor appeal details page view to use summary list builder

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
fix incorrect copy on appellant case valid confirmation page
BOAT-349
=> fix(web): fix incorrect copy on appellant case valid confirmation page

appeals/api/src/server/endpoints/appeals/appeals.formatter.js, appeals/api/src/server/endpoints/constants.js, appeals/api/src/server/state/transition-state.js, appeals/api/src/server/utils/format-documentation-status.js, appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js, appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/__tests__/__snapshots__/lpa-questionnaire-review.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire-review/lpa-questionnaire-review.controller.js
Document status fix: reflects the validation outcome in the UI
https://pins-ds.atlassian.net/browse/BOAT-335
=> fix(web/appeals): document status

docs/fix-duplicate-data-migration.md, docs/prisma-runbook.md
=> docs(api): add runbook for prisma migrations

apps/api/src/message-schemas/events/nsip-project-update.schema.json, apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js, apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js, apps/web/src/server/applications/case/project-updates/project-updates-views.d.ts, apps/web/src/server/applications/case/project-updates/project-updates.controller.js, apps/web/src/server/applications/case/project-updates/project-updates.router.js, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, apps/web/src/server/views/applications/case/project-updates/project-updates-details.njk, apps/web/src/styles/7-components/_summary-list.scss, packages/applications/lib/application/project-update.js, packages/applications/types/project-update.d.ts
Project Update review change, with change links and logic on the edit pages depending on status.
[ASB-1520](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1520)
[ASB-1520]: https://pins-ds.atlassian.net/browse/ASB-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(applications): project update review

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
remove ts-ignore comments previously required to work around session types issue
BOAT-374
=> refactor(web):  remove ts-ignore comments previously required to work around session types issue

apps/api/src/server/applications/application/representations/representation.mapper.js
=> feat(api/applications): redacted notes get all notes

apps/api/src/database/migrations/20230801133050_project_update_type/migration.sql, apps/api/src/database/schema.prisma, apps/api/src/server/applications/application/project-updates/__tests__/project-updates.test.js, apps/api/src/server/applications/application/project-updates/project-updates.mapper.js, apps/api/src/server/applications/application/project-updates/project-updates.validators.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/__tests__/project-updates.test.js, apps/web/src/server/applications/case/project-updates/__tests__/project-updates.view-model.test.js, apps/web/src/server/applications/case/project-updates/project-updates.controller.js, apps/web/src/server/applications/case/project-updates/project-updates.router.js, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, packages/applications/lib/application/project-update.js, packages/applications/types/project-update.d.ts
Project Updates need a type, so the API and types are updated to support this, and web page added to capture the type.
[ASB-1678](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1678)
[ASB-1678]: https://pins-ds.atlassian.net/browse/ASB-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(applications): project updates type page

apps/api/src/server/applications/application/documents/document.routes.js, apps/api/src/server/applications/application/representations/download/rep-download.router.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js
`swagger-autogen` was emitting some warnings about syntax issues. This PR sorts those, and removes a duplication defintion.
N/A
=> fix(api): sort out #swagger comment issues

apps/api/src/message-schemas/commands/new-deadline-submission.schema.json, apps/api/src/message-schemas/events/nsip-exam-timetable-submission.schema.json
* docs(api/applications): add a command schema for deadline submissions
* docs(api/applications): create an event type for deadline submissions
[BOAS-1025](https://pins-ds.atlassian.net/browse/BOAS-1025)
[BOAS-1025]: https://pins-ds.atlassian.net/browse/BOAS-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deadline event schemas

README.md
I had some trouble setting up Azure Data Studio on Mac, so I've added some further instructions to the README.
=> chore(api/applications): add more info about connecting using ADS

apps/api/.env.development, apps/api/.env.production, apps/api/.env.test, apps/api/src/message-schemas/events/nsip-document.schema.json, apps/api/src/server/applications/application/application.validators.js, apps/api/src/server/applications/application/documents/__tests__/document-payload.test.js, apps/api/src/server/applications/application/documents/__tests__/mark-as-published.test.js, apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js, apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.js, apps/api/src/server/applications/application/documents/document.routes.js, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/applications/application/documents/document.validators.js, apps/api/src/server/config/config.js, apps/api/src/server/config/schema.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/functions/document-publish/publish-document/__tests__/publish-document.test.js, apps/functions/document-publish/publish-document/__tests__/test-event.json, apps/functions/document-publish/publish-document/index.js
Also removed the 'path' property from the schema
=> Store published file paths for front office to consume

apps/api/src/server/applications/application/documents/document.js, apps/functions/document-publish/.env.test, apps/functions/document-publish/publish-document/__tests__/publish-document.test.js, apps/functions/document-publish/publish-document/__tests__/test-event.json, apps/functions/document-publish/publish-document/index.js
=> fix(api): add sanitisation for slashes in URI components

apps/api/src/server/applications/application/documents/document.js, apps/functions/document-publish/publish-document/__tests__/publish-document.test.js, apps/functions/document-publish/publish-document/index.js
=> fix(api): use correct endpoint verb for setting document to published

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js, appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js, appeals/web/src/server/appeals/appeal-details/appeal-details.router.js, appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.router.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.validators.js, appeals/web/src/server/appeals/appeals.copy.js, appeals/web/src/server/lib/validators/date-input.validator.js, appeals/web/src/server/lib/validators/time-input.validator.js, appeals/web/src/server/views/app/components/time-input.njk, appeals/web/src/server/views/appeals/appeal/appeal-details.njk, appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk, appeals/web/testing/app/fixtures/referencedata.js
=> feat(web): arrange site visit

apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/repositories/document.repository.js
change count to be scoped to case
=> fix(api): return ready to published based on latest version

apps/web/src/server/applications/case/project-updates/project-updates-views.d.ts, apps/web/src/server/applications/case/project-updates/project-updates.controller.js, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, apps/web/src/server/views/applications/case/project-updates/project-updates-details.njk, apps/web/src/server/views/applications/case/project-updates/project-updates-form.njk
Back links didn't go back to the page you expect
[ASB-1519](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1519)
[ASB-1519]: https://pins-ds.atlassian.net/browse/ASB-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications): project updates back links

docs/front-office-submissions.md
Just a Mermaid diagram for the new submissions function behaviour. Copied from here https://miro.com/app/board/uXjVMx5rqn8=/
=> docs(functions): add Mermaid diagram for how FO submissions are handled

apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/project-updates.controller.js, apps/web/src/server/applications/case/project-updates/project-updates.mapper.js, apps/web/src/server/applications/case/project-updates/project-updates.validators.js, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js
Use a more specific POST field name to allow a specific WAF exception
[ASB-1692](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1692)
[ASB-1692]: https://pins-ds.atlassian.net/browse/ASB-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications/web): use a more specific field name for project updates content

apps/api/src/server/applications/application/documents/document.controller.js
=> fix(api): provide caseId parameter to ready to publish count

azure-pipelines-build.yml
=> fix(api): fix pipeline build issue

appeals/api/src/database/seed/data-static.js
Updated the text of the Appellant Case Incomplete Reasons
https://pins-ds.atlassian.net/browse/BOAT-429
=> fix(appeals/api): update text of appellant case incomplete reasons

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/lib/__tests__/libraries.test.js, appeals/web/src/server/lib/boolean-formatter.js, appeals/web/testing/app/fixtures/referencedata.js
site access accordion fix for null values
BOAT-409
=> fix(web): site access accordion fix for null values

appeals/api/src/database/seed/data-test.js
Update the Appellant Case to remove the status and so it displays in the UI as not yet reviewed for Appeals with a status of Ready to Start.
https://pins-ds.atlassian.net/browse/BOAT-433
=> feat(appeals/api): update the appelant case status in the test data

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
review appellant case copy changes
BOAT-419
=> fix(web): review appellant case copy changes

apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/config/config.js, apps/api/src/server/config/schema.js, apps/api/src/server/repositories/document.repository.js
=> fix(api): log document count

apps/api/src/server/applications/application/documents/__tests__/mark-as-published.test.js, apps/api/src/server/applications/application/documents/document.service.js
=> fix(api): remove endless loop

appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap, appeals/web/src/server/views/appeals/components/appeals-table.njk
national list adjustments
BOAT-321
=> fix(web): national list adjustments

appeals/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/views/app/check-and-confirm.njk, appeals/web/src/server/views/app/components/global-header.njk, appeals/web/src/server/views/app/confirmation.njk, appeals/web/src/server/views/app/layouts/app.layout.njk, appeals/web/src/server/views/appeals/all-appeals/dashboard.njk, appeals/web/src/server/views/appeals/appeal/appeal-details.njk, appeals/web/src/server/views/appeals/appeal/appellant-case.njk, appeals/web/src/server/views/appeals/appeal/lpa-questionnaire.njk, appeals/web/src/styles/7-components/app-header.scss
header adjustments, including changes to column classes on some pages
BOAT-407
BOAT-417
BOAT-418
=> fix(web): header adjustments

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
update linked and other appeals to display short reference
BOAT-421
=> fix(web): update linked and other appeals to display short reference

azure-pipelines-build.yml
=> fix(tooling): deployment pipeline fix

appeals/web/src/server/appeals/national-list/national-list.controller.js
fix 500 error when entering spaces in national list search
BOAT-376
=> fix(web): fix 500 error when entering spaces in national list search

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
update appeal details case timetable "review appeal" link href to point to appellant case page
BOAT-216
=> fix(web): appeal details review appeal link fix

azure-pipelines-build.yml
Change mv commands to recursive copy
=> fix(functions): change mv commands to recursive copy

apps/api/src/database/migrations/20230814101918_s51_advice_document_table/migration.sql, apps/api/src/database/schema.d.ts, apps/api/src/database/schema.prisma, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/applications/s51advice/s51-advice.controller.js, apps/api/src/server/applications/s51advice/s51-advice.routes.js, apps/api/src/server/repositories/s51-advice-document.repository.js, apps/api/src/server/repositories/s51-advice.repository.js, apps/api/src/server/swagger-output.json
[BOAS-1001](https://pins-ds.atlassian.net.mcas.ms/browse/BOAS-1001)
[BOAS-1001]: https://pins-ds.atlassian.net/browse/BOAS-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(api): add endpoint to upload s51 document attachments

apps/web/src/server/applications/case/project-updates/project-updates.controller.js
Back link on delete page should go back to review.
[ASB-1690](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1690)
[ASB-1690]: https://pins-ds.atlassian.net/browse/ASB-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications/web): fix confirm-delete back link

azure-pipelines-build.yml
=> build: fix function build after merge issue

azure-pipelines-build.yml
=> build: fix function build after merge issue - again

apps/functions/notify-subscribers/notify-subscribers/function.json
=> fix(functions): fix notify-subscribers subscription name

apps/web/src/client/components/html-content-editor/html-content-editor.js, apps/web/src/server/app/app.express.js, apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, apps/web/src/server/views/applications/components/html-content-editor.njk
Show a warning message when the recommended character count is exceeded.
[ASB-1751](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1751)
[ASB-1751]: https://pins-ds.atlassian.net/browse/ASB-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications/web): show warning message when exceeding character count

appeals/web/src/server/appeals/appeal-details/appeal-details.middleware.js, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/outcome-incomplete/outcome-incomplete.router.js, appeals/web/src/server/appeals/appeals.types.d.ts, appeals/web/src/server/views/appeals/appeal/update-due-date.njk
https://pins-ds.atlassian.net/browse/BOAT-447
=> feat(web): bOAT-447-lpaq-incomplete-updates

apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js, apps/functions/deadline-submissions/deadline-submission-command/blob-client.js, apps/functions/deadline-submissions/deadline-submission-command/event-client.js, apps/functions/deadline-submissions/deadline-submission-command/index.js, apps/functions/document-check/check-document/event-client.js, apps/functions/document-check/check-document/index.js
=> fix(functions): add .js extension to relative imports

apps/functions/deadline-submissions/deadline-submission-command/function.json
The Azure function isn't being triggered at the moment. I think the function.json config might be incorrect.
=> chore(functions): change direction of binding for deadline submissions

apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js
- Correct reference to API host environment variable
=> fix(functions): correct reference to API host environment variable

apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js
- Improve error logging around API requests for deadline submissions function
=> chore(functions): improve error logging in deadline submissions function

apps/api/src/server/applications/application/application.controller.js, apps/api/src/server/applications/application/application.routes.js
It was returning 404 as the `reference` query argument was being trimmed.
* fix(api/applications): fix root endpoint for querying applications
It was returning 404 as the `reference` query argument was being
trimmed.
=> fix(api/applications): fix root endpoint for querying applications

appeals/api/setup-tests.js, appeals/api/src/server/config/config.js, appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js, appeals/api/src/server/endpoints/constants.js, appeals/api/src/server/utils/notify-client.js
Small update to the GOV Notify integration to use the TEST_MAILBOX env var if it's set
https://pins-ds.atlassian.net/browse/BOAT-463
=> feat(appeals/api): update gov notify integration to use test_mailbox env var if it's set

apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js
Remove unnecessary JSON.parse() after request for timetable items. This is currently throwing an error.
=> fix(functions): remove unnecessary JSON.parse() after GET request

azure-pipelines-e2e-appeals.yml
Fix for Appeals e2e tests. Added new variables to use for Appeals tests
=> ci: fix appeals e2e pipeline, adding correct env vars

azure-pipelines-e2e-appeals.yml
=> Boas 1079 fix appeals pipeline

apps/e2e/cypress/e2e/back-office-appeals/reviewLpaq.spec.js, apps/e2e/cypress/page_objects/appealsListPage.js
##
##(https://pins-ds.atlassian.net/browse/BOAT-236)
=> test(e2e): e2e tests for lpaq incomplete flow

README.md, appeals/api/package.json, apps/api-testing/api-test.sh, apps/api/package.json
- fix `db:seed:prod` to use `cross-env`
- remove `dev:queue:listen` (references a file that doesn't exist)
- rename `swagger-autogen` to `gen-api-spec` to be more descriptive
N/A
=> chore: npm script changes

README.md
Updated the README file with a default value for `TEST_MAILBOX` env var for the Appeals API.
=> chore(appeals): update readme with appeals api test_mailbox env var

appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk
amend copy for details component on schedule site visit page
BOAT-430
=> fix(web): amend copy for details component on schedule site visit page

apps/e2e/cypress/e2e/back-office-applications/documentVersioning.spec.js, apps/e2e/cypress/page_objects/basePage.js, apps/e2e/cypress/page_objects/documentPropertiesPage.js, apps/e2e/cypress/page_objects/uploadFiles.js
E2E Test for document versioning
=> test(e2e): versioning test

azure-pipelines-deploy.yml
=> fix(api): temp revert deployment pipeline

azure-pipelines-deploy.yml
=> fix(tooling): deploy dev, test and prod automatically

appeals/api/src/database/seed/data-static.js
Update the Appellant Case Incomplete Reasons reference data 
https://pins-ds.atlassian.net/browse/BOAT-437
=> fix(appeals/api): update appellant case incomplete reasons reference data

docs/types.md
Add an example of a Prisma type with a relation included.
N/A
=> docs: add prisma type example with relation

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.router.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.router.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.router.js
add routes for appellant case outcome confirmation pages
BOAT-441
=> fix(web): routes for appellant case outcome confirmation pages

azure-pipelines-ci.yml
=> feat(tooling): cache result of build:release

azure-pipelines-build.yml, azure-pipelines-ci.yml, turbo.json
=> feat(tooling): cache result of tscheck

appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/lpa-questionnaire.test.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.controller.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/lpa-questionnaire.router.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/outcome-incomplete/outcome-incomplete.router.js
add routes for lpaq outcome confirmation pages
BOAT-442
=> fix(web): routes for lpaq outcome confirmation pages

apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, apps/web/src/server/views/applications/case/project-updates/project-updates-details.njk, apps/web/src/server/views/applications/case/project-updates/project-updates-form.njk, apps/web/src/server/views/applications/case/project-updates/project-updates-table.njk, apps/web/src/styles/7-components/project-update.scss, apps/web/src/styles/main.scss
Project updates would show with top margin and look odd in a table.
[ASB-1792](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1792)
[ASB-1792]: https://pins-ds.atlassian.net/browse/ASB-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications/web): ensure project updates show in line in table

apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap, apps/web/src/server/views/applications/case-s51/properties/tab-details.component.njk, apps/web/src/server/views/applications/case-s51/s51-check-your-answers.njk
=> fix(web/applications): fix typos on s51 pages (boas-1107)

appeals/api/src/database/migrations/20230905113921_update_lpa_questionnaire/migration.sql, appeals/api/src/database/schema.d.ts, appeals/api/src/database/schema.prisma, appeals/api/src/database/seed/data-samples.js, appeals/api/src/database/seed/data-test.js, appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js, appeals/api/src/server/openapi.json, appeals/api/src/server/swagger.js, appeals/api/src/server/tests/data.js
Update Appeals endpoint to add LPA Questionnaire fields and updating the Listed Building details.
https://pins-ds.atlassian.net/browse/BOAT-490
=> feat(appeals/api): update appeals api to add additional lpa questionnaire fields

appeals/api/src/message-schemas/events/nsip-project.schema.json, apps/api/src/database/migrations/20230906132516_add_key_dates/migration.sql, apps/api/src/database/schema.prisma
=> feat(api): add key dates to prisma schema

apps/functions/deadline-submissions/test-deadline-submission/function.json
Add further config for HTTP trigger.
Manually invoking the function doesn't seem to work without enabling CORS. I suspect properly setting up the function's API endpoint will be simpler.
=> chore(functions): add a function.json file to test-deadline-submissions

apps/api/src/server/repositories/document.repository.js, apps/api/src/server/repositories/s51-advice-document.repository.js
Use originalFilename instead of fileName to check for duplicates.
[BOAS-1119](https://pins-ds.atlassian.net/browse/BOAS-1119)
[BOAS-1119]: https://pins-ds.atlassian.net/browse/BOAS-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(api/applications): use originalFilename to check for duplicates

apps/functions/deadline-submissions/test-deadline-submission/function.json
Change auth level to `anonymous`. This is the lowest level of auth for `httpTrigger`. We could change this later, but I'm getting a 500 at the moment due to auth. Just trying to see if this will get it working.
=> test(functions): change test-deadline-submission to minimal auth

apps/api/src/server/applications/applications.routes.js, apps/api/src/server/applications/key-dates/__tests__/get-key-dates.test.js, apps/api/src/server/applications/key-dates/__tests__/update-key-dates.test.js, apps/api/src/server/applications/key-dates/key-dates.controller.js, apps/api/src/server/applications/key-dates/key-dates.mapper.js, apps/api/src/server/applications/key-dates/key-dates.routes.js, apps/api/src/server/applications/key-dates/key-dates.utils.js, apps/api/src/server/applications/key-dates/key-dates.validators.js, apps/api/src/server/repositories/key-dates.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/api/src/server/utils/mapping/map-date-string-to-unix-timestamp.js, apps/api/src/server/utils/mapping/map-date-to-unix-timestamp.js, apps/api/src/server/utils/mapping/map-unix-timestamp-to-date.js
=> feat(api): endpoints to get and update key dates

apps/api-testing/utils/test-data.js, apps/api/src/server/applications/application/__tests__/create-application.test.js, apps/api/src/server/applications/application/__tests__/get-application-details.test.js, apps/api/src/server/applications/application/__tests__/update-application.test.js, apps/api/src/server/applications/application/application.mapper.js, apps/api/src/server/applications/application/application.validators.js, apps/api/src/server/applications/key-dates/key-dates.controller.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger.js, apps/api/src/server/utils/mapping/map-case-details.js, apps/api/src/server/utils/mapping/map-date-to-unix-timestamp.js, apps/api/src/server/utils/mapping/map-key-dates.js, apps/e2e/cypress/page_objects/createCaseSections/keyDates.js, apps/web/src/server/applications/applications.types.d.ts, apps/web/src/server/applications/common/components/form/form-key-dates.component.js, apps/web/src/server/applications/create-new-case/check-your-answers/applications-create-check-your-answers.service.js, apps/web/src/server/applications/create-new-case/check-your-answers/applications-create-check-your-answers.types.d.ts, apps/web/src/server/applications/create-new-case/key-dates/__tests__/__snapshots__/applications-create-key-dates.test.js.snap, apps/web/src/server/applications/create-new-case/key-dates/__tests__/applications-create-key-dates.test.js, apps/web/src/server/applications/create-new-case/key-dates/applications-create-key-dates.types.d.ts, apps/web/src/server/applications/create-new-case/key-dates/applications-create-key-dates.validators.js, apps/web/src/server/views/applications/case/overview.njk, apps/web/src/server/views/applications/components/case-form/key-dates/date-internal.njk, apps/web/src/server/views/applications/components/case-form/key-dates/date-published.njk, apps/web/src/server/views/applications/create-new-case/check-your-answers.njk, packages/applications/types/application.d.ts
=> feat(api): return all key dates with publish preview

appeals/api/src/server/infrastructure/topics.js, appeals/functions/casedata-import/README.md, appeals/functions/casedata-import/app/back-office-api-client.js, appeals/functions/casedata-import/app/config.js, appeals/functions/casedata-import/app/function.json, appeals/functions/casedata-import/app/index.js, appeals/functions/casedata-import/host.json, appeals/functions/casedata-import/local.settings.json, appeals/functions/casedata-import/package.json, appeals/functions/create-appeal/index.js, appeals/functions/create-document/index.js, appeals/functions/hr-data-import/README.md, appeals/functions/hr-data-import/app/back-office-api-client.js, appeals/functions/hr-data-import/app/config.js, appeals/functions/hr-data-import/app/function.json, appeals/functions/hr-data-import/app/index.js, appeals/functions/hr-data-import/host.json, appeals/functions/hr-data-import/local.settings.json, appeals/functions/hr-data-import/package.json, appeals/functions/lpaq-import/README.md, appeals/functions/lpaq-import/app/back-office-api-client.js, appeals/functions/lpaq-import/app/config.js, appeals/functions/lpaq-import/app/function.json, appeals/functions/lpaq-import/app/index.js, appeals/functions/lpaq-import/host.json, appeals/functions/lpaq-import/local.settings.json, appeals/functions/lpaq-import/package.json, azure-pipelines-build.yml, azure-pipelines-deploy-appeals.yml
New azure function base code for the following integration consumers:
- Appellant case import (data produced by FO)
- LPAQ import (data produced by FO)
- HR import (data produced by ODW)
BOAT-498, BOAT-499, BOAT-500
=> feat(appeals): function pipelines / initial consumer functions

azure-pipelines-build.yml, azure-pipelines-deploy-appeals.yml
=> fix(appeals): pipeline yml format

azure-pipelines-build.yml
=> fix(appeals): pipeline ymp fix 2

apps/api/src/server/applications/application/__tests__/application.test.js, apps/api/src/server/applications/application/application.js, apps/api/src/server/applications/key-dates/__tests__/update-key-dates.test.js, apps/api/src/server/applications/key-dates/key-dates.controller.js
=> feat(api): publish key dates

azure-pipelines-deploy-appeals.yml
=> fix(appeals): deploy pipeline

apps/api/src/server/applications/key-dates/__tests__/update-key-dates.test.js, apps/api/src/server/repositories/key-dates.repository.js
=> fix(api): correct prisma call

azure-pipelines-build.yml
Fixes the deployment of the 'appellant-case' import function.
=> fix(appeals): import casedata definition typo

azure-pipelines-build.yml
=> fix(appeals): typo in azure function definition

azure-pipelines-build.yml
Small fixes to the function install for appeals
=> fix(appeals): azure functions install fix

appeals/functions/casedata-import/package.json, appeals/functions/hr-data-import/package.json, appeals/functions/lpaq-import/package.json, azure-pipelines-build.yml, package-lock.json, package.json
Adds appeals/functions workspace, func typo
=> fix(appeals): workspace for appeals functions

apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap, apps/web/src/server/views/applications/case-s51/properties/tab-details.component.njk
Change format of dates on S51 properties page.
[BOAS-1107](https://pins-ds.atlassian.net/browse/BOAS-1107)
[BOAS-1107]: https://pins-ds.atlassian.net/browse/BOAS-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(web): change date format on S51 properties to dd MMM yyyy

appeals/api/src/server/common/validators/uuid-parameter.js, appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js, appeals/api/src/server/endpoints/appeals/appeals.controller.js, appeals/api/src/server/endpoints/appeals/appeals.service.js, appeals/api/src/server/endpoints/appeals/appeals.validators.js, appeals/api/src/server/repositories/appeal.repository.js
Enable an assigned Case Officer or Inspector to be removed from an Appeal
https://pins-ds.atlassian.net/browse/BOAT-493
=> feat(appeals/api): enable an assigned user to be removed from an appeal

appeals/api/src/server/repositories/integrations.repository.js, appeals/functions/lpaq-import/README.md
Fix a small issue when posting a message from appellant case  FO topic to the integration endpoint.
=> fix(appeals): appellant case integration

.eslintignore, apps/api/package.json, apps/functions/migration/.funcignore, apps/functions/migration/.gitignore, apps/functions/migration/database/copy-schema.js, apps/functions/migration/host.json, apps/functions/migration/jsconfig.json, apps/functions/migration/local.settings.json, apps/functions/migration/package.json, apps/functions/migration/project-updates-migration/function.json, apps/functions/migration/project-updates-migration/index.js, apps/functions/migration/project-updates-migration/src/config.js, apps/functions/migration/project-updates-migration/src/project-updates-migration.js, package-lock.json
Initial migration function with Prisma schema/db access. WIP, merging in stages for testing.
[BOAS-1081](https://pins-ds.atlassian.net/browse/BOAS-1081)
[BOAS-1081]: https://pins-ds.atlassian.net/browse/BOAS-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(applications): add poc migration function

apps/api/src/server/applications/application/application.validators.js, apps/api/src/server/applications/s51advice/s51-advice.routes.js, apps/api/src/server/applications/s51advice/s51-advice.validators.js
Parameters required by updateS51Advice handler are being trimmed.
[BOAS-1135](https://pins-ds.atlassian.net/browse/BOAS-1135)
[BOAS-1135]: https://pins-ds.atlassian.net/browse/BOAS-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(api/applications): fix required params being trimmed

appeals/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap, appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap, appeals/web/src/server/appeals/appeal-details/lpa-questionaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/views/app/components/global-header.njk, appeals/web/src/server/views/app/layouts/app.layout.njk
Fix layout to use 960px instead of 1200px
https://pins-ds.atlassian.net/browse/BOAT-528
=> fix(appeals/web): set layout and header to 960px

apps/functions/deadline-submissions/test-deadline-submission/index.js
It would be useful for Kim and Ola to be able to create a fake FO message that relates to a real line item. This will allow them to pass query strings to the test function.
[BOAS-1110](https://pins-ds.atlassian.net/browse/BOAS-1110)
[BOAS-1110]: https://pins-ds.atlassian.net/browse/BOAS-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(functions): allow test-deadline-submission function to take args

README.md, appeals/functions/casedata-import/README.md, appeals/functions/hr-data-import/README.md, appeals/functions/lpaq-import/README.md, docs/azurite-blob-emulator.md, docs/enabling-ad-locally.md, docs/self-signed-ssl.md, docs/uploading-files.md
- Added more specific info on running appeals vs applications
- Added guides on SSL, running over HTTPS and AD
=> docs(appeals): updated docs

apps/functions/deadline-submissions/deadline-submission-command/back-office-api-client.js, apps/functions/deadline-submissions/test-deadline-submission/index.js
- Allow the case reference to be specified to the deadline submissions test script.
- Make sure all folders for a case are returned in the deadline submissions function, not just top level folders.
Tested by making these changes in the 'Code + Test' section of Azure console before committing.
[BOAS-1110](https://pins-ds.atlassian.net/browse/BOAS-1110)
[BOAS-1110]: https://pins-ds.atlassian.net/browse/BOAS-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deadline submission changes

azure-pipelines-build.yml
=> fix(tooling): fix migration function build

apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> fix(api): use context.log instead of console.log

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/applications/case/examination-timetable/__tests__/__snapshots__/applications-timetable.test.js.snap, apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap, apps/web/src/server/views/applications/case/components/case-page-navigation.component.njk
Remove the 'Fees' item from the case navigation.
[BOAS-1058](https://pins-ds.atlassian.net/browse/BOAS-1058)
[BOAS-1058]: https://pins-ds.atlassian.net/browse/BOAS-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(web/applications): remove 'Fees' item from the case navigation

apps/functions/applications-migration/project-updates-migration/index.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> feat(api): implement queries for project updates

apps/api/src/database/migrations/20230918102414_project_update_content_size_increase/migration.sql, apps/api/src/database/schema.prisma, apps/api/src/server/migration/README.md, apps/api/src/server/migration/migrators/nsip-project-update-migrator.js, apps/api/src/server/migration/migrators/utils.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js, packages/event-client/src/service-bus-event-client.js
Some fixes to project updates migration which were found during end-to-end testing. Also refactoring from previous PR, plus additional refactoring to make some code re-usable for nsip subscriptions migration (which is still a WIP)
=> fix(api): fixes and refactoring for project updates migration

package-lock.json
Fix package-lock after bad merge resolution.
=> fix(tooling): package-lock changes for swagger-typescript-api

appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js, appeals/api/src/server/endpoints/appeals/appeals.formatter.js, appeals/api/src/server/openapi-types.ts, appeals/api/src/server/openapi.json, appeals/api/src/server/swagger.js
Update GET Appeal API endpoint to return `firstName` and `lastName` for each of the Neighbouring Site contacts.
https://pins-ds.atlassian.net/browse/BOAT-530
=> feat(appeals/api): update the get appeal endpoint to return the neighbouring contact name

apps/api/src/database/migrations/20230918123521_subscriptions_migrated_id/migration.sql, apps/api/src/database/schema.prisma, apps/api/src/server/migration/migrator.service.js, apps/api/src/server/migration/migrators/nsip-subscription-migrator.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
Migrate NSIP Subscription entities into Back Office Subscribers.
=> feat(api): migrate project subscriptions

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js, appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.service.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js, appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
fix 500 error when viewing appellant case page with existing outcome
BOAT-536
=> fix(web): fix 500 error when viewing appellant case page with existing outcome

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js, apps/api/src/server/migration/migrators/nsip-subscription-migrator.js
=> fix(api): publish correct event types for updates

apps/api/src/server/applications/application/application.controller.js, apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/applications/common/services/case.service.js, apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk, apps/web/src/server/views/applications/case/preview-and-publish.njk
* feat(web/applications): render key dates on Preview & Publish page
* refactor(web/applications): improve concision of methods in case service
* feat(api/applications): return 404 if case is not found when publishing
* test(web/applications): update test snapshots
[BOAS-1043](https://pins-ds.atlassian.net/browse/BOAS-1043)
[BOAS-1043]: https://pins-ds.atlassian.net/browse/BOAS-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Display key dates on Preview & Publish page

apps/functions/applications-migration/project-updates-migration/src/back-office-api-client.js
=> fix(api): don't resolve body

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js, apps/api/src/server/migration/migrators/nsip-subscription-migrator.js, apps/api/src/server/migration/migrators/utils.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
Create a default case for subscriptions
=> fix(api): create default case for subscriptions

apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> fix(api): fix case stage mapping on subscriptions

apps/api/src/server/applications/subscriptions/subscriptions.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
remove duplicate records from tags
remove sensitive console log
=> fix(api): migrate draft updates

apps/api/src/server/applications/s51advice/s51-advice.controller.js, apps/api/src/server/migration/migrators/nsip-project-update-migrator.js
=> fix(api): don't publish drafts

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> fix(api): write out html content of banners

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js, apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> fix(api): manually replace control characters with line breaks

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js
=> fix(api): replace all newlines

appeals/api/src/server/config/config.js, appeals/api/src/server/config/schema.js, appeals/api/src/server/endpoints/integrations/integrations.controller.js, appeals/api/src/server/endpoints/integrations/integrations.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/appellant-case.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/casedata.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/index.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/lpa.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.routes.js, appeals/api/src/server/endpoints/integrations/integrations.service.js, appeals/api/src/server/openapi.json, appeals/api/src/server/repositories/integrations.repository.js, appeals/functions/casedata-import/app/back-office-api-client.js, appeals/functions/hr-data-import/app/back-office-api-client.js, appeals/functions/lpaq-import/app/back-office-api-client.js
Integration progress / POC: publishes appeal to service bus
Progress towards BOAT-283
=> feat(appeals): integration progress

apps/web/src/server/lib/nunjucks-filters/date.js, apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk
Format key dates using `displayDate` function
[BOAS-1177](https://pins-ds.atlassian.net/browse/BOAS-1177)
[BOAS-1177]: https://pins-ds.atlassian.net/browse/BOAS-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(web/applications): properly format key dates during preview

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/allocation-details/__tests__/__snapshots__/allocation-details.test.js.snap, appeals/web/src/server/appeals/appeal-details/allocation-details/__tests__/allocation-details.test.js, appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.controller.js, appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.mapper.js, appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.router.js, appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.service.js, appeals/web/src/server/appeals/appeal-details/allocation-details/allocation-details.validators.js, appeals/web/src/server/appeals/appeal-details/appeal-details.router.js, appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/appeals/appeal.constants.js, appeals/web/src/server/lib/mappers/appeal.mapper.js, appeals/web/src/server/views/patterns/display-page.pattern.njk, appeals/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/BOAT-346
=> feat(web): allocation details inspector score

appeals/functions/hr-data-import/app/index.js, appeals/functions/lpaq-import/app/index.js
Update the function to accept `EventType.Update`
=> fix(appeals): lpaq import function to accept EventType.Update

apps/api/src/server/migration/migrators/nsip-project-update-migrator.js
=> fix(api): manually replace http links with https

apps/web/src/server/applications/case/s51/__tests__/__snapshots__/applications-s51.test.js.snap, apps/web/src/server/applications/case/s51/__tests__/applications-s51.test.js, apps/web/src/server/applications/case/s51/applications-s51.controller.js, apps/web/src/server/applications/case/s51/applications-s51.router.js, apps/web/src/server/applications/case/s51/applications-s51.service.js, apps/web/src/server/lib/nunjucks-filters/url.js, apps/web/src/server/views/applications/case-s51/components/enquirer-string.njk, apps/web/src/server/views/applications/case-s51/properties/s51-properties.njk, apps/web/src/server/views/applications/case-s51/properties/tab-attachments.component.njk, apps/web/src/server/views/applications/case-s51/properties/tab-details.component.njk, apps/web/src/server/views/applications/case-s51/s51-delete-attachment.njk, apps/web/src/server/views/applications/case-s51/s51-delete.njk, apps/web/src/server/views/applications/case-s51/s51-publishing-queue.njk, apps/web/src/server/views/applications/components/folder/folder-status.component.njk
=> feat(web/applications): add page to delete s51 (boas-1057)

README.md, appeals/api/.env.example, apps/api/.env.example
=> chore(tooling): add .env.example for api apps

appeals/api/src/server/config/schema.js, apps/api/src/server/config/schema.js
Validate api config before app start - i.e. set fields to required that are required.
[BOAS-1100](https://pins-ds.atlassian.net/browse/BOAS-1100)
[BOAS-1100]: https://pins-ds.atlassian.net/browse/BOAS-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(api): ensure required fields are checked before start

apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk
This date can be in any text format (e.g. Q4 2023)
* fix(web/applications): do not attempt to format submissionAtPublished
This date can be in any text format (e.g. Q4 2023)
This is likely the issue causing the error Ola was seeing when trying to publish.
=> fix(web/applications): do not attempt to format submissionAtPublished

apps/web/src/server/applications/case/project-updates/__tests__/__snapshots__/project-updates.test.js.snap, apps/web/src/server/applications/case/project-updates/project-updates.view-model.js, packages/applications/lib/application/project-update.js
Labels & values didn't match for Project Update Type.
[ASB-1854](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1854)
[ASB-1854]: https://pins-ds.atlassian.net/browse/ASB-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications/web): ensure project update type labels match the value

apps/api/src/server/applications/subscriptions/subscriptions.controller.js, apps/api/src/server/applications/subscriptions/subscriptions.routes.js, apps/api/src/server/applications/subscriptions/subscriptions.validators.js, apps/api/src/server/repositories/subscription.respository.js, apps/api/src/server/swagger-output.json, apps/functions/notify-subscribers/notify-subscribers/src/back-office-api-client.js, apps/functions/notify-subscribers/notify-subscribers/src/notify-subscribers.js
Previously we weren't filtering subscriptions based on `endDate`, which is how unsubscribe is handled. So we'd notify people who had unsubscribed!
[ASB-1898](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-1898)
[ASB-1898]: https://pins-ds.atlassian.net/browse/ASB-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications): don't notify unsubscribed subscribers

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/views/applications/case/components/case-applicant-table.component.njk, apps/web/src/server/views/applications/case/components/case-info-table-preview.component.njk, apps/web/src/server/views/applications/case/components/case-info-table.component.njk, apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk, apps/web/src/server/views/applications/case/preview-and-publish.njk, apps/web/src/styles/7-components/_preview-table.scss, apps/web/src/styles/main.scss
=> feat(web/applications): update the preview and publish page (boas-1112)

apps/web/src/server/applications/case/documentation-metadata/__tests__/__snapshots__/documentation-metadata.test.js.snap, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.controller.js
=> feat(web/applications): add two metadata types (boas-1166)

appeals/api/src/server/config/config.js, appeals/api/src/server/config/schema.js, appeals/api/src/server/endpoints/integrations/integrations.controller.js, appeals/api/src/server/endpoints/integrations/integrations.mapper.js
- Removes flag to disable integration (this is controlled by an existing app setting, and locally only logs the message out)
- Map reference to caseReference
=> fix(appeals/api): mapping caseRef and removing integration flag

appeals/api/src/database/seed/seed-clear.js
Updated the clear seed script to delete Users earlier so we avoid constraint issue with linked tables.
=> fix(appeals/api): delete users earlier in the seeding to avoid constraint issues

appeals/api/src/database/seed/data-samples.js
=> fix(appeals/api): remove config set test mailbox from seeding

appeals/api/src/database/seed/seed-development.js, appeals/api/src/database/seed/seed-production.js, apps/api/src/database/seed/seed-development.js, apps/api/src/database/seed/seed-production.js
don't load all app config for seeding
=> fix(tooling): don't load all app config for seeding

appeals/api/src/server/config/config.js, appeals/api/src/server/config/schema.js, appeals/api/src/server/endpoints/constants.js, appeals/api/src/server/utils/business-days.js
Bankholiday feed in constant to avoid loading config in db:seed
=> chore(appeals/api): moved bank holiday feed to static const

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/applications/case/__tests__/applications-case.test.js, apps/web/src/server/applications/case/applications-case.controller.js, apps/web/src/server/applications/case/key-dates/__tests__/__snapshots__/applications-key-dates.test.js.snap, apps/web/src/server/lib/nunjucks-filters/key-dates-property.js, apps/web/src/server/views/applications/case/layouts/applications-case-layout.njk, apps/web/src/server/views/applications/case/project-information.njk, apps/web/src/server/views/applications/case/project-success-banner.njk
=> fix(web/applications): add publishing success page (boas-1206)

apps/api/src/server/applications/application/documents/__tests__/publish-document.test.js, apps/api/src/server/applications/application/documents/__tests__/update-document-status.test.js, apps/api/src/server/applications/application/documents/document.controller.js, apps/api/src/server/applications/application/documents/document.routes.js, apps/api/src/server/applications/application/documents/document.service.js, apps/api/src/server/applications/application/documents/document.validators.js, apps/api/src/server/repositories/document-metadata.repository.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger-types.ts, apps/web/src/server/applications/case/documentation-metadata/__tests__/documentation-metadata.test.js, apps/web/src/server/applications/case/documentation-metadata/documentation-metadata.service.js, apps/web/src/server/applications/case/documentation/__tests__/applications-documentation.test.js, apps/web/src/server/applications/case/documentation/applications-documentation.controller.js, apps/web/src/server/applications/case/documentation/applications-documentation.service.js, apps/web/src/server/views/applications/case-documentation/documentation-table.njk
* refactor(api/applications): improve code consuming document update API
* feat(api/applications): remove `/update` from path of document update
* refactor(api/applications): improve code structure in update handler
* feat(api/applications): return results + errors when updating documents
* refactor(api/applications): code improvements in document controller
* fix(web/applications): display inline document errors send from API
* chore(api/applications): generate Swagger spec
I did decide to make the changes in one PR as it would have been tricky to separate them out.
The ticket also mentions S51 items---I'll do that next in another PR.
[BOAS-1204](https://pins-ds.atlassian.net/browse/BOAS-1204)
[BOAS-1204]: https://pins-ds.atlassian.net/browse/BOAS-1204?atlOrigin=eyJpIjoiNW …
=> Document API changes + BOAS-1204 fix

apps/web/src/server/applications/case/__tests__/__snapshots__/applications-case.test.js.snap, apps/web/src/server/views/applications/case/components/case-key-dates-table.component.njk
'Deadline for submission' -> 'Deadline for submission of Recommendation'
* fix(web/applications): fix copy on preview & publish key dates section
'Deadline for submission' -> 'Deadline for submission of Recommendation'
[BOAS-1206](https://pins-ds.atlassian.net/browse/BOAS-1206)
[BOAS-1206]: https://pins-ds.atlassian.net/browse/BOAS-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(web/applications): fix copy on preview & publish key dates section

appeals/api/src/server/endpoints/constants.js
Update error message to start with a lowercase letter to they read better when they are prepended by the field name in the UI.
=> feat(appeals/api): update error messages to start with a lowercase letter

apps/api/src/server/applications/subscriptions/__tests__/subscriptions.test.js, apps/api/src/server/applications/subscriptions/subscriptions.controller.js, apps/api/src/server/applications/subscriptions/subscriptions.routes.js, apps/api/src/server/applications/subscriptions/subscriptions.validators.js, apps/api/src/server/swagger-output.json, apps/api/src/server/swagger-types.ts, apps/api/src/server/swagger.js, apps/functions/handle-subscriptions/handle-subscription-command/__tests__/handle-subscription-command.test.js, apps/functions/handle-subscriptions/handle-subscription-command/back-office-api-client.js, apps/functions/handle-subscriptions/handle-subscription-command/index.js
Don't log out email addresses, either directly or via query params in URLs.
[BOAS-1222](https://pins-ds.atlassian.net/browse/BOAS-1222)
[BOAS-1222]: https://pins-ds.atlassian.net/browse/BOAS-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(applications): don't log out email addresses

appeals/api/package.json, package-lock.json
=> fix(appeals/api): ajv defined in dev deps

appeals/api/src/server/endpoints/appeal-allocation/__tests__/appeal-allocation.test.js, appeals/api/src/server/endpoints/appeal-allocation/appeal-allocation-controller.js, appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js, appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js, appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js, appeals/api/src/server/endpoints/appeals/appeals.controller.js, appeals/api/src/server/endpoints/appeals/appeals.service.js, appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js, appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js, appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js, appeals/api/src/server/endpoints/audit-trails/audit-trails.service.js, appeals/api/src/server/endpoints/constants.js, appeals/api/src/server/endpoints/documents/__tests__/documents.test.js, appeals/api/src/server/endpoints/documents/documents.controller.js, appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js, appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js, appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js, appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js, appeals/api/src/server/endpoints/site-visits/site-visits.controller.js, appeals/api/src/server/state/transition-state.js, appeals/api/src/server/utils/string-token-replacement.js
Initial group of audit trail logs for features that have already been developed.
https://pins-ds.atlassian.net/browse/BOAT-531
=> feat(appeals/api): add audit trail logging

appeals/api/src/database/migrations/20231005112224_serviceusers_lpa_models/migration.sql, appeals/api/src/database/schema.d.ts, appeals/api/src/database/schema.prisma, appeals/api/src/database/seed/data-samples.js, appeals/api/src/database/seed/data-test.js, appeals/api/src/database/seed/seed-clear.js, appeals/api/src/server/endpoints/appeals.d.ts, appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js, appeals/api/src/server/endpoints/appeals/appeals.formatter.js, appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js, appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js, appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js, appeals/api/src/server/endpoints/appellants/__tests__/appellants.test.js, appeals/api/src/server/endpoints/appellants/appellants.controller.js, appeals/api/src/server/endpoints/appellants/appellants.formatter.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/appellant-case.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/index.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/lpa.mapper.js, appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js, appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js, appeals/api/src/server/repositories/appeal.repository.js, appeals/api/src/server/repositories/integrations.repository.js, appeals/api/src/server/tests/data.js
Restructures DB tables to reflect PINS data model structure:
- appellant / agent mapping to service customers
- LPA separate table
=> feat(appeals/api): Appeal Service Users

appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js, appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js, appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js, appeals/web/src/server/lib/address-formatter.js, appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk
update to book site visit page (site details to display neighbour addresses)
BOAT-489
=> fix(web): site details to display neighbour addresses

apps/functions/applications-migration/project-updates-migration/src/project-updates-migration.js
=> feat(api): add automatic updates
